### ISSUE TITLE
React ChipGroup Component is using workspace styles

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1010]
The component uses an h4 for the title, the workspace is overriding this style, it shouldn't be bold.

<img width="668" alt="Screen Shot 2019-04-30 at 3 46 11 PM" src="https://user-images.githubusercontent.com/20118816/56988965-437f6b80-6b5f-11e9-9cfb-db1fd762857a.png">

**Comment by rachael-phillips** [comment]
Should be resolved by Red Hat typography
