### ISSUE TITLE
Pie charts don't render one beside the other

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#102]
The pie chart samples are rendering one ontop of the other rather than one beside the other.
![screen shot 2016-06-03 at 8 47 31 am](https://cloud.githubusercontent.com/assets/1832037/15777718/df621ab2-2967-11e6-974f-171d61d652a2.png)

**Comment by dlabrecq** [comment]
This is intentional. There isn't enough room for the hover feature when they are side-by-side. As a result, the tooltips wrap undesirably.

**Comment by andresgalante** [comment]
Cool 👍 thanks @dlabrecq
