### ISSUE TITLE
Update CSS Vars Table - Grid Modifier 

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1021]
Update the grid modifier used on the table for the CSS vars, once a larger modifier becomes available in Patternfly Core. This is the issue in Core: https://github.com/patternfly/patternfly-next/issues/1640

<img width="1094" alt="Screen Shot 2019-05-01 at 1 32 37 PM" src="https://user-images.githubusercontent.com/20118816/57031380-9c114000-6c15-11e9-82f5-69c0428478fc.png">

<img width="853" alt="Screen Shot 2019-05-01 at 1 29 44 PM" src="https://user-images.githubusercontent.com/20118816/57031251-3ae96c80-6c15-11e9-9686-f48afbe61194.png">

**Comment by rachael-phillips** [comment]
@christiemolloy how critical do you think this is for the user experience for our devs? Does this require much work on the site side?

**Comment by christiemolloy** [comment]
Not bad at all, and its a really easy fix, just need to do it on the Core side.

**Comment by rachael-phillips** [comment]
@christiemolloy will create issue in core
