### ISSUE TITLE
Date picker is missing examples

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#103]
Date picker has different ways to use, on the website we only show one.

We show component, we are missing: range, inline and text input.

**Comment by dlabrecq** [comment]
We've duplicated what is shown on the existing web site. However, I'll will defer to @LHinson here?

**Comment by LHinson** [comment]
This will be resolved with this issue: https://github.com/patternfly/patternfly-design/issues/459

Closing it here since it's redundant.
