### ISSUE TITLE
Form level help example is broken

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#104]
The form level help example is broken. The icon is also off.

@LHinson Also this doesn't seem to be part of the test pages, or at least I couldn't find it. I though we use the bootstrap help test for it. Also, having a link inside a label doesn't give a good user experience since the label by itself is a link.

![Uploading Screen Shot 2016-06-03 at 8.51.51 AM.png…]()

**Comment by dlabrecq** [comment]
It doesn't appear to be broken to me. I can click on the icon and see a popup.

The example is from the popovers test page. It's just a template, so it's imported as is.
https://rawgit.com/patternfly/patternfly/master/tests/popovers.html

**Comment by andresgalante** [comment]
@dlabrecq it brakes at an specific with, try resizing the browser until it brakes. This might be a PF bug. @LHinson can you add a story for me to take a look at it. Also I think the icon is too small.


<img width="356" alt="screen shot 2016-06-03 at 10 59 43 am" src="https://cloud.githubusercontent.com/assets/1832037/15780953/61d1b716-297a-11e6-9d0d-c2e8dca5e649.png">

**Comment by dlabrecq** [comment]
I was able to give the example a little more room, so now the icon won't wrap. I'll leave this open if you want to investigate further?

**Comment by andresgalante** [comment]
@dlabrecq @LHinson I change the container to fluid here: https://rawgit.com/patternfly/patternfly/master/tests/popovers.html

And I don't get the same error. There is something off with the implementation of the website. I'll investigate as soon as I can.

**Comment by rachael-phillips** [comment]
I'm closing this issue because it is stale.
