### ISSUE TITLE
[Symbol lib] Unclear what each type of tab is

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1042]
In the symbol library, it is very unclear what the tabs are.

![Xnip2019-05-02_11-48-30](https://user-images.githubusercontent.com/23172038/57088458-56657d80-6cd0-11e9-89f0-e66543fee053.jpg)

Are the ones further up the menu the primary type?
Why is there a second group of "primary" tabs, that don't match the documentation on the website?

**Comment by rachael-phillips** [comment]
Hi @gdoyle1 making you aware of this one!

**Comment by rachael-phillips** [comment]
@gdoyle1 would you mind transferring this to the symbol library repo?

**Comment by gdoyle1** [comment]
@rachael-phillips This should be fixed with the newest updates we've made in the symbol library! Will close this if @katierik confirms this is fixed

**Comment by katierik** [comment]
@gdoyle1 when will the new lib be updated? I'm not seeing any change on my side.

**Comment by gdoyle1** [comment]
Make sure you're using this link for it: https://sketch.cloud/s/gb1ka. Tabs were changed a week or so back! @katierik

**Comment by katierik** [comment]
Verified as awesome
