### ISSUE TITLE
https://www.patternfly.org/v4/ footer uses old Red Hat logo 

### ISSUE THREAD

**Issue by dongniwang** [patternfly/patternfly-org#1047]
Just visited the https://www.patternfly.org/v4/ and the footer is still using the old Red Hat logo. 

<img width="1333" alt="Screen Shot 2019-05-02 at 2 51 52 PM" src="https://user-images.githubusercontent.com/24943812/57099245-f67bd080-6ce9-11e9-9f66-a974ae301fcd.png">

**Comment by rachael-phillips** [comment]
Great find! Thanks!

**Comment by rachael-phillips** [comment]
We're addressing this now @dongniwang

**Comment by dgutride** [comment]
Fixed - thanks @christiemolloy
