### ISSUE TITLE
Tooltip example is broken on the React side

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1049]
The tooltip example is broken on the React side: https://www.patternfly.org/v4/documentation/react/components/tooltip/

It should look like the html example: https://www.patternfly.org/v4/documentation/core/components/tooltip

**Comment by jschuler** [comment]
<img width="1237" alt="Screen Shot 2019-05-03 at 9 36 32 AM" src="https://user-images.githubusercontent.com/869106/57140921-f54cb100-6d86-11e9-8914-7337126528a1.png">

They look the same to me? Left is react, right HTML

**Comment by rachael-phillips** [comment]
Closing this issue as we found an interim solution
