### ISSUE TITLE
Horizontal menu missing snippets on Navbar Variations

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#107]
Since for this version of the website we are not going to write tech documentation to explain the difference and modifiers for each variation of the menu, maybe we should add code snippets on Navbar Variations.

**Comment by LHinson** [comment]
I'm confused. Don't we have the code variations? See: http://beta.patternfly.org/pattern-library/navigation/horizontal-navigation/#example-code-3

I didn't notice there is some overlap with the example and the "reference markup" link. I'll file a separate bug

**Comment by andresgalante** [comment]
Yes, we do, I don't know how I miss it! Thanks @LHinson
