### ISSUE TITLE
Demo links broken when you navigate from home page 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#1075]
From the main page, if you select the "view Demos" link ( towards the bottom ), and then try any of the 'Full page' links:

i.e. from this landing page - all those links don't work: 
![image](https://user-images.githubusercontent.com/7924406/57263265-3b7f6a00-703e-11e9-9414-6ac97e9ebc2e.png)

If you navigate via the Layouts landing page, and then try examples, i.e. from here: https://www.patternfly.org/v4/documentation/react/demos/pagelayout/
and follow links like: https://www.patternfly.org/v4/documentation/react/demos/pagelayout/pagelayoutdefaultnav
it works fine.

I've had a look at what links are used on both pages, and it looks like the 'view demos' page is missing a subdir - see below:

View Demos page:              https://www.patternfly.org/v4/documentation/react/demos/pagelayoutdefaultnav <-- doesn't work
Layouts->Examples page: https://www.patternfly.org/v4/documentation/react/demos/pagelayout/pagelayoutdefaultnav   <--works

**Comment by jschuler** [comment]
Fixed by #1077
