### ISSUE TITLE
Mobile navigation bug - toggle

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1078]
When I click on the toggle in the mobile view the navigation closes. I'm in Safari.

**Comment by mindreeper2420** [comment]
@rachael-phillips Can you add a screenshot or video to clarify what you are seeing? The navigation on mobile is working for me, both on my iOS device (using Safari) and on desktop using smaller viewports.

**Comment by rachael-phillips** [comment]
It's on the click, and I don't think I can capture it in a screenshot. Right now when I click on the toggle, the menu closes, but it should stay open :) we can discuss on Monday if you want :)
