### ISSUE TITLE
Vertical menu missing something on the snippet

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#108]
@jeff-phillips-18 Can you please help me review this snippet: http://beta.patternfly.org/pattern-library/navigation/vertical-navigation/#_code
We are missing something on the snippet to add the margin on the left of the content to make room for the menu.
<img width="318" alt="screen shot 2016-06-03 at 9 06 10 am" src="https://cloud.githubusercontent.com/assets/1832037/15778136/9de50d26-296a-11e6-9383-6bd8342fe866.png">

Thanks!! 😄

**Comment by dlabrecq** [comment]
@andresgalante Could it be this?

<html lang="en-us" **class="layout-pf layout-pf-fixed"**>

  {% include head.html %}
  <body class="cards-pf">
    {{ content }}
  </body>
</html>

**Comment by dlabrecq** [comment]
Fixed.
