### ISSUE TITLE
Demos are pulling in website styles

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1080]
<img width="1164" alt="Screen Shot 2019-05-07 at 3 59 08 PM" src="https://user-images.githubusercontent.com/20118816/57329114-1a238a00-70e1-11e9-89d6-154b65211f8c.png">

**Comment by rachael-phillips** [comment]
@mindreeper2420 I unassigned you for now until you have some time!

**Comment by christiemolloy** [comment]
The demos aren't pulling in website styles anymore from as far as I can tell, but the previews are. But I think @jschuler fixed that yesterday?

**Comment by christiemolloy** [comment]
Closing this issue as it is resolved
