### ISSUE TITLE
Switch is broken in PF4 docs

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#1084]
From @quarckster :

Go to https://www.patternfly.org/v4/documentation/react/components/switch/ and click on Simple switch. Nothing will happen. The switch should change its state and the text should be changed to "Message when off".

**Comment by rachael-phillips** [comment]
@redallen has this been resolved?

**Comment by redallen** [comment]
This was a website issue. It's fixed now in https://staging.patternfly.org/v4/documentation/react/components/switch/ , so it can be closed.
