### ISSUE TITLE
Code snippet is incorrect

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1085]
Reported by @rhamilto, the code snippet for the "Using Expandable Navigation" example is incorrect on https://www.patternfly.org/v4/documentation/react/demos/pagelayout/.

I'm not sure if this issue is localized to that example or may be present in other examples, too.

**Comment by jschuler** [comment]
Appears to be an upstream bug because i can see the same thing here:
http://patternfly-react.surge.sh/patternfly-4/demos/pagelayout/

**Comment by rachael-phillips** [comment]
Can we close this @jschuler or was this resolved?

**Comment by rachael-phillips** [comment]
Closing because this is complete
