### ISSUE TITLE
Toolbar Documentation: Include example of toolbar existing in top subheader area when not attached to a component below

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-org#1087]
This has come up a few times now and I've noticed its due to a gap in documentation, but also brings in a larger question:

![image](https://user-images.githubusercontent.com/30935938/57233414-94bead80-6fec-11e9-9c10-2c7ceedc130c.png)

When a toolbar is needed for a component that doesn't have an area for it to exist (e.g. grid view) the toolbar should be located at the bottom of the white background subheader area. The toolbar should never exist on it's own detached from anything as seen above.

We should include an example of the correct version of the above, and make sure to mention that it should never exist on it's own as a standalone item in the page.

Here is a quick example of the corrected above, but we should probably use the same examples currently in the documentation for the addition. This is just to more visually explain the above.

![image](https://user-images.githubusercontent.com/30935938/57233880-80c77b80-6fed-11e9-869e-7a3b819cf0b0.png)

This also brings into question the inconsistency here - a toolbar in a list/table view exists at the top of the table, but we can't do that for a grid view. Should we choose a direction that maintains consistency for toolbars no matter what the component? This difference in application might be confusing for users. There's situation where you would want them attached (multiple toolbars/lists per page) and situations where it makes more sense to be consistent (going from a page like the above to another page with a single list view), so it's a tough call on the best approach for me. @mcarrano @kybaker @rachael-phillips @LHinson

**Comment by gdoyle1** [comment]
We also use the connected toolbar to the white background subheader area in the card view demo that is here https://github.com/patternfly/patternfly-next/pull/1716. It is currently being worked on to update the cards in the grid but will exist as a demo on the site. I think we could add this into our documentation for the toolbar as well. 
<img width="1434" alt="Screen Shot 2019-05-10 at 1 41 32 PM" src="https://user-images.githubusercontent.com/30870144/57545999-d1aadd00-7329-11e9-99a6-3b4d649e32d4.png">

**Comment by mcarrano** [comment]
Changes merged via #1438
