### ISSUE TITLE
Add Mega Menu to Navigation System design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1088]
Existing design guidelines page here needs to be updated to include the new mega-menu: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/navigation-system

Reference patternfly-next issue: https://github.com/patternfly/patternfly-next/issues/1767

**Comment by stacymcauliffe** [comment]
Un-assigned myself from this until we're ready to document. Right now, we've decided to pursue some additional testing.

**Comment by LHinson** [comment]
Will not pursue at this time... only need atm are enhancements to the app launcher
