### ISSUE TITLE
Update Typography page for new font

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1090]
The Typography page needs to be updated to reflect transition to the new Red Hat font. Page to update: https://www.patternfly.org/v4/design-guidelines/styles/typography

Reference issue: https://github.com/patternfly/patternfly-next/issues/1524

**Comment by stacymcauliffe** [comment]
Put up [PR 1408 for this](https://github.com/patternfly/patternfly-org/pull/1408) - I made the copy changes. @jschuler will need to make additional updates to the PR so that the typography examples are shown in Red Hat font instead of Overpass.
