### ISSUE TITLE
Cross-check browsers

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1097]
Need to check parts of the website across browsers (particularly FF). Make a running list of issues here:

**Comment by christiemolloy** [comment]
[chartIssue.zip](https://github.com/patternfly/patternfly-org/files/3179367/chartIssue.zip)

**Comment by christiemolloy** [comment]
On iPhone (mobile) the header is lacking space between menu, logo and search. @rachael-phillips do you know if theres a design?

<img width="345" alt="Screen Shot 2019-05-20 at 12 28 59 PM" src="https://user-images.githubusercontent.com/20118816/58037196-e0984900-7afa-11e9-8fbc-5df2ffebd21a.png">

**Comment by mindreeper2420** [comment]
@christiemolloy - the spacing should be fixed in my Search improvements PR. I also adjusted the size of the PatternFly logo in that PR too.

**Comment by christiemolloy** [comment]
On mobile the code blocks aren't wrapping

<img width="323" alt="Screen Shot 2019-05-20 at 12 33 17 PM" src="https://user-images.githubusercontent.com/20118816/58037474-7d5ae680-7afb-11e9-918e-ef4792c11fdc.png">

**Comment by christiemolloy** [comment]
On iPhone/mobile, the link is bleeding out of the popover 

<img width="339" alt="Screen Shot 2019-05-20 at 12 43 38 PM" src="https://user-images.githubusercontent.com/20118816/58038050-e98a1a00-7afc-11e9-96c8-6787e17cbee5.png">

**Comment by christiemolloy** [comment]
Typography page table needs space

<img width="394" alt="Screen Shot 2019-05-20 at 12 47 11 PM" src="https://user-images.githubusercontent.com/20118816/58038223-687f5280-7afd-11e9-94c2-778351d5b873.png">

**Comment by christiemolloy** [comment]
Text is cutting off here- Spacers page

<img width="415" alt="Screen Shot 2019-05-20 at 12 49 05 PM" src="https://user-images.githubusercontent.com/20118816/58038314-ada38480-7afd-11e9-887e-cfc625b487db.png">

**Comment by christiemolloy** [comment]
Table on mobile, @christiemolloy to talk with @redallen 

<img width="426" alt="Screen Shot 2019-05-20 at 12 50 53 PM" src="https://user-images.githubusercontent.com/20118816/58038424-ed6a6c00-7afd-11e9-900e-199afd72ef90.png">

**Comment by rachael-phillips** [comment]
This work has been complete
