### ISSUE TITLE
Widgets: Copy link is out of place

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#110]
On snippets the copy link is out of place.
![screen shot 2016-06-03 at 9 08 16 am](https://cloud.githubusercontent.com/assets/1832037/15778194/f55a4f08-296a-11e6-88ff-3fe6f709f6b1.png)

**Comment by dlabrecq** [comment]
The pretty print code here is slightly different than what we're using on the code pages. Looks like an easy fix.

**Comment by dlabrecq** [comment]
Fixed.
