### ISSUE TITLE
Bug: Clicking back and forth from App Launcher on website doesn't work 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#1101]
I'm using Chrome browser and when I try to click back and forth between react and html, it jumps me over to the "about modal box" page. 

Steps to repeat: 

1. With React toggled, click on app launcher 
2. Now click on HTML 
The page jumps over to the "about modal box" 

or 

1. With HTML toggled, click on app launcher
2. Now click on React 
The page jumps over to the "about modal box" 

I see this same bug for the following: 
- Chip
- Check or check box 
- Login

**Comment by rachael-phillips** [comment]
This bug is because we don't have a 1:1 ratio with out components. I will leave this open, but we don't have a way of resolving this issue for the time being. @mcarrano would it be confusing for users to jump between Chip-HTML and ChipGroup-React? They aren't 1:1 for the time being

**Comment by mcarrano** [comment]
Yep, this is the problem with not having exact equivalence between the two libraries. Yeah, we could try to map things, like Chip -> Chip group. Or we can try to enforce more consistency. Not sure what the best way forward is or if this is confusing to users (sounds like it was to you @LHinson ). Perhaps a good discussion with the dev teams.

**Comment by evwilkin** [comment]
Closing this as it's mostly resolved as follows, and will no longer be a factor in new redesign in progress (https://github.com/patternfly/patternfly-org/issues/1793):

- Application launcher maps between HTML & React correctly
- Chip group maps correctly between HTML & React
  - Chip in HTML redirects to Release Notes in React as there is no corresponding React component
- Checkbox (React) & Check (HTML) map correctly
- Login (HTML) maps to Login page (React) correctly
