### ISSUE TITLE
Horizontal navigation needs arrow to indicate scroll

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-org#1103]
"Contribute" becomes hidden at smaller screen sizes on the horizontal navigation and there's no indication that scrolling is possible. Can we add the arrow seen here https://pf4.patternfly.org/demos/Page/examples-full/?component=Page%20component%20horizontal%20nav%20example in? We may have to somehow switch the dark background of the arrow to a light background if a tab is hovered over (since our tabs turn from a dark background to light on hover)

**Comment by rachael-phillips** [comment]
@joachim is working on this

**Comment by jschuler** [comment]
I created a PR upstream to add scroll buttons
https://github.com/patternfly/patternfly-react/pull/2071
