### ISSUE TITLE
Charting Docs: Add Brush and Zoom

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#1106]
Brush and zoom enhancement is being added to pf-charts as seen here: https://github.com/patternfly/patternfly-react/issues/1715

This issue is to ensure that our documentation is appropriately updated with information re: brush and zoom

**Comment by gdoyle1** [comment]
Documenting in this [google doc](https://docs.google.com/document/d/1o1BfrgkNBvUM1a8rvaesUzhsall39RJHQexWYOVsoyk/edit?usp=sharing) - WIP
