### ISSUE TITLE
Charting Docs: Add information regarding thresholds 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#1107]
Thresholds are being introduced to charting as seen in the following issue: https://github.com/patternfly/patternfly-next/issues/901

This issue is to ensure that documentation is appropriately updated.

**Comment by gdoyle1** [comment]
[Google doc](https://docs.google.com/document/d/1o1BfrgkNBvUM1a8rvaesUzhsall39RJHQexWYOVsoyk/edit?usp=sharing) for chart documentation - WIP. Need to ensure accessibility is approved (meeting about this tomorrow) before updating designs/content for thresholds

**Comment by gdoyle1** [comment]
@mcarrano @stacymcauliffe I finished the documentation here: https://docs.google.com/document/d/1o1BfrgkNBvUM1a8rvaesUzhsall39RJHQexWYOVsoyk/edit?usp=sharing. Please take a look! I am open to changes for naming of the charts & etc.

**Comment by mcarrano** [comment]
@gdoyle1 I gave this a look. Just commented on some inconsistency with the labeling on the legend. I think the documentation does a great job describing elements of the chart, but says nothing about intended usage. Can that be added? Also, when do we recommend using a percentage vs. a quantity in the center of the donut?
