### ISSUE TITLE
Widgets: Infotip missing image

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#111]
The path to the logo on info tips is broken:

![screen shot 2016-06-03 at 9 10 41 am](https://cloud.githubusercontent.com/assets/1832037/15778224/19b50c4e-296b-11e6-81c0-fbaebccc87c8.png)

**Comment by dlabrecq** [comment]
This was actually fixed yesterday. If you're using a local repo, you may have missed it.
