### ISSUE TITLE
Date and time Pickers - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1111]
Introduce design documentation for:
1. Date picker: https://www.patternfly.org/v4/components/date-picker
2. Time picker: https://www.patternfly.org/v4/components/time-picker/
3. Calendar month: https://www.patternfly.org/v4/components/calendar-month
(For calendar month, it can be very short, and you can link to the date picker design guidelines "for more information"!)

Related Issue: https://github.com/patternfly/patternfly-next/issues/180

- Describe it's basic usage (what you can do with it)
-  Include examples/use cases of when to use:
     - as a filter in a toolbar
     - in a form

**Comment by mmenestr** [comment]
Prioritize maybe

**Comment by MariSvirik** [comment]
[Draft in  WIP](https://docs.google.com/document/d/1UMm_3-A5Q1Vf1flgHJjNhsmwB72NmDgMrzj8M1QDpzg/edit#heading=h.3u89l1u88jbe)
It should be done by the end of the week (01/22/2021)

**Comment by MariSvirik** [comment]
Old guidelines: https://docs.google.com/document/d/1hlS0R1l7gnoe-YDu1SEHpUSrf6WMuZPejR5AwYr0a20/edit#

**Comment by MariSvirik** [comment]
Content feedback implemented

**Comment by MariSvirik** [comment]
PR: https://github.com/patternfly/patternfly-org/pull/2484
