### ISSUE TITLE
Dashboard - Design Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1112]
Introduce design and usage documentation for the Dashboard demo. Topics should include:

* General dashboard layout guidelines
* Card types: examples and how they are used
* Valid card variants
* Guidelines for creating custom / product specific cards.

Related issue: #278

**Comment by mcarrano** [comment]
We have a draft of the design guidelines document here: https://docs.google.com/document/d/1_KA8WzNd-66CxVszRtosiLH0DIgUpZBcKEr0yRwFL6Y/edit?usp=sharing

@stacymcauliffe @mceledonia @LHinson and I met to discuss next steps. Need to review open issues from current draft and identify Sketch examples that we need. Currently targeting for the July release milestone.

**Comment by mmenestr** [comment]
Questions to address - where does this live?

**Comment by mcarrano** [comment]
Here is an original draft of this document by @mceledonia : https://docs.google.com/document/d/1VYTC2VrjdlwWPwEF7oVcCT-ict16bb3kDUmfHf9lpQA/edit?usp=sharing  Review and potentially pull some of this back in.

**Comment by mcarrano** [comment]
I have taken earlier work, consolidated into one doc, made some edits and added a bunch of examples. The resulting draft is here: https://docs.google.com/document/d/1_KA8WzNd-66CxVszRtosiLH0DIgUpZBcKEr0yRwFL6Y/edit?usp=sharing

@mmenestr @afialkoff can you review this when you get a chance? It is intentionally different than some of our other guidelines and reads more like a tutorial. But I think having this step-by-step approach to designing dashboards will be valuable for anyone trying to accomplish this. Thanks again @mceledonia for taking the time to verbalize your process.

Welcome your feedback.
