### ISSUE TITLE
[Sketch] Missing icons from library

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1113]
The icons in the sketch file are not an exact match for the icons available & on the website.

Two of the icons that are missing:
Info (?) - Not on website or sketch file, accessible to devs
![image (4)](https://user-images.githubusercontent.com/23172038/57786005-bca2c500-7700-11e9-9c18-2f41be24231c.png)

error-circle-o - On website, not in sketch file
![Xnip2019-05-15_11-01-53](https://user-images.githubusercontent.com/23172038/57786093-e0fea180-7700-11e9-82fc-6c98536565de.jpg)

cc @cshinn

**Comment by jschuler** [comment]
Currently, the icons that are visible on the site are based on the [icons definition in Core](https://github.com/patternfly/patternfly-next/blob/master/src/icons/definitions/pf-icons.json).
We should discuss what set of icons we should display. Everything available to devs? Also there's this related issue https://github.com/patternfly/patternfly-next/issues/1877

**Comment by evwilkin** [comment]
Icons to show on site resolved in https://github.com/patternfly/patternfly-org/issues/1687

**Comment by evwilkin** [comment]
@gdoyle1 do you know if this is still an issue or if we can close it out after the recent icon updates?

**Comment by gdoyle1** [comment]
@evwilkin this is resolved! Everything in the design kit matches what is on the Icons page

**Comment by evwilkin** [comment]
Closing per comment above this is no longer an issue.
