### ISSUE TITLE
Widgets: pretty print example has the copy link

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#112]
The pretty print example should not have the copy btn:

![screen shot 2016-06-03 at 9 11 54 am](https://cloud.githubusercontent.com/assets/1832037/15778244/4de156bc-296b-11e6-9a8f-c66a16f1a2ff.png)

**Comment by dlabrecq** [comment]
The pretty print code here is slightly different than what we're using on the code pages. Looks like an easy fix.

**Comment by dlabrecq** [comment]
Fixed.
