### ISSUE TITLE
Clean up styling for PF4 docs pages

### ISSUE THREAD

**Issue by stacymcauliffe** [patternfly/patternfly-org#1121]
Take an initial pass at cleaning up the styling and readability for the design documentation and getting started content on the PF4 website. 

- [ ] Add a max-width to the text content to prevent stretching across the entire width of the container
- [ ] Add additional spacing between content elements to increase white space between sections
- [ ] Left-align all images

After we tackle this initial clean up, we might consider adding TOC for header elements to documentation to improve navigation within each topic.

**Comment by stacymcauliffe** [comment]
Invision example: https://redhat.invisionapp.com/share/FARZNV93HEV#/363048638_Content_Layout_Example

**Comment by redallen** [comment]
All of this has been done in the latest release.

Closing.
