### ISSUE TITLE
Mobile: Browser background color is purple

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly-org#1122]
Using Chrome on Android 9 (Pixel 3a), the background color of the browser changes to purple. On most sites, it is either grey/white or color-coded to the site's color palette.

Ideally, it would be great to see PatternFly.org/v4 either grey/white, or blue/black (to match the primary colors).

These colors are defined in a `manifest.json` file, found at the root directory of the site. _See [The Web App Manifest](https://developers.google.com/web/fundamentals/web-app-manifest/)._

![Screenshot_20190517-101422](https://user-images.githubusercontent.com/4032718/57934170-0c15fc00-788d-11e9-81f8-98a0d17d5b10.png)

**Comment by rachael-phillips** [comment]
Color: https://www.color-hex.com/color/151515

**Comment by jschuler** [comment]
Should be addressed by #1165
