### ISSUE TITLE
website - typos in manual include instructions

### ISSUE THREAD

**Issue by gregsheremeta** [patternfly/patternfly-org#1123]
in https://www.patternfly.org/v4/get-started/developers

> Configure your project
> If you want to use PatterFly 4 utilities in your project, find the utilities file, patternfly-addons.css

[should be: If you want to use PatternFly]

> Copy patternfly-addons.scss into your project’s CSS directory.

[should be: .css]

> In your HTML file, add the following line to the bottom of your list of CSS files:
> &lt;link rel="stylesheet" href="css/patternfly-addons.scss"&gt;

[should be: .css]

**Comment by rachael-phillips** [comment]
@stacymcauliffe making you aware?

**Comment by stacymcauliffe** [comment]
Thanks - @rachael-phillips @LHinson - put up [a PR for this](https://github.com/patternfly/patternfly-org/pull/1134) and added Leslie and Coker to review. Let me know if we need confirmation of these changes from anyone else and I'll add them to the PR. Thanks!

**Comment by stacymcauliffe** [comment]
Did not mean to close this :)

**Comment by rachael-phillips** [comment]
Fantastic - thanks @stacymcauliffe
