### ISSUE TITLE
Widgets: basic charts: Duplicated examples

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#113]
We are duplicating information, charts are already on charts section:

**Comment by LHinson** [comment]
@andresgalante do you mean that we are duplicating charts between the widgets and pattern page? If so, Joe recently completed research about how we should approach this. If it makes sense for it to be redundant or if one should be a pattern vs widget. Let me know if you meant something else.

**Comment by andresgalante** [comment]
@LHinson I don't think it should be redundant. Duplicated documentation leads to impossible maintenance, specially onces we start actually writing docs.

**Comment by LHinson** [comment]
agreed @andresgalante. I've looped around with Joe on this too. Let's delete the charts from widgets since it's redundant @dlabrecq

**Comment by dlabrecq** [comment]
Done.
