### ISSUE TITLE
Update Forms design guidelines

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1137]
Update forms design guidelines to reflect changes to the design. Some issues to be addressed include:

* Ensure all mockups are correct, up to date, and use appropriate icons for field-level help, etc. Should reflect updated form designs as specified in https://github.com/patternfly/patternfly-next/issues/919. The designer on Forms V2 is @mceledonia

* Prioritize "vertical" form layout (top aligned labels) along for rationale - see note below.

* Provide guidance on use of forms in a page. What's the maximum recommended width? How are they located in a page?

* Multi-column forms? When to use them and layout rules.

* Remove details on pop-up help and reference https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/embedded-assistance so that this information is not repeated.

* Ensure all examples reflect best practices (especially for placeholder text) See https://github.com/patternfly/patternfly-org/issues/1614 

This page would also benefit from a TOC since it is a long page with lot's of content.

**Comment by rachael-phillips** [comment]
On this next iteration of design guidelines we should portray the horizontal layout that is currently recommended in a less positive light. After speaking with @mceledonia I learned all of the reasons that the layout of having the field name above the form field (top-aligned) is preferable: 

- You don’t run into a situation with longer labels that either push the text fields far to the right, or have to wrap to a second line which disrupts the vertical spacing of the form… Good example of this above is the checkbox, note how disconnected it is from its label now, but it would look weird if the checkbox was all of a sudden closer to the label and not aligned with the text fields above
- Top-aligned labels save horizontal room which is A+ for responsive design
- Labels are always in close proximity to their text fields (re: first point)
- If the label wraps its still in close proximity and doesn’t change the actual space between fields
- Easier scanning, the field and label feel like one object as opposed to two separate things

**Comment by mcarrano** [comment]
Per issue #1004 we should also discuss embedding a form in a full page - setting form width, etc.

**Comment by rachael-phillips** [comment]
This should be resolved now

**Comment by mcarrano** [comment]
Need to reflect mockups shown here: https://github.com/patternfly/patternfly-next/issues/919
