### ISSUE TITLE
Widgets: Bootstrap Switch

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#114]
@LHinson @dlabrecq So, I think this must be a bug in Patternfly.
If you add the bootstrap switch js to your html it converts all your checkboxes to On/Off toggles.

I don't think that's the correct behaviour since a page can have toggles and checkbox.

**Comment by dlabrecq** [comment]
I cannot reproduce the issue. As a test, I added another checkbox, but only the checkbox with the bootstrap-switch class is converted.

![screen shot 2016-06-03 at 12 26 27 pm](https://cloud.githubusercontent.com/assets/17481322/15785671/70ab719e-2986-11e6-9027-ffc866d516f5.png)

**Comment by andresgalante** [comment]
@dlabrecq you are right, sorry my test env was set up differently. My bad
