### ISSUE TITLE
Website side menu broken on mobile

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1142]
I just checked the patternfly website on my iPhone (safari) and there is no hamburger menu (maybe there was never one,  i cant remember), but if i want to link from "Get Started" to "Design Guidelines" to "Documentation" there is no way of getting the side menu to open up so that i can click other options.

I actually also see this happening at a small Desktop size too.

**Comment by mindreeper2420** [comment]
After recent updates (merging of PR #1099), staging.patternfly.org/v4 is no longer broken. Once production is updated with the latest revisions, this should be rechecked.

![Screen Shot 2019-05-28 at 9 04 08 AM](https://user-images.githubusercontent.com/4032718/58480152-b8769e80-8127-11e9-953d-3089bddad987.png)

**Comment by christiemolloy** [comment]
This issue was resolved a while ago
