### ISSUE TITLE
Widgets: Bootstrap Datepicker: Duplicated examples

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#115]
We are duplicating this one.

**Comment by dlabrecq** [comment]
I've also noticed there are examples in multiple places. Although, I believe this is intentional. I'll defer to @LHinson here.

**Comment by andresgalante** [comment]
To me duplicated examples will only lead to problems, specially when we have text to maintain around samples.

What do you think?

**Comment by LHinson** [comment]
agreed @andresgalante. I think date picker needs to be removed from patterns and just stay on widgets.

**Comment by dlabrecq** [comment]
Just want to be sure? This has an Angular example, which isn't shown anywhere else on the site.

**Comment by dlabrecq** [comment]
I've removed the link to the page. The page is still available in the code if anyone decides the pattern doc/image and Angular-PatternFly example are worth while.

**Comment by LHinson** [comment]
doh! shoot, I hadn't even thought about angular widgets. No action at this time. I've created a spike in the backlog https://patternfly.atlassian.net/browse/PTNFLY-1537

**Comment by LHinson** [comment]
Improved organization will happen with the "next" effort. I'm closing this issue as it's not a priority at this time.
