### ISSUE TITLE
Table on mobile styles

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1152]
Table on mobile, @christiemolloy to talk with @redallen 

<img width="426" alt="Screen Shot 2019-05-20 at 12 50 53 PM" src="https://user-images.githubusercontent.com/20118816/58038424-ed6a6c00-7afd-11e9-900e-199afd72ef90.png">

_Originally posted by @christiemolloy in https://github.com/patternfly/patternfly-org/issues/1097#issuecomment-494067173_

**Comment by christiemolloy** [comment]
@redallen The way the React props in the table are styled in the website is different to in the React repo. In the react repo its using the Patternfly table component. How difficult would it be to transfer the table to the Patternfly table component?

**Comment by redallen** [comment]
It's not much trouble at all. I was in a hurry when I did it in react-docs, so I just used html. Open an issue in patternfly-react for it!
