### ISSUE TITLE
Background image error 

### ISSUE THREAD

**Issue by lareplog** [patternfly/patternfly-org#1161]
To reach this issue: 

1.    https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/login
2.   go to this section https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/login#elements
3. click on the "Background image" link
4. You should see in Examples there's a text that says "This preview can only be accessed in full page mode", even if you begin in full page. 
5. Clicking the "full page mode" link directs you to a 404 error.

**Comment by gdoyle1** [comment]
@mmenestr I think we need to update the link in the login usage and behavior section to link to /documentation/react/components/backgroundimage/ - the only difference between the correct link and the one that is existing (leading to a 404) is there is no / at the end of the 404 one. So I think it's worth a try

**Comment by mmenestr** [comment]
Closing because I believe its been fixed!
