### ISSUE TITLE
PF3 - api/code examples broken

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-org#1164]
From Slack:
Hi, just got an Issue filed against angular-patternfly that the api/code examples are no longer available on patternfly.org?  https://github.com/patternfly/angular-patternfly/issues/775   I also see the same issue for patternfly-ng.   Are patternfly 3 api docs still available somewhere?

Can confirm, on e.g. https://www.patternfly.org/pattern-library/navigation/vertical-navigation/#code the "View Angular PatternFly Example" and "View PatternFly NG Example" links are broken (edited) 
They redirect to the `/v4/404.html` page, so it looks like something about how we set up routes for the new v4 site

**Comment by jschuler** [comment]
Related issue at https://github.com/patternfly/angular-patternfly/issues/775

**Comment by redallen** [comment]
Fixed patternfly.org/angular-patternfly and patternfly.org/patternfly.ng with some redirects for now.
