### ISSUE TITLE
Toolbar examples hard to see / interpret

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#1166]
https://www.patternfly.org/v4/documentation/core/components/toolbar-full

These examples are overlapping each other. It looks like I can click on things like the sort dropdown but nothing actually happens. Is this meant to be a working code example or just static images?

**Comment by rachael-phillips** [comment]
Thanks for filing @ajacobs21e we've tried resolving this. @jschuler how can we solve this?

**Comment by ajacobs21e** [comment]
i'd recommend either a) making the example clickable so the user can open / close each element as needed or b) spacing these out so the menus don't overlap the example below

**Comment by rachael-phillips** [comment]
Agreed

**Comment by jschuler** [comment]
Each full page example is supposed to open with just that example and not overlapping with the others. This is done in the HTML examples by appending `?component=something` to the URL, for example: https://www.patternfly.org/v4/documentation/core/components/toolbar-full?component=Toolbar%20simple. This behavior is buggy right now and needs to be fixed.

In terms of interactivity, HTML examples are static and not interactive. So even if the example is displayed by itself as it should be, it won't be interactive. The React examples are interactive.

**Comment by rachael-phillips** [comment]
@jschuler does this have to be fixed in React upstream?

**Comment by jschuler** [comment]
no we'll fix this in the website, i think this issue is relevant #926
