### ISSUE TITLE
Overlap with example and "reference markup" expand link

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#117]
Overlap with example and "reference markup" expand link. See http://beta.patternfly.org/pattern-library/navigation/horizontal-navigation/#example-code-3
<img width="362" alt="two-level" src="https://cloud.githubusercontent.com/assets/7924406/15779983/72352834-296d-11e6-9673-e9f99e367dbb.png">

**Comment by dlabrecq** [comment]
This appears to be due to a smaller screen size. That is, "more options" is wrapping onto the next line.

**Comment by dlabrecq** [comment]
Added more height to prevent example from overlapping.
