### ISSUE TITLE
Forms documentation and guidelines don't follow capitalization standards

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-org#1171]
Our style guide promotes sentence style capitalization
https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology#capitalization

However, our forms doc and guidelines do not support this. 

- The doc and guidelines should be updated to remind users to use sentence case for form labels. 

- The actual examples violate the guideline and show a mix of cases. See:
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms
https://www.patternfly.org/v4/documentation/react/components/form/

**Comment by rachael-phillips** [comment]
I'm closing because I believe this has been completed
