### ISSUE TITLE
Add "Go to PatternFly 3" banner to every page

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#1177]
What do others think?
It seems odd to me that the banner is only applied on the homepage. This could lead to some confusion to users entering via a page other than the homepage.

**Comment by rachael-phillips** [comment]
Hi @matthewcarleton I'm going to close this issue because we hope to change the PF4 homepage over to patternfly.org soon.

**Comment by rachael-phillips** [comment]
We should add this capability to every page

**Comment by jschuler** [comment]
@rachael-phillips , should the banner be closable? In that case, I imagine it should close it for all pages.
Continuing with that assumption, would the banner be shown again when they reload the page? How about if they currently have a tab open, close the banner, then open another tab? Should the close action persist across tabs for the duration of the browser session?

**Comment by matthewcarleton** [comment]
@jschuler I'd say any action they take should be reflected in every instance of that same window.  I like the idea of closing the banner, but we'd need to ensure the path is still available if they don't act on it right away but then choose to do so at a later point while in the same session. We have PF3 in the footer of PF4 and could do the same for PF3 if we think that's sufficient. It's not very discoverable, but I'd say this is an edge case anyway.

**Comment by jschuler** [comment]
Addressed in #1248
