### ISSUE TITLE
New website: list view preview tile missing top border

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#118]
https://v2-patternfly.rhcloud.com/pattern-library/#_

<img width="533" alt="screen shot 2016-06-03 at 10 47 51 am" src="https://cloud.githubusercontent.com/assets/6415742/15782515/a6e30c4e-2978-11e6-8883-63f3ff2ab73c.png">

Top border missing from List View preview image

**Comment by dlabrecq** [comment]
I'll have to defer to @kybaker as he created the thumbnail.

**Comment by LHinson** [comment]
Just submitted a PR to fix - https://github.com/patternfly/patternfly-org/pull/133

**Comment by dlabrecq** [comment]
Fixed.
