### ISSUE TITLE
Link to pf4 icon font file is incorrect

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1185]
on https://www.patternfly.org/v4/design-guidelines/styles/icons

> To use an icon in your desktop applications, you can install the PatternFlyIcons-webfont.ttf, set it as the font in your application, and paste the icons into your designs.

The link to "PatternFlyIcons-webfont.ttf" is for the PF3 icon font. Instead we should link to either

* https://github.com/patternfly/patternfly-next/tree/master/src/patternfly/assets/pficon 
  * this is all of the icon fonts we offer, not just the TTF, and it includes the stylesheet (pficon.scss) you could use to generate CSS, too.
* https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/assets/pficon/pficon.ttf
  * this would be the same as the current link on the pf website, just updated to reference the pf4 font.

**Comment by rachael-phillips** [comment]
I'm closing because I believe this has been completed
