### ISSUE TITLE
Change Colors on the Website

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1188]
cc: @gdoyle1 

The primary color has the right color but not the right description:

<img width="540" alt="Screen Shot 2019-06-03 at 10 27 31 AM" src="https://user-images.githubusercontent.com/20118816/58809603-3fc18780-85ea-11e9-91e6-5560bac9d9bf.png">

The secondary color for alert it also incorrect:
<img width="524" alt="Screen Shot 2019-06-03 at 10 28 13 AM" src="https://user-images.githubusercontent.com/20118816/58809664-52d45780-85ea-11e9-8b35-87fe9e2231dd.png">

**Comment by rachael-phillips** [comment]
Are we ready to close this issue based on @lareplog most recent PR?

**Comment by rachael-phillips** [comment]
Closing because this is complete
