### ISSUE TITLE
Nav is causing bug

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1190]
on iPhone 8, Chrome, the nav is causing a bug where the nav is bleeding over its parent causing everything to be cut off. 

<img width="413" alt="Screen Shot 2019-06-03 at 10 41 55 AM" src="https://user-images.githubusercontent.com/20118816/58810650-5b2d9200-85ec-11e9-8185-3e8fd3574934.png">

**Comment by evwilkin** [comment]
This is no longer a problem.
