### ISSUE TITLE
Update React table in Pf-org to use pf component

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1197]
Related to #1152 

In the React workspace the table for the react props documentation uses the patternfly table component. Can we update pf-org to use this component too.  cc: @redallen

**Comment by rachael-phillips** [comment]
@redallen will #1218 resolve this?

**Comment by redallen** [comment]
I believe so @rachael-phillips !

**Comment by rachael-phillips** [comment]
I'm closing this issue as it has been resolved
