### ISSUE TITLE
Fixes for PF4 Website - Design Guidelines Tab

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#1199]
Identified needed fixes on PF4 Website for the Design Guidelines section of the website.
Fix(es needed outline in this document: 
[https://docs.google.com/document/d/18-OtALUdzgS5GKsKRxNOPtd_uNd3UCPW11RM_AlUIyE/edit?usp=sharing](url)

**Comment by rachael-phillips** [comment]
I'm closing because I believe this has been completed
