### ISSUE TITLE
Fixes for PF4 Website - Documentation | React Tab

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#1200]
Identified needed fixes on PF4 Website for the Documentation (React) section of the website.
Fixes needed outline in this document: 
https://docs.google.com/document/d/1UBH863m3KnZOOQ-ijFhsUgSnN7N53EzPOQzdhh0mIhQ/edit?usp=sharing

**Comment by bgliwa01** [comment]
Under About modal tab
-The "Show About Modal" buttons should be in sentence case to follow the PF4 guidelines

**Comment by bgliwa01** [comment]
Under Alert tab
-in examples all of the "x" buttons close out the alert except the first danger alert

**Comment by bgliwa01** [comment]
Under Card tab
-In the Props section, card should not be capitalized in the middle of a sentence
-In the Props section, the word "defaults" should be capitalized after a period

**Comment by bgliwa01** [comment]
Under Data list
-in the props section, the spacing of the charts don't match up with each other

**Comment by rachael-phillips** [comment]
I'm closing because I believe this has been completed
