### ISSUE TITLE
Fixes for PF4 Website - Documentation | HTML Tab

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#1201]
Identified needed fixes on PF4 Website for the Documentation (HTML) section of the website.
Fixes needed outline in this document: 
https://docs.google.com/document/d/1QiIkskdb0-suWFn_X7JhGdUg0O-wuTuMwpCww9xUpbU/edit?usp=sharing

**Comment by bgliwa01** [comment]
HTML
under components > popover
link for title component leads to 404

**Comment by rachael-phillips** [comment]
I'm closing because I believe this has been completed
