### ISSUE TITLE
Fixes for PF4 Website - Contribute Tab

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#1202]
Identified needed fixes on PF4 Website for the Get started section of the website.
Fixes needed outline in this document: 
https://docs.google.com/document/d/132XQyt3NwoLOYcBLdMAp8aSBLGHlxMVvGOjy8pP-OU4/edit?usp=sharing

**Comment by bgliwa01** [comment]
Under Develop Tab
-on steps to file a bug, only the fourth step includes a period, but there are other full sentences

**Comment by bgliwa01** [comment]
Under Design Tab
-the heading for Design Guidelines is labeled "Design Guideline"

**Comment by bgliwa01** [comment]
Under Design Tab
-In Design contribution lifecycle, design is spelled incorrectly in the 3rd bullet under 2. Propose a design

**Comment by mmenestr** [comment]
Closing because issue was fixed and merged.
