### ISSUE TITLE
Gatsby configuration - unify configuration across pf-next and pf-react

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-org#1208]
We need to unify the gatsby configuration used between pf-org, pf-next and pf-react (react-docs).  Currently, we are maintaining three separate gatsby sites, we should do the following:

- [x] Make sure all pf-next functionality is available in the gatsby site used by pf-org
- [x] Make sure all pf-react functionality is available in the gatsby docs used by pf-org
- [x] Add gatsby configuration from -org to pf-next (possibly using gitsubmodule or other mechanism to share code without copying
- [x] Add gatsby configuration from -org to pf-react (possibly using gitsubmodule or other mechanism to share code without copying
- [ ] Add env variable to hide certain parts of the site if deployed from pf-next or pf-react
- [x] Make sure PR deploys on both react/next use the new gatsby configuration for deploying

**Comment by redallen** [comment]
Closed by https://github.com/patternfly/gatsby-theme-patternfly-org . There's still cleanup to be done, but all the site configuration is shared.
