### ISSUE TITLE
Deprecate pf4.patternfly.org and patternfly-react.surge.sh/patternfly-4

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-org#1209]
After https://github.com/patternfly/patternfly-org/issues/1208 is complete:

- [ ] Replace pf4.patternfly.org with landing page or redirect to https://www.patternfly.org/v4/documentation/core/components/aboutmodalbox
- [ ] Replace patternfly-react.surge.sh/patternfly-4 with landing page or redirect to https://www.patternfly.org/v4/documentation/react/components/aboutmodalbox
- [ ] Scrub documentation to ensure all old links now point at patternfly.org
- [ ] Send e-mail to mailing list and add forum post

**Comment by redallen** [comment]
If we deprecate these, what's the expected way for devs to share workspace changes in between releases? Will we give them new workspace links or will we update create a "beta" section on patternfly.org that we try to release nightly? Updating patternfly.org nightly is slow and error-prone.

**Comment by evwilkin** [comment]
@dgutride @redallen are there any updated thoughts on next steps here?

**Comment by evwilkin** [comment]
Closing - new staging sites have been rolled out:

- https://core-staging.patternfly.org/
- https://react-staging.patternfly.org/
- https://extensions-staging.patternfly.org/
