### ISSUE TITLE
Add PatternFly 4 version information and release notes to patternfly.org

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-org#1211]
The latest release notes and version information for the following packages should be available with the code documentation.

Release notes can be a running log (prepended to with each milestone release).  We also need to make sure we can quickly show which versions the current documentation refers to.

For instance - the following NPM package information is necessary for the @patternfly packages that ship together:
@patternfly/patternfly: 2.8.2
@patternfly/react-core: 3.34.0
@patternfly/react-styles: 3.2.3
@patternfly/react-tokens: 2.5.3
@patternfly/react-table:2.9.0
@patternfly/react-charts: 4.0.1
@patternfly/react-inline-edit-extension: 2.5.0

**Comment by rachael-phillips** [comment]
@lboehling will be working on the design

**Comment by lboehling** [comment]
https://marvelapp.com/64d80gd/screen/60019520 here are a few design options for the Release anchor links on the versioning page. 

@dgutride @redallen what level of detail is needed for each release at the top of the page? I included a couple of options where the packages that shipped in each release are also called out. 

@rachael-phillips

**Comment by lboehling** [comment]
Final version: https://marvelapp.com/project/4251596/
sketch file: [PF.Org-ReleaseNotes.zip](https://github.com/patternfly/patternfly-org/files/3474108/PF.Org-ReleaseNotes.zip) 

Do we need a description under the Page title? or should I remove that from the mocks? @rachael-phillips @stacymcauliffe @dgutride @redallen

**Comment by rachael-phillips** [comment]
@dana @stacymcauliffe do you think we need a description for the release notes page?

**Comment by evwilkin** [comment]
Resolved in https://github.com/patternfly/gatsby-theme-patternfly-org/pull/119
