### ISSUE TITLE
Login page props table isn't responsive

### ISSUE THREAD

**Issue by bgliwa01** [patternfly/patternfly-org#1215]
in the react documentation, the table listing loginform props isn’t responsive while the rest are

**Comment by rachael-phillips** [comment]
@jschuler making you aware

**Comment by rachael-phillips** [comment]
Hi @bgliwa01 what is the example that isn't working responsively?

**Comment by bgliwa01** [comment]
<img width="963" alt="Screen Shot 2019-06-20 at 1 11 55 PM" src="https://user-images.githubusercontent.com/51342070/59867744-05334b00-935d-11e9-914e-98d8875b68e7.png">

The loginform props table in the screenshot above
