### ISSUE TITLE
Dark Mode Component Examples are affecting styling of workspace

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1219]
<img width="1031" alt="Screen Shot 2019-06-05 at 4 17 00 PM" src="https://user-images.githubusercontent.com/20118816/58987499-97f4b700-87ad-11e9-9745-cdc3503c9075.png">

**Comment by christiemolloy** [comment]
Looks like this is an upstream issue: @dgutride or @redallen can we make the dark mode preview styles specific to just the example?

<img width="828" alt="Screen Shot 2019-07-09 at 4 45 52 PM" src="https://user-images.githubusercontent.com/20118816/60921675-10490f00-a269-11e9-8b76-5445dde16a6b.png">

**Comment by redallen** [comment]
@jschuler is the dark mode master who understands how it works -- I don't fully.

**Comment by jschuler** [comment]
Fixed by #1279
