### ISSUE TITLE
Investigate how to display the left nav on documentation page

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-org#1233]
Currently we cannot see the other categories under "components" when on the documentation page because the list is extensive. Some solutions to this may include:
1. Collapsing all groups when user comes to page - this will be landing page for documentation and include a TOC or something like that
2. Limiting amount of items to show per category so that other collapsed categories are visible and allow for left nav scrolling

**Comment by evwilkin** [comment]
Closing - this looks outdated, the "Overview" section is expanded when visiting Documentation tab which allows for all left nav sections to be visible on the screen by default.
