### ISSUE TITLE
Search on mobile view broken

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1234]
<img width="389" alt="Screen Shot 2019-06-11 at 4 00 27 PM" src="https://user-images.githubusercontent.com/40275806/59302575-42635300-8c62-11e9-8eba-dccffb7b3e58.png">

Search does not fit window in mobile view. It needs a responsive treatment

**Comment by christiemolloy** [comment]
where are you seeing this? I see this on Chrome:
<img width="528" alt="Screen Shot 2019-06-11 at 4 08 50 PM" src="https://user-images.githubusercontent.com/20118816/59302990-42178780-8c63-11e9-9c0b-7e797ce83ecc.png">

**Comment by rachael-phillips** [comment]
I was seeing it on Chrome, too

**Comment by rachael-phillips** [comment]
I viewed this on an iPhone 8

**Comment by matthewcarleton** [comment]
I'm seeing this in Chrome still 
![IMG_6095](https://user-images.githubusercontent.com/287880/64448895-11ee5200-d0b5-11e9-9b9d-96f3c0b72ddc.PNG)

**Comment by rachael-phillips** [comment]
Thanks for adding this!

**Comment by evwilkin** [comment]
Closed in #1802
