### ISSUE TITLE
Table font issue

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1237]
The text on table needs to be corrected to Overpass:
<img width="625" alt="Screen Shot 2019-06-11 at 4 34 53 PM" src="https://user-images.githubusercontent.com/40275806/59304753-dafbd200-8c66-11e9-9846-94fd77284634.png">

Here is the link: https://staging.patternfly.org/v4/documentation/react/components/table/

**Comment by jschuler** [comment]
Are you referring to the text above the example or the text within the example? My impression is that the text surrounding the examples should be in Red Hat font as it matches the website font, but the examples and text in the examples should be Overpass

**Comment by rachael-phillips** [comment]
I'm just referring to the text in the in the Screen Shot I posted - the link is not Red Hat font, and should be.

**Comment by christiemolloy** [comment]
This font is coming upstream from the react repo so we can't change it on the website but we can change it in React, however I think its best to wait until we switch over to the Red Hat font to address it. @rachael-phillips

**Comment by evwilkin** [comment]
Fixed in patternfly/patternfly-react#2832
