### ISSUE TITLE
Login pattern: Copyediting

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#124]
Following are typos or copy changes for the [Login pattern](https://v2-patternfly.rhcloud.com/pattern-library/application-framework/login-page/#_ ). 

Key: _old text_ -> _new text_ (_where to find the text_)

- error messages -> error message (Overview)
- case by case -> case-by-case (Design, # 3)
- Login button -> Log In button (Design, # 3)
- "A “Remember username” checkbox" -> A “Remember Username” checkbox (Design, # 4)
- Due to security reasons -> For security reasons (Design, # 4)
- "Forgot username or password?" is a link -> "Forgot Username or Password?" is a link (Design, # 5)
- The login button appears -> The Log In button appears (Design, # 6)
- Apply text sparingly, do not -> Use text sparingly; do not (Design, # 7)
- If there are multiple strings, each message would appear on its own line and the area adjusts as needed in order to fit these messages. A couple examples of these messages include:  -> If there are multiple strings, each message appears on its own line, and the area adjusts as needed to fit these messages. Examples of these messages include: (Design, # 8)
- the value entered -> the values entered (Design, # 8)

**Comment by dlabrecq** [comment]
Done.
