### ISSUE TITLE
Indescriptive documentation of some components and layouts in v4

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-org#1241]
A few components and layouts don't go into well enough detail of what the component should be used for or what it even is.

Examples

#### HTML:

>Simple brand component.

#### React:

>Brand is used to place a product logotype on a screen.

Place it where? Is this component responsive? Why should I use it instead of an img or svg?

The props of Brand component in React is also non-descriptive. Should `src` be location of the file? The file itself?

#### HTML:

>Use a bullseye layout when there is a single child element, and that child is centered both vertically and horizontally in the parent.

#### React:

>None

#### HTML:

>A Gallery layout makes all of the children a uniform size, the children are displayed horizontally, and they wrap as needed.

#### React:

>None

#### HTML:

>A Grid layout framework including responsive columns, row spans and gutters. Breakpoints: base (no breakpoint value), -on-sm, -on-md, -on-lg, -on-xl. Example .pf-m-6-col-on-lg

#### React:

>None

#### HTML:

>A level is a layout that distributes the space between children evenly and it centers children on the x-axis. By default it positions the children horizontally, but on smaller devices it will position the children vertically.

#### React:

>None

#### HTML:

>Split layouts are meant for use in positioning items horizontally, with one of the items being the main content area.

#### React:

>None

What's the difference between Level and Split? When should I choose one over the other?

#### HTML:

>A stack layout is a layout that positions its items vertically. In a stack layout there is one primary item that will expand vertically to fill the container if needed.

#### React:

>None

#### React:

>None

What is toolbar doing if you're not using sections? Just adding margins and padding?

Sections seem to be putting it in a newline. Why use this instead of Grid?

**Comment by rachael-phillips** [comment]
@mcarrano @stacymcauliffe @dgutride making you aware. Perhaps we should brainstorm on how to make this documentation more helpful in the future

**Comment by mmenestr** [comment]
This has now been addressed with the addition of short descriptions...
