### ISSUE TITLE
Pattern Library Overview table broken

### ISSUE THREAD

**Issue by mattreid** [patternfly/patternfly-org#1246]
When I click on Pattern Library in the main nav on the site, I get taken to https://www.patternfly.org/pattern-library/ where I see a table that has no rows. Looking at the console, there's a 404 on pattern-status.json.

Seems like this table is broken. Not sure if that status call is used to populate the table somehow, or is unrelated?

**Comment by rachael-phillips** [comment]
@LHinson 's  proposal is to fix this by removing the table.
