### ISSUE TITLE
Aggregate Status Card: Copyediting

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#125]
Following are typos or copy changes for the [Aggregate Status Card](https://v2-patternfly.rhcloud.com/pattern-library/cards/aggregate-status-card/#/api) pattern.

Key: _old text_ -> _new text_ (_where to find the text_)

-  Make sure you are consistent and either opt to always use the icon or not. -> Be consistent; either use the icon on all the cards throughout your application, or don't use it in any. (Design, Header Area # 2)
- Icons should be used thoughtfully and sparingly. -> Use icons thoughtfully and sparingly. (Design, Header Area # 2)
- Ensure that the icon’s visual metaphor provides valuable meaning rather than pointless clutter. -> Ensure that the icon’s symbol metaphor provides valuable meaning. (Design, Header Area # 2)
- A status icon represents -> This represents (Design, Header Area # 1)
- If no objects exists -> If no objects exist (Design, Content Area # 3)
- with an underline on hover -> with an underline that appears on hover (Design, Content Area # 5)

**Comment by dlabrecq** [comment]
Done.
