### ISSUE TITLE
Styling bugs on site

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1258]
1. The about Modal example in React is still pulling in Red Hat font
2. All of the previews, including demos, are pulling in Red Hat font

cc @gdoyle1

**Comment by jschuler** [comment]
2nd issue is fixed. 1st one will be more tricky to fix as the modal is added to the root `<body>` and therefore outside the scope of the shadow root encapsulation. Will need to look more into it if we can also encapsulate the modals.
