### ISSUE TITLE
Login pattern: Example images

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#126]
Following are changes that need to be made to the example images in the [Login pattern](https://v2-patternfly.rhcloud.com/pattern-library/application-framework/login-page/#_).
- On Design tab, the hi-fi mockup shows “Forgot Username or Password?” but the wireframes in # 8 show “Forgot username or password?”.  The sample on the Code tab shows “Forgot username or password”.  All should show "Forgot username or password?"
- On Design tab, the hi-fi mockup shows “Remember Username” but the wireframes in # 8 show “Remember username”. The sample on the Code tab also shows “Remember username”.  All should show "Remember username"

**Comment by dlabrecq** [comment]
@LHinson Will need someone to create new images.

**Comment by mcarrano** [comment]
I can get someone to work on these updates.  @kybaker Do you know where original source images (i.e. PSD files) live?  Or should we just recreate them?

**Comment by kybaker** [comment]
@mcarrano I have the PSD - Here is the Dropbox link: https://www.dropbox.com/s/umcm8g1znu6fm8d/PF-Login_2015-08-26.psd?dl=0

**Comment by mcarrano** [comment]
Thanks, @kybaker

**Comment by zhutaoredhat** [comment]
<img width="590" alt="2017-05-19 4 45 04" src="https://cloud.githubusercontent.com/assets/13375283/26240150/97de92a6-3cb2-11e7-8b7e-525552043bf0.png">
<img width="613" alt="2017-05-19 4 45 15" src="https://cloud.githubusercontent.com/assets/13375283/26240149/97db5226-3cb2-11e7-8d09-5c6b68adc8ac.png">
One more inconsistent. Application Name: The application or project name uses a combination of Open Sans Extra Bold and Open Sans Regular. All of the letter is capitalized. The logo on the right top corner didn't display either.

**Comment by zhutaoredhat** [comment]
Hi@kybaker. I had uploaded some mockups here. We had some questions about how the inline alerts should appear in the login page and would love your input. @mcarrano 
Login Page （Fix letter case）
![1](https://cloud.githubusercontent.com/assets/13375283/26437112/bcf360d6-414d-11e7-95e3-7d33c23e9bfd.png)
![2](https://cloud.githubusercontent.com/assets/13375283/26437113/bcf84880-414d-11e7-9810-56b35da36b14.png)

Inline Notifications 
![3](https://cloud.githubusercontent.com/assets/13375283/26437114/bcf928e0-414d-11e7-9d18-12f0890e4b44.png)
![4](https://cloud.githubusercontent.com/assets/13375283/26437116/bcfc7be4-414d-11e7-8b98-df59a32bec7d.png)
![5](https://cloud.githubusercontent.com/assets/13375283/26437115/bcfbb6c8-414d-11e7-991b-bfee4cdba1fa.png)

**Comment by mcarrano** [comment]
@kybaker Please take a look and let us know what you think.

**Comment by mcarrano** [comment]
@kybaker and I discussed. Let's move forward with these. @zhutaoredhat please go ahead and create a PR to update the library.

**Comment by LHinson** [comment]
Closing since this has been merged.
