### ISSUE TITLE
Context Selector in React is broken

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1261]
If you go to this link you'll see that it isn't working. The search isn't working, and when you click an item in the dropdown it doesnt get selected.

https://www.patternfly.org/v4/documentation/react/components/contextselector/

cc: @rachael-phillips

**Comment by rachael-phillips** [comment]
@christiemolloy is this a problem with the React workspace or the website?

**Comment by christiemolloy** [comment]
@rachael-phillips its working in the react workspace but not the website, same for the dropdown

**Comment by evwilkin** [comment]
This looks to be resolved now.
