### ISSUE TITLE
Add Sparkine chart to Charts design guideline doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1266]
Sparkline is being added to the Charts library as a new variant of an Area chart. We should update the Charts guidelines (https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/charts) to include usage information for these.

For PF3 documentation, see: https://www.patternfly.org/pattern-library/data-visualization/sparkline/

**Comment by gdoyle1** [comment]
@mcarrano Added my draft of documentation here: https://docs.google.com/document/d/1C8wtOHl7piHUMBQ3vR1PeNCHRiu00QCCmuyLnhG03vA/edit?usp=sharing. I attempted to put the documentation in context within the rest of the charts stuff so you'll see it highlighted in yellow!
