### ISSUE TITLE
RFE: Better linking to sources on GitHub from the website

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-org#1269]
I frequently find myself looking around in the patternfly-react source when I'm trying to consume our components in an app, to get a reference for their behavior and how they actually use the props I'm passing in. Thorough documentation of the props is great, but sometimes a single sentence doesn't give me quite as much info as I'm looking for and I want to check the source.

Currently to do this, I need to either search for the file in my local clone of patternfly-react, or navigate to it on GitHub. I typically already have the patternfly website open to that component's documentation, so I think it would be really nice to have a link on each component's docs page to the source code of that component on GitHub.

Right now on the website, we have one github icon in the footer that links to the core repo (https://github.com/patternfly/patternfly) and if you dig around and find this page: https://www.patternfly.org/v4/contribute/developers it has links specifically to the issues lists for the pf-next and pf-react repos.

I think linking to specific component source files or at least just to the main pf-react repo somewhere prominent on the website would be not only convenient, but would encourage community contributions.

**Comment by rachael-phillips** [comment]
@dgutride what do you think about this approach. Is this something we would want to contribute to the site design?

**Comment by evwilkin** [comment]
Closing in favor of https://github.com/patternfly/patternfly-org/issues/1785 - This is being incorporated as part of the redesign work started in that issue
