### ISSUE TITLE
Aggregate Status Card: Example images

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#127]
Following are changes to make to the example images in the [Aggregate Status Card ](https://v2-patternfly.rhcloud.com/pattern-library/cards/aggregate-status-card/#/api)pattern.
- Design tab, “Top Accent (optional):”  If it’s optional, show one example with and the other without.  Same for “Object Icon.”
- On the 793 Hosts image in “Content Area,” move the pink callouts so they don’t overlay the content.
- On the 856 Hosts image in “Content Area,” move the cursor so it doesn’t obscure the underline (which is the thing we’re trying to demonstrate).

**Comment by dlabrecq** [comment]
@LHinson Will need someone to create new images.

**Comment by yih-wang** [comment]
I'm interested in working on this issue. @kybaker Do you know where the source file lays? Thanks.

**Comment by zhutaoredhat** [comment]
@mcarrano The images had been updated. please have a review~ https://github.com/patternfly/patternfly-design/pull/667

**Comment by LHinson** [comment]
This has been addressed so I'm closing!
