### ISSUE TITLE
Page component demos are not full height

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1272]
https://www.patternfly.org/v4/documentation/react/demos/pagelayout/

https://www.patternfly.org/v4/documentation/core/demos/page

If you go to any of the Page demos, they aren't the full height of the browser. Every extra element between `<body>` and `<div class="pf-c-page">` should have `height: 100%;` applied. Is this something we can fix?

**Comment by jschuler** [comment]
They're full height now
