### ISSUE TITLE
documentation overview page and example page differ in style

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-org#1274]
I got a bit confused about what's the correct style for the navigation.
The [documentation overview page](https://www.patternfly.org/v4/documentation/react/components/aboutmodal) has a blue line to the left, but the [navigation example](https://www.patternfly.org/v4/documentation/react/demos/pagelayout/pagelayoutsimplenav/) page does not have this blue line in the navigation. So I'm a bit confused what's the right way to do it.

**Comment by andreasn** [comment]
Documentation overview page:
![Screenshot from 2019-07-03 12-19-54](https://user-images.githubusercontent.com/209895/60584197-e4bbb580-9d8c-11e9-9e24-6317408a2e04.png)

Navigation example:
![Screenshot from 2019-07-03 12-20-20](https://user-images.githubusercontent.com/209895/60584224-f69d5880-9d8c-11e9-8497-fb25abf568ba.png)

**Comment by andreasn** [comment]
Somewhat related, the text color and font seems to differ.

**Comment by jschuler** [comment]
The correct style is the one in the examples, the website consumes PatternFly but with additional style overrides
