### ISSUE TITLE
Background image example page is blank

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-org#1275]
The [preview](https://www.patternfly.org/v4/documentation/react/components/backgroundimage/) shows a nice background, but the [example page](https://www.patternfly.org/v4/documentation/react/components/backgroundimage/simplebackgroundimage/) is all blank for some reason.

**Comment by andreasn** [comment]
Could be the same as issue #1270, but not sure.

**Comment by andreasn** [comment]
This only seem to affect the react page, as the [HTML example](https://www.patternfly.org/v4/documentation/core/components/backgroundimage-full?component=Background%20image%20example) works fine.

**Comment by jschuler** [comment]
Fixed
