### ISSUE TITLE
Create storybook locations for product organizations

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-org#1278]
We'd like to create a storybook deployment for the Integration products and Openshift similar to what we see here:

https://cloud.redhat.com/docs/storybook?path=/story/welcome--getting-started

This should involve creating a repository, deploying the storybook and adding a dns alias for those sites (openshift.patternfly.org, integration.patternfly.org).

**Comment by evwilkin** [comment]
No longer needed - closing
