### ISSUE TITLE
Change demo "data table" to "table"

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-org#1286]
Referencing #1280 

Update occurrences of "data table" within the demo to use "table"

**Comment by mcoker** [comment]
@gdoyle1 we have a demo in the core workspace called "data table" as well - https://pf4.patternfly.org/demos/DataTable/examples/

Should we rename that?

**Comment by gdoyle1** [comment]
@mcoker @jschuler I realized issues will need to be created in both core and react to rename the "data table" occurrences to "table" because I can't fix it myself! Should I create new issues in pf-next and pf-react?

**Comment by mcoker** [comment]
@gdoyle1 I have an issue for core - https://github.com/patternfly/patternfly-next/issues/1814

**Comment by rachael-phillips** [comment]
This should be resolved now.
