### ISSUE TITLE
Keyboard nav funkiness - audit needed

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-org#1287]
On the surge website, keyboard nav requires tabbing through the full list of components before getting to the page content. 

On the main website, I quickly get to the page content, but can't figure out how to get to the nav itself with keyboard navigation. That might be due to my inexperience, but I'm thinking a quick audit wouldn't hurt! @jgiardino is this something you could take a look at?

The solution for the surge website problem is adding a "Jump to content" (sometimes called skip nav) button which only appears when the user hits their first tab, and is the first item of focus. 

Reference: https://www.w3.org/TR/WCAG20-TECHS/G1.html
Bonus NCSU!: https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/mouse-and-keyboard-events/skip-to-main-content/

**Comment by jessiehuff** [comment]
This was fixed with #[1588](https://github.com/patternfly/patternfly-org/pull/1588). Skip to contents were added, and we currently do a monthly a11y audit.
