### ISSUE TITLE
React modal example button location incorrect

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1290]
In the react documentation, the location of the buttons in the modal is incorrect. As per design standards the buttons should be on the LEFT but in the documentation it is on the RIGHT.

https://www.patternfly.org/v4/documentation/react/components/modal/
![Xnip2019-07-16_14-20-09](https://user-images.githubusercontent.com/23172038/61297782-dcc03480-a7d4-11e9-949e-de2490f8200b.jpg)

**Comment by rachael-phillips** [comment]
Hi @katierik I'm going to close this issue because this is something we are currently updating in the Next repo.
