### ISSUE TITLE
Fix a11y issues in site: All page content must be contained by landmarks

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1295]
This issue occurs across the entire site: "All page content must be contained by landmarks"

You can click on any page and run the axe audit in order to reproduce the error. 

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by redallen** [comment]
Closing in favor of #2158
