### ISSUE TITLE
Fix a11y issue in React tables

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1304]
This is on multiple pages https://www.patternfly.org/v4/documentation/react/components/accordion/

The a11y issue is:
1. All th elements and elements with role=columnheader/rowheader must have data cells they describe

<img width="486" alt="Screen Shot 2019-07-17 at 9 50 03 AM" src="https://user-images.githubusercontent.com/20118816/61380938-46dde580-a878-11e9-8489-ed631a4e216d.png">

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by jessiehuff** [comment]
This issue appears to be fixed by one of our updates.
