### ISSUE TITLE
Fix a11y issue in Documentation/React/Breadcrumb

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1308]
https://www.patternfly.org/v4/documentation/react/components/breadcrumb/

There is one type of a11y issue to work on (the others are handled in separate issues):
1. Heading levels should only increase by one

<img width="495" alt="Screen Shot 2019-07-17 at 9 59 51 AM" src="https://user-images.githubusercontent.com/20118816/61381830-a25ca300-a879-11e9-8b5b-6c929729c7f2.png">

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by jessiehuff** [comment]
This issue was solved in #1588. 🙂
