### ISSUE TITLE
Fix a11y issues in Documentation/React/Card

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1309]
https://www.patternfly.org/v4/documentation/react/components/card/

There is 1 type of a11y issue (the rest is covered in separate issues):
1. Images must have alternate text

<img width="484" alt="Screen Shot 2019-07-17 at 10 01 42 AM" src="https://user-images.githubusercontent.com/20118816/61382000-e51e7b00-a879-11e9-8d70-95a61726e7e0.png">

**Comment by jessiehuff** [comment]
This issue looks like it's been solved. 🙂
