### ISSUE TITLE
Fix a11y issues in Documentation/React/Nav

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1316]
https://www.patternfly.org/v4/documentation/react/components/nav/

There are __ types of a11y issues (the rest are covered by separate issues):
1. Heading levels should only increase by one
2. Banner landmark must not be contained in another landmark
3. Document must not have more than one banner landmark
4. The skip-link target should exist and be focusable

<img width="490" alt="Screen Shot 2019-07-17 at 10 14 11 AM" src="https://user-images.githubusercontent.com/20118816/61382916-a4276600-a87b-11e9-9302-762323a69e43.png">

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by redallen** [comment]
Closing in favor of #2158
