### ISSUE TITLE
Fix a11y issues in Documentation/React + HTML /Page

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1317]
https://www.patternfly.org/v4/documentation/react/components/page/
https://www.patternfly.org/v4/documentation/core/components/page/

There are 4 types of a11y issues in this page:
1. Banner landmark must not be contained in another landmark
2. Main landmark must not be contained in another landmark
3. Document must not have more than one banner landmark
4. Document must have one main landmark

<img width="499" alt="Screen Shot 2019-07-17 at 10 16 23 AM" src="https://user-images.githubusercontent.com/20118816/61383062-f2d50000-a87b-11e9-9dce-72ea3cfa28e8.png">

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by redallen** [comment]
Closing in favor of #2158
