### ISSUE TITLE
Fix a11y issue in Documentation/React/components/Radio

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1318]
https://www.patternfly.org/v4/documentation/react/components/radio/

There is one type of a11y issue in this page(the rest are covered by separate issues):
1. Radio inputs with the same name attribute value must be part of a group

<img width="485" alt="Screen Shot 2019-07-17 at 10 18 13 AM" src="https://user-images.githubusercontent.com/20118816/61383205-33cd1480-a87c-11e9-90e7-b1d016c85420.png">

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by jessiehuff** [comment]
This issue looks to be solved, likely from #[2567](https://github.com/patternfly/patternfly-react/pull/2567). 🙂
