### ISSUE TITLE
Update Login design guidelines to reflect new placement of language selector

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1321]
The images on the Login page reflect the old placement of the language selector. These need to be updated to reflect the new designs.

https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/login

**Comment by mmenestr** [comment]
@mceledonia hey, do you mind adding screenshots of the new design here, or even the sketch file with them in it?

**Comment by japhilli-RH** [comment]
@mceledonia will be creating new mockups for the page!

**Comment by japhilli-RH** [comment]
@mceledonia says we can close this and that he can add the mockups later!
