### ISSUE TITLE
Fix a11y issues in Documendation/React/Charts

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1322]
https://www.patternfly.org/v4/documentation/react/charts/chartarea/

There are 2 types of a11y issue in every chart type:
1. Elements must have sufficient color contrast
2. ARIA attributes must conform to valid values

<img width="494" alt="Screen Shot 2019-07-17 at 10 35 40 AM" src="https://user-images.githubusercontent.com/20118816/61384463-a50dc700-a87e-11e9-9fe5-d7620e4821bd.png">

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by christiemolloy** [comment]
@seanforyou23 should I file an issue in React to look at a11y for charts? Or can we say this is not an issue?

**Comment by seanforyou23** [comment]
Yea I'd say file an issue in [patternfly-react](https://github.com/patternfly/patternfly-react) and if we can solve it on our end we likely will. If we can't solve in on our end for whatever reason, then we'll know the specifics and can look at paths forward from there.

**Comment by redallen** [comment]
Closing in favor of #2158
