### ISSUE TITLE
Fix a11y issues in Documentation/React/Global-CSS-Variables

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1323]
https://www.patternfly.org/v4/documentation/react/css-variables/

There is 1 type of a11y issues (the rest are covered by separate issues
1. Heading levels should only increase by one

<img width="488" alt="Screen Shot 2019-07-17 at 10 38 51 AM" src="https://user-images.githubusercontent.com/20118816/61384684-16e61080-a87f-11e9-9897-a74b6bd8a7f4.png">

Steps to reproduce the a11y errors:

1. Right click on the page and choose inspect
2. In the developer tools, choose "axe" from the top menu
3. Run the test

**Comment by jessiehuff** [comment]
This issue appears to be solved. 🙂
