### ISSUE TITLE
Icon page improvements

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1358]
The implementation of the [Icon page](https://www.patternfly.org/v4/design-guidelines/styles/icons) on the website should be refactored to allow for searchable descriptions and to be more easily maintainable by non-developers. Specific changes include:

* Decouple the Icons page from the core repo by building the page from a separate JSON file to be created in -org.
* Include a field for description along with name in each icon record to allow for usage information to be associated with the icon and make that description searchable and displayable on the page.
* Include both commonly used 'fa' icons along with pf-icons so that we can point to fa icons that are adopted for use in PatternFly components (like in Alerts).

Once this structure is built, it can easily be maintained by any website content maintainer and updated as new icons are added (or icons are revised).   

cc: @rachael-phillips @jschuler

**Comment by andybraren** [comment]
Could this also include adding `id`s to each item to make it easier to point folks to a specific icon via the URL? I notice that the search field in the top-right corner adds anchors to the end of URLs like this, but without an `id` they don't jump to anything:

`https://www.patternfly.org/v4/design-guidelines/styles/icons#resources-full-popover-bottom-header`

**Comment by mcarrano** [comment]
Going to close this one out in favor of newer issue #1687
