### ISSUE TITLE
Lists and Tables design doc link to Toolbars

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-org#1376]
In the Lists and Tables design documentation, the [Standard data list](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/lists-and-tables#standard-data-list) section includes the following link to the Toolbar design document:
https://www.patternfly.org/v4/design-76afa8e1a342ba004a5ea32666a06c06.md

I expected it to take me here instead:
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/toolbar

**Comment by rachael-phillips** [comment]
This should be resolved now, so I'm going to close this
