### ISSUE TITLE
Request to include inline table example in documentation

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-org#1378]
We have this really helpful example of inline editing for table

https://patternfly-react.surge.sh/patternfly-4/inline%20table/inlineedit/

But it's not included in the new website documentation. Some people are not finding this example, can we add it to the docs like the rest of the demos/examples? This would help a lot with the discoverability of these more advanced usages.

<img width="1332" alt="Screen Shot 2019-07-30 at 9 14 11 AM" src="https://user-images.githubusercontent.com/5942899/62132109-6cbcae80-b2aa-11e9-9fb4-b3f75179660d.png">

**Comment by mcarrano** [comment]
I have opened a new issue to adding inline edit usage documentation for tables here: https://github.com/patternfly/patternfly-org/issues/1450  Will close this as a duplicate.
