### ISSUE TITLE
Red Hat font on site

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1380]
This epic will include several changes we need to see to transition smoothly to Red Hat font
- All React and HTML examples must be updated
- Red Hat font must be updated on the Typography page
- Red Hat font announcement should go out to blog, forum, mailing list.
- Red Hat font should be accessible from release notes with a link to Red Hat font document
- Red Hat font document should be hosted on GitHub or other place that is not Google docs.

**Comment by rachael-phillips** [comment]
**A list of the items we'll need to get aligned and completed (Rache is creating an epic for this):**

**PF website**
- Update the typography page on the PF website to reflect RH font
      - I have an action to set up time with Gina for help with this
      - We don't want to make this change until we're ready to announce.
- Update all component and demo examples (Core and React) to use RH font on the PF website
        - We'll need help from Joachim or Zack for this
        - We don't want to make this change until we're ready to announce. Should be timed with the updates to typography page

**Sketch files**
- Update sketch resources to Red Hat font

**Documentation**

- Move Coker's documentation about the new font opt-in process from Google doc to a PF location - something that makes sense to host the information long term

     - @dana @leslie @jan Where should this live? An md file in the PF next repo? Somewhere else?
     - Add info to the release notes about the typography change
            - Link to opt-in docs from here

**Communication to the community**

- Write and post a blog to let the community know about the change
          - Link to opt-in docs from here
- Blog promotion
          -  Email to mailing list with link to blog
          - Forum post with link to blog and/or opt-in docs
          - Twitter post with link to blog

We might also want to include a note or inline alert on the typography page alerting users to the change (Something like "We've recently updated our typography from Overpass to Red Hat font. Learn more about how you can opt-in and start using the new font") with a link to the opt-in docs. 

**General messaging:** 
We're moving PatternFly from Overpass to the new Red Hat font. You can continue to use Overpass in your projects or you can opt-in to the updated font. Include a link to the information on how users can opt-in and begin using the new font.

**Comment by jan** [comment]
@rachael-phillips I am not sure, but I trust you will make a great decision on this.

**Comment by rachael-phillips** [comment]
Sorry @jan for the wrong tag - I had an auto-tagging problem there!

**Comment by gdoyle1** [comment]
@rachael-phillips The sketch assets won't be transferred to Red Hat font until the QA period is over for the current one... I'd say it's about 50% done right now and we are making updates based on that feedback as it comes in!

**Comment by rachael-phillips** [comment]
Thanks so much for the update, @gdoyle1 !

**Comment by rachael-phillips** [comment]
I'm closing this epic because it has been completed
