### ISSUE TITLE
Add root documentation pages

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#1385]
We might want the user to not be instantly taken to AboutModal's documentation, but instead have a landing page which greets them with some info about the documentation. We could possibly include the promoted package versions here, among other things.

This is more intuitive because the left side nav will be collapsed, showing all available options.

Relevant pages:
https://www.patternfly.org/v4/documentation/react
https://www.patternfly.org/v4/documentation/core

**Comment by rachael-phillips** [comment]
Hi @redallen do you think this is still necessary once we build out our release note pages more?

**Comment by redallen** [comment]
Yes @rachael-phillips, design-wise I don't think our release notes should be the landing page. I think I opened this issue after we came to that conclusion from some discussion.
