### ISSUE TITLE
Not sufficient spacing for two rows of labels/chips for "components used section"

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#1388]
![image](https://user-images.githubusercontent.com/7924406/62479403-6aab9180-b77b-11e9-9ea8-bc2a0c684bf6.png)

**Comment by rachael-phillips** [comment]
Totally agree!

**Comment by rachael-phillips** [comment]
@LHinson I think the question would be here do we want to reintroduce this feature if we find a way to visually style it well?

**Comment by evwilkin** [comment]
Closing in favor of #1434 which includes new approach for related components and is leading towards how to style the related components link. These were originally removed for redesign in https://github.com/patternfly/patternfly-org/pull/2051
