### ISSUE TITLE
Sketch - Pop-over component incomplete

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1389]
The Sketch library component "Popover/No Header or Footer" is incomplete. 
When expanding, the text does not go to two lines even though there is spacing.
The triangle pointer & box do not have a shadow, which makes it almost impossible to see on a white background.
![Xnip2019-08-05_14-10-50](https://user-images.githubusercontent.com/23172038/62485616-2b853c80-b78b-11e9-948a-e025bdc7f6e5.jpg)

**Comment by gdoyle1** [comment]
@katierik Closing this and moving it to patternfly-design-kit repo
