### ISSUE TITLE
Opt-in visual for website

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1390]
Any opt-in options that are the design standard should specify this in the documentation on the website 

latest visuals: https://marvelapp.com/666e09a/screen/60830370

**Comment by lboehling** [comment]
@rachael-phillips here are some visual options for the flagging opt-in components: https://marvelapp.com/666e09a/screen/60830370. The side nav labels could be used in addition to the inline page alerts/labels? Let me know what you think!

**Comment by rachael-phillips** [comment]
Hi @lboehling This looks fantastic, and I think this is comprehensive of what we would need. Let's see what the group says tomorrow because we may need to refine the design from there.

**Comment by jschuler** [comment]
Closed with https://github.com/patternfly/patternfly-org/pull/1443
