### ISSUE TITLE
Add Red Hat typography opt-in documentation to repo

### ISSUE THREAD

**Issue by stacymcauliffe** [patternfly/patternfly-org#1393]
Move typography opt-in documentation from [this google doc](https://docs.google.com/document/d/1NnWmhwuY2rC53HgQIpQYUYYcv8NqSQ7IrHaxo5hVM3Q/edit?usp=sharing) to an .md file on the pf-next repo.

**Comment by rachael-phillips** [comment]
Closing because this has been complete
