### ISSUE TITLE
Update component and demo examples on the pf website to use Red Hat font

### ISSUE THREAD

**Issue by stacymcauliffe** [patternfly/patternfly-org#1394]
Currently, component and demo examples on the pf website to use Overpass. In the workspaces, we are using RH font. We'll need to switch the examples on the website to use RH font. 

We want to time this switch to coordinate with the updates to typography page on the website and the blog announcement to the community.

**Comment by janwright73** [comment]
@jschuler - let's make sure that we document this opt in font option in a similar way as the dark nav and left aligned buttons on the modal.

**Comment by rachael-phillips** [comment]
Closing because this has been complete
