### ISSUE TITLE
Version Switcher

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1398]
Documentation released that is out of date needs to be publicly accessible - this can be reached using a version switcher, archived somewhere (or in some other way). Users should be able to quickly identify which version the documentation refers to and view documentation for older releases.

Discussion is needed about whether we do this for major breaking changes (so when @patternfly/patternfly bumps from 2.x to 3.x - do we archive and allow people to switch back to 2.x) and then just update the 3.x visible documentation until we hit 4.x. We also need to discuss what this means for the @patternfly/react-* packages which can move independently. A version switcher for those packages could be harder to embed. We could just bump the switcher for each milestone and only have major breaking milestones once a quarter or on some other cadence.

**Comment by lboehling** [comment]
Marvel prototype: https://marvelapp.com/9bfe268/screen/61545448

I used plain dropdown (just text + icon) with default color to match the light gray icon/text of the search menu. On hover the text/icon lightens to white, and a white underline shows. Underline thickens to 2px (same active underline thickness in the standard default dropdown, and also appears under the search field when it is active). Dropdown is grouped into two categories: the latest release and past releases, and also includes a link to view all release notes.

**Comment by rachael-phillips** [comment]
Hi @lboehling this looks fantastic! @redallen, @dgutride, @LHinson will you review the design above and let us know if we are ready to move forward with development?

**Comment by rachael-phillips** [comment]
Requirements captured about version switcher:

- The version numbers should exist in body of page
- We would like to create a release page that only includes all of the version numbers from Core and React, which would serve as the Documentation homepage
- When a user selects a very old release, the dropdown states will not change - they will be static
- Eventually pre-releases should live in the dropdown, but in the interim they will live on the site and will not be available via the dropdown, because that will be future functionality we build in.
- The "Release Notes" tab of the dropdown will default to the combine core and React doc page

**Comment by redallen** [comment]
I'm not sure about the following requirements:

> We would like to create a release page that only includes **all** of the version numbers
Can we just support since version `2019.08` when we started using the theme? Backfilling more versions than that is technically difficult.
> The "Release Notes" tab of the dropdown will default to the combine core and React doc page
Didn't we decide against having "Release Notes" in the dropdown? I'm not sure combining them is feasible. Right now I'm implementing the dropdown to stay on the same page when context switching.

I'll open a PR soon and we can iterate from there.
