### ISSUE TITLE
Trend Card: copyediting

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#140]
Following are typos or copy changes for the [Trend Card](https://v2-patternfly.rhcloud.com/pattern-library/cards/trend-card/#/_overview) pattern.

Key: _old text_ -> _new text_ (_where to find the text_)

- The location of the actual value or percentage should be shown. -> Shows the current value or percentage. (Design, Card with a Single Trend #2)
- (ƒoptional) -> (optional)  (Design, Card with a Single Trend #3)
- The location of the actual value should be shown to the right of the sparkline. -> Shows the current value to the right of the sparkline. (Design, Card with Multiple Trends #4)
- Card With Single Trend Chart -> Card with Single Trend (Code)
- Card With Multiple Trends -> Card with Multiple Trends (Code)

**Comment by dlabrecq** [comment]
Done.

The last two will have to be modified in Angular-PatternFly.
