### ISSUE TITLE
Documentation update: Get Started Designer tab

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#1405]
Update this page: [https://www.patternfly.org/v4/get-started/designers](https://www.patternfly.org/v4/get-started/designers)
to have the content found in this document: [https://docs.google.com/document/d/1nC0dc8t7NSr1wP4fl-FbWfpgH4KvCXIHpM422OtSsdA/edit?usp=sharing](https://docs.google.com/document/d/1nC0dc8t7NSr1wP4fl-FbWfpgH4KvCXIHpM422OtSsdA/edit?usp=sharing)

Images in the document can be found in [this downloadable sketch document ](https://sketch.cloud/s/ggDwz)in the get started page

**Comment by rachael-phillips** [comment]
I'm closing this issue because it has been complete
