### ISSUE TITLE
Add embedded assistance design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1406]
Add guidelines to go along with https://github.com/patternfly/patternfly-next/issues/1893

**Comment by stacymcauliffe** [comment]
Draft doc: https://docs.google.com/document/d/1v-_QA2DuDzKk73OJG5TZDTdQwnSQBec6J-Q-yKPRKKs/edit?usp=sharing

**Comment by mcarrano** [comment]
This work is complete and a PR was sent to update the website.
