### ISSUE TITLE
Various typos on website

### ISSUE THREAD

**Issue by kywalker-rh** [patternfly/patternfly-org#1407]
**Charts**
• Line chart https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/charts#line-chart
   • A line chart plot… (add “s”)
<img width="514" alt="Screen Shot 2019-08-14 at 11 01 04 AM" src="https://user-images.githubusercontent.com/53235442/63042778-ba373f00-be98-11e9-8130-77f95d782cfe.png">

**Data input**
• Useage: Bound-entry controls https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/data-input#usage-bound-entry-controls
   • … As a result, field should be is unnecessary. (?... Not sure what this is saying)
<img width="1351" alt="Screen Shot 2019-08-14 at 11 00 15 AM" src="https://user-images.githubusercontent.com/53235442/63042858-efdc2800-be98-11e9-9f73-13094350e644.png">

**Filters - Same comment for Attribute-value, Faceted, and Type-ahead**
• Attribute-value (textbox) filters https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#attribute-value-textbox-filters
   • After the image the “1... 2…” seem like they should be bulletized, or otherwise made more obvious, they were difficult to reference in the in-line text
   • They are consistent in this one page (Filters) but all numbered captions are bulletized in the rest of the “Usage and behavior” pages
<img width="1411" alt="Screen Shot 2019-08-14 at 11 08 03 AM" src="https://user-images.githubusercontent.com/53235442/63042927-1bf7a900-be99-11e9-88af-387c8bdc021f.png">

• Faceted https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#faceted-checkbox-filters
<img width="1401" alt="Screen Shot 2019-08-14 at 11 09 27 AM" src="https://user-images.githubusercontent.com/53235442/63042992-3b8ed180-be99-11e9-9e5a-2fd7c47e3155.png">

• Type-ahead https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#type-ahead-filters
<img width="1394" alt="Screen Shot 2019-08-14 at 11 11 05 AM" src="https://user-images.githubusercontent.com/53235442/63043047-5a8d6380-be99-11e9-8fa4-0e70f8cc69de.png">

• Complex faceted filter https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters#when-to-use-6
  • … for example, and search field and… (delete the first “and”)
<img width="1358" alt="Screen Shot 2019-08-14 at 11 15 15 AM" src="https://user-images.githubusercontent.com/53235442/63043146-a3451c80-be99-11e9-984f-95c217a5b450.png">

**Login**
• Single Sign On (SSO) https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/login#single-sign-on-sso
   • Additional SSO elements - After the image the “1... 2…” seem like they should be bulletized, or otherwise made more obvious (same as Filter comments)
<img width="1243" alt="Screen Shot 2019-08-14 at 11 18 18 AM" src="https://user-images.githubusercontent.com/53235442/63043213-c243ae80-be99-11e9-9963-2ee38d86908e.png">

**Progress Bar**
• Styling https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/progress-bar#styling
   • A green progress bar… and the accompanying the check-circle… (delete second “the”)
<img width="1344" alt="Screen Shot 2019-08-14 at 11 24 22 AM" src="https://user-images.githubusercontent.com/53235442/63043258-dab3c900-be99-11e9-8cc4-48d1814b8601.png">

• Content https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/progress-bar#content
   • Titles should… that is being measure. (add “d”)
<img width="701" alt="Screen Shot 2019-08-14 at 11 25 39 AM" src="https://user-images.githubusercontent.com/53235442/63043294-eef7c600-be99-11e9-89ec-053cf7b109cb.png">

**Wizard**
• Review and completion https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/wizard#review-and-completion
   • After the third picture the 1… 2… should be bulletized
<img width="1416" alt="Screen Shot 2019-08-14 at 11 28 45 AM" src="https://user-images.githubusercontent.com/53235442/63043328-00d96900-be9a-11e9-9e7a-6cfdcf03a243.png">

**Comment by janwright73** [comment]
For Data Input item - consulted @mcarrano, he agreed 'As a result, field should be is unnecessary.' >> 'As a result, field validation should be unnecessary'

**Comment by janwright73** [comment]
packages/patternfly-4/content/design-guidelines/usage-and-behavior/forms/img/all-required.png - is missing; appears to be deleted by Merge pull request #1422 from patternfly/card-view-docu** @mcarrano - any back story on this image?  should it be recovered?  
http://localhost:8000/design-guidelines/usage-and-behavior/forms - search/find 'All required' to see missing image.

**Comment by rachael-phillips** [comment]
Closing this issue as it has been resolved
