### ISSUE TITLE
Trend Card: substantive edit

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#141]
On the Design tab on the Trend Card, these should be added to the content:
- On # 5 Total Value: We should provide guidance on how many decimal points to show (if any and when).
- Unit of Measurement: In both instances (# 4 in the first section, # 6 in the second), link to the T&W for preferred/correct abbreviations.

**Comment by dlabrecq** [comment]
@LHinson Please take a look at this one.

**Comment by Essjaysee** [comment]
Regarding unit of measurements, the section I was thinking about has not yet been published to the T&W, so that link will need to wait until then.

**Comment by LHinson** [comment]
I'm closing this one for now as we don't have standards available yet to point to for this. This would need to go to pf-design first. @stacymcauliffe is looking into providing more robust guidance for T&W for us and PF will update once that is available.
