### ISSUE TITLE
fix a11y issues in documentation/react/wizard 

### ISSUE THREAD

**Issue by lareplog** [patternfly/patternfly-org#1410]
one type of issue to address:

- id attribute value must be unique 

<img width="400" alt="Screen Shot 2019-08-16 at 10 09 08 AM" src="https://user-images.githubusercontent.com/50547577/63173454-ee803c00-c00d-11e9-8076-e54ade1cbe9c.png">

**Comment by jessiehuff** [comment]
This issue appears to be solved in one of our updates. 🙂
