### ISSUE TITLE
Inconsistent documentation for forms

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#1415]
The documentation for forms [1] is confusing because it include two variations of the (?) - one that is solid and one that is an outline. After getting guidance from @kybaker, he says: 

> [the correct version is the] ...filled version. It is a gray color 72767b then turns black on hover. You can see [the icon color and hover behavior] here -  https://www.patternfly.org/v4/documentation/react/components/applicationlauncher/

[1]https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms#provide-the-right-kind-of-help

**Comment by mattreid** [comment]
There are other inconsistencies beyond the help icon that could cause confusion. At least if I'm interpreting the recommendation to always use sentence case from https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology properly (and from further down in the Forms doc). A number of the examples either mix capitalization casing, or are examples with title casing, which goes against the recommendation to use sentence casing. 

https://www.patternfly.org/v4/static/75236fce11162ee46f6d6da07e601292/4221c/form-elements.png
Has "Expiration Date", "Payment Information", and "Personal Information", as well as "Card number".

https://www.patternfly.org/v4/static/b13895bc05c4a95acf61d8c662aab90d/276eb/top-aligned.png
"Phone Number"

https://www.patternfly.org/v4/static/c0255c8a6d54be44192a3d1c7b9f03d8/276eb/left-aligned.png
"Phone Number"

https://www.patternfly.org/v4/static/f9289a547d93298c60d7af1321228846/1e1f5/validation-example.png
"First Name", "Last Name", "Phone Number"

**Comment by mcarrano** [comment]
I am going to close this one. We should be addressing as part of https://github.com/patternfly/patternfly-org/issues/1137  @mmenestr please take note.
