### ISSUE TITLE
Privacy policy / GDPR page

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#1418]
GDPR directly applies to PatternFly.org, the blog and the forum.  Since Slack is a 3rd party, we are safe there since we aren’t the ones collecting information.  All three of those sites though do use cookies to track users and potentially collect some information.  

In this issue, we will create a single privacy/gdpr page that we host on PatternFly.org that we link to from the other locations.  We also might need to add an opt-out banner at the bottom of PatternFly.org, the blog and the forum similar to what we’ve seen on other sites. 

We can leverage the boilerplate GDPR here: https://docs.google.com/document/d/1jF8eNu4kX8ioDS2fg3SRTHTw75W1RHETY0dN1JxBFfs/edit?usp=sharing

**Comment by rachael-phillips** [comment]
@LHinson @dgutride I'll figure some options around where this could live on the site. Do you have any thoughts on the urgency of this issue?

**Comment by rachael-phillips** [comment]
In progress: https://docs.google.com/document/d/1HQkJ2GpWTQw_Dsq5frUz4rhRPHE3Rrunjn-yu5fJNkY/edit#

**Comment by evwilkin** [comment]
@LHinson @rachael-phillips we're adding the GDPR banner in the next release through this closed PR for the site (#1703 - preview link available) and this pending PR for react (https://github.com/patternfly/patternfly-react/pull/3831).

The banner is currently just linking to the Red Hat Privacy statement, but we have this PR opened a while back to add a PatternFly Privacy statement & link to it under the `Quicklinks` section in the PF footer (#1584 - preview link available).  Do we want to move forward with adding the PF Privacy statement page & update the link in the banner, and if so should we revisit the styling/position of the footer link that's just above the Red Hat footer & privacy statement link or accept pending #1584  as it is now?

**Comment by evwilkin** [comment]
Closed by https://github.com/patternfly/patternfly-org/pull/1901
