### ISSUE TITLE
Add Bullet Chart to Charts design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1421]
Want to add the bullet chart as a new chart type here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/charts

**Comment by gdoyle1** [comment]
@mcarrano here's the draft of the chart guidelines! Everything new content-wise is highlighted in yellow  https://docs.google.com/document/d/19lPzHlx2T2MyJ-Pm8og7QXovRVHdHs7RynLMYhjlh0g/edit?usp=sharing
