### ISSUE TITLE
Add acronyms to sentence case exceptions in v4 design guidelines

### ISSUE THREAD

**Issue by apinnick** [patternfly/patternfly-org#1423]
V4 design guidelines says the following about [sentence case capitalization](https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology#capitalization):

Use sentence-style capitalization for all text elements, except:
 - Product names and proper nouns

I recommend adding acronyms to the exceptions because `Url` looks strange.

**Comment by mmenestr** [comment]
Suggested updated copy (make each exception it's own bullet point and add examples for each)
---------------------------------------------------------------------------------------------------
Use sentence-style capitalization for all text elements, except:

* Product names (e.g., Open Shift, PatternFly, Cloud Forms)
* Proper nouns (e.g., the name of an individual, organization or place starting with a capital letter like America, Jim, Red Hat)
* Acronyms (e.g., RHEL, CNV, AMQ) 

Sentence style capitalizes only the first word of each sentence and proper nouns, like names.
---------------------------------------------------------------------------------------------------
 @mcarrano

**Comment by apinnick** [comment]
You are going to edit this text before adding it, aren't you?

> ## Suggested updated copy (make each exception it's own bullet point and add examples for each)

`it's` > `its`

> Use sentence-style capitalization for all text elements, except:
> 
>     * Product names (e.g., Open Shift, PatternFly, Cloud Forms)

OpenShift, CloudForms

**Comment by mmenestr** [comment]
That first 'header' with the 'it's' mistake will not be in the text - that was just to explain the suggested changes! (careless spelling mistake on my part)

If there are no other suggested edits, then this italicized text is what will be added: 

_Use sentence-style capitalization for all text elements, except:

• Product names (e.g., OpenShift, PatternFly, CloudForms)
• Proper nouns (e.g., the name of an individual, organization or place starting with a capital letter like America, Jim, Red Hat)
• Acronyms (e.g., RHEL, CNV, AMQ) 

Sentence style capitalizes only the first word of each sentence and proper nouns, like names._


@apinnick @mcarrano Let me know if you think there should be any changes to that^. I won't add anything until you've given me the OK!

**Comment by mcarrano** [comment]
This looks good to me @mmenestr

**Comment by apinnick** [comment]
I see. In that case, I'm going to rewrite so that it fits our technical writing guidelines.
>>>
Use sentence case capitalization for all text elements except the following:

• Product names (Red Hat Virtualization, PatternFly, Red Hat CloudForms)
• Proper nouns (individual, organization, or location)
• Acronyms and initialisms (RHEL, URL, TCP/IP) 
>>>

Personally, I'm not sure we need examples. The terms should be self-evident. 
Product names are also proper nouns, but I have no objection to separating the two.
Acronyms and initialisms are different kinds of abbreviations, so I added `initalisms` for the sake of accuracy.

**Comment by mmenestr** [comment]
Thank you for rewriting that to conform to the technical writing style!

@mcarrano had suggested adding some examples, which I agree would be helpful for readers who may still be unsure. I also personally think that the last sentence is useful and good to keep, especially given the brevity of the sentence. It is already in the current copy, and sometimes it's nice to have direct access - although I understand someone could just look it up! 

Honestly, I could go either way but those are my thoughts! :)

**Comment by mcarrano** [comment]
Yes, let's keep the examples. You'd be surprised @apinnick how many people don't understand what a proper noun in in conversations I've had about this :)
