### ISSUE TITLE
Default alert does not display correct styling

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1427]
Default alert was recently added to the Alert component. The new styling does not display when this component is previewed on the website. Looks correct when previewed in the workspace.

Looks like this...

![Screen Shot 2019-08-27 at 11.46.46 AM.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/edc82914-930b-43b6-b3f1-e5476c0627cd)

Should look like this...

![Screen Shot 2019-08-27 at 11.21.40 AM.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/b63cb7df-d9c9-4c81-a90d-40ed7b457930)

**Comment by rachael-phillips** [comment]
Closing as this is complete
