### ISSUE TITLE
Utilization Bar Card: copyediting

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#143]
Following are typos or copy changes for the [Utilization Bar Card pattern](https://v2-patternfly.rhcloud.com/pattern-library/cards/utilization-bar-card/#/_design).

Key: _old text_ -> _new text_ (_where to find the text_)

- percentage is displayed in a tooltip -> percentage used is displayed in a tooltip (Design tab, # 6)
- This can be shown with the used value (i.e x of y used) or you may opt to provide this additional information in a tooltip. -> Show this with the used value (i.e. x of y Used) or provide it in a tooltip. (Design tab, # 4)

**Comment by dlabrecq** [comment]
Done.
