### ISSUE TITLE
Implement lookup table for resolving component page links

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1434]
Problem:

Component and demo links in Design Guideline pages are currently hard coded links. This will lead to broken links when items are promoted from experimental to production (or any time an item moves in the navigation. While this can be addressed by manually updating the Markdown, it presents maintenance overhead that would be best to avoid.

Proposal:

Create a function that can be embedded in a Markdown page that will build the list of related component and demos by passing in a list of items and outputting a formatted list of links. The mapping of component names to locations should be maintained in a lookup table that can be updated whenever a feature is promoted. No updates to the design guideline page source should be needed. In addition to mapping component names to URLs, it must be possible to indicate when a feature is experimental so this can be noted within the page output.

**Comment by redallen** [comment]
This is now easily possible if you'd like to start adding a list of related components to the frontmatter of design guideline files.

```md
---
id: Button
related: ['Chip', 'Toggle group']
---
```

**Comment by evwilkin** [comment]
@mcarrano does the suggestion above meet your needs, or is any further guidance needed?

**Comment by mcarrano** [comment]
I think this could work. So does this require a change @redallen or is that functionality that already exists? @mmenestr do you think this would be useful or is it just easier to link directly to the related pages?

When I filed this issue we were moving things between Experimental and Components leading to lots of broken links, but it's not so much of an issue now.

**Comment by redallen** [comment]
I've created the `related: ['Button', ...]` sections for all design guidelines that had related components.

They can be rendered however you'd like on the page and the links can be dynamically created and always correct.

**Comment by mmenestr** [comment]
I think that would be super useful! If i'm understanding correctly, in order to link a new guideline as a "related" component, we can just input the component/file's name up there?

**Comment by redallen** [comment]
Yes. Since the redesign mandates each component having a unique `id` it's easy to map them to urls.

**Comment by evwilkin** [comment]
Closing per discussion above, feel free to reopen if any further follow-up is needed.
