### ISSUE TITLE
Tabs - Design Guidelines Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1436]
Introduce design documentation for Tabs. Should address when to use different tab styling, primary vs secondary tabs, content that can be placed in a tab.

Related issue: patternfly/patternfly-next#2016

**Comment by mmenestr** [comment]
@abichen assigned you to this because I just learned you're working on it!

**Comment by gdoyle1** [comment]
@abichen has been working on this here: https://docs.google.com/document/d/1_LFmUOEWuCkGxywuMx-YCiQytrROAKpt_54ql8nlX5M/edit?usp=sharing

**Comment by gdoyle1** [comment]
Here's a doc with what I have so far: https://docs.google.com/document/d/1dCbpJfvp3Sk-6A5rVtCJcAFdVlw7tTGjYXlwH4Ljai8/edit?usp=sharing. Meeting with Matt, Michael and Michael Coker Thurs so there will be most likely more edits to make. I haven't added images but attached the marvel link to the beginning of that doc.
