### ISSUE TITLE
Add detailed instructions about working with experimental features 

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1446]
Add detailed instructions for working with experimental features to Documentation landing page.

**Comment by evwilkin** [comment]
@mcarrano are this and related issue https://github.com/patternfly/patternfly-org/issues/1445 needed still, as the Experimental section is gone (replaced by the Beta banner which is not contained in a separate section) but Beta components/features still exist?  cc @abichen

**Comment by mcarrano** [comment]
@evwilkin I think that we should place something on the site about beta features, but do you think we should open a new issue or just rename this? One question I have is whether it's possible to auto-generate a list of all beta features to add to this page. i wouldn't want to manually update it after every release, but I think it would be good to have a place where all beta features are listed.

**Comment by redallen** [comment]
I think we need a "Birth of a new component" page or something of the like that details and beta process starting from design to implementation.

**Comment by mcarrano** [comment]
Yes. I've been thinking the same thing @redallen Welcome any ideas you have on this.

**Comment by redallen** [comment]
I think a `/contribute/new-components` page would work nicely. I can write the content for the supported frontmatter tags.

**Comment by redallen** [comment]
Closing since we no longer have a documentation landing page.

I'm happy to change the content for the inline alerts or create a page that links from them if you open a separate issue.
![image](https://user-images.githubusercontent.com/47335686/112681211-c214de80-8e44-11eb-8734-a255f8c0f4a5.png)
