### ISSUE TITLE
Utilization Bar Card: example images

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#145]
On the [Design tab](https://v2-patternfly.rhcloud.com/pattern-library/cards/utilization-bar-card/#/_design), update both example images to show the hand cursor icon near the tooltip to indicate hovering.

**Comment by dlabrecq** [comment]
@LHinson Need new images here

**Comment by zhutaoredhat** [comment]
@mcarrano  I had pulled the request to fix this bug, please have a review. https://github.com/patternfly/patternfly-design/pull/666

**Comment by LHinson** [comment]
Closing since this PR has been merged!
