### ISSUE TITLE
Drawer component display

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1456]
In the current implementation of experimental component, Drawer. The way the example displays looks buggy: https://staging.patternfly.org/v4/documentation/react/experimental/drawer/

If we display this on the site, we need to design the display. Check out the Material UI approach: https://material-ui.com/components/drawers/

cc @dgutride @mcarrano

**Comment by rachael-phillips** [comment]
I would expect spacing between toggle button and content. I would also replace the Loren ipsum block with a custom empty state

**Comment by redallen** [comment]
If you still think there's a problem with the Drawer at https://www.patternfly.org/v4/components/drawer open a design issue and I'm sure Core/React can implement it while the component is still in beta.

**Comment by mcarrano** [comment]
Actually, if I understand correctly @rachael-phillips , your problem is with the example on the React page, not the drawer itself. Am I correct? If so, this would need to be fixed in the React repo by adding some spacing in the code that generates the example. I would open a React issue.
