### ISSUE TITLE
Utilization Bar Card: substantive edit

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#146]
On the [Design tab](https://v2-patternfly.rhcloud.com/pattern-library/cards/utilization-bar-card/#/_design), # 3 and # 4: we should provide guidance on how many decimal points to show (if any and when).

**Comment by dlabrecq** [comment]
@LHinson Need a designer here.

**Comment by LHinson** [comment]
There is an effort by @stacymcauliffe to provide a more robust guidelines. Once those guidelines area available, PF will update. In the meantime, I'm closing this issue as there is no current standard for us to reference.
