### ISSUE TITLE
Updates to Contribution page

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#1467]
On the contribution page, I think it would be a great addition if we could hyperlink to the different github repos to which they can contribute. For newer folks, especially designers, it's unclear where you are opening an issue.

**Comment by rachael-phillips** [comment]
HI @Rohoover I think that's a great point. We will need to update this page with a new and approved contribution process, so I think this is good for us to keep in mind.

**Comment by mmenestr** [comment]
@abichen Would you say this is in line with the work you, Jake and Alana are doing regarding the contribution process? If so I might assign this one to you

**Comment by abigaeljamie** [comment]
You can assign this to me, @mmenestr ! Jake is working on the contributions guidelines draft, so I can add the repo links to that.

**Comment by mmenestr** [comment]
https://docs.google.com/document/d/1Tn4syt_65MC7zQEbbvYTspGvL6Z1jgXL7QUm0supt_U/edit#heading=h.srn1w3mz6h76

**Comment by abigaeljamie** [comment]
The Google Doc linked above was created as a new page with its own nav item, and [that issue has been closed](https://github.com/patternfly/patternfly-org/issues/1946).  

For this issue, I created a hyperlinked list of GitHub repos that folks can contribute to, and that can be added to PF's Contribute > [About page](https://www.patternfly.org/v4/contribute/about). I emailed the Markdown for that change to @mmenestr
