### ISSUE TITLE
Props section on website is very hard to read

### ISSUE THREAD

**Issue by andreasn** [patternfly/patternfly-org#1468]
I'm trying to read the props section for the Popover widget, but I'm having a very hard time to decipher it and figure out what `Type` and `Default` belongs to what `Name`.
The columns have `word-break: break-word`; for some reason, and the `vertical-align` seems to default to `middle`.

![Screenshot from 2019-09-17 14-49-38](https://user-images.githubusercontent.com/209895/65043215-c6f8f800-d95a-11e9-9013-af1191683fa4.png)

**Comment by andreasn** [comment]
Quickly poked at it with the Firefox web inspector to disable the break-word rule on `.ws-table td` and add `vertical-align: top;` to that class instead.
![Screenshot from 2019-09-17 14-59-20](https://user-images.githubusercontent.com/209895/65043714-c319a580-d95b-11e9-8617-ad1cfca00e53.png)

**Comment by rachael-phillips** [comment]
Hi @andreasn is this issue currently blocking you or were you able to find a work around?

**Comment by andreasn** [comment]
Not blocking me at all. I just fixed it locally with the web inspector, and then I was able to read it easier.

**Comment by rachael-phillips** [comment]
Thanks for the details!

**Comment by seanforyou23** [comment]
+1 to this issue, I was about to raise a similar request before I found this. I think if we turned these prop tables into our very own [compound expandable tables](https://www.patternfly.org/v4/documentation/react/components/table/#compound-expandable-table) then we could just make the lengthy content columns expandable (like type and description) which could free up some space to give the other smaller columns enough room to fit properly.

Even the name column which can be relatively small content-wise doesn't have enough room to fit the names without wrapping, while there's a lot of empty space on the right side.

<img width="1552" alt="Screen Shot 2019-10-14 at 6 47 36 PM" src="https://user-images.githubusercontent.com/5942899/66787953-a5d0ec00-eeb3-11e9-880e-a04c48c3d44c.png">

**Comment by janwright73** [comment]
Hey @seanforyou23 - the linked PR is currently staged with changing the 1st, 2nd, and 4th columns to nowrap (just not promoted to production yet).  If you want to pursue your suggestion, then let's leave this issue open, else I was planning on shutting down the issue.  thoughts?

**Comment by seanforyou23** [comment]
Staging looks a lot better, I still think some of the more complex prop tables are kinda hard to read and there is an awful lot of empty space in some places (example below from Table props) but with the text not wrapping so aggressively the immediate problem is solved for me. Feel free to close the issue if you like, no need to keep it open just for me.

<img width="1546" alt="Screen Shot 2019-10-15 at 11 54 13 AM" src="https://user-images.githubusercontent.com/5942899/66848136-88972e80-ef42-11e9-8752-9e4efd8b91c7.png">

**Comment by janwright73** [comment]
closing original issue - future enhancements to be track with new issue #1516

**Comment by janwright73** [comment]
![Screen Shot 2019-10-15 at 2 06 53 PM](https://user-images.githubusercontent.com/40367673/66857344-154ae800-ef55-11e9-8747-16ae5568bb24.png)
