### ISSUE TITLE
Provide documentation on icon usage

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#1469]
There are styles available for icon usage here:
```--pf-global--icon--Color--light: #{$pf-global--icon--Color--light};
  --pf-global--icon--Color--dark: #{$pf-global--icon--Color--dark};
  --pf-global--icon--FontSize--sm: #{$pf-global--icon--FontSize--sm};
  --pf-global--icon--FontSize--md: #{$pf-global--icon--FontSize--md};
  --pf-global--icon--FontSize--lg: #{$pf-global--icon--FontSize--lg};
  --pf-global--icon--FontSize--xl: #{$pf-global--icon--FontSize--xl};
```
But no official docs on how to use them. 
An example would be a help icon. On the OpenShift side we've seen some variation here and I think having this documented would make things more clear. 
Maybe have the following:
Colours:
Default state
active state 
hover state

Sizes and when each is appropriate

There is also the case where the link button has an icon and it's blue, we should document this and have an explanation for it. We could see some confusion around when to use an icon inside a `pf-c-button` and when not to.

**Comment by janwright73** [comment]
@christiemolloy - would this be a candidate for a katacoda training module or best to document on the website?

**Comment by matthewcarleton** [comment]
@janwright73 @christiemolloy I started a rough google doc around this too if you want I can share it with you. Just let me know :)

**Comment by mcarrano** [comment]
I think this is a good topic to add into the design guidelines section on the website. I'm going to move this over to our -org repo where we can track. @matthewcarleton if you have a draft, it would be great to add a link here. Any interest in contributing this :)

**Comment by matthewcarleton** [comment]
hey @mcarrano I did start a rough draft here:
https://docs.google.com/document/d/1LZtYY_Uz5G7J-_kQbSu6t_pUcNhae_7r4_1ZRqOGT8U/edit#heading=h.rpnyt562cxpl
lots of questions there :)

**Comment by mcarrano** [comment]
Just a brief update on this. We have an ongoing issue here to better clarify icon usage: https://github.com/patternfly/patternfly-design/issues/787  @bdellasc @mceledonia please take a look at this issue. Is this something you agree should be added to the Icons page on the website?

**Comment by mcarrano** [comment]
This request should be covered by the design work being done here: https://github.com/patternfly/patternfly-org/issues/1687  I will close this out. @matthewcarleton I encourage you to review the designs attached to that issue to see if they provide what you are looking for. There is also an issue to update our Colors page here that is related: https://github.com/patternfly/patternfly-org/issues/1517  @gdoyle1 is working on both of those.
