### ISSUE TITLE
Document and user opt-out the use of all PIA and cookies across web properties

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1472]
This issue should include
1. Documenting the use of all PIA and cookies across the web properties for user knowledge
2. Allowing the user to opt-out of all PIA and cookies across web properties
3. Make sure this carries over to pf3 and pf4 sections of the website since they are built separately and just bundled at deploy time

Web properties include
- patternfly.org/v4
- patternfly.org/v3

**Comment by evwilkin** [comment]
Closing out as we mirrored the redhat.com approach of indicating that they agree to opt in by using the website, rather than allowing users to opt out (https://github.com/patternfly/patternfly-org/issues/1645)
