### ISSUE TITLE
Bullet chart example broken

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1475]
The font and messaging on bullet chart is distracting and the font should be updated: https://www.patternfly.org/v4/documentation/react/charts/chartbullet/

**Comment by dlabrecq** [comment]
In ChartBullet, we use `<>...</>` tags instead of React.Fragment. Just a guess, but that could be related -- may not be supported in the pf.org env?

**Comment by dlabrecq** [comment]
Apparently, empty tags are not supported for pf.org.

"we use react-live which uses https://github.com/bublejs/buble , which does allow a custom jsxFragment" -- @redallen

**Comment by dlabrecq** [comment]
Should be fixed by https://github.com/patternfly/patternfly-react/pull/2988

**Comment by redallen** [comment]
Can close next time we bump -react.
