### ISSUE TITLE
Pattern Library Overview: "Find" thumbnail on Overview page refers to Search

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#148]
On the overview page, the thumbnail for the “Find” pattern has the world ‘search’ in the text box. Should we update this to read ‘find’?

**Comment by LHinson** [comment]
Story created: https://patternfly.atlassian.net/browse/PTNFLY-1533

**Comment by LHinson** [comment]
Here you go @dlabrecq 
![find](https://cloud.githubusercontent.com/assets/7924406/15971935/a1fee0b8-2f09-11e6-95a3-81e7deb94e41.png)

**Comment by dlabrecq** [comment]
Done.

**Comment by LHinson** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7681590-130956820_9-s4-v1.png?palette=1&width=246)
