### ISSUE TITLE
Spike: Carry over descriptions of React components to HTML

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1485]
Evan will spend 1 day investigating this spike. Spike will include looking into effort needed for carrying over descriptions of React components to HTML.

For any issue that has a 1:1 mapping of a component, automatically populate to the description on other pages. 

Examples include: Accordian, Alert, App launcher

Reference the component audit: 
https://docs.google.com/spreadsheets/d/1ckp6eWYwbgRoBUAPR01oUmLYR3qk5uzxo5IKAOb3fEM/edit?usp=sharing

**Comment by rachael-phillips** [comment]
Component descriptions should be mapped directly to the names of the components - the only exception is check and checkbox. We can use the description for checkbox for check.

**Comment by evwilkin** [comment]
@rachael-phillips I believe the updated site addresses this - closing out this issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
