### ISSUE TITLE
Correct naming of all components that should map 1:1 

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1486]
Correct these names - may have to be fixed upstream. 

HTML
App launcher should be **Application launcher**
Nav should be **Navigation**

React 
Application Launcher some of the example names need updating ** app to application**
DataToolbar should be **Data toolbar**
FormSelect should be **Form select**
Nav should be **Navigation**
NotificationBadge should be **Notification badge**
TopologyView should be **Topology view**

**Comment by janwright73** [comment]
React items are resolved.

**Comment by janwright73** [comment]
Core items also resolved via https://github.com/patternfly/patternfly-next/issues/2355 and https://github.com/patternfly/patternfly-next/pull/2356

**Comment by rachael-phillips** [comment]
Closing because this has been resolved
