### ISSUE TITLE
Add Component descriptions and corresponding design guideline links

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1489]
This work should be completed after issue #1486 

**Core** (Components that map 1:1 with core are accounted for below, and any changes should be applied to the Core examples)

- About modal box
- Alert group
- Backdrop
- Check
- Chip
- Content
- Form control
- Modal box
- Tab content
- Title
- Toolbar
- Alert
- About modal
- Basic forms
- Card view
- Data list
- Modal
- Table
- Wizard
- Divider
- Overflow menu

**React**
*Add new description + link to design guidelines**
- Notification badge
- Topology view

**Add new link to design guidelines**
- Accordion
- Application launcher
- Background image
- Badge
- Brand
- Card
- Clipboard copy
- Dropdown
- Empty state
- Label
- List
- Options menu
- Popover
- Skip to content
- Tabs
- Text
- Title
- Tooltip
- Wizard
- Page layout
- Pagination table
- Toolbar
- Data toolbar
- Drawer 
- Spinner

- All layouts

**Comment by mcarrano** [comment]
@rachael-phillips I created a spreadsheet that lists all of the items that need either descriptions or design doc links added. https://docs.google.com/spreadsheets/d/1Mi93S23lOUE4HaL2hTuEiiI14Sh-fG8DXT8uhpNiT-Q/edit?usp=sharing  Let's discuss next steps.

**Comment by mcarrano** [comment]
@rachael-phillips I've updated the spreadsheet with missing descriptions: https://docs.google.com/spreadsheets/d/1Mi93S23lOUE4HaL2hTuEiiI14Sh-fG8DXT8uhpNiT-Q/edit?usp=sharing

I was able to fill in definitions for most of the layouts. @mcoker can you verify that my descriptions make sense? What do you think are next steps @rachael-phillips ?

**Comment by rachael-phillips** [comment]
@mcarrano this is looking great! Once we are complete, next steps are surfacing this to @evwilkin to see where this fits on the Org + Infrastructure roadmap.
