### ISSUE TITLE
Pattern Library Overview: Missing "Forms" thumbnail

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#149]
We are missing a thumbnail for the “Forms” pattern on the overview page.

**Comment by dlabrecq** [comment]
Yes, I believe "Forms" was added after Kyle's initial set of thumbnails.

@LHinson Can you provide a thumbnail for this?

**Comment by LHinson** [comment]
Story created: https://patternfly.atlassian.net/browse/PTNFLY-1533

**Comment by LHinson** [comment]
This Overview page has gone through a series of updates. Also closing because it will soon be replaced with design status page.
