### ISSUE TITLE
font-family CSS issue on Org

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1500]
We'll need to add info about the CSS font-family to the Typography page.

**Comment by mmenestr** [comment]
@mcarrano @rachael-phillips would this be a whole new table, or has this already been addressed with the "Font size CSS variable" row in each typography table? 

![image.png](https://images.zenhubusercontent.com/5e750f70a086dc7bdce718bd/383f3b13-1dcd-489a-86f2-7c53a865c127)

**Comment by rachael-phillips** [comment]
Hey @mmenestr I'm sorry to say I can't remember the context of this issue. @evwilkin do you remember?

**Comment by evwilkin** [comment]
I'm not familiar with the context behind this issue - may be that it's since been resolved @mmenestr
