### ISSUE TITLE
Wrong link to PatternFly template in "Get started" page

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly-org#1501]
The link to the **PatternFly template** under the [Download the template file](https://www.patternfly.org/v4/get-started/designers#download-the-template-file) paragraph in [https://www.patternfly.org/v4/get-started/designers](https://www.patternfly.org/v4/get-started/designers) links to the wrong file: [https://sketch.cloud/s/r9k28](https://sketch.cloud/s/r9k28)

**Comment by mcarrano** [comment]
Thanks for flagging this @cntlsn . We should fix this ASAP. @gdoyle1 can you tell us what this link should be? @rachael-phillips I know we just did a site release last week, but is there any way to fix this before the next release cycle?

**Comment by gdoyle1** [comment]
@mcarrano The Patternfly 4 template file (with Overpass font) can be downloaded here: https://sketch.cloud/s/R9k28

**Comment by rachael-phillips** [comment]
@cntlsn @gdoyle1 @mcarrano is this the view you currently see when you click on the link from https://www.patternfly.org/v4/get-started/designers

<img width="1325" alt="Screen Shot 2019-10-07 at 11 38 43 AM" src="https://user-images.githubusercontent.com/40275806/66326593-42651e00-e8f7-11e9-8217-3d79ce55ede2.png">

**Comment by cntlsn** [comment]
Hi @rachael-phillips, yes that's what I'm seeing.
I think the issue is in a lowercase typo: the page currently links to `/r9k28` but the correct file lives at `/R9k28`
