### ISSUE TITLE
Update PatternFly org landing page for unsupported browsers.

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-org#1507]
When navigating to patternfly.org in IE or another unsupported browser, it would make for a friendlier user experience if we had a screen letting the users know that their browser is not supported.  Currently the users are greeted with an unformatted web page as shown in the attached screen shot.

![IE](https://user-images.githubusercontent.com/6126356/66419199-a22ff780-e9d1-11e9-9a0c-450865c00dca.png)

**Comment by rachael-phillips** [comment]
Hi Don, I don't think we're planning on supporting IE right now
