### ISSUE TITLE
Datepicker: AngularJS type column looks clickable when it's not

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#151]
Under Datepicker -> AngularJS -> Parameters, the type column makes it seem like the user can click on the items, but they aren’t actually links.

**Comment by dlabrecq** [comment]
This example is included, as is, directly from Angular-Patternfly. This particular "String" parameter is generated from ngDocs. This behavior is the same for all Angular-Patternfly components showcased at http://angular-patternfly.rhcloud.com/#/api. For example, all parameters have these empty links for; object, boolean, string, etc.

@LHinson I don't know that we want to spend time customizing ngDocs for Angular-Patternfly?

**Comment by LHinson** [comment]
The website has been updated to include links out to the showcases instead of embedding that code into the page. That said, I don't see "datepicker' over in http://www.patternfly.org/angular-patternfly/#/api

If this is an issue, it should be opened against angular-pf repo. 

Closing this one.
