### ISSUE TITLE
Review the data-input documentation

### ISSUE THREAD

**Issue by janwright73** [patternfly/patternfly-org#1513]
While trying to investigate https://github.com/patternfly/patternfly-org/issues/1271 - i was confused by the 'Selection controls' listed towards the top of https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/data-input

Specifically 'Checkboxes, Radio buttons, Select lists' as they do not directly map to our component names.  

- Should they instead read 'checkbox, radio, select,..'?
- Did we purposefully not link out to the component documents because these are more abstract design concepts? 

Within the Select lists section we appear to have an outdated image for  'Multi-select enables users to select one or more options.'  

we have this:
![image](https://user-images.githubusercontent.com/40367673/66599246-c37b1a00-eb70-11e9-8231-98a8be9cefee.png)

 instead of this:
![Screen Shot 2019-10-10 at 3 16 14 PM](https://user-images.githubusercontent.com/40367673/66599318-f0c7c800-eb70-11e9-9ca7-c44597b2e40f.png)

**Comment by janwright73** [comment]
@mcarrano - tagging you on this entry.  Please correct/update away!

**Comment by mcarrano** [comment]
Thanks for entering this @janwright73 ! We should definitely review these guidelines and both bring them up to date with latest implementations and provide more specific guidance on usage of the various components including both native and custom selects as well as option menus that are used for settings vs. data input.
