### ISSUE TITLE
Upgrade props table to pf4 table

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-org#1516]
Currently, our prop tables are generated by a [wrapper](https://github.com/patternfly/patternfly-react/tree/master/packages/patternfly-4/react-docs/plugins/gatsby-transformer-react-docgen-typescript) around react-docgen. It's quite helpful but the overall design of the table could be improved.

There are some places where there is too much empty space, and other places where there isn't enough. All of these problems have been solved in PF4 react-table, so I'd like to recommend we adopt this component for use with these prop tables.

If we think it's a good idea, I imagine it just becomes a matter of picking exactly which combination of table features would be best and any additional styling/interaction requirements are considered.

It's an enhancement request that picks up where https://github.com/patternfly/patternfly-org/issues/1468 leaves off.

**Comment by rachael-phillips** [comment]
Thanks for filing @seanforyou23. I agree that this is something we should enhance.

**Comment by redallen** [comment]
Props tables now use PF4 tables and some width modifiers.
