### ISSUE TITLE
Colors page redesign

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1517]
There are color variables that are in the Sketch document (e.g. pf-orange-300) that are not available in PF4. 

PF3 had these documented on the [color palette page](https://www.patternfly.org/v3/styles/color-palette/)
PF4 has only select colors (the most common & tied to functions) on the [color palette page](https://www.patternfly.org/v4/design-guidelines/styles/colors)

The [PF4 global variable list](https://www.patternfly.org/v4/documentation/react/overview/css-variables/) also does not list the color variables.

They appear to be in PF4 based on [this](https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/colors.scss) ? But are not in any clear documentation.

The request is to have the color variables documented in the Global CSS variables list.

**Comment by katierik** [comment]
Somewhat related to the design kit issue about color variable names here: https://github.com/patternfly/patternfly-design-kit/issues/105

**Comment by gdoyle1** [comment]
Hi Katie @katierik - all of the colors that are presented here: https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/colors.scss are all of the colors that PF4 offers. You'll see that in some of the charts, they created a new palette of colors (for example the whole green family is DIFFERENT than the $pf-color-green-### family in the .scss color file). $pf-color-orange-300 is offered in PF4 as seen in sketch as #EC7108 which is actually the same family of colors used for charts (where variables are reassigned as $pf-chart-color-orange-###). I updated the color swatches in the library palettes in Sketch that hopefully will decrease this confusion. I added the exact variable name to them too so that should help.

**Comment by katierik** [comment]
So, are all the colors in the scss available for devs to use?

**Comment by gdoyle1** [comment]
No not all the colors in the scss are available unless they are assigned to a variable. For example - go here https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/_chart-globals.scss and you can see all the chart variables that are offered in that package where the orange colors in the scss are assigned to orange chart color variables. I was more answering the sketch file issue here so we might want to pull someone in who works on the site/a css dev

**Comment by rachael-phillips** [comment]
@gdoyle1 is this something that needs to be enhanced or fixed on the site?

**Comment by gdoyle1** [comment]
@rachael-phillips We could probably redesign the colors page to look more like pf3's and supply the whole color palette

**Comment by gdoyle1** [comment]
Spoke with Rachael and Matt Carrano about this on Slack:

[Created this spreadsheet](https://docs.google.com/spreadsheets/d/1T5gllFGnwROOI-03JeLYlxpeOcXn8zVFesVTfv8jq7A/edit?usp=sharing) to figure out which colors within the colors.scss file are assigned to global variables. All the ones that are highlighted in red have not yet been defined. I'll need the global variable to list each color family in a table on the colors page. Screenshot of the start of that is below:
<img width="641" alt="Screen Shot 2019-12-11 at 1 52 45 PM" src="https://user-images.githubusercontent.com/30870144/70650687-8e954d00-1c1d-11ea-9f11-f1f19e7ffdb9.png">

Michael Coker, Matt, Rachael and Michael Celedonia and I will meet to figure out the best approach to this. Whether we give all of the colors global variables or if we consolidate some of them.

**Comment by gdoyle1** [comment]
Here's what I've come up with! https://marvelapp.com/5i7da32 I'd love some feedback on the wireframes. The table I added to the end of the page is possibly the most important since it gives all the global variables assigned to each color. I have this whole spreadsheet with those: https://docs.google.com/spreadsheets/d/1T5gllFGnwROOI-03JeLYlxpeOcXn8zVFesVTfv8jq7A/edit?usp=sharing but did not add _all_ of them to the wireframe. I added enough to see what the design would look like! @mcarrano @rachael-phillips @katierik

**Comment by mcarrano** [comment]
@gdoyle1 The wireframe looks great. My only comment is that as I compare this to the page that exists on the website now, the new page definitely exposes the color palette more fully and helps me understand what colors are available. However the current page does better to place the color choices in context by identifying what colors are used for links, alert levels, etc. Is there a way to satisfy both of these goals?

@mceledonia would also be interested in hearing your feedback.

**Comment by gdoyle1** [comment]
@mcarrano We could definitely add sections (possibly before exposing the whole palette) that shows the colors in use and groups them as we do now. It may be harder to keep up-to-date if component designs/colors change. The CSS variable listing at the bottom will give designers that information as well. That was something I wasn't sure if I should add a link to the component that the variable is used in for each variable. It's a possibility but will take a while to manually create!

**Comment by gdoyle1** [comment]
Worked with @mceledonia a lot on this! But here's what we came up with: https://marvelapp.com/5i7da32. Some of the marvel project is interactive but you can also forward through the screens and understand the flow. 

@mcarrano @rachael-phillips let me know what you think!

**Comment by mcarrano** [comment]
I like it @gdoyle1 !

**Comment by gdoyle1** [comment]
Updated the colors page mocks based off our conversation today https://www.google.com/url?q=https://marvelapp.com/5i7da32&sa=D&ust=1584225238737000&usg=AOvVaw2h4x0pu9UyRPEI4bT6UoUu! Let me know what you think.

@mcarrano @rachael-phillips @mceledonia @bdellasc

**Comment by gdoyle1** [comment]
Commenting for progress update:

- The [Marvel project here](https://marvelapp.com/5i7da32) seems to have come to a solid place
- I added tablet and mobile versions of the mocks
- Added expand all/collapse all capabilities on the color palette individual tables

**Comment by mcarrano** [comment]
@rachael-phillips @evwilkin We feel like design work here is complete.

**Comment by rachael-phillips** [comment]
Fantastic! @evwilkin do you think this is something we could bring into planning?

**Comment by evwilkin** [comment]
@rachael-phillips yes!

**Comment by gdoyle1** [comment]
@evwilkin Going to list all of the resources for the final design!
1. [Marvel project](https://marvelapp.com/5i7da32) (includes a desktop, tablet and mobile spec - there are 9 screens - the first 5 are the prototype and the last 4 are specs!)
2. [Google doc](https://docs.google.com/document/d/1GAGgV5XcfWparqwvy7ylyYiHkmXS5w4H7abzOgdbSco/edit?usp=sharing) with all final content
3. Cursor SVG
[pointinghand.svg.zip](https://github.com/patternfly/patternfly-org/files/4389926/pointinghand.svg.zip)

I realize that this is a pretty hefty design and there will probably be questions, so please reach out whenever this is worked on!
