### ISSUE TITLE
Ellipses are present in Filtering documentation, but not recommended

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1518]
The image examples on the filtering documentation say "Filter by ___..." with an ellipsis. 
I think that PF recommends not using ellipsis?
It would be great to have these images reflect the best practice.

**Comment by rachael-phillips** [comment]
Thanks for filing this @katierik. I'm placing this in our backlog. @mcarrano confirming this is correct?

**Comment by mcarrano** [comment]
@mceledonia @gdoyle1 Can one of you confirm this for me? I think that we landed on not using ellipses, but wanted to check on what we are using in our Sketch library for placeholder text,

**Comment by gdoyle1** [comment]
@mcarrano We have not included a "..." with placeholder text in the sketch library

**Comment by rachael-phillips** [comment]
@mcarrano would we want to go ahead and slip in a fix for this this sprint?

**Comment by mcarrano** [comment]
Do we have someone who can pick this up, @rachael-phillips ?

**Comment by rachael-phillips** [comment]
Hi @mcarrano I was thinking on this. Can we bring this into design planning for next sprint? I could probably pick this up if we don't have anyone.

**Comment by mcarrano** [comment]
That would be great @rachael-phillips I will put it on the agenda.
