### ISSUE TITLE
Referring to PF.org patterns from a design requirements doc

### ISSUE THREAD

**Issue by beaumorley** [patternfly/patternfly-org#1522]
When writing design requirements to share with UI developers, I would like to be able accurately reference the PF pattern that I am using in my design. I would like to be able to do this at a pretty granular level like the UI component.

For example, my design used the Expandable pattern and I wanted to reference the page in PF.org that I looked at to decide on using that pattern and more info on it. I thought this could be useful to the UI developer. Today, when referencing a PF pattern, I use the PF URL. However, as the PF website changes, I am concerned that this link may become broken.

My proposal would be to create a standard convention for referencing patterns in PF that could be leveraged by UI developers when they are working on a design requirement. For example, reference UI Pattern 1.2.3.4 in the PF4 library for more details. This could be done in a bunch of ways but could be as simple as giving each pattern a unique identifier. Then there could be a method that is put in place to be able to find a pattern by its identifier (like 1.2.3.4). This could even get fancy and we could develop some kind of auto link generator that generate a link to the correct UI pattern.

**Comment by rachael-phillips** [comment]
Thanks for filing! I've seen this, and labeled it as an enhancement.

**Comment by rachael-phillips** [comment]
@mcarrano I wanted to make you aware of this issue. Do you have any ideas here of how we could accomplish this without a big development push?

**Comment by mcarrano** [comment]
@beaumorley Thanks for raising this issue. It is very closely related to some conversations I've been having with @matthewcarleton and @LHinson about how designers can best communicate their exact intent when they hand off a design to be developed. I'd be glad to loop you into those conversations.

@rachael-phillips as for the question of how best to link to patterns or components on the website, I too have concerns about how we can do this in a way that protects us from broken links. There was an issue I filed a while ago to create some type of lookup table to protect against this (https://github.com/patternfly/patternfly-org/issues/1434). It would be great if we can consider this in our plan for website improvements.

**Comment by matthewcarleton** [comment]
@beaumorley yes, this is very close to what I've been working on too!
Another aspect of this is documenting designs that are outside of PF components but still use proper PF variables (colours, spacing, fonts, etc).

**Comment by beaumorley** [comment]
@mcarrano @matthewcarleton @rachael-phillips Happy to brainstorm with you guys on this down the line. I've done a lot of design requirements in my career and have lots of thoughts. This was fun to think about as it was my first real peek into Patternfly docs and Github. Good stuff!

**Comment by redallen** [comment]
Most components now have a "Design guidelines" tab where designers can share requirements. The URLs will not change. If you'd like to see that content changed or restructured please open a new issue!
