### ISSUE TITLE
Update Empty State design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1526]
Update the empty state design guidelines to provide more detailed usage guidance. This should be based on the analysis done here: https://docs.google.com/presentation/d/14l3A2oLx6AEZIPijbWcBmaSRoqZfR2sLZqYgaO33tto/edit?usp=sharing

**Comment by mmenestr** [comment]
This doc contains the exact copy that should be put into the update empty state documentation:
https://docs.google.com/document/d/1N1617z-Q2UZ9GFg92xFeP952ZrXEcb0bPfULic4VS-o/edit?usp=sharing
