### ISSUE TITLE
Sketch download link goes to HP Landing Page

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-org#1527]
From Yasen_Dimov:

> The very first link to the Sketch template here https://www.patternfly.org/v4/get-started/designers#download-the-template-file 1 leads to an [HP Landing page](https://sketch.cloud/s/r9k28) instead of the PatternFly 4 library.

**Comment by rachael-phillips** [comment]
Hi @SpyTec this is a known issue and should be resolved.
