### ISSUE TITLE
Update Charts design guidelines to include information on interactive legends

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1533]
The Charts design guideline documentation here should be updated to include information on behavior and usage of interactive legends. https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/charts

**Comment by nlcwong** [comment]
Here is the first draft of what I would like to publish: https://docs.google.com/document/d/1ILnkLevLE4J90WCT9G-u_MIUTAIRGoi2Q7B2mT0HBL0/edit?usp=sharing

**Comment by rachael-phillips** [comment]
@mcarrano making you aware of Natalie's link above :)
