### ISSUE TITLE
Content recommendations for the site

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1535]
- Remove periods from Getting Started page
- Should titles end with a period?
- Get started vs. Why PatternFly?
- Rethink the buttons on the homepage
- Who is “we?”
- Sticking to a consistent person and audience
- Make the differences between PatternFly developers and PatternFly designers more obvious.
- Clarify the best place to start
- Explain the colors: what are the theme colors?
- These are our colors and this is how to use them. Providing more context.
- Icons page - clarify the language
- Explain where and why the Red Hat font is used and should be used.

**Comment by redallen** [comment]
I think the homepage and color pages have been changed and had new copies added since this issue was opened.

Feel free to open a new issue with whatever bullet points are remaining.
