### ISSUE TITLE
Find: Clarity on when to use pattern needed

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#154]
On the Design tab of Find there is a statement that reads "Focused Object: The first matching object is brought into view by scrolling or paging and highlighted. When the focus is changed via the previous/next buttons, the view should change, if necessary, to display the newly focused object.” This seems contradictory to the overview which states that this pattern should not be used if paging is required.

**Comment by dlabrecq** [comment]
@LHinson

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2016.
