### ISSUE TITLE
Experimental features are not discoverable

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#1540]
Since experimental components are only located in the experimental section, they are difficult to discover. 
I have noticed that product team members did not know about experimental components that would have been useful for them. One solution would be to also display the experimental components in the main navigation with the other components, but clearly mark them as experimental.

**Comment by rachael-phillips** [comment]
Hi @srambach thank you for filing this! This is great feedback to have. @evwilkin making you aware.

**Comment by redallen** [comment]
Closing in favor of https://github.com/patternfly/patternfly-react/issues/3624 which moves experimental components to be with all the other components.
