### ISSUE TITLE
Experimental features need information about time/criteria to become full-fledged

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#1541]
Those outside the PF team need to have an idea when a given experimental feature may become full-fledged, and/or what criteria must be met. I have received feedback from product team members that they didn't think they could use a feature they needed and didn't know when they'd be able to, so they'd begun to build their own.

**Comment by evwilkin** [comment]
@mcarrano I know we've discussed this several times, should we document this on the site?

**Comment by mcarrano** [comment]
Yes, I believe we should @evwilkin . I just have not had a chance to figure out what this should look like. You can assign this issue to me if you want.

**Comment by evwilkin** [comment]
@mcarrano @nicolethoen with our updated process around promoting Beta components, let's revisit this idea of how to best communicate this through the site.  Perhaps this could be related to a homepage refresh to include more dynamic content?

**Comment by nicolethoen** [comment]
Perhaps we can update beta components who have a projected promotion date so that their docs list the projected promotion date?

**Comment by nicolethoen** [comment]
Every beta component could have a link to a promotion plan?
