### ISSUE TITLE
Update Navigation System doc to reflect current recommendations

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1542]
Update https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/navigation-system to reflect most current navigation mockups and guidance. 

* Since we are not supporting the Context Selector placed in the masthead as an "official" PatternFly design pattern, want to remove references to it from the page.

* Check examples against current dark nav variants.

**Comment by mmenestr** [comment]
Waiting on Gina to update navigation symbols in lib

**Comment by mmenestr** [comment]
Change context selector from being in the masthead to potentially navigation? + meet with Matt to go over it
Make sure the text is still relevant
Change all the pictures
