### ISSUE TITLE
Primary-detail design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1544]
Introduce design guidelines for the primary-detail pattern. A draft can be found here: https://docs.google.com/document/d/1kzGP37tb-lf7sVz43xBnnoYEWPsQN4GvNvffebxiuTE/edit?usp=sharing

**Comment by mmenestr** [comment]
Start with guidelines attached and go from there

**Comment by mmenestr** [comment]
Naming of this is going to change, but can work on this as is for now, and can change the naming at a later date.

**Comment by abigaeljamie** [comment]
Sent Google Doc draft to Margot for review

**Comment by mcarrano** [comment]
@abigaeljamie @mmenestr Since you are working on this, wanted to make you aware of a couple of things that could effect this:

1- We're changing the name to "Primary-detail."

2- @maryshak1996 is currently working on a design issue for a Catalog view: https://github.com/patternfly/patternfly-design/issues/848 Upon reviewing her initial work, we all realized that this is really just a special case of a Primary-detail and not really a different view. I expect that somehow we'll want to roll these things together from a documentation standpoint so something to consider.

**Comment by abigaeljamie** [comment]
Thank you, @mcarrano ! I'll change instances of "master-detail" to "primary-detail." Once we feel like the document is in good shape, I can touch base with Mary to see how we can roll our work together.

**Comment by abigaeljamie** [comment]
Finished doc and applied all feedback. Sent MD file and images to @mmenestr for PR.
