### ISSUE TITLE
Site Navigation Exploration

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1545]
In our PatternFly F2F the need arose to create a simplified and clear site navigation that accomplishes a variety of user goals and questions:

- Navigate the website as easy as the workspaces
- Further Separate the design and developer experience
- Remove the context selector and combine docs
- Refine search and blog experiences to better integrate with the navigation

**Comment by mcarrano** [comment]
Lets revisit post testing
