### ISSUE TITLE
Improve padding across the site

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1558]
@rachael-phillips commented on [Tue Nov 05 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/87)

There are many places across the site where the padding is off and the visual styling needs to be improved so that we reach a user experience that represents the PF brand as trustworthy. 

Here are some examples:
The padding below and above the Color headers should be the same:

<img width="1325" alt="Screen Shot 2019-11-05 at 9 56 23 AM" src="https://user-images.githubusercontent.com/40275806/68218652-afc9a480-ffb2-11e9-96b3-ec7821ef150d.png">

---

@rachael-phillips commented on [Tue Nov 05 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/87#issuecomment-549872188)

Get Started - Develop page: 
<img width="501" alt="Screen Shot 2019-11-05 at 10 25 14 AM" src="https://user-images.githubusercontent.com/40275806/68220981-ad694980-ffb6-11e9-878a-1d2a123c503d.png">

---

@rachael-phillips commented on [Tue Nov 05 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/87#issuecomment-549872509)

Migration guide:

This needs more breathing room for readability:
<img width="789" alt="Screen Shot 2019-11-05 at 10 26 28 AM" src="https://user-images.githubusercontent.com/40275806/68221038-c96ceb00-ffb6-11e9-85c3-b7dd88164abd.png">

---

@rachael-phillips commented on [Tue Nov 05 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/87#issuecomment-549882464)

Spacing on Card view under Usage and Behavior:

https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/bulk-selection
<img width="1308" alt="Screen Shot 2019-11-05 at 10 49 57 AM" src="https://user-images.githubusercontent.com/40275806/68223063-156d5f00-ffba-11e9-81f7-52de0104af52.png">

Later on the page:
<img width="1292" alt="Screen Shot 2019-11-05 at 10 50 40 AM" src="https://user-images.githubusercontent.com/40275806/68223102-27e79880-ffba-11e9-8a45-16b6ca87893b.png">

Bottom of page:
<img width="428" alt="Screen Shot 2019-11-05 at 10 53 53 AM" src="https://user-images.githubusercontent.com/40275806/68223380-ab08ee80-ffba-11e9-9b25-08383fdc4c62.png">

---

@rachael-phillips commented on [Tue Nov 05 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/87#issuecomment-549954711)

This is on page layout. The spacing should be uniform across other components.

<img width="1120" alt="Screen Shot 2019-11-05 at 1 25 53 PM" src="https://user-images.githubusercontent.com/40275806/68234721-d64a0880-ffcf-11e9-9595-6a314b628a96.png">

---

@rachael-phillips commented on [Tue Nov 05 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/87#issuecomment-549955294)

The headers need to be uniform across all component pages:
<img width="423" alt="Screen Shot 2019-11-05 at 1 27 04 PM" src="https://user-images.githubusercontent.com/40275806/68234790-072a3d80-ffd0-11e9-98e4-f20cbd11ba01.png">

This is an issue across demos, experimental, inline table, layouts, and virtual scroll

---

@rachael-phillips commented on [Tue Nov 05 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/87#issuecomment-549957489)

Spacing is off here in the paragraph text.

<img width="1019" alt="Screen Shot 2019-11-05 at 1 32 13 PM" src="https://user-images.githubusercontent.com/40275806/68235152-bb2bc880-ffd0-11e9-9293-f8fb15663ad3.png">

---

@rachael-phillips commented on [Tue Nov 05 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/87#issuecomment-549961064)

Props and CSS Variables Headers across the site:
<img width="1328" alt="Screen Shot 2019-11-05 at 1 38 57 PM" src="https://user-images.githubusercontent.com/40275806/68235792-db0fbc00-ffd1-11e9-97ff-81c3a187219e.png">

**Comment by redallen** [comment]
Where do we still need to refine padding @rachael-phillips ? Many of these issues have been addressed.

**Comment by redallen** [comment]
I think with the pending redesign this can be safely closed.
