### ISSUE TITLE
Vertical Navigation: Anchor Links on design page?

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#156]
Vertical Navigation -> Design - This page is long with multiple examples. Do we want to add anchor links on this page as we've done elsewhere?

**Comment by dlabrecq** [comment]
I don't believe we have links on any design page, but will defer to @LHinson.

**Comment by LHinson** [comment]
Page [1] now includes anchor links! Closing

[1] http://www.patternfly.org/pattern-library/navigation/vertical-navigation/
