### ISSUE TITLE
Refine tables

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1560]
@rachael-phillips commented on [Thu Nov 07 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/105)

Hey @redallen did we update the tables? Can we talk about next steps on how to make the tables unified and not broken. 

Should be:
<img width="584" alt="Screen Shot 2019-11-07 at 5 35 43 PM" src="https://user-images.githubusercontent.com/40275806/68433665-156d8a80-0185-11ea-8346-190baea1a7cc.png">

---

@redallen commented on [Fri Nov 08 2019](https://github.com/patternfly/gatsby-theme-patternfly-org/issues/105#issuecomment-551901435)

From #106:
It'd be difficult to change the Core docs table to a more dynamic React table like the "CSS Variables" table or like the "AlertActionCloseButton" table, but it's possible.

For now, I've changed the React props tables to be like the "CSS Variables" tables. Come next site release we can talk about what other refinements we want.

**Comment by redallen** [comment]
Tables seem to be a constant struggle @rachael-phillips . Currently for React they have a max-width of `calc(100vw - 418px)` and fit the content of the "name" column:
![image.png](https://images.zenhubusercontent.com/5cb4eb924103d93ceadefd64/e39863b1-e2a2-4c7f-a358-be786543912f)

For core, we use our normal HTML table without fitting columns, without a background, and a max-width of `680px`:
![image.png](https://images.zenhubusercontent.com/5cb4eb924103d93ceadefd64/d64cab5e-9c60-4601-a3e8-0993b8f0e568)

Our core tables also do not always have the same headers or columns, so we can't make many assumptions about the content.

We could investigate making our HTML tables look like our React tables. We can style them however we want. What design do we want @rachael-phillips ?

**Comment by redallen** [comment]
Closing in favor of #1808
