### ISSUE TITLE
Horizontal Navigation: Two-Level Menu Bar vs Multi-Level Menu Bar terminology

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#157]
I wonder if the "Two-Level Menu Bar” example of the within the Horizontal Navigation pattern should actually read “Multi-Level Menu Bar” since is includes tertiary nav, too.

**Comment by dlabrecq** [comment]
@LHinson Can you please take a look at this one?

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2016.
