### ISSUE TITLE
Search results don't differentiate between HTML and React sections

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#1575]
Certain search results are not differentiated between the HTML and React components.  You can only tell the difference by hovering and checking the URL.

![image](https://user-images.githubusercontent.com/19825616/70180111-63ef4580-16ad-11ea-864e-1e1f9226ffb7.png)

**Comment by jschuler** [comment]
Fixed with https://github.com/algolia/docsearch-configs/pull/1145
