### ISSUE TITLE
list of icons in PF should be provided

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-org#1576]
As a consumer, I should be able to find a list of all icons that are available in PF. The following are some obstacles I experienced in trying to find an icon that I needed:

- Currently, the website does not list all icons available. There is a statement about these icons being a subset, and there's a link to a getting started page that provides some information about icons, but that information doesn't point me to any place where I can find a full list of icons available.
- From past experience, I was aware that there was a [react workspace that listed all icons](https://patternfly-react.surge.sh/patternfly-4/icons/), but I couldn't find a link to this from either the website or the patternfly-react repo documentation. 
- It isn't obvious what the React component name for icons are. For example, in the full list in the React workspace, the names are written like "Add Circle O" but the react icon component is named "AddCircleOIcon". The following are steps that I took to come to this realization: 
  1. Find an icon on the [pf.org icon page](https://www.patternfly.org/v4/design-guidelines/styles/icons)
  2. Click the icon
  3. Click Copy React
  4. Paste the copied contents
  5. At this point, I realized that the names are CamelCase. But also, not knowing what was getting copied was a little weird (like where do I know where to paste this text without knowing what it is 🤷‍♀ ). And for the next icon I need, the abilty to copy the react is also a little weird because I don't need the full import statement, but I also might not be exactly sure what the icon name is either. 

Some ideas for these pain points are:
- include links to the React and HTML workspace pages that list the full set of icons if listing the full set on the website is not an option
- In the popup that displays for an icon on the website, display both the react and html names of the icon. Also:
  - Consider listing both the react name and react import statement
  - Consider displaying the text that gets copied along with the copy action so that consumers know what they're copying
- In the list of icons on the [React workspace](https://patternfly-react.surge.sh/patternfly-4/icons/), display the component name along with the icon (e.g. "AddCircleOIcon" instead of "Add Circle O")

**Comment by evwilkin** [comment]
Related issue https://github.com/patternfly/patternfly-org/issues/1888 to clarify additional icons available outside of PF recommended subset

**Comment by redallen** [comment]
@bdellasc compiled a list of allowed PF icons and the list is here: https://www.patternfly.org/v4/guidelines/icons#all-icons . The React name is included as well as how to include it in React/HTML.
