### ISSUE TITLE
Horizontal Navigation: Dropdown code examples on Overview and Code pages scrolling off the page

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#158]
Playing with the "Menu Bar with Drop-Downs” examples at the bottom of the Overview and Code pages of horizontal navigation produces a little bit of finicky behavior with scrolling since the dropdown scrolls off the page.

**Comment by dlabrecq** [comment]
Gave a little more room at the bottom of the page so the menus won't drop off the page.
