### ISSUE TITLE
Button placement docs enhancement

### ISSUE THREAD

**Issue by seanforyou23** [patternfly/patternfly-org#1592]
We currently have a page dedicated to explaining usage of [buttons and links](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/buttons-and-links) in our docs website. One of the topics I see often asked about is regarding the placement of buttons when there are several side-by-side. We have a really helpful [blog post](https://blog.patternfly.org/patternfly/button-placement-on-forms/) on how to best handle this scenario, but people often don't know about it. Can we reference this in some way from the docs?

**Comment by rachael-phillips** [comment]
@mcarrano making you aware of this

**Comment by mcarrano** [comment]
@seanforyou23 Thanks for filing this. @mmenestr  is currently working on updating these guidelines, and this is a topic we will address.

**Comment by mcarrano** [comment]
This was resolved by https://github.com/patternfly/patternfly-org/pull/1638
