### ISSUE TITLE
Training card component styles applying to documentation examples

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1599]
These styles aren't scoped and are applying globally across the site, impacting cards anywhere they're displayed.

https://github.com/patternfly/patternfly-org/blob/master/packages/patternfly-4/gatsby-theme-patternfly-org/components/trainingCard/trainingCard.css#L1-L56

<img width="1211" alt="Screen Shot 2019-12-19 at 12 48 10 PM" src="https://user-images.githubusercontent.com/35148959/71200539-d63f5880-225d-11ea-86d0-216ad342775e.png">

cc @kybaker

**Comment by evwilkin** [comment]
@mcoker can you confirm if this is resolved now? It looks like https://github.com/patternfly/patternfly-org/pull/1566 updated the selector specificity for the Org examples, but that was wrapped up before this issue was logged.

**Comment by mcoker** [comment]
@evwilkin lgtm!
