### ISSUE TITLE
Utilization Trend Card: copyediting

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#160]
Following are typos or copy changes for the [Utilization Trend Card pattern](https://v2-patternfly.rhcloud.com/pattern-library/cards/utilization-trend-card/#/_overview).

Key: _old text_ -> _new text_ (_where to find the text_)

- End point and tooltip on circle should be 82%. (Overview tab, Single Metric example)
- Gpbs -> Gbps (Overview tab, Single Metric example and on the Code tab)
- End point and tooltip for circle on Network card should be 82%. (Overview tab, Multiple Metrics example)
- This could be available, which is the PatternFly default, or used. -> This could be the amount available (PatternFly default) or the amount used.  (Design tab, Single Metric # 2 and Multiple Metric # 4)

**Comment by dlabrecq** [comment]
Why must the end point and tooltip be 82%?

These examples are included directly from the PatternFly test pages and Angular-PatternFly ngDocs. It takes some doing to change all this code in multiple repos. Currently, the patternfly example is showing 85% and the Angular-Patternfly example is showing 76%. I don't see anything on the design page that suggests this must be 82%?

**Comment by Essjaysee** [comment]
My math is bad, no worries!  Skip that one.

**Comment by dlabrecq** [comment]
Done.
