### ISSUE TITLE
New 404 page design

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1607]
Improve the user experience when a user is on a page that doesn't exist in another version and they get a 404 when navigating between them. We don't have a current pattern for this in PF so I would suggest looking at 404 patterns within other RH sites and other design system sites for inspiration!

This is what the current 404 page looks like on patternfly.org (you can get to it if you try to navigate to patternfly.org/v5 for example)
<img width="1328" alt="Screen Shot 2020-06-22 at 9 43 12 AM" src="https://user-images.githubusercontent.com/30870144/85294615-da4a6e00-b46c-11ea-8bf5-457f012105e9.png">

cc @evwilkin @dgutride

**Comment by rachael-phillips** [comment]
@dgutride can you tell me more about what you were envisioning when users land on the 404 page? Would you rather it be a page that offers them a link to the current and updated documentation. The content could read something link "We're sorry, this documentation doesn't exist in this release. If you would like to see the updated documentation please follow this link." Abi could help advise us on the copy here, of course :)

**Comment by redallen** [comment]
Warning: we don't get any context when a user lands on our 404 page where they came from. They could have mistyped an address in the URL bar, they could click a dead link in the PF3 version of the site, or be trying to switch to an older version of the website that doesn't have a new page.

**Comment by gdoyle1** [comment]
FYI this is what the current 404 page looks like on patternfly.org (if you try to navigate to patternfly.org/v5 for example)
<img width="1328" alt="Screen Shot 2020-06-22 at 9 43 12 AM" src="https://user-images.githubusercontent.com/30870144/85294615-da4a6e00-b46c-11ea-8bf5-457f012105e9.png">

**Comment by fionayhlin** [comment]
Hi! Since we're making one general 404 error page, I wanted the design to provide as much flexibility and information as possible. On this page, the user is notified of an error and given the option to either search for what they're looking for, or browse similar pages on patternfly.org. This also somewhat mirrors the redhat.com 404 page.

I have attached a rough wireframe of this here:

<img width="1255" alt="Screen Shot 2020-06-24 at 1 29 29 PM" src="https://user-images.githubusercontent.com/49918197/85603840-bcbd0600-b61e-11ea-8269-57803d53022a.png">

Thoughts?

**Comment by redallen** [comment]
I like it. The searchbox would show the same results as the one in the upper left, but we could possibly style it differently. Not sure what we'd put for the page titles. The documentation sections of the site are getting an overhaul per @rachael-phillips 's design soon. What do you think @rachael-phillips ?

**Comment by gdoyle1** [comment]
@fionayhlin I think a "get in touch" type of card could go well here! Same with "contribute". Thinking about the site overhaul happening soon... I'm thinking adding "get started" (link to the "about" section) and "styles" (link to the colors page) would be good since those won't be moving. I'm not sure if you checked in with @mceledonia on the 404 graphic here but I think there was a possibly effort to update that in the near future as well!

**Comment by fionayhlin** [comment]
Thanks for the feedback! Here's the updated draft with content. I did check in with @mceledonia, he provided the main icon!

<img width="1114" alt="Screen Shot 2020-07-06 at 9 02 12 AM" src="https://user-images.githubusercontent.com/49918197/86595871-62e60580-bf67-11ea-951c-79d297724743.png">

**Comment by gdoyle1** [comment]
@fionayhlin I like the icons! I have a couple more comments about the design:
1. If we are expecting to be able to click on those cards, I think we should make that more clear... maybe add a link button at the bottom? Check out these training cards we also have on the site: https://www.patternfly.org/v4/documentation/react/overview/react-training for ideas.
2. I think we can make the titles of the cards larger - if they are 16 now, maybe 18?

**Comment by fionayhlin** [comment]
@gdoyle1 I actually did make a second option with the link and no icon! I'll combine the two. As for the titles, they're already 18, I could go up to 20?

**Comment by fionayhlin** [comment]
<img width="1143" alt="Screen Shot 2020-07-06 at 10 30 45 AM" src="https://user-images.githubusercontent.com/49918197/86604724-c0804f00-bf73-11ea-8277-ff9b70720206.png">
<img width="1089" alt="Screen Shot 2020-07-06 at 10 31 49 AM" src="https://user-images.githubusercontent.com/49918197/86604839-e73e8580-bf73-11ea-9100-1d3270955aa7.png">

@gdoyle1 some options!

**Comment by gdoyle1** [comment]
@fionayhlin If they're 18, then that's great! I would replace "see" with "view" and then I think they're good to go!

**Comment by fionayhlin** [comment]
<img width="1213" alt="Screen Shot 2020-07-06 at 1 02 48 PM" src="https://user-images.githubusercontent.com/49918197/86619777-2f1bd780-bf89-11ea-82b5-33a25557b02f.png">

[PF-404Error.zip](https://github.com/patternfly/patternfly-org/files/4880288/PF-404Error.zip)

Final version :)

**Comment by gdoyle1** [comment]
Very nice! @mcarrano @mceledonia What do you think?

@rachael-phillips Does this solve the initial issue reported?

**Comment by rachael-phillips** [comment]
Yes, absolutely! Great job @fionayhlin!

**Comment by mcarrano** [comment]
This is looking great @fionayhlin @gdoyle1 . The only thing I wonder is if the cards are providing the right option. Most likely, someone will land on this page because they are looking for content that have been moved, renamed, etc. Maybe these topic areas should more closely link to the primary nav items. That would mean including Design Guidelines and Documentation (Styles is part of Design Guidelines). Other thoughts on this?

**Comment by gdoyle1** [comment]
@fionayhlin @mcarrano sorry for the late response on this - I agree linking to design guidelines and documentation may be better than "styles" and "contribute". Fiona, would you mind replacing "styles" with "design guidelines" and then "contribute" with "documentation" ? After that change, I think this would be good to go!

**Comment by fionayhlin** [comment]
@gdoyle1 @mcarrano

<img width="1296" alt="Screen Shot 2020-08-03 at 11 07 42 AM" src="https://user-images.githubusercontent.com/49918197/89197341-8e194000-d579-11ea-87e7-0a9c006cd5d3.png">

**Comment by gdoyle1** [comment]
@fionayhlin nice! This looks good to me

**Comment by mcarrano** [comment]
This looks great @fionayhlin . Just one small thing. Should the link in the second card be "View design guidelines," or is it "View Design Guidelines" because this names a section in the website? I'm never sure about these capitalization rules :)

**Comment by fionayhlin** [comment]
@mcarrano Thank you! That's what I was wondering too... Maybe "Design guidelines" since that's how it's written in the nav?

**Comment by mcarrano** [comment]
Yes, I think that works @fionayhlin . @gdoyle1 @abigaeljamie what do you think?

**Comment by gdoyle1** [comment]
@mcarrano @fionayhlin Design guidelines sounds good to me!

**Comment by fionayhlin** [comment]
@mcarrano @gdoyle1 mock updated above :)

**Comment by abigaeljamie** [comment]
Sorry, I was on PTO Monday and Friday, so I'm just seeing this now. I love the new design! 

The only suggestion I have is to change the last part "or go home" to something like "or return to the home page," and hyperlink that to PF's home page (if possible). The "go home" part initially sounded like we're asking them to go home (not to the home page). But the extra clarity eliminates any kind of ambiguity.

**Comment by evwilkin** [comment]
@fionayhlin @gdoyle1 are we moving forward with this design?  This may make sense to pull into the next round of website updates once the redesign is live.  Please feel free to open a new issue for dev when ready - thanks!

**Comment by gdoyle1** [comment]
@fionayhlin do you mind updating your sketch file based on Abi's comment above?

**Comment by fionayhlin** [comment]
Sorry I missed this! Here's the updated screen @abigaeljamie @gdoyle1 @evwilkin 

<img width="1196" alt="Screen Shot 2020-09-17 at 12 22 30 PM" src="https://user-images.githubusercontent.com/49918197/93499018-76efa100-f8e0-11ea-8aef-7baa6572b817.png">

**Comment by evwilkin** [comment]
@fionayhlin can you link to or attach the images used in this redesign?  I'm not able to access the Sketch file in the comments above - thanks!

**Comment by evwilkin** [comment]
@fionayhlin @gdoyle1 I believe we also need to update the end of the "Try searching patternfly.org or go home" sentence as well, similar to the CTA, per @abigaeljamie's comment?  Should that read "Try searching patternfly.org or return to the home page"?  No need to update the mockups, just wanted to confirm what to change that to.

**Comment by gdoyle1** [comment]
@evwilkin linking the images that are used in the cards here... and then based on @abigaeljamie 's comment, Fiona had made the change of "Go Home" to "Return to the home page" - which I believe was what Abi was saying to do! _I think_ she was giving two options of what to add in the CTA either that ^ or "Try searching patternfly.org"
[pforg404.zip](https://github.com/patternfly/patternfly-org/files/5357350/pforg404.zip)

**Comment by abigaeljamie** [comment]
Thanks, Evan and Gina! Yes, just changing that "or go home" copy to "or return to the home page" will be perfect 👍 It matches the CTA too, which will look nice.

**Comment by gdoyle1** [comment]
@evwilkin @abigaeljamie @mcarrano I think we should put this on hold for the meantime since we've redesigned the website and the categories don't quite make sense anymore. I would assume the set-up of the page would remain the same but the content should change!

**Comment by gdoyle1** [comment]
Based on our conversation today, @abigaeljamie will work on finalizing the descriptions for the cards below. @mcarrano and I will review once she's done and then @fionayhlin will update the Sketch file once the content is finalized!

Cards will become the following:

1. Get started (link to [About](https://www.patternfly.org/v4/get-started/about))

2. Guidelines (link to [Colors](https://www.patternfly.org/v4/guidelines/colors))

3. Components (link to [About modal](https://www.patternfly.org/v4/components/about-modal))

4. Charts (link to [About](https://www.patternfly.org/v4/charts/about))
- will need @fionayhlin to work on finding a new illustration for this

**Comment by fionayhlin** [comment]
@gdoyle1 @abigaeljamie @evwilkin 

Design updated with new copy:

![PF-404Error-101520](https://user-images.githubusercontent.com/49918197/96151407-62032f00-0ed9-11eb-964f-0fa87c7e8ea1.png)

**Comment by abigaeljamie** [comment]
Thanks, @fionayhlin ! I think the second like under "404" can be spruced up so that it's more conversational. Here are some options we could try: 

_Another page might have the information you need, so try searching PatternFly.  

Another page might be what you need, so try searching PatternFly.  

Another page might be what you’re looking for, so try searching PatternFly.  

You might find what you’re looking for elsewhere, so try searching PatternFly.  

Perhaps another page might help you out, so try searching PatternFly._

**Comment by redallen** [comment]
@fionayhlin Where should the "View components" or "View charts" links link to? About modal and Area chart?

**Comment by gdoyle1** [comment]
> @fionayhlin Where should the "View components" or "View charts" links link to? About modal and Area chart?

@redallen we'll use the links in this comment! https://github.com/patternfly/patternfly-org/issues/1607#issuecomment-707821720

**Comment by redallen** [comment]
I've implemented the empty state and added another search input.

Algolia follows along as you type, so a search button is redundant. It's already difficult to add one to a TextInput, so I forewent that.

I'd like your 5 icons as SVGs, please! Then I can add them.

**Comment by abigaeljamie** [comment]
@gdoyle1 / @fionayhlin : Did one of you have a chance to pick a new line of copy to place below the heading from the above options?

**Comment by fionayhlin** [comment]
@redallen The preview looks great! Slacking you the icons because Github doesn't accept SVGs.

**Comment by fionayhlin** [comment]
@abigaeljamie with new copy:

<img width="1271" alt="Screen Shot 2020-10-19 at 4 32 38 PM" src="https://user-images.githubusercontent.com/49918197/96508513-b46d8400-1228-11eb-9130-bc052892230b.png">
