### ISSUE TITLE
Add design guidelines for inline edit

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1608]
Introduce a new design guideline document for inline editing applied at the field, row, or page level. 

Design documentation: https://docs.google.com/document/d/15aOWgpkd0Zp0hvbKM4jfG6Jf00FHjY_f92bkosbo1Ds/edit?usp=sharing

**Comment by mmenestr** [comment]
Just have inline edit topic - may not want to split it up in topics. But can assess that when going through the doc!

**Comment by doruskova** [comment]
Shared [this doc](https://docs.google.com/document/d/1RHqz-FAXo-0WTzjMl8pq3tSHbkkO_lnSj0Fyml4RRdk/edit?usp=sharing) with Inline edit doc + images
