### ISSUE TITLE
Add design guidelines for drag & drop pattern

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1609]
Introduce documentation on drag & drop pattern that can be applied to a variety of components. Should cover visual affordances for drag and drop together with interactions and recommended usage. Visual design approach is documented here: https://marvelapp.com/51cf3fa/screen/65012767

**Comment by mcarrano** [comment]
The following article includes some great guidance on implementing an accessible drag & drop pattern: https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09

**Comment by mmenestr** [comment]
Latest news: Just entered into the core sprint...

**Comment by mcarrano** [comment]
@mmenestr We were having some discussion in the OpenShift sync meeting today about drag & drop. They have a custom implementation within a form. We have currently added this capability to the Data List component and we should probably document there. But I'm also wondering if we need a general guideline about this to drive any custom implementations, i.e. what icons or other affordances to use, etc. I expect we might see more custom implementations (as this is a pretty use case unique thing) so it brings into question what developers should consider to make for a consistent and usable experience. Thoughts?

**Comment by mmenestr** [comment]
@mcarrano I don't have much background on our current drag and drop pattern, but are people using custom implementation in a visual sense, or just in a "technical" sense?

**Comment by mcarrano** [comment]
@mmenestr This came up because I was seeing that OpenShift had a custom implementation, which was fine, but I felt like there was an opportunity to be more consistent around icon usage and visual affordance. Right now that's not documented anywhere on the PatternFly site. This is not a big priority, but we can discuss more during the next doc planning meeting.

**Comment by mmenestr** [comment]
@mcarrano oh okay, interesting. It does seem like it would be good to keep the visual pattern consistent across products. Would be curious to hear more about the custom implementation, and why they felt the custom implementation was needed!

**Comment by mmenestr** [comment]
Update- has been implemented in data list.
Trying to figure out how we should add this guidance since it's not technically a component.

**Comment by mmenestr** [comment]
Closing bc covered here: https://app.zenhub.com/workspaces/design-doc-workspace-5f08c64d6a6ef2001d56a458/issues/patternfly/patternfly-org/2348
