### ISSUE TITLE
Utilization Trend Card: example image

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#161]
Typo in the example image on the [Design tab](https://v2-patternfly.rhcloud.com/pattern-library/cards/utilization-trend-card/#/_design), Single Metric graphic: GB Available -> Gbps Available.

**Comment by dlabrecq** [comment]
@LHinson Need new images.

**Comment by LHinson** [comment]
@dlabrecq 
![singe-metric-utilization-card2](https://cloud.githubusercontent.com/assets/7924406/15974035/7269bd40-2f14-11e6-9f86-f853a7807800.png)

**Comment by dlabrecq** [comment]
Done.
