### ISSUE TITLE
React's Gallery layout codesandbox link doesn't work

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1610]
This might be a problem with other layouts/components, just something I noticed with the react gallery component's "basic" example codesandbox link - https://www.patternfly.org/v4/documentation/core/layouts/gallery#basic

**Comment by redallen** [comment]
https://codesandbox.io/s/g1e8y works now. Not sure if @ddonahue007 's efforts were what fixed it, but closing.
