### ISSUE TITLE
First character in HBS block is removed

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1611]
I noticed that if the first character in an ` ```hbs ` block is regular text, the first character is cut off. For example, the text "Editable" in this [clipboard copy hbs block](https://github.com/patternfly/patternfly-next/blame/master/src/patternfly/components/ClipboardCopy/examples/ClipboardCopy.md#L29) renders as "ditable" - https://www.patternfly.org/v4/documentation/core/components/clipboardcopy#expanded

**Comment by redallen** [comment]
You seem to have changed that specific example to `<h4>Editable</g4>`, are there any other examples for me to debug? I'm not sure why this would be happening.

**Comment by mcoker** [comment]
@redallen I'm not sure if there are other examples with the problem, but to debug it just put some text in an example hbs block. Looks like the first and last character are cut off.

<img width="741" alt="Screen Shot 2020-01-31 at 5 27 44 PM" src="https://user-images.githubusercontent.com/35148959/73581499-0aa65700-444f-11ea-90ab-8ace59ef5017.png">
