### ISSUE TITLE
Gatsby theme styles bleeding into examples

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1615]
https://github.com/patternfly/patternfly-org/blob/master/packages/patternfly-4/gatsby-theme-patternfly-org/components/commonComponents/commonComponents.css#L14-L16

The styles above are creating an issue seen in this issue that was filed in the core repo - https://github.com/patternfly/patternfly-next/issues/2547 (no bottom border after expanded rows)

But it seems like [all of the unscoped table component styles](https://github.com/patternfly/patternfly-org/blob/master/packages/patternfly-4/gatsby-theme-patternfly-org/components/commonComponents/commonComponents.css#L10-L32) (including the rules in the media queries) will be problematic. Are they needed for any reason?

**Comment by rachael-phillips** [comment]
@evwilkin making you aware of this issue
