### ISSUE TITLE
Utilization Trend Card: substantive edit

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#162]
The [Overview examples](The Overview examples don’t show Last 30 days, but the Design tab does, and it doesn’t mention that it’s optional.) don’t show 'Last 30 Days' at the bottom of the chart, but the examples on the Design tab do, and the callouts don’t mention that it’s optional. So, either add it to the examples or put in the callout that it's optional.

**Comment by dlabrecq** [comment]
Added optional to the callout.
