### ISSUE TITLE
Cross browser & cross device compatibility testing

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1624]
Look for solution to test across different browsers & different devices

**Comment by ddonahue007** [comment]
This might fall under the QE/QA are and not want to have it in our pipeline.

**Comment by redallen** [comment]
I'd follow the same architecture as in https://github.com/patternfly/patternfly/pull/2599.

If we want to dedicate time to this and specify more of what tests look like feel free to reopen.
