### ISSUE TITLE
Replace full page previews with images

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1630]
Revert to images for previews, addressing both #1557 and #1562

**Comment by redallen** [comment]
I think we can create a post-build step where we start serve the built site (minus the fullscreen image thumbnails), grab the screenshots from localhost:9000/whatever (there's already a list of fullscreen pages in .cache/fullscreenPages.json that's used for the a11y tool), and then save them back to the public folder under static/some-sha-known-at-compile-time/Button/basic.png.

We would add this step to the theme.

**Comment by redallen** [comment]
Closing in favor of #1660
