### ISSUE TITLE
Please add "Build with Patternfly page"

### ISSUE THREAD

**Issue by williamjmorenor** [patternfly/patternfly-org#1631]
Hello, as far as I know these are the major projects using patternfly:

* Cockpit: https://cockpit-project.org/
* OpenShift: https://www.openshift.com/
* FreeIPA: https://www.freeipa.org/page/Documentation

Can you please a "Build with PatternFly" to see a list of projects using patternfly in production.

**Comment by williamjmorenor** [comment]
Ovirt also uses patternfly:

https://ovirt.github.io/ovirt-design/admin-ui/compute/vm-dashboard

**Comment by rachael-phillips** [comment]
Hi @williamjmorenor thanks for opening this! We have discussed this before, and it's an idea we are very curious about! @evwilkin @mcarrano @dgutride making you aware

**Comment by evwilkin** [comment]
Discussed for inclusion as part of homepage revamp, which is starting to get under way.  In the meantime, we have some community projects listed on our Community page (https://www.patternfly.org/v4/community).

**Comment by dlabaj** [comment]
Currently do not have plans to add this.  We can open this up for further discussions in the future if needed.
