### ISSUE TITLE
Add links in site to related training

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1634]
Now that the PatternFly developer training is officially on patternfly.org, we can create links within the website to the relevant training modules.

@rachael-phillips is going to help with a design story for how these links should look on the pages in the website.

@dgutride @janwright73 can you quickly browse these links to make sure this looks good:

- (Table React component)[https://www.patternfly.org/v4/documentation/react/overview/training] links to `react-components/table-intro`

- (Select React component)[https://www.patternfly.org/v4/documentation/react/components/select] links to `react-components/select`

- (Data Toolbar React component)[https://www.patternfly.org/v4/documentation/react/experimental/datatoolbar] links to `react-components/toolbar-filter`

- (Area Chart)[https://www.patternfly.org/v4/documentation/react/charts/chartarea] links to `react-charts/area-chart`

- (Bar Chart)[https://www.patternfly.org/v4/documentation/react/charts/chartbar] links to `react-charts/bar-chart`

- (Bullet Chart)[https://www.patternfly.org/v4/documentation/react/charts/chartbullet] links to `react-charts/bullet-chart`

- (Donut Chart)[https://www.patternfly.org/v4/documentation/react/charts/chartdonut] links to `react-charts/donut-chart`

- (Donut Utilization Chart)[https://www.patternfly.org/v4/documentation/react/charts/chartdonututilization] links to `react-charts/donut-utilization-chart`

- (Line Chart)[https://www.patternfly.org/v4/documentation/react/charts/chartline] links to `react-charts/line-chart`

- (Pie Chart)[https://www.patternfly.org/v4/documentation/react/charts/chartpie] links to `react-charts/pie-chart`

- (Stack Chart)[https://www.patternfly.org/v4/documentation/react/charts/chartstack] links to `react-charts/stack-chart`

- (Sparkline Chart)[https://www.patternfly.org/v4/documentation/react/charts/sparkline] links to `react-charts/sparkline-chart`

- (Bullseye Layout)[https://www.patternfly.org/v4/documentation/core/layouts/bullseye] links to `html-css/layouts`

- (Flex Layout)[https://www.patternfly.org/v4/documentation/core/layouts/flex] links to `html-css/layouts`

- (Gallery Layout)[https://www.patternfly.org/v4/documentation/core/layouts/gallery] links to `html-css/layouts`

- (Grid Layout)[https://www.patternfly.org/v4/documentation/core/layouts/grid] links to `html-css/layouts`

- (Level Layout)[https://www.patternfly.org/v4/documentation/core/layouts/level] links to `html-css/layouts`

- (Split Layout)[https://www.patternfly.org/v4/documentation/core/layouts/split] links to `html-css/layouts`

- (Stack Layout)[https://www.patternfly.org/v4/documentation/core/layouts/stack] links to `html-css/layouts`

- (Get started > Develop)[https://www.patternfly.org/v4/get-started/developers] links to `html-css/building-blocks` and `react/react-basics`

- I'm not sure where `html-css/variable-naming-principles` and `html-css/modifier-utilities` should go because I don't think we have a page dedicated to how to write variables and how we follow BEM etc. We used to have this on the old website, I think Matt Carleton bought it up. Is there any progress on adding this back in?

**Comment by redallen** [comment]
You've created a whole "Training" page now! https://www.patternfly.org/v4/get-started/training

If you'd like to add those links to all of those components' design guidelines, feel free to reopen and rename the issue. If you'd like to add them to the Core/React docs themselves, this issue should be split up between those repos.

Closing.
