### ISSUE TITLE
Make fullscreen example code selectable

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#1641]
Allow copying text even when we pass `disabled` to react-live.

Possible implementations include overriding `react-live`s styles, or making our own implementation of `disabled` that does not allow text to be edited.

**Comment by guillaumevincent** [comment]
![image](https://user-images.githubusercontent.com/943762/73431545-f6743400-4340-11ea-8e09-bd889560e6ea.png)

Selection on the text is possible but the copy is not.
It is confusing.

**Comment by redallen** [comment]
Turns out this is a CSS and Firefox issue. Fix should be deployed shortly.

**Comment by redallen** [comment]
Fix is deployed to patternfly.org. Let me know if you still have issues @guillaumevincent .

**Comment by guillaumevincent** [comment]
I confirmed! Thank you @redallen much better!
