### ISSUE TITLE
Mobile view of qualtrics

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1654]
The placement of the mobile view of qualtrics should be centered rather than left-bottom on mobile. We should also find a way to grey out the homepage background because it is so invasive to the mobile view. This does not need to hold up release. 
![PatternFl](https://user-images.githubusercontent.com/40275806/73396092-b5334400-42ae-11ea-9832-5b47811aa0e9.jpg)

**Comment by rachael-phillips** [comment]
cc @evwilkin

**Comment by rachael-phillips** [comment]
@ddonahue007 happy to work with you on what this should look like. Let me know how I can help!

**Comment by ddonahue007** [comment]
Notes: 
1. find the breakpoint that the qualtrics survey moves to the corner (if there's any)

2. use that breakpoint (or a patternfly breakpoint listed here: https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/scss-variables.scss#L157) to write some css to center the div qualitrics is inserting

**Comment by ddonahue007** [comment]
I am able to get what I believe we want via the inspector.

![Screen Shot 2020-02-17 at 11.58.20 AM.png](https://images.zenhubusercontent.com/5dc5dcfe586229000122b6e7/243b31f9-2d78-4d15-be3b-6d411bec7617)

![Screen Shot 2020-02-17 at 11.58.39 AM.png](https://images.zenhubusercontent.com/5dc5dcfe586229000122b6e7/db0275dc-9df8-4e35-8537-b9d630fc42b6)

**Comment by ddonahue007** [comment]
have the centering working

 ![Screen Shot 2020-02-17 at 11.58.20 AM.png](https://images.zenhubusercontent.com/5dc5dcfe586229000122b6e7/dde1fb4c-89be-43bb-8230-ff0ba72021d7)

**Comment by evwilkin** [comment]
Closed by #1692
