### ISSUE TITLE
Some patterns missing from Patterns Overview page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#166]
On this page, https://v2-patternfly.rhcloud.com/pattern-library/#_, in the Communications section there are some patterns in the navigation that don't have corresponding tiles in the body of the page.  They are: About Modal, Notifications Drawer, and Wizard.

**Comment by dlabrecq** [comment]
@LHinson, we're also missing:

Forms #149 
Find #148 
Horizontal navigation #150

**Comment by LHinson** [comment]
I've created a story here to cover the work - https://patternfly.atlassian.net/browse/PTNFLY-1533

**Comment by kybaker** [comment]
Finished this. It will appear in the next release.

**Comment by LHinson** [comment]
Closing this as we will update this page with the design status page instead.
