### ISSUE TITLE
Table workspace style is affecting Table component/demo

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#1661]
Max-width was set on tables which is causing this:

<img width="1325" alt="Screen Shot 2020-01-31 at 1 53 13 PM" src="https://user-images.githubusercontent.com/20118816/73566573-2f400600-4432-11ea-87af-1c6709327948.png">

@evwilkin

**Comment by evwilkin** [comment]
@christiemolloy this was definitely an issue we saw but should have been resolved in [#1642](https://github.com/patternfly/patternfly-org/pull/1642/files#diff-a43d066c11eb71b9a5efce191eec4fc4)

I just checked the site and am not seeing the issue anymore, are you seeing this live?  If it's local, you may just need to pull these updates from a few days back - let me know!

**Comment by evwilkin** [comment]
Closing as this issue no longer exists, was resolved in #1642 
![Screen Shot 2020-03-28 at 11 18 25 AM](https://user-images.githubusercontent.com/8651509/77826463-eaf57d00-70e5-11ea-902c-4f44cf1a6d74.png)
