### ISSUE TITLE
Typography page update to clarify monospaced font type

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#1665]
Update the typography page [1] to specify that Liberation mono is the available monospaced font in PF. 

[1] https://www.patternfly.org/v4/design-guidelines/styles/typography

**Comment by mmenestr** [comment]
More guidance:
Add another "table" like the one below for the font mentioned above^?

Call this "Code text"? 
Font family: Liberation Mono
etc

![image](https://user-images.githubusercontent.com/51165119/85301815-4c738080-b476-11ea-8bcb-dd4210c9e106.png)
