### ISSUE TITLE
Standardize card design and styling across the flow

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1666]
In the introduction of the new training modules, a new card design was introduced that should be styled like our other cards across the site. The grey border should be removed and this card should look like our release notes card.

<img width="1482" alt="Screen Shot 2020-02-03 at 11 20 37 AM" src="https://user-images.githubusercontent.com/40275806/73670905-0c069800-4678-11ea-9e29-da2768119acc.png">

cc @mcarrano for your awareness @evwilkin

**Comment by redallen** [comment]
@christiemolloy is the one who implemented the cards. Is all you're wanting removed the grey border?

**Comment by evwilkin** [comment]
@rachael-phillips with recent site redesign there are no longer cards on the [release notes page](https://www.patternfly.org/v4/get-started/release-notes). I wanted to confirm before moving forward with this issue that we still want to make this change, as there's no longer a mismatch present.

**Comment by rachael-phillips** [comment]
That makes sense!
