### ISSUE TITLE
Word "above" in Inline Notifications Overview no longer makes sense.

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#167]
On this page: https://v2-patternfly.rhcloud.com/pattern-library/communication/inline-notifications/#/_design text first item reads: "Background: The notification should occupy the full width of the main content area. See the "In Context" example above." This is no longer above as the content was broken into separate pages. My recommendation is to remove the work "above" and just link the text "In Context example."

**Comment by dlabrecq** [comment]
Fixed.
