### ISSUE TITLE
Remove qualtrics survey

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1670]
We should aim to remove the qualtrics survey after 90 days. 2020.05 milestone, end of April. cc @evwilkin for awareness

**Comment by redallen** [comment]
Can we set an alert for this or put it on a calendar? Seems like an easy thing to forget if it's only here in an issue.

**Comment by evwilkin** [comment]
>Can we set an alert for this or put it on a calendar? Seems like an easy thing to forget if it's only here in an issue.

@redallen on it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rachael-phillips** [comment]
@redallen @evwilkin I think we can go ahead and take this down this sprint, correct?

**Comment by evwilkin** [comment]
@rachael-phillips looks correct!  I'll pull this issue into our milestone
