### ISSUE TITLE
Create yeoman generator

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1676]
Define & prioritize goals to improve developer experience with PatternFly

**Comment by redallen** [comment]
I think a lot of overhead for new developers is setting up the scaffolding for a new SPA that uses PatternFly. I believe a yeoman generator to create projects similar to our seed project would be really helpful for the developer experience, and we could use that generator as a base for other getting started content. I think the following options would be beneficial to devs:

- Webpack or Rollup (Rollup support isn't great right now, but would be awesome!)
- JS+Babel or Typescript+tsc
- Single patternfly.css or Modular patternfly-base.css + imports
- Jest+Enzyme or No tests
- Cypress or No integration tests
