### ISSUE TITLE
Add link to /v3 from the /v4 version switcher?

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1678]
The link to patternfly 3 isn't that easy to find in the footer. Should we add a link to it at the bottom of the version switcher, similar to https://getbootstrap.com/?

cc @rachael-phillips

**Comment by redallen** [comment]
@rachael-phillips Ping

**Comment by rachael-phillips** [comment]
Here is the design. Up for a review @mcarrano @evwilkin @mcoker 

<img width="443" alt="Screen Shot 2020-03-31 at 10 33 45 AM" src="https://user-images.githubusercontent.com/40275806/78038844-51bfa400-733b-11ea-9bf5-4089401db8b0.png">

Requirements
1. List only 4 releases total
2. Add PatternFly 3 text with external link icon - links to patternfly.org/v3
3. Remove patternfly.org/v4 to be patternfly.org
