### ISSUE TITLE
Bug - Lorem ipsum in search results

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1685]
Searched for Icon, got this "Lorem ipsum" in the search results. Doesn't seem right.
![Xnip2020-02-11_08-53-14](https://user-images.githubusercontent.com/23172038/74242501-0cbcb100-4cac-11ea-8401-7d7703384e1d.jpg)

**Comment by rachael-phillips** [comment]
Thanks for filing this @katierik ! This points to a deeper need to reevaluate our search experience across desktop and mobile.

**Comment by evwilkin** [comment]
This appears to be resolved now.
