### ISSUE TITLE
Update Icons page on website with updated icons and recommentations

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1687]
Update the Icons page to reflect the PatternFly icon and usage recommendations found in [this  spreadsheet](https://docs.google.com/spreadsheets/d/1FwcP3qQm6zseNT-MKM2BwEmlu1La6KSmWe7i-9JzNFw/edit?usp=sharing): 

- **icons in yellow (12)** have open questions. These icons have notes, some of which instruct to keep the usage text blank or leave the icon off the webpage (until we get more info from the team)
- **icons in pink (9)** these will be added to a migration table. These icons have notes, some of which instruct to leave the icon off of the webpage (until we create the icon migration table), but the new icon recommendations will remain on the webpage and are marked as such.
- **icons in blue (4)** need to be added to the PF font. There is a separate story for adding them here: https://github.com/patternfly/patternfly-next/issues/2707
- any new usage text is prepended with "Suggestion:" Any usage text with a strikethrough should be left off of the webpage for now (until we get more info from the team)

Columns to display: Icon Usage, Icon, Icon Name, Icon Type, Font Set

The original icon story is here: [https://github.com/patternfly/patternfly-design/issues/787](https://github.com/patternfly/patternfly-design/issues/787)

Work with @bdellasc throughout the process

cc @rachael-phillips @LHinson

**Comment by mcarrano** [comment]
Note that there is an older issue here that includes further enhancement recommendations: #1358

**Comment by gdoyle1** [comment]
Here's what I've done so far https://marvelapp.com/dj2867b! I'd love some feedback on how to organize the links within the icons table better (or really all the actions so Copy React, Copy HTML, and Download SVG).

My plan for next steps is:
1. Refine the icon sizes section copy and add the size variables
2. Refine the icon colors section copy and add the color variables
3. Possibly minimize the width of the "all icons" + table section

**Comment by bdellasc** [comment]
@mcarrano @gdoyle1 - I think that's a question for the front-end devs, if it's something they use on a regular basis? I'd hate to lose something that is useful for their work.

@rachael-phillips @mceledonia

**Comment by gdoyle1** [comment]
> @mcarrano @gdoyle1 - I think that's a question for the front-end devs, if it's something they use on a regular basis? I'd hate to lose something that is useful for their work.
> 
@bdellasc Ok I'll look more into this then!

**Comment by rachael-phillips** [comment]
Hi all @gdoyle1 @bdellasc @mcarrano my question is are the graphics on this page helpful? I am all about showing the different sizes if we think that is helpful, but if that is the case, can we show them more in context. I would opt for the text and then get straight to the table, to get to the table below the fold.

**Comment by gdoyle1** [comment]
@rachael-phillips I totally agree - I wasn't really sure what to put there for graphics or if we even need them. @mceledonia do you think graphics are needed to explain icon sizes and colors?

**Comment by gdoyle1** [comment]
Commenting for progress update:

- I've updated the [Marvel project here](https://marvelapp.com/dj2867b) with a possible design solution for a migration table (obviously all icons are not listed in the All icons table and _also_ all migrated icons/recommendations are not listed in the Migration table - full list can be found in Brian's spreadsheet)
- Will work with Matt Carrano on getting the PF font on GitHub and PF recommended icons SVG folder on GitHub

**Comment by gdoyle1** [comment]
The design for this has been completed:
1. [Marvel project](https://marvelapp.com/dj2867b) (includes a spec)
2. [Icons spreadsheet](https://docs.google.com/spreadsheets/d/1FwcP3qQm6zseNT-MKM2BwEmlu1La6KSmWe7i-9JzNFw/edit?usp=sharing)
- See tab 1: Website format for "All icons" table
- See tab 2: Updated recommendations for "Updated icon recommendations" table
3. [Google doc](https://docs.google.com/document/d/1pf5bXKaoPebn9-ChTFhstmgmM4WUwovBzyXXDSK9j4s/edit?usp=sharing) with all content for the page

We will be discussing how the PF font can be created at the end of this week so that may update some of the content listed in the Google Doc, but the design and icon tables are set.

**Comment by mcarrano** [comment]
Thanks for all your work on this @gdoyle1 !

@evwilkin I've removed the design label from this and passing off to the Infrastructure team for implementation.

**Comment by evwilkin** [comment]
Pushing back to 2020.06 milestone per discussion:

- Awaiting new icon font file ready & QA'd
- Need to post the SVGs to Github
