### ISSUE TITLE
Add short usage and design descriptions (design snippets) to Demo pages

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1689]
We currently do not have a good way to include design snippets in the Demo pages on the site. The current system breaks down when a component and demo have the same name. Currently, we have text for these in the 'src/content/design-snippets' folder but a fix was put in to hide them on the site due to the naming issue.

cc @evwilkin @rachael-phillips

**Comment by redallen** [comment]
What demos do you have text for? We can move this text to the demo's MD file itself in either HTML or React.

**Comment by mcarrano** [comment]
I have text for all of the current demos. You can see them listed in the spreadsheet here: https://docs.google.com/spreadsheets/d/1Mi93S23lOUE4HaL2hTuEiiI14Sh-fG8DXT8uhpNiT-Q/edit?usp=sharing I created a .md file for each of these living in the design-snippets folder.

**Comment by redallen** [comment]
There's now a tab for design guidelines that lives next to the demo tab. If you'd like to add example captions to demos that will have to be done in the Core/React repos and you can open an issue or PR there.
