### ISSUE TITLE
Update Pagination guideline to reflect latest enhancements

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-org#1694]
Pagination on patternfly.org is not showing the latest designs. 
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/pagination#main-content

this is confusing when putting together mocks

* More prominently reflect compact pagination option.
* Update mobile pagination approach per https://github.com/patternfly/patternfly-next/issues/2879

**Comment by mmenestr** [comment]
Need to update images before I can merge this PR (I am going to do that)
