### ISSUE TITLE
patternfly logo link sends user to a github issue

### ISSUE THREAD

**Issue by elmiko** [patternfly/patternfly-org#1700]
the anchor sends me to https://github.com/patternfly/patternfly-org/pull/1693, i expected it to direct back to https://www.patternfly.org

this image shows the link 

![image](https://user-images.githubusercontent.com/190649/75086179-2f966300-54ff-11ea-8ca8-555356fbc701.png)

**Comment by evwilkin** [comment]
Thanks for filing this @elmiko  - this will get resolved with our next release, and you're correct that it will direct back to https://www.patternfly.org as expected.

**Comment by evwilkin** [comment]
This is working correctly now - thanks again @elmiko
