### ISSUE TITLE
External link guidance needed

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#1701]
Requesting guidance on how to treat external links in a page in Patternfly.

Based on the customer portal (and the very common Wikipedia pattern!) we have been using this external link pattern:
"View in [destination] [external link icon]"

e.g. 
![image](https://user-images.githubusercontent.com/23172038/75164201-6b434f80-56ee-11ea-8822-80034b421867.png)

This would be great to have documented on the Patternfly website and in the Sketch library.

**Comment by katierik** [comment]
This is the only external link documentation I could find in the Sketch lib... which isn't easy to find!
![image](https://user-images.githubusercontent.com/23172038/75164452-d725b800-56ee-11ea-9b4e-91d8888f0fb4.png)

**Comment by gdoyle1** [comment]
@katierik that symbol is specifically for the application launcher - the spacing is already built into it as a list item within the menu. Since that padding is built in, I wouldn't recommend using that symbol as a standard "external link" pattern. I can work with @mcarrano on getting this added and documented in the correct place though!

**Comment by mcarrano** [comment]
It's true that we don't really state a guideline anywhere about this. Where would you expect to find this @katierik ? Would you expect to see an external link variant associated with link button?

**Comment by katierik** [comment]
I would actually most expect this documentation with general documentation about icons (size, spacing, etc), which doesn't seem to be on PF.org now.

**Comment by mcarrano** [comment]
@gdoyle1 @mmenestr What are your thoughts about this issue? We should probably update this page to reflect icon placement for external links: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/buttons-and-links  Do you think our updated Icons documentation can/should reflect this, also?

**Comment by mmenestr** [comment]
@mcarrano That documentation has a section on these links. Although I did create [this issue ](https://github.com/patternfly/patternfly-org/issues/1704) to address/reflect the new possibility of having the icon to the right of the link button as well as on the left.

I also worked with Gina to reflect both those possibilities in the Sketch library under PatternFly > Button > 7. Link button with left icon / 7. Link button with right icon!

In terms of whether we should update the icon documentation to reflect this information as well, i don't know. I personally would expect to find this in the link and button documentation where it currently is!

**Comment by gdoyle1** [comment]
@mcarrano @mmenestr we could always add a link from the icons page to the buttons/links guidelines but I agree with @mmenestr that this documentation should live where it currently is. Link buttons would be the thing to use in this case (I'm assuming?) but we should update the links/buttons documentation with the ability to add an icon on the left or right of the text. Maybe for this _specific_ case, we should recommend only adding it to the right of the text for external links?

**Comment by mcarrano** [comment]
Per @mmenestr 's comment, we will update the Buttons document to provide guidance. 

Agree @gdoyle1 that it would be worth linking to this from the Icons page in case users look for the information there. Maybe just add a note to say something like, "For more information about icon usage in buttons and links, see Buttons usage guidelines" with a link. Can you address this as part of your icon page work?

**Comment by mcarrano** [comment]
This will be addressed by https://github.com/patternfly/patternfly-org/issues/1687 and https://github.com/patternfly/patternfly-org/issues/1704  Will close this.
