### ISSUE TITLE
Look into using Docker images w/Katacoda

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1702]

**Comment by ddonahue007** [comment]
Status on this so far. we have a docker image that seems to be working correctly. Katacoda has it available on their Beta site. Hitting one issue with the verify step scripts. Gaby(Katacoda contact) thinks it might be something on their side of things.

**Comment by evwilkin** [comment]
Closing out due to progress stalled, focus shifting to Quick Starts for training/walkthroughs.
