### ISSUE TITLE
The <title> element in the HTML <head> should update to reflect the page being viewed

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-org#1705]
Right now, the `<title>` element on every page of the website just says "PatternFly 4". As you navigate the site, the title reflected in browser history stays the same, bookmarking any page will just title the bookmark "PatternFly 4", and when opening different docs pages in multiple tabs they all just say "PatternFly 4".

Trying to hop back a few pages in history to a specific component I was looking at, this is what I see when I right-click my back button:
![Screenshot 2020-02-26 14 07 53](https://user-images.githubusercontent.com/811963/75378448-b2be0d00-58a1-11ea-9796-9b0dd4649b40.png)

We should update the `<title>` on every route change to read something like "PatternFly 4 - Accordion" or "PatternFly 4 - Release Notes", etc.

**Comment by srambach** [comment]
Yes please! I screenshot this yesterday intending to make an issue for it but @mturley beat me to it.

**Comment by evwilkin** [comment]
Thanks @mturley and @srambach for pointing this out - I've just put up a fix here:
https://github.com/patternfly/patternfly-org/pull/1707
