### ISSUE TITLE
Add "Feedback" or "Report a problem" to website footer

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#1709]
It would be nice to have a direct link in the footer to the github issues page for the website if possible. This would make it much faster to report issues like broken links, as well as lowering the barrier for visitors from outside the team to know where to provide suggestions or to report problems.

**Comment by evwilkin** [comment]
Thanks @srambach - there's a similar discussion in progress to finalize designs for this feature here: https://github.com/patternfly/patternfly-design/issues/820

I'll keep this issue open to address those changes once the designs are finalized!

**Comment by evwilkin** [comment]
Closing in favor of #1780
