### ISSUE TITLE
Provide guidance around specific pull request description formatting for breaking change notes

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-org#1710]
We'd like to extract breaking change notes related to developer impact from pull requests.  Please provide a specific format that can be used to pull text from the description of a PR (wrapping in tildes for example - ~~Rename pf-var-one to pf-var-two~~).  This should allow us to run a script against github pr's regularly during breaking change release cycles to provide a digest of information for consumers that might want to be proactively keeping up.

**Comment by evwilkin** [comment]
Please put ## Notes at the end of the PR, followed by notes that we'll pull.

**Comment by redallen** [comment]
Our breaking change release is now over. This format worked well and I'd recommend it again!
