### ISSUE TITLE
Some links not maintaining browser history

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1713]
The following steps will link you to the next page, but not give you an option to navigate back to the original page:

1. Open [https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/bulk-selection](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/bulk-selection)
2. Click either of the Core or React "Split Button" links at the bottom of the page.
3. Check browser history - if pressing the Back button you'll see no record of the original page linked above, and if you're in a new tab you won't have the option to navigate back.

**Comment by redallen** [comment]
These interactions don't exist anymore with the new design.

Closing.
