### ISSUE TITLE
GDPR banner layout

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1715]
When we have an element like an alert, popover, etc with text and a close button, the close button should be positioned in the top/right corner. The GDPR banner currently positions the close icon in the center.

<img width="622" alt="Screen Shot 2020-03-09 at 10 02 06 AM" src="https://user-images.githubusercontent.com/35148959/76227980-19222400-61ee-11ea-8974-49a4178d8b41.png">

Should be:

<img width="644" alt="Screen Shot 2020-03-09 at 10 01 54 AM" src="https://user-images.githubusercontent.com/35148959/76227992-1c1d1480-61ee-11ea-8d48-36746dedd471.png">

can you confirm @mcarrano? 

To achieve that layout, you can use the following:

* remove `.pf-u-mr-xl` and associated CSS from the close icon wrapper
* remove `.pf-u-my-md` from the text wrapper
* add `.pf-u-py-md` and `.pf-m-align-items-flex-start` to `#ws-gdpr-banner`
* remove `align-items: center;` from `#ws-gdpr-banner`

optional:
* add `transform: translateY(calc(-1 * var(--pf-global--spacer--form-element)));` to either the close button or close button wrapper to offset its top position by its top padding.

**Comment by evwilkin** [comment]
@mcoker these changes look great except for one question at 1724px+
- The "x" button has top/bottom padding, and when the text is all on 1 line this button padding causes it to be taller than the line of text so the `flex-start` class is pulling the text up so it's not aligned with the button. Would it be best to add a media query for this edge case?
<img width="1727" alt="Screen Shot 2020-03-09 at 11 31 51 AM" src="https://user-images.githubusercontent.com/8651509/76230349-f5fd7180-61f9-11ea-8d4c-1fe1500a2efb.png">

**Comment by mcoker** [comment]
@evwilkin nice catch. I can't seem to get the banner to show up again, but try changing `.pf-m-align-items-flex-start` to `.pf-m-align-items-center` on the parent, then `.pf-m-align-self-flex-start` on the button wrapper.

**Comment by evwilkin** [comment]
Thanks, that works!  Also in case you need it, you can get the banner back by running `sessionStorage.removeItem('gdpr-banner-closed')` in the browser console then refreshing the page.
