### ISSUE TITLE
Context selector design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1719]
Introduce guidelines on usage and placement of context selector controls. Consider whether to include as part of existing [navigation system guidelines](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/navigation-system) or as a new page.

Background and preliminary guidance: https://docs.google.com/document/d/1c0tKt8DBNWx67QmLocvpUnbR_EeJodxKSyaHzLVXxIw/edit?usp=sharing
Designs: https://marvelapp.com/4d9chi8

+  Context selector can be placed within the header of a page as well (on white part of the screen) where it changes the context of the data shown on that page
+ check #897 in PF design
+ add ability to add actions above search bar - check epic for more info

**Comment by mmenestr** [comment]
Writing guidelines for this as part of the big document effort to get guidelines into the new website...

**Comment by mmenestr** [comment]
Also add: Context selector can be placed within the header of a page as well (on white part of the screen) where it changes the context of the data shown on that page

**Comment by mmenestr** [comment]
+ check #897 in PF design

**Comment by mmenestr** [comment]
+ add ability to add actions above search bar - check epic for more info
