### ISSUE TITLE
Bug in navigation of the website

### ISSUE THREAD

**Issue by nazzzzym** [patternfly/patternfly-org#1720]
1. Section name and contents do not match
2. Bad scaling of the shadow. Shadow can be extended or can be removed
3. Multiple sections in nav-bar are shown to be active

![bug](https://user-images.githubusercontent.com/57250339/76600586-688b8b80-6531-11ea-81c6-c186ce7ab835.png)

**How to reproduce:**
Go to patternfly.org in you mobile device/PC and try to switch between different sections in nav bar.

**Comment by mcarrano** [comment]
@evwilkin @rachael-phillips just wanted to bring this to your attention. It is add that multiple items on the primary nav bar can show as selected. Looks like a problem if I tap and hold the item to scroll the bar vs just a single tap.

**Comment by redallen** [comment]
There is no longer top navigation on patternfly.org.

That said, our site still needs mobile-friendly breakpoints to avoid overflow on the x axis (see #1808).
