### ISSUE TITLE
Make it really easy to figure out where to enter an issue against PatternFly

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-org#1723]
We hear frequently that people don't know where to open issues when they are using PatternFly.  It would be great to have something really noticeable on patternfly.org, a clear message at the top of our github org and clear directions on github.com/patternfly/patternfly as the main landing place for new issues.

**Comment by evwilkin** [comment]
@dgutride there's a [related issue in design currently](https://github.com/patternfly/patternfly-design/issues/820) for the patternfly.org part of this, which proposes adding links on most patternfly.org pages to both the source file for that page on github as well as a link to create an issue which references that file.

Those are a bit more page-specific, do you think it would be helpful to have something more general as well, maybe on the homepage or in the footer for example, to take people right to a new issue?

**Comment by janwright73** [comment]
+1 for something more general in addition to the noted existing issue

**Comment by redallen** [comment]
There is now a "View source" link at the bottom of each page that links to the MD file in GithHub.

@rachael-phillips can we add another link to open an issue referencing the MD file?

**Comment by evwilkin** [comment]
@rachael-phillips wondering if you have any suggestions where to include this information/link in the new website design?

**Comment by rachael-phillips** [comment]
Sounds like a good idea to me. Why don't we add some information about this to the Getting started section? What do you think @mcarrano ?

**Comment by mcarrano** [comment]
Either there or maybe 'Get in touch' or both?

**Comment by evwilkin** [comment]
Per offline discussion, change "Contribute" CTA on the homepage to "Github" and link to [PatternFly's Github page ](https://github.com/patternfly).  Also add Github icon linking to the same page in the Masthead to the left of the search icon.
