### ISSUE TITLE
Survey popup breaks docs on Firefox

### ISSUE THREAD

**Issue by SpyTec** [patternfly/patternfly-org#1725]
Going to any page on Firefox initially loads the site correctly, but after a second or two it simply breaks and shows this on any docs page.

![image](https://user-images.githubusercontent.com/6598829/76855379-4eafb880-6851-11ea-81fa-065c339736e3.png)

Doing the same on Chromium displays a survey popup

![image](https://user-images.githubusercontent.com/6598829/76855422-62f3b580-6851-11ea-91fb-b7e021aaa4a8.png)

There is no errors in console

---

OS: Fedora 31
Browser: Firefox 74.0 (64-bit)

**Comment by ddonahue007** [comment]
Do you not see the survey on Firefox at all?

**Comment by SpyTec** [comment]
I do not, the first screenshot I posted is as much as I see

**Comment by ddonahue007** [comment]
Just tested with the same versions you have listed and did not run into any issues. Could you try running Firefox in safe mode.

https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode

**Comment by SpyTec** [comment]
Same issue in Safe mode. Going to https://www.patternfly.org/v4/ seems to work fine, it takes a while for the popup to appear but it does.
Going to https://www.patternfly.org/v4/documentation/react/overview/release-notes or any other documentation however still breaks.

If I go to /v4/ and close the popup it no longer displays and I can browse docs freely

**Comment by ddonahue007** [comment]
The survey has been removed I think it is safe to go ahead and close this issue
