### ISSUE TITLE
Update Lists an tables doc to reflect new preterence for compact spacing

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1745]
Want to update the text and images in the [Lists and Tables design guideline](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/lists-and-tables) doc to reflect new guidance on using compact spacing where possible to increase information density.

**Comment by ajacobs21e** [comment]
The full page examples on this page also use filler copy in the heading that says "body text should be Overpass...". These examples should also be updated.
