### ISSUE TITLE
Chore: Create detailed release timeline docs

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1763]
Create a document outlining each step of the release process with timeline implications for any fixes/patches needed that arise at any step in the process.

**Comment by redallen** [comment]
I'd be interested in readable ways to modify #1792 to include implications for fixes/patches. Maybe a flow chart?

**Comment by redallen** [comment]
I think for this upcoming release we should try to at least document the release tasks and times they were completed. This can help us better evaluate our timeline.

**Comment by evwilkin** [comment]
Closing as this has been created [here](https://docs.google.com/document/d/1c_gUzvx8JAxxXAAFax8FQuPrWR-_e6cdif81qhUR1Ng/edit#heading=h.eywpf2d8dyaj) as part of PF Scrum Master docs
