### ISSUE TITLE
Broken link from Flex utilities to React

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#1767]
From the Flex Utilities page, switching the documentation dropdown to React results in a 404 error.

https://www.patternfly.org/v4/documentation/core/utilities/flex

It is attempting to go to https://www.patternfly.org/v4/documentation/react/utilities/flex

**Comment by redallen** [comment]
There are about 50 broken links that need to be fixed upstream in the Core/React repos.

I'll open PRs there today.

**Comment by redallen** [comment]
https://github.com/patternfly/patternfly-react/issues/4869 / https://github.com/patternfly/patternfly/issues/3503
