### ISSUE TITLE
Bugs and possible changes in Documentation

### ISSUE THREAD

**Issue by nazzzzym** [patternfly/patternfly-org#1768]
### **BUGS**
Broken links: when I try to switch from START to DESIRED PAGE, I got the WRONG PAGE:

_In components_
1. From HTML Alert group to React Alert group and vice versa. For example:
START : https://www.patternfly.org/v4/documentation/core/components/alertgroup
DESIRED PAGE: https://www.patternfly.org/v4/documentation/react/components/alertgroup
WRONG PAGE: https://www.patternfly.org/v4/documentation/react/overview/release-notes
2. HTML Data toolbar -> React Data toolbar
3. HTML Drawer -> React Drawer
4. HTML File upload -> React File upload and vice versa
5. HTML Modal box -> React Modal and vice versa
6. HTML Page -> React Page (results in 404 Error)
7. HTML Simple list -> React Simple list and vice versa

_in Layouts_ all, _in Demos_ Card view

### POSSIBLE CHANGES
HTML Utilities and Demos (except Card view) do not have their React alternatives
React Charts do not have their HTML alternatives
Thus, dropdown Frameworks might be disabled when appropriate.

**Comment by redallen** [comment]
Working on a PR now to solve these.

1. :heavy_check_mark: 
2. :heavy_check_mark: 
3. :heavy_check_mark:
4. We don't have a design snippet for this component. Once we do, it will link the two.
5. :heavy_check_mark: 
6. :heavy_check_mark: 
7. We don't have a design snippet for this component. Once we do, it will link the two.
