### ISSUE TITLE
Bug with search on mobile version

### ISSUE THREAD

**Issue by nazzzzym** [patternfly/patternfly-org#1769]
1. Search results do not fit horizontally and thus partially appear out of the page.
2. When you try hide the keyboard to see the whole result vertically by clicking on "done" on ios (or by clicking the tick (v) on android) - the search results disappear. But you can scroll, which is not comfortable, for example, for users with small display.

Same issue on ios and android, on browsers Safari, Google Chrome, Mozilla, Yandex.

![image](https://user-images.githubusercontent.com/57250339/78559839-c1430100-781d-11ea-9d9d-291ba595eece.png)

**Comment by redallen** [comment]
We've removed search from mobile. Closing in favor of #2159.
