### ISSUE TITLE
Colors for charts page design update

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-org#1771]
The [colors for charts](https://www.patternfly.org/v4/design-guidelines/styles/colors-for-charts) page was created last year before the update to the [colors page](https://www.patternfly.org/v4/design-guidelines/styles/colors) happened. We want to update the design of the colors for charts so that:
1) it reflects the most recent chart colors (color palette is [here](https://www.patternfly.org/v4/documentation/overview/global-css-variables#chart-css-variables))
2) it is more consistent with the design of the colors page

The content on the page is still up-to-date, so you can leave that.
The GIFs may be showing incorrect colors within the charts. These _could be_ updated if you are interested! Contact Michael Celedonia for more info about those. This isn't required!

**Comment by beccaglass** [comment]
Hi @mcarrano @gdoyle1! I mocked up two versions of the page and would love to get feedback before I make specs:

https://marvelapp.com/project/5075049

The main difference is 1. the color swatches (circles vs. palettes) and 2. the layout of the system section. Can mix and match or just go ahead with one of these versions. Let me know what you think!

**Comment by mcarrano** [comment]
These look great @beccaglass ! I will defer to @gdoyle1 on the details.

**Comment by gdoyle1** [comment]
@beccaglass Those options both look great! I prefer the one with the circular color swatches, I think we should go with that. One change I think we should make is vertically stacking the examples in the "Use cases" section so that all of the images are on the right. 

On other thing I noticed was that the code font doesn't look like its `Liberation mono`. Can you confirm if it is or not? You may have to download that font here: https://www.fontsquirrel.com/fonts/liberation-mono

**Comment by beccaglass** [comment]
@gdoyle1 @mcarrano Updated mocks and specs for desktop and mobile. Let me know what you think!

https://marvelapp.com/project/5075049

**Comment by gdoyle1** [comment]
Looks great @beccaglass! I think this is good to go to implementation

@mmenestr tagging you if want to take a look as well

**Comment by mmenestr** [comment]
Looks good to me as well! @evwilkin is there anyway we could get this on the roadmap? It's basically an update to the [colors for charts page](https://www.patternfly.org/v4/design-guidelines/styles/colors-for-charts) to mimic the styling of the colors page! Let me know if you need me to create an issue, or what the next steps are!

**Comment by evwilkin** [comment]
@gdoyle1 @beccaglass I don't have permission to access that Marvel doc, can you open it up for sharing?

@mmenestr if you can create a new issue in this Org repo to update this page I think that works best - rather than keeping this issue open & potentially changing the labels and assignee, I think it would be better to close this out as the design work is done and start fresh with a new issue referencing this one to track the development work. Thank you!
