### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#1776]
Text to use: https://docs.google.com/document/d/1iDBUOku2QuaaIx8QwzLNyDgMkbYs46MByOp1bvv0NKE/edit

We're just awaiting two new logos?

**Comment by abigaeljamie** [comment]
Thank you, Zack! Yes, we're just awaiting two logos. They should be done by April 30.

**Comment by abigaeljamie** [comment]
Hi, @evwilkin ! I haven't received them yet. I'll check in with the visual design folks to see where they're at.

**Comment by abigaeljamie** [comment]
Update: Michael created the new logos. I emailed you and Zack the SVG files.

**Comment by abigaeljamie** [comment]
Hello, @evwilkin ! Did you get the graphics I emailed? The content should be good to go now. Are you still up for applying the changes to the home page? Thanks!

**Comment by evwilkin** [comment]
@abigaeljamie yep the images came through, we've got this slotted to tackle this week - thank you!
