### ISSUE TITLE
Nav component design change impacts website styles

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1777]
As result of a nav component redesign in https://github.com/patternfly/patternfly/pull/2884, the website styles are impacted since they use the nav component.

You can preview the impact here - http://patternfly-v4.surge.sh/

**Comment by mcoker** [comment]
As a follow-up there were more changes that will be introduced in https://github.com/patternfly/patternfly/pull/2978

**Comment by ddonahue007** [comment]
After having a conversation with @redallen, This task is more than just changes to org site.

We can make org use the new breaking change design or write some CSS to make it look like it used to. 

**what's required is this:**

- fix nav overflow and buttons in react
- bump react in theme and remove the permanent `isScrollable` attribute
- bump theme in core/react

**Whats next:**
- ask @rachael-phillips if sidenav at v4.patternfly.org is okay or if we want to keep old design?

**Comment by redallen** [comment]
First 3 are done. All that's left is deciding whether or not we want to keep the redesigned sidenav on v4.patternfly.org or write some new CSS to make it looks like it used to on patternfly.org @rachael-phillips .

**Comment by ddonahue007** [comment]
I am working on bullet item 4 with @rachael-phillips. I have already filed a task on one of the changes and should have a PR soon
