### ISSUE TITLE
Unable to find patternfly-react v3 code examples any longer

### ISSUE THREAD

**Issue by dgutride** [patternfly/patternfly-org#1779]
With the move away from keeping v3 code in the master branch (and gh-pages a long time ago) - I can't find patternfly-react (v3) code examples anywhere.  The links from patternfly.org/v3 are also broken.  

For example:  https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/index.html?selectedKind=patternfly-react%2FData%20Visualization%2FCharts&selectedStory=Area%20Chart doesn't work anymore.

We do need to continue to provide access to this documentation.

**Comment by redallen** [comment]
The docs now live at https://patternfly-react-pf3.surge.sh . Rawgit was broken since I got here -- would you like effort put into getting it working again?

**Comment by redallen** [comment]
I got http://patternfly.github.io/patternfly-3/tests/application-launcher.html working for our old JQuery examples and opened a PR to fix the links in patternfly-design to working links. Once those are updated we can pull in those changes in org.

**Comment by redallen** [comment]
This should be fixed on staging.patternfly.org/v3 now, feel free to reopen if you find more broken links.
