### ISSUE TITLE
Remove widow from homepage description, adding break

### ISSUE THREAD

**Issue by dcaryll** [patternfly/patternfly-org#1783]
![Screen Shot 2020-04-14 at 1 12 55 PM](https://user-images.githubusercontent.com/1249747/79253742-b7d71b80-7e51-11ea-80be-4208f3d44928.png)

Would be ideal to break the text in the description of the site, perhaps before the last "and", so that "teams" does not sit on its own line. 

Maybe add a smaller max width to that section?

**Comment by redallen** [comment]
Hm, #1776 will soon change the caption to "PatternFly is an open source design system helping teams turn patterns and code into unified product experiences." Not sure how the text will wrap with that line, but feel free to leave a comment in #1776.
