### ISSUE TITLE
Release dropdown doesn't work

### ISSUE THREAD

**Issue by dcaryll** [patternfly/patternfly-org#1784]
![Screen Shot 2020-04-14 at 1 21 07 PM](https://user-images.githubusercontent.com/1249747/79254531-e0134a00-7e52-11ea-930b-7a936a3d6d07.png)

This dropdown isn't functioning.

**Comment by redallen** [comment]
We're aware of this, sorry for the inconvenience. The pages are still there, so you use https://patternfly.org/2020.03/ in the meantime.

**Comment by redallen** [comment]
Fixed and it has a pretty new design! 
![image](https://user-images.githubusercontent.com/47335686/79473685-7cfcf100-7fd3-11ea-962e-54eb0992160c.png)
