### ISSUE TITLE
Update Card View with revised spacing for cards

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1786]
Update Card View design guidelines to reflect new card spacing. We may want to think about renaming the "Card View" section to something like "Cards"... or keeping 2 sections so that one focuses on types of Cards vs. Card view.
**Spacing updates:**
We now recommend using compact cards by default. Compact cards use 16px spacing with 8px spacer between the header and body, and 16px between the body and footer.
We also provide another card type, large cards, that use 24px spacing with 16px spacer between the header and body, and 24px between the body and footer.
(You can find images in the [PatternFly Template File](https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89))
<img width="758" alt="Screen Shot 2020-06-22 at 10 15 55 AM" src="https://user-images.githubusercontent.com/30870144/85297900-5e9ef000-b471-11ea-9105-443f5c7adcd7.png">
Related issue: #1804

**Comment by abigaeljamie** [comment]
Are these the guidelines to be updates, @mcarrano ? https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/card-view

**Comment by mcarrano** [comment]
Yes

**Comment by abigaeljamie** [comment]
Sent draft to @mcarrano and @mmenestr for technical review.
