### ISSUE TITLE
Update images in Wizard guidelines for proper spacing

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1788]
Update images to show correct spacing of Next, Back, and Cancel buttons.

**Comment by mmenestr** [comment]
**More info:**
Spacing between Next and Back = 16px
Spacing between Back and Cancel = 48px

**Comment by mmenestr** [comment]
Here is a visual of what that might look like (this image has the spacers, but the examples probably wouldn't have them)

![image](https://user-images.githubusercontent.com/51165119/85750622-dbcb9e80-b6d7-11ea-917b-ad2bfdf36a1d.png)

Zoom in on buttons with spacers visible:
![image](https://user-images.githubusercontent.com/51165119/85750707-f140c880-b6d7-11ea-886b-8a553e06e296.png)


Zoom in on buttons with spacers hidden:
![image](https://user-images.githubusercontent.com/51165119/85750736-f9006d00-b6d7-11ea-8c09-91646f41b15c.png)
