### ISSUE TITLE
[Redesign] Combine core/react documentation

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#1793]
Per proposed design in #1785, we need to combine Core and React component documentation pages.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/47335686/79380230-24bfe380-7f2e-11ea-9515-38eaf2482b41.png">

Our Core and React components do not map 1-1. I think the best way would be add some frontmatter as a common key upstream in Core/React. Design would have to choose what they want that common key to be (ie. About modal or About modal box @mcarrano @rachael-phillips  ?)

**Comment by mcarrano** [comment]
Yes, I think we would need to somewhere define how we want things to map if that's what you are asking @redallen .  So for example, we might want the page named "About modal" to pull in "About modal" from React and "About modal box" from core.

**Comment by evwilkin** [comment]
See related issue #1807
