### ISSUE TITLE
[Redesign] Allow example captions

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#1794]
Per design in #1785, we need to support per-example captions that could be written by a non-technical writer:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/47335686/79382209-2ccd5280-7f31-11ea-94f3-63030b28da2f.png">

The easiest way would be to add a `caption` field like:
``````
```js title=Basic caption=My-caption-that-can't-include-spaces
<Example />
```
``````

but we could parse something that's more readable and would render better on non-docs pages like:

``````md
## Basic

My caption that can include spaces or images or any other markdown.

Maybe even two paragraphs.

```js
```
``````

into an AST like:
```
{
  tag: "example"
  title: "Basic"
  caption: { children: [
    {tag: "p", text: "My caption that can include spaces or images or any other markdown."},
    {tag: "p", text: "Maybe even two paragraphs."}
  ]},
  language: "javascript",
  example: { tag: "code", text: "<Example />" }
}
```

by writing a unifiedJS plugin.

**Comment by evwilkin** [comment]
See new example dropdown design per #1806
