### ISSUE TITLE
[Redesign] Add rendered HTML in addition to React code

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#1795]
Implement the HTML button in #1785:

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/47335686/79382103-ff80a480-7f30-11ea-90f7-7385faaa7812.png">

While this is very easy to achieve on the technical side, I'm not quite sure about two things in this design @rachael-phillips and @mcarrano :
1. What is the purpose of this toggle? Do we even want people copying the generated HTML from our React examples (cc @dgutride), or would we rather them copy the pristine HTML from our HTML examples?
2. Why is the text area so small compared to the rest of the page? Is it resizable? Are you _supposed_ to be able to read it, or only copy it?
3. Why would anyone want to see the HTML in such a small text area when they can just inspect the example in their dev tools to inspect the example see the HTML in a much larger area?

<img width="797" alt="image" src="https://user-images.githubusercontent.com/47335686/79382495-98172480-7f31-11ea-97ca-011f4657e5c3.png">

**Comment by mcarrano** [comment]
Correct me if I'm wrong @rachael-phillips but I assumed you made the text area small only to keep the wireframe from becoming too long. Agree with @redallen that this needs to be larger to be useful. It should also be collapsible. We can update the design.

**Comment by redallen** [comment]
The new tabs HTML/React tabs design serves us better than this one. This is technically difficult for React examples, would allow copying uninteractive code, and is useless compared to the inspector tool. Closing.
