### ISSUE TITLE
Sidebar not collapsing at the correct breakpoint

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#1801]
Core changed the page component's CSS so that the sidebar is hidden at the `xl` breakpoint instead of the `md` breakpoint. However it looks like the react page component has a managed sidebar feature that triggers a mobile view at `globalBreakpointMd.value`.

https://github.com/patternfly/patternfly-react/blob/c9a233b1aa9fc12326c14a296fb7f32b4b24a19d/packages/react-core/src/components/Page/Page.tsx#L104

Opening this issue to get the preview site updated since it uses the react page component.

<img width="1184" alt="Screen Shot 2020-04-17 at 9 46 44 AM" src="https://user-images.githubusercontent.com/35148959/79581796-8c8e3f80-8090-11ea-9f04-bff75ca6953b.png">

**Comment by redallen** [comment]
Org depends on React implementing this.

I'll see if I have time today to cut a `v4` branch for org where we can pull in `v4` of Core/React to quickly find things like this.

**Comment by redallen** [comment]
This has since been fixed.
