### ISSUE TITLE
Card usage guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1804]
Introduce card usage guidelines based on analysis documented in https://github.com/patternfly/patternfly-design/issues/798

Lucia worked on some in-depth documentation on when to use cards within a content view and when not to: https://marvelapp.com/22g12786

She also created this Marvel project with examples of what those Card Views will look like now: https://marvelapp.com/5996ff7

TLDR: Use a white background for card views when the content view can change (i.e. master detail, where the card can open an expandable panel on the right _also_ where the card view can toggle into a table or list view). Use a gray background for card views when the sole purpose of that content view is the cards. Reference Design issue [#834](https://github.com/patternfly/patternfly-design/issues/834) for more details (this one is specifically about pagination but gives the different examples)

Related issue: #1786

**Comment by abigaeljamie** [comment]
@mcarrano , are we adding the guidelines to this existing doc? https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/card-view

**Comment by mcarrano** [comment]
That's a good question. I think it might make sense to have a more general topic labeled "Cards" and incorporate card view into that. But I'm not wedded to that idea. @mmenestr @gdoyle1 what do you think?

**Comment by mmenestr** [comment]
I agree, I would make a new page called "Cards" and incorporate card view into that. I would also make sure to differentiate the difference between "Cards" and "Card view" since that is a bit confusing!

**Comment by abigaeljamie** [comment]
Sounds good to me, thanks!

**Comment by abigaeljamie** [comment]
Sent draft to @mcarrano and @mmenestr for technical review.

**Comment by mcarrano** [comment]
@abigaeljamie There is a change we made to Card View to account for a bottom footer. See https://github.com/patternfly/patternfly-design/issues/834 I wasn't sure if this was already accounted for in these updates, but if not, we should include it. Thanks!

**Comment by abigaeljamie** [comment]
Thanks, @mcarrano ! I can add that in and get the image from Gina. There's a bit of convo there about color and stickiness. How much detail do we want in the doc? Should we mention the stickiness at all, or should we advise readers to add a footer with pagination and then show the image Gina created as an example?

**Comment by mcarrano** [comment]
I'd avoid talking about stickiness at this point since we are still trying to figure out details of how that will work.
