### ISSUE TITLE
Build dropdown interaction in body of page

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1806]
To view each example, the user selects the example from the dropdown as seen in the wireframe below. 

![79273013-46f32c00-7e70-11ea-9da6-e8d6c1e9c4a3](https://user-images.githubusercontent.com/40275806/79889504-1b21fa00-83cc-11ea-874f-0e16c3749987.jpg)

**Comment by redallen** [comment]
I believe we decided against this design. Closing.
