### ISSUE TITLE
Adding React and HTML tabs

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1807]
Add the React and HTML tabs as seen in the mockup, which toggles between the React and HTML code:
![79273013-46f32c00-7e70-11ea-9da6-e8d6c1e9c4a3](https://user-images.githubusercontent.com/40275806/79889848-997e9c00-83cc-11ea-8d32-2fc5d8211061.jpg)

**Comment by redallen** [comment]
These have been added and are a wild success!

Closing.
