### ISSUE TITLE
Restyling table for website to match wireframes

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1808]
Build new tables for documentation pages as seen in the wireframe

![79273013-46f32c00-7e70-11ea-9da6-e8d6c1e9c4a3](https://user-images.githubusercontent.com/40275806/79889980-ca5ed100-83cc-11ea-8f53-b47f90695ffa.jpg)

**Comment by evwilkin** [comment]
Closing due to stale - design has gone in a different direction and Table was recently updated with composable table.
