### ISSUE TITLE
Expanding content styling in Documentation page 

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1809]
At the bottom of the page, expanding content styling in Documentation page. See the styling for CSS Variables or Accessibility sections at the bottom of the page:
![79273013-46f32c00-7e70-11ea-9da6-e8d6c1e9c4a3](https://user-images.githubusercontent.com/40275806/79890235-33dedf80-83cd-11ea-84ed-842025bf6992.jpg)

**Comment by evwilkin** [comment]
Decision was made by design not to implement expanding/collapsible sections.
