### ISSUE TITLE
Update navigation and bring over content 

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1810]
Update navigation to be reflective of wireframes:
![79273013-46f32c00-7e70-11ea-9da6-e8d6c1e9c4a3](https://user-images.githubusercontent.com/40275806/79890513-97690d00-83cd-11ea-8643-b7df1cf598b1.jpg)

More details to come. To do for @rachael-phillips

**Comment by evwilkin** [comment]
Closed in #2043
