### ISSUE TITLE
Remove HTML/CSS context selector left nav

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#1811]
As seen in the wireframe remove the context selector from the left nav:
![79273013-46f32c00-7e70-11ea-9da6-e8d6c1e9c4a3](https://user-images.githubusercontent.com/40275806/79890939-3f7ed600-83ce-11ea-97cc-f1369566c6df.jpg)

**Comment by evwilkin** [comment]
Closed in #2043
