### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1820]
PatternFly.org redesign combining Core & React docs and updating examples

**Comment by mundane140** [comment]
Do you need help with this one?

**Comment by evwilkin** [comment]
@mundane140 thanks for reaching out - our design team is still working out feasibility to confirm final designs, so there's no action to take on this issue yet.

**Comment by mundane140** [comment]
Roger that

**Comment by redallen** [comment]
Closing in favor of the only redesign issue left -- #1796.
