### ISSUE TITLE
Release 2020.06

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#1827]
This issue will serve as a megathread, live status, and planned timeline for the 2020.06 release.

This is a complicated release because we currently have 4 release streams that are merging back down into 2. There will be two halves to this release. The first half is normal release that concludes this sprint. The second half is an off-beat release that may take up to a sprint as we verify breaking changes in product, stabilize, and prepare notes, blog posts, v4.patternfly.org, and potentially other PatternFly press for consumers detailing the benefits of our `v4` release and how to upgrade.

**Release coordinator:** @redallen 

## Status

The release is live and we're wrapping up [codemod](http://github.com/patternfly/pf-codemods) fixes.

### Master release
Estimate   | Actual    | Task                                             | Assignees
-----------|-----------|--------------------------------------------------|----------
05-07 16:00| N/A       | Core docs verified at pf4.patternfly.org         | @mcoker @rachael-phillips
05-07 17:00| 05-07 13:07 | Core release notes updated                       | @mcoker
05-07 17:00| 05-07 13:07 | Core changes complete                           | @redallen @tlabaj @jschuler
05-07 17:00| 05-08 15:24 | React release notes standing by                  | @tlabaj
05-08 10:00| 05-11 14:23 | React bumps core version                         | @redallen
05-08 17:00| 05-11 14:06  | React verified in product by developers          | @redallen @dlabrecq @dtaylor @mfrances17
05-08 17:00| 05-11 14:45 | React docs verified at patternfly-react.surge.sh | @tlabaj @rachael-phillips
05-08 17:00| 05-11 12:53 | React release notes updated                      | @tlabaj
05-08 17:00| 05-11 14:45  | React changes complete                           | @redallen @tlabaj @jschuler
05-08 17:00| 05-11 14:15 | React promoted for consumer use                  | @redallen
05-11 10:00| 05-11 15:31 | Bump staging.patternfly.org                      | @evwilkin or @redallen
05-11 12:00| N/A       | staging.patternfly.org verified                  | @mcoker @tlabaj @rachael-phillips
05-11 13:00| 05-11 15:51 | patternfly.org released                          | @evwilkin or @redallen

### V4 release
Estimate   | Actual    | Task                                             | Assignees
-----------|-----------|--------------------------------------------------|----------
05-01 17:00| 05-11 12:12 | React bumps core version                         | @mcoker @redallen
05-12 17:00| 05-12 12:13 | Core create v3 branch. Merge v4 -> master        | @mcoker @redallen
05-12 12:00| 05-15 09:55 | React create v3 branch. Merge v4 -> master       | @tlabaj @redallen
05-12 13:00| 05-15 12:42 | React bumps core version                         | @redallen
05-13 12:00| 05-15 12:53 | React rc1 prerelease                         | @redallen
05-18 17:00| 05-15 15:00 | Org create v3 branch. Merge v4 -> master         | @redallen
05-18 17:00| 05-21 15:01 | React verified in product by early adopters[^1]  | @redallen @dlabrecq @dtaylor @mfrances17 @jschuler @whoever can help
05-18 17:00|           | Core release notes updated                       | @mcoker
05-18 16:00|           | Core docs verified at pf4.patternfly.org         | @mcoker @rachael-phillips
05-18 17:00|           | Core changes complete                            | @redallen @tlabaj @jschuler
05-19 17:00|           | React release notes updated                      | @redallen
05-19 12:00|           | React docs verified at patternfly-react.surge.sh | @tlabaj @rachael-phillips
05-19 17:00|           | React changes complete                           | @redallen @tlabaj @jschuler
05-19 17:00|           | React promoted for consumer use                  | @redallen
05-19 17:00|           | Codemod release notes updated                    | @redallen
05-19 17:00|           | Codemod changes complete                         | @redallen @tlabaj @jschuler
05-20 10:00|           | Bump staging.patternfly.org                      | @evwilkin or @redallen
05-20 12:00|           | staging.patternfly.org verified                  | @mcoker @tlabaj @rachael-phillips
05-20 17:00|           | patternfly.org released                          | @evwilkin or @redallen
05-20 09:00|           | Press releases for changes published             | @LHinson @abigaeljamie 

[^1]: This is the part I am most unsure about. Some products may be able to integrate our changes in a single day. It may take other weeks. It all depends on what components they are using (and how). For product developers, this looks like upgrading to v4, updating their code, and verifying their sites visually. For PatternFly developers, this looks like writing codemods and debugging errors. For community managers, this looks like evangelizing v4, encouraging product developers, and pairing them with PatternFly developers if they have problems. Getting the community onboard is extremely important or people will stay on our v3 line forever.

**Comment by evwilkin** [comment]
Major release is live
