### ISSUE TITLE
Add Skeleton Loading to Data Loading guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1842]
Add guidance for Skeleton Loading to the documentation here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/data-loading  Be sure to discuss when to use skeleton loading vs spinners or progress bars. More background in the design issue here: https://github.com/patternfly/patternfly-design/issues/766

**Comment by mmenestr** [comment]
Part of big doc effort... new website
