### ISSUE TITLE
Add early support for Sketch design e-training

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-org#1855]
The creation of a [Sketch design e-training](https://patternflyt-training.thinkific.com/courses/pf-sketch-e-training) is about 95% complete, and this should be hosted on patternfly.org as a resource for the whole design community. We have a design for a landing page that we would like to implement to serve as an introduction to the training, but we would first like to address some quick interim solutions to at least get the training itself out in the open. [Here's what the overall flow will look like](https://marvelapp.com/55dfejd). 

### Here are the items that need to get taken care of for this first launch of the training

- [x] Add linking to [this training](https://patternflyt-training.thinkific.com/courses/pf-sketch-e-training) on the [getting started for designers page](https://www.patternfly.org/v4/get-started/designers) under 'Using the design kit' (screenshot below of what this section should say and how it should look) 
<img width="941" alt="Screen Shot 2020-05-22 at 3 07 34 PM" src="https://user-images.githubusercontent.com/19824574/82701373-15733a80-9c3e-11ea-9572-ddc1afc16dc2.png">

- [ ] Add a secondary nav item into the getting started > designers flow to [the training](https://patternflyt-training.thinkific.com/courses/pf-sketch-e-training) as well (screenshot below of what this section should say and how it should look) 
<img width="426" alt="Screen Shot 2020-05-22 at 3 07 11 PM" src="https://user-images.githubusercontent.com/19824574/82701472-42275200-9c3e-11ea-83c1-ed1463cb6912.png">

- [ ] Host a PDF version of the cheatsheet asset (required asset for the training) on the site. For right now, the URL doesn't matter, as it will just be externally linkable from the training itself. The user should be able to view and/or download the PDF attached here

[ACrashCourseinSketchProficiency (2).pdf](https://github.com/patternfly/patternfly-org/files/4669964/ACrashCourseinSketchProficiency.2.pdf)

**Comment by evwilkin** [comment]
@maryshak1996 can we confirm what is still needed here?  I believe our site nav has changed since this issue was created so there isn't a place for the additional nav item shown in task 2 above.  We can host the PDF on the site (vs the github linked PDF), is that something that's still needed and should we send the URL to you to update in the training?

**Comment by maryshak1996** [comment]
Hey @evwilkin thanks for reaching back out! With the updated nav, could add a secondary nav item under the primary 'Training' section (Like the attached screenshot)? And it could either link out to the [existing anchor link](https://www.patternfly.org/v4/get-started/design#sketch-design-training) for the training on the Getting started / Design page (and then the user would have the launch it from there) OR it could open the [external platform](https://patternflyt-training.thinkific.com/courses/pf-sketch-e-training) in a new tab.
![Screen Shot 2021-08-05 at 4 30 14 PM](https://user-images.githubusercontent.com/19824574/128417259-ff35c467-0ee5-4a15-8db5-76bf3fe39cd5.png)
