### ISSUE TITLE
fix text break on homepage

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#1875]
I might be alone here but the max-width that is causing this orphan text in the header could be fixed so it's all on one line.
<img width="751" alt="Screen Shot 2020-06-09 at 4 11 03 PM" src="https://user-images.githubusercontent.com/287880/84189730-1c86af00-aa6c-11ea-8c57-b1cce416298a.png">

**Comment by rachael-phillips** [comment]
I totally agree, @matthewcarleton ! Would love to see this fixed. @evwilkin can we prioritize this in future sprints?

**Comment by evwilkin** [comment]
@matthewcarleton @rachael-phillips this should be easy enough, thanks for the feedback
