### ISSUE TITLE
Featured content carousel images

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-org#188]
A few things needed to clean up these images and usability of this widget
- Dashboard Layout image has placeholder chrome. Looks good, but other images do not have this. Should pick a style for all. 
- List View image is squished width. Need to adjust size
- Notification Drawer is showing a Red Hat UI - shouldn't it be patternFly?
- Rather than Learn More button, this would be much easier to use if the images were just links.

**Comment by kybaker** [comment]
Corrected all of the images as suggested. I make each image a link and added a border. I doubled the image resolution which will render sharper on high resolution devices. I also corrected the carousel header to scale more accurately.

**Comment by LHinson** [comment]
Closing this since it's been resolved! Thank you both!
