### ISSUE TITLE
Font missing from Get in touch page

### ISSUE THREAD

**Issue by fionayhlin** [patternfly/patternfly-org#1880]
<img width="1205" alt="Screen Shot 2020-06-11 at 9 56 32 AM" src="https://user-images.githubusercontent.com/49918197/84393647-d5163500-abc9-11ea-959c-91c6842ea4e5.png">

See screenshot. Header is in a serif font.

**Comment by evwilkin** [comment]
@fionayhlin thanks for logging this - I have a PR up (#1853) that should resolve this and similar issues as well, if you don't mind taking a look.
