### ISSUE TITLE
Update or remove 'Documentation/Red Hat font' page

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1883]
`RedHatDisplay` font [has been removed](https://www.patternfly.org/v4/documentation/core/overview/upgrade-guide#default-font), but is still referenced heavily throughout the [Red Hat font page](https://www.patternfly.org/v4/documentation/overview/red-hat-font) on the site.

**Comment by mcarrano** [comment]
We ended up reverting this back. So this issue should be closed.
