### ISSUE TITLE
Pin nav items

### ISSUE THREAD

**Issue by abigaeljamie** [patternfly/patternfly-org#1884]
Pin nav items for PatternFly's new content guidelines so that they follow this order: 
- Welcome 
- Brand voice and tone 
- UX writing best practices 
- Terminology 
- Numerics 
- Punctuation 
- Truncation 
- Capitalization 
- Sentence structure 
- Writing for all audiences 
- UI areas

**Comment by evwilkin** [comment]
Per @abigaeljamie this issue is no longer needed.
