### ISSUE TITLE
Update Typography page to reflect font changes

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1886]
Typography page still referenced Red Hat Display font used for headings despite the fact the this font is no longer being used. Update to show all examples in the Red Hat Text font.

https://www.patternfly.org/v4/design-guidelines/styles/typography

**Comment by ajacobs21e** [comment]
The examples all seem to be using 16pt

**Comment by evwilkin** [comment]
Font has been reverted to RedHatDisplay & font sizes should be resolved in https://github.com/patternfly/patternfly-org/pull/1893 - FYI the preview link in that PR is rendering the fallback font in place of RedHatDisplay as the repo wasn't bumped to the newer version of Core with the font added back in yet.
