### ISSUE TITLE
Update Modal design guidelines to include additional content guidance

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1887]
Update Modal guidelines here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal

@abigaeljamie please add details

**Comment by abigaeljamie** [comment]
Thanks, @mcarrano ! Here's what I'd like to add to the "Content" section: 

__________________________________
Confirmation dialogs should be clear, concise, and direct. Give the user the important information first—additional detail like “Are you sure?” clutters your message and can be distracting.  

Depending on your design template, follow this format for confirmation dialogs: 
**Headline**: A headline is usually phrased as a question. Include important keywords (like “permanent”) in the headline.
**Body text**: Body text gives information about the action’s consequence. 
**Buttons**: Buttons allow a user to answer the headline question. These can simply be “yes” or “no,” but adding some context increases clarity—especially when skimming.     

Before: 
**Are you sure you want to delete this record?** 
If you delete this record, then you will permanently lose all of its information. Do you wish to proceed?  

Cancel | Delete 


After: 
**Permanently delete record?** 
Record name, location, and notes will be gone forever.

No, keep | Yes, delete 

_________________________

The "Before" and "After" can be side-by-side in a chart, like we'll have in the PF content style guide.
