### ISSUE TITLE
Max width needed for Home page

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-org#189]
The new home page looks very good, but the lack of a max width on the content lets down the design. Obviously PatternFly is focused on app UI, but in cases like this, where you have a marketing-like splash content layouts, context-appropriate styles need to be considered for this type of content. 

Rationale
- It would just look better. Right now, wide rivers of space open up between featured items. Right and left margins are uncomfortably close to the screen edges as the proportion of the center content area widens.
- On larger screens, the line length of text goes well beyond common accepted guidelines for line length legibility

Just compare to http://getbootstrap.com/ or pretty much any other site with a splash/landing page like this. Thanks for listening!

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2016.
