### ISSUE TITLE
Tour/First Use Experience Guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1890]
Develop guidelines for designing and building guided tours that can integrate with any product and are platform neutral.

**Comment by mmenestr** [comment]
Working draft here: https://docs.google.com/document/d/12RYMI7Z_09-2QhhAFdBTsfUaCm7oimLMU5GbqH41VQI/edit#
(For now waiting on finalizing the naming conventions for these tours, to then create guidelines around them)
