### ISSUE TITLE
Add documentation for "legend tooltips" to Charts guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1919]
Legend tooltips were introduced in release 2020.08. See https://github.com/patternfly/patternfly-react/pull/4371 We should add to Charts documentation here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/charts

**Comment by nlcwong** [comment]
Draft of write up: https://docs.google.com/document/d/1hMmZlZDeih8PyDCO4FHtjMulvkdLAUvDaqnynJKHVXo/edit?usp=sharing
