### ISSUE TITLE
PatternFly design doc contribution guidelines: Process

### ISSUE THREAD

**Issue by abigaeljamie** [patternfly/patternfly-org#1946]
Document the design doc contribution process on PatternFly. Add the information to the [PatternFly Contribute page.](https://www.patternfly.org/v4/contribute/about) 

Incorporate information from these internal docs: 

- **[Contributing PatternFly Design Guidelines]**(https://docs.google.com/document/d/1mVg5NcXkk0uk3kftOv7pvag991oL1XNvti2z5ddfjH4/edit?usp=sharing) 

- **[Contributing to patternfly.org]**(https://docs.google.com/document/d/1kaDqOZel_zEuLbPNKftl84SIxnA8doEAaxdOE5Y__m0/edit?usp=sharing) 

This information will focus on the steps involved in contributing, not on the docs' written content. We'll be creating a new page on the PF content style guide for writing design docs. We'll LINK to that page from this Contribute page.  

Issue for written content info, #1947

**Comment by japhilli-RH** [comment]
@mceledonia will be creating new mockups for the page

**Comment by abigaeljamie** [comment]
Converted Jake's Google Doc draft into MD file and sent it to @redallen for publication.
