### ISSUE TITLE
Create "Writing design docs" page on the PatternFly content style guide

### ISSUE THREAD

**Issue by abigaeljamie** [patternfly/patternfly-org#1947]
Create content guidelines for writing PF design docs. Add these guidelines as a new page to the [PatternFly content style guide. ](https://www.patternfly.org/v4/design-guidelines/content/about)  

Expand upon our existing [Writing design guidelines internal doc](https://docs.google.com/document/d/1qiXom3xWAGC9N_sdKMQRWD33IeaP8f4XWpgY-eHA39g/edit?usp=sharing)

This new page will NOT focus on the contribution process. It will instead focus on content quality, consistency, and clarity for design docs. We're creating contribution process info on the PF Contribute page, and we'll LINK to that page from this one. 

Issue for contribution process info, #1946

**Comment by abigaeljamie** [comment]
@afialkoff shared a draft of this with me. Round 1 of feedback is complete. Round 2 is in progress.

**Comment by afialkoff** [comment]
Received round 2 of feedback this morning (9/16). Edits in progress!
