### ISSUE TITLE
Add guidance around custom alerts to Alerts docs

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-org#1953]
Add section about using custom alerts, specifically about having the ability to change the icon, and color? of the alert to whatever fits your needs best, if it's not already covered in the given options.

**Comment by mmenestr** [comment]
Add section about using custom alerts, specifically about having the ability to change the icon, and color? of the alert to whatever fits your needs best, if it's not already covered in the given options.

**Comment by mmenestr** [comment]
This is still not in React - so leaving this on hold for now. There is also an issue for this in the design-kit that hasn't been completed either bc it's not in React either.
Tracked here: https://github.com/patternfly/patternfly/issues/3257
