### ISSUE TITLE
Add documentation on Tiles

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#1955]
See original issue here: https://github.com/patternfly/patternfly-design-kit/issues/220

Mention how they should be used, give examples of use cases (ie: in place of radio buttons in a form when you want more of a visual, or a description, logos etc)

**Comment by mmenestr** [comment]
Mention how they should be used, give examples of use cases (ie: in place of radio buttons in a form when you want more of a visual, or a description, logos etc)

**Comment by mmenestr** [comment]
Has been added to the pf design kit so we can now write guidelines on it

**Comment by mmenestr** [comment]
Hey @bmignano just checking up on the status of this issue. Would you say this is pretty much done with what's in [this doc](https://docs.google.com/document/d/1SkjBCvv8xSC1U04eUh2nwpIOUGLDIt40kRX95m1th78/edit#heading=h.afyux7avutof), or did you have more somewhere else?

**Comment by bmignano** [comment]
@mmenestr I think we're all set on this!
