### ISSUE TITLE
Add documentation for Description list

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#1958]
Describe the description list, maybe give some use cases and examples. This probably won't be very long.
Here is what the description list looks like/demo: https://patternfly-pr-3243.surge.sh/documentation/core/components/descriptionlist

View this issue for background: https://github.com/patternfly/patternfly/issues/1919
+ this is the design kit issue: https://github.com/patternfly/patternfly-design-kit/issues/247

**Comment by gdoyle1** [comment]
@mmenestr here's what I came up with for this! https://docs.google.com/document/d/14-wx8nG_LbE3yyCfGnN5tcQnbOyuZpo3Ypvx0L6cX4o/edit?usp=sharing

**Comment by mmenestr** [comment]
@gdoyle1 cool! Just read it and feel like that's good. Only thing I did was bring the usage section to the top and put the types below. I'm also going to get Brie to look at it for a second opinion since I don't know that much about description lists

**Comment by gdoyle1** [comment]
Sounds good! @mmenestr
