### ISSUE TITLE
Create documentation for Search input

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#1960]
Search input basically works like "control+F". 
Describe how it's different from a basic filter, and give examples of usage + images.

**Original design issue with mocks:** https://github.com/patternfly/patternfly/issues/3151
**Mocks:** https://marvelapp.com/prototype/e9ge7g7/screen/69349151

**Comment by mmenestr** [comment]
Mary worked on designs - can send. Check that Gina added to design kit!

**Comment by mmenestr** [comment]
Add when to use search input vs input group for search. Biggest diff - for one you have to press enter for the search to happen, and for the other you don't

**Comment by gdoyle1** [comment]
Here's my doc! https://docs.google.com/document/d/1OArup7Ghirft77pQVua2At-dQRJxqyE6ZkMdWijhZN8/edit?usp=sharing

@mmenestr @mcarrano

**Comment by mcarrano** [comment]
Looks good @gdoyle1 . Left a few comments.

**Comment by gdoyle1** [comment]
Going to wait to add this until we do the big first merge

**Comment by gdoyle1** [comment]
Sketch cloud link for images (added in Search input page): https://www.sketch.com/s/f0f4c388-fd8d-4016-bc28-bcb8950fd535
