### ISSUE TITLE
Rename "Master-detail" demo to "Primary-detail"

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#1968]
In the interest of supporting inclusion and diversity, we would like to rename the Master-detail demo to "Primary-detail" (with hyphen).

@evwilkin I realize this work may actually need to take place in Core and React repos, but opening here as a placholder to track this work. Please open any additional issues as needed.

**Comment by redallen** [comment]
This has been renamed in all our repos.
