### ISSUE TITLE
Updates to icons table

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#1996]
Copied from comment in #1980 

**Icon table fixes**
- [x] Show status icons in the color they typically appear. Danger (red), warning (yellow), ok (green), info (blue), 1 instance of the bell (teal).
- [x] **Group all bell icons**: Add a teal bell as a second icon for the second line in the contextual usage column (see [line 15 in the spreadsheet](https://docs.google.com/spreadsheets/d/1FwcP3qQm6zseNT-MKM2BwEmlu1La6KSmWe7i-9JzNFw/edit?usp=sharing)). Add "Status" label to the "type" column, force return between the three definitions (to keep all in the row):
    - **Type** | **Contextual usage**
    - Framework | Indicates the ability to open a notification drawer 
    - Status | Represents status: default notification
    - Status | Represents status: attention
- [x] **fas-check icon row**: add contextual usage column text:
    - **Type** | **Contextual usage** 
    - Status | Represents status: Indicates a switch toggle is in the enabled position
- [x] **fa-check-circle**: add "Action" label to the "type" column, force return between the two definitions (to keep both in the row):
    - **Type** | **Contextual usage**
    - Action | Indicates the ability to commit edited changes. 
    - Status | Represents status: OK in content views such as tables

**New icons in main table**
- [x] Add "Module" and "Package" pf-icons to the table:
    - **Type** | **Contextual usage**
    - Object | Represents a module 
    - Object | Represents a package

**Replace icons in main table**
- [x] pf-icon-running
    - Status | Represents status: running 

**New icons in updated recommendations table**
- [x] See lines 196-197 in ["Updated recommendations (final)" tab](https://docs.google.com/spreadsheets/d/1FwcP3qQm6zseNT-MKM2BwEmlu1La6KSmWe7i-9JzNFw/edit?usp=sharing)
    - **Type** | **Contextual usage**
    - Status | Represents status: running  

**SVGs:**
[SVGs.zip](https://github.com/patternfly/patternfly-org/files/5301820/SVGs.zip) includes:
- pf-icon-module
- pf-icon-package
- pf-icon-running

**Comment by bdellasc** [comment]
@evwilkin I updated the issue content here since some of the issues previously found have already been resolved. 

CC @gdoyle1 @mcoker

**Comment by bdellasc** [comment]
Added the icons from these issues to this issue's content area:
- https://github.com/patternfly/patternfly/issues/1533
- https://github.com/patternfly/patternfly/issues/1552
