### ISSUE TITLE
Update "Colors for charts" page with new design

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2000]
The "Colors for charts" pages has been redesigned as follows: https://marvelapp.com/prototype/4j44628
Need to update it to reflect that!

@evwilkin

**Comment by evwilkin** [comment]
@mmenestr the color values in the Marvel mockup differ from what's on the site currently - for instance, the first Grey value in the mockup is #F0F0F0 but on the site currently it's #D2D2D2. Can you confirm which values are correct to display with this redesign?

**Comment by mmenestr** [comment]
@evwilkin I’ll defer to @beccaglass to answer that since she did the mocks^!

**Comment by beccaglass** [comment]
@evwilkin refer to the mockup for correct values. Thank you!

**Comment by evwilkin** [comment]
@beccaglass with the website redesign going live with the next release (see original issue https://github.com/patternfly/patternfly-org/issues/1785) the width of the content area is constrained to 832px. 
It looks like this is too tight to fit the color grid 4 columns wide, causing text to both overflow the color circles and in some cases wrap to 2 rows (see 1st image below).

Should we switch to 3 columns across instead (2nd image below)?

<img width="1601" alt="Screen Shot 2020-09-08 at 7 54 59 PM" src="https://user-images.githubusercontent.com/8651509/92538932-08d71a00-f20e-11ea-96bf-eb0be46351dd.png">

<img width="1604" alt="Screen Shot 2020-09-08 at 8 01 47 PM" src="https://user-images.githubusercontent.com/8651509/92539001-3c19a900-f20e-11ea-9464-b95671ba804d.png">

**Comment by beccaglass** [comment]
@evwilkin yes 3 columns across looks great, thank you!!
