### ISSUE TITLE
Nav Tab Bug with Small Screen Width

### ISSUE THREAD

**Issue by abichen** [patternfly/patternfly-org#2002]
The nav tabs display strange wiggly behavior/movement when the width of the screen is decreased, and the user switches between side tabs.

Link to screen recording: https://drive.google.com/file/d/1azBvtXrlAejzCUnPzxwSmOXLhlCbtI2l/view?usp=sharing

**Comment by redallen** [comment]
With the new design, we no longer have a top nav to wiggle.

Closing.
