### ISSUE TITLE
Update README w/workspace instructions

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#2004]
Update the main README to either link to or include instructions for spinning up the React workspace, found in the wiki [here](https://github.com/patternfly/patternfly-react/wiki/Getting-Started-as-a-Contributor#docs)

**Comment by redallen** [comment]
The v4 workspace doesn't use Gatsby anymore and the startup/build times are different. We also need to add MIT `LICENSE` file to the root of the repo.
