### ISSUE TITLE
Rework Get Started/Design page to use less h3 headers

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2019]
This page http://staging.patternfly.org/v4/get-started/design has an inappropriately long ToC when viewed in the new website,

**Comment by mcarrano** [comment]
@mmenestr @afialkoff I was just reviewing some old issues and wanted to get your thoughts on this one. Maybe this changed since last year, but it no longer seems like such a problem to me. What do you think? Is the page OK as is or do you think this still needs to be addressed?

**Comment by afialkoff** [comment]
@mcarrano It seems alright to leave as-is because all of the ToC content fits within the initial view. If we needed to scroll to view more table items, then I'd be more concerned about shortening it... What do you think, @mmenestr?

**Comment by mmenestr** [comment]
I agree this seems fine to me! Closing
