### ISSUE TITLE
Create design guidelines for toggle group

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2028]
Background info: https://github.com/patternfly/patternfly/issues/2625
This one is probably going to be short.

**Comment by mmenestr** [comment]
Can ask Michael C for more example
Brie says could be used as YAML switcher as an example

**Comment by gdoyle1** [comment]
Doc: https://docs.google.com/document/d/1QDGT-lM6J-pOVK1pGoAFTDXxN1sY1fhlpL0BTJYxhUU/edit?usp=sharing
