### ISSUE TITLE
Description is missing for popover documentation

### ISSUE THREAD

**Issue by gautamkrishnar** [patternfly/patternfly-org#2037]
There's no description showing up in the Props table:

<img width="1440" alt="Screenshot 2020-08-18 at 5 37 55 PM" src="https://user-images.githubusercontent.com/8397274/90511162-b314d200-e179-11ea-98c1-84b58b120ae5.png">

https://www.patternfly.org/v4/documentation/react/components/popover#props

**Comment by evwilkin** [comment]
This issue exists for the Tooltip as well:
https://www.patternfly.org/v4/documentation/react/components/tooltip#props

**Comment by redallen** [comment]
This was fixed in React by adding proper type annotations to those components.
