### ISSUE TITLE
Accordion widgets normal and fixed heights should be one after the other

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly-org#204]
I am referencing an issue on patternfly: patternfly/patternfly#339

**Comment by dabeng** [comment]
This issue has been fixed - http://www.patternfly.org/pattern-library/widgets/#fixed-height-accordion

<img width="557" alt="screen shot 2018-02-08 at 12 46 07 pm" src="https://user-images.githubusercontent.com/5689075/35956043-31c08942-0cce-11e8-936b-7c9b9c627a7e.png">

**Comment by andresgalante** [comment]
👍  excellent, thanks!
