### ISSUE TITLE
JSX code editor not working in more than half of the demos

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-org#2053]
**Describe the issue. What is the expected and unexpected behavior?**
The JSX code editor is not editable for the following demos:
- banner
- card view
- master detail
- notification drawer
- page layout 
- primary detail 
- sticky header table

With the exception of sticky header table, all other table demos seem to have a working JSX editor.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

https://www.patternfly.org/v4/documentation/react/demos/bannerdemo
https://www.patternfly.org/v4/documentation/react/demos/cardview
https://www.patternfly.org/v4/documentation/react/demos/masterdetaildemo
https://www.patternfly.org/v4/documentation/react/demos/notificationdrawerdemo
https://www.patternfly.org/v4/documentation/react/demos/pagelayout
https://www.patternfly.org/v4/documentation/react/demos/stickyheadertable

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug

**What is your product and what release version are you targeting?**

**Comment by redallen** [comment]
Now that there are proper fullscreen image thumbnails, I think it makes more sense why the code is not editable. If you'd like further indication via some styles, feel free to reopen.
