### ISSUE TITLE
Edit design guideline first liners to be consistent

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2088]
**3 things to change:**
1. Some of these start off with a definition ("A drawer is..."), whereas others start with usage instead ("Use the divider...").  Make this consistent one way or the other, up to you!
2. Bold the component words on the first sentence of each design guideline
3. Make sure all component names are in lower case

**Comment by mmenestr** [comment]
Bold the component words, + make sure all component names are in sentence case!

**Comment by abigaeljamie** [comment]
Consistency notes: 
- Start off each line with a definition (e.g., "A *card* is..."). 
- Make all component names lowercase. 
- Bold each component name upon first use. 
- Use "a" instead of "the" for components (for example, use "a card" instead of "the card").
