### ISSUE TITLE
Content guidance: Tooltips, pop-overs, hints

### ISSUE THREAD

**Issue by abigaeljamie** [patternfly/patternfly-org#2097]
Tooltips: https://www.patternfly.org/v4/components/tooltip/design-guidelines 
Popovers: https://www.patternfly.org/v4/components/popover/design-guidelines 
Hints: https://www.patternfly.org/v4/components/hint/design-guidelines/ 

Add a "Content" section to each page. Use guidelines from CCS/UXD collaboration doc: https://docs.google.com/document/d/1bHnXWpclbLH7Zj3N41lPJPpZG9QccWMevQGPs-T52iM/edit

**Comment by mmenestr** [comment]
@abigaeljamie @afialkoff The On-screen help design guidelines will no longer exist after the new website! But you could add these guidances to the individual component guidelines. So you can add content guidelines directly into the tooltip design guidelines that will be available in the next release!

**Comment by abigaeljamie** [comment]
That sounds like a good plan! Thanks, @mmenestr !

**Comment by abigaeljamie** [comment]
Working with CCS and UXD to add content guidelines to brainstorm doc

**Comment by abigaeljamie** [comment]
Team is adding stuff to brainstorm doc. Plan to have all content added by 11/20, then we can get to review and PR.
