### ISSUE TITLE
Add "Cancel" instances to PatternFly's terms list

### ISSUE THREAD

**Issue by abigaeljamie** [patternfly/patternfly-org#2099]
[PatternFly terminology](https://www.patternfly.org/v4/design-guidelines/content/terminology) 

Add: 
- Canceling (not cancelling)
- Canceled (not cancelled)

Home page (not homepage)

**Comment by afialkoff** [comment]
Emailed content edits and Markdown text with @mmenestr today (9/14), via Google docs.
