### ISSUE TITLE
Provide clarity around how to include icons that don't ship with patternfly

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#2105]
https://www.patternfly.org/v4/design-guidelines/styles/icons#all-icons

It isn't clear that PF core only ships `fas` icons, and we have `far` icons listed in the icons table. It would be good to include some instructions on how to include `far` icons into a product so that you can use `<i className="far [insert-icon-name]"></i>` to include an icon.

Here's a rough draft:

## FAS vs FAR

The PF icon set supports use of any FAS (font awesome solid) icons. Therefore, designers may use any FAS icon in their designs. If an FAR icon is needed, developers must include the FAR icon(s) themselves. There are a few ways of doing so:

1. Hosting it yourself (https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself)
1. Including via a package manager (https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers) 
1. Linking to a CDN (https://cdnjs.com/libraries/font-awesome)
1. Use the SVG code directly from fontawesome.com (though this requires attribution)

**Comment by mmenestr** [comment]
@mcoker where would you expect this to be located within the icon guidelines? Should it be an H3 underneath the "All icons" section, before the tables?
