### ISSUE TITLE
Add to badges design guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2107]
https://www.patternfly.org/v4/components/badge/design-guidelines

This should be a short one, but we would like to add a guideline to say that "Badges shouldn't be used if selectable tags are needed (instead use labels)" 

I think this fits in a future issue we already have filed

**Comment by lclay2** [comment]
@mmenestr - should the badge info also cover OpenShift like badges? http://openshift.github.io/openshift-origin-design/conventions/documentation/badges.html

**Comment by mmenestr** [comment]
@lclay2 no, this should be kept quite vague about badges in general!

**Comment by lclay2** [comment]
Thanks @mmenestr , just wondering what is the use case for the read and unread states?

**Comment by mmenestr** [comment]
@lclay2 you technically don't need to worry about this since this issue isn't to address that but @mcarrano do you have more background on the read and unread states? It seems like it's not always very clear when one should be used over the other. Sometimes there is no read or unread!

**Comment by lclay2** [comment]
Thanks @mmenestr , okay I'll just skip that aspect of it and focus on the points that it's only used to show numeric counts, and cannot link to other stuff (other than a tooltip, or info tip.) Wdyt?

**Comment by mmenestr** [comment]
These guidelines already exist for the badges, so you really just need to focus on what's outlined in the description of this issue: "we would like to add a couple lines to say that "Badges shouldn't be used if selectable tags are needed (instead use labels)" Ie: don't use badges for clickable/selectable items. 

![image](https://user-images.githubusercontent.com/51165119/114755501-b3c13080-9d27-11eb-8dbc-066f1f3f97f3.png)

**Comment by lclay2** [comment]
@mmenestr kk, so how about something like this:
"Badges are not intended to be hyperlinked. If you need a selectable annotation consider using a [label] instead."

**Comment by mmenestr** [comment]
I like it, thanks Liz! I can create a PR

**Comment by lclay2** [comment]
Thanks @mmenestr!
