### ISSUE TITLE
Introduce Community page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2109]
Want to introduce a Community page to the website using the content here: https://docs.google.com/document/d/13RD3FmaABC99Nz_jHyg4CZsiXvFoIzuh85-ZhfCHeJY/edit?usp=sharing

@evwilkin did we decide where this page is going to live in the nav?

**Comment by evwilkin** [comment]
@mcarrano I don't think we did decide where this will live, I could see it being its own section, or going under "Get started" or "Contribute" but definitely open to suggestions.
