### ISSUE TITLE
Add to accordion design guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2112]
Add to what currently exists on the site - maybe some examples?
https://www.patternfly.org/v4/components/accordion/react

**Comment by mmenestr** [comment]
Assign to Kevin

**Comment by mmenestr** [comment]
@kevinhatchoua

**Comment by kevinhatchoua** [comment]
Here is the [first draft](https://docs.google.com/document/d/1YVoWP9XwOrzhz8mi4LKzRgyogpWcqUhCVUJc3TWLwW8/edit?usp=sharing) I put together, looking for some feedback, thanks!

**Comment by kevinhatchoua** [comment]
Guidance for single row expansion pending discussion with the PF team

**Comment by kevinhatchoua** [comment]
Draft PR: https://github.com/patternfly/patternfly-org/pull/2331

**Comment by kevinhatchoua** [comment]
PR reviewed and merged. Closing with no further actions.
