### ISSUE TITLE
Create dropdown design guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2115]
Want to have some guidelines for drop downs, to describe how they work, how they are different from select lists (because I know this has been a point of confusion for people), and add in some examples!

Talk about how drop downs just list out a list of actions that you can take. It is different from a select list in that you don't select an option and that's it - selecting a menu item in a dropdown takes you somewhere else...

+ add anything else you think makes sense!

**Comment by mcarrano** [comment]
Here is a link to a first draft of these guidelines: https://docs.google.com/document/d/1zi_eSwenJHYcmQI7Tpe53vJ8ke_tTDMV-T7z0F4AfbQ/edit?usp=sharing  Feedback welcome.
