### ISSUE TITLE
Create design guidelines for the Menu component

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2118]
- Explain the different types of menu options that there are
- Mention the relationship between menu items and drop downs
- Talk about the different menu styles, and "nested" menu items (ie: menu items that can unveil more menu options from that category)

Look at react examples for more ideas

**Comment by mcarrano** [comment]
@mmenestr here is a first draft of the Menu design guidelines document: https://docs.google.com/document/d/1zUtZ8BJ-8vGAMcGaQ7daxQso8LiTu3ZGNtRyfFSPoRA/edit?usp=sharing Feedback welcome. Let me know if you think anyone else should review this. Thanks.

**Comment by mmenestr** [comment]
@mcarrano thanks Matt! Just left a few comments for you
