### ISSUE TITLE
Update progress bar design guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2119]
Review these guidelines: https://www.patternfly.org/v4/components/progress/design-guidelines/#using-progress-bars-in-your-designs
- Update images to use updated Red Hat font components
- Go through the guidelines to see if it's still relevant  
- Update content guidelines link to the UX writing style guide

**Comment by mcarrano** [comment]
@abigaeljamie @beccaglass Just wanted to make you aware of this issue: https://github.com/patternfly/patternfly/pull/3567#issuecomment-737457528 We've been reworking the way that spacing is handled when the label is placed at the end of the bar and we should probably cover this in the design documentation.  I would be glad to talk through this with you to give more background.
