### ISSUE TITLE
Create guidelines for Splitter component

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2123]
These will be added to the **drawer** component!

Little blurb on what a splitter is/does
Examples of when you would use them

**Comment by doruskova** [comment]
In progress (at the beginning). Doc is [here](https://docs.google.com/document/d/12aPq49wy3Tjr6IBBieI28oFcsz9vwgfjvno4PSJ17o4/edit?usp=sharing)

**Comment by doruskova** [comment]
@mmenestr Updated the [guideline doc](https://docs.google.com/document/d/12aPq49wy3Tjr6IBBieI28oFcsz9vwgfjvno4PSJ17o4/edit?usp=sharing)
