### ISSUE TITLE
Inconsistent code block styling across docs

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#2128]
Docs site has several different styling treatments applied to code blocks, should these be consistent?  examples:
- https://staging.patternfly.org/v4/guidelines/colors#typography-and-iconography-colors
- https://staging.patternfly.org/v4/guidelines/typography/#usage-guidelines
- https://staging.patternfly.org/v4/get-started/accessibility-guide/#what-patternfly-should-address

**Comment by evwilkin** [comment]
@rachael-phillips @mcarrano no urgency here - I'm not sure if this was done intentionally during redesign or just a result of different pages being updated at different times, any thoughts on if this something we should change?

**Comment by mcarrano** [comment]
@evwilkin I definitely don't think this was by intent. Agree that it would be nice to have a consistent styling. What drives this now? Are we applying unique CSS? Are any of these pages Markdown which has it's own native code block styling?

**Comment by evwilkin** [comment]
Thanks @mcarrano - it's mostly specific CSS styling applied for Org that vary from page to page.  I'll look to match it to the code styling laid out on our Typography page for consistency.
