### ISSUE TITLE
Add Catalog View design guideline

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2143]
It's not currently part of official PatternFly. It's currently just a React extension so we wouldn't have anywhere to put design guidelines... keeping it in the backlog in case that changes as there is a probably going to be a demo for it soon (noted march 23rd 2021)

Core issue: https://github.com/patternfly/react-catalog-view/issues/22

**Comment by mmenestr** [comment]
ON HOLD - waiting for it to be implemented

**Comment by mcarrano** [comment]
When we get around to working on this, let's consider this use case as summarized here: https://docs.google.com/document/d/1-hrOTK3NpKc_saCKOmZbvgi6xlrOPOXc0LPwnK9AD28/edit?usp=sharing

**Comment by mcarrano** [comment]
Consider guidance on showing and hiding the filter panel as discussed in the issue here: https://github.com/patternfly/patternfly-design/issues/932
