### ISSUE TITLE
Add top positioning to Modal guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2144]
Would need to add a "Placement on page" guidelines section
Could mention two possibilities: 
1. Default is to have it appear vertically and horizontally centered
2. Other options is to have it appear at the top of the page vertically, and still centered horizontally

**Comment by doruskova** [comment]
WIP doc [here](https://docs.google.com/document/d/13RWveUTqmv7jsowYuSacyyBHvBNvm3PY2vLXnElBvU4/edit?usp=sharing)

**Comment by mcarrano** [comment]
cc @mmenestr

**Comment by doruskova** [comment]
@mmenestr Updated doc[ here](https://docs.google.com/document/d/13RWveUTqmv7jsowYuSacyyBHvBNvm3PY2vLXnElBvU4/edit?usp=sharing)
