### ISSUE TITLE
Add Code editor design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2146]
Create guidelines for this new component: https://www.patternfly.org/v4/components/code-editor

**Design mocks:** https://marvelapp.com/prototype/b284chd/screen/70964526
**Design background:** https://app.zenhub.com/workspaces/pf4-design-workspace-5b2142ff9499cb7cdaf1e632/issues/patternfly/patternfly-design/836

**Comment by gdoyle1** [comment]
@mmenestr this is ready for a review! https://docs.google.com/document/d/1mK5C_fflcFHbZak2D9QaUvUc6oLgpf8VwBcZulnVOjI/edit?usp=sharing

**Comment by gdoyle1** [comment]
I'm having trouble getting my terminal to work sooo @mmenestr said she'd type these up - imgs added to **code editor** page in design doc assets and google doc is linked above!
