### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#2147]
We should change the naming of our main branches across all of PatternFly from master to main.  See related https://github.com/patternfly/patternfly/issues/3227, https://github.com/patternfly/patternfly-react/issues/4462.

**Comment by evwilkin** [comment]
Update 9/21 - Github to rename new repos to main starting next month, provide steps for updating existing repos to by EOY: zdnet.com/article/github-to-replace-master-with-main-starting-next-month

**Comment by evwilkin** [comment]
We're planning on making the switch to `main` when Github provides an automated process for this, sometime before the end of the year.

**Comment by redallen** [comment]
Finished updating today.
