### ISSUE TITLE
Move Tiles demo into Tile component page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2164]
I'm noticing that we have a Tiles demo page here: https://www.patternfly.org/v4/demos/tiles  Not sure why this exist here since we also have a Titles component. Shouldn't that live with the Tile component here? https://www.patternfly.org/v4/components/tile

**Comment by evwilkin** [comment]
Resolved by https://github.com/patternfly/patternfly-react/pull/4862 - this can be previewed in the React workspace [here](http://patternfly-react.surge.sh/components/tile/react) and will go live with the next release.
