### ISSUE TITLE
Hide sidebar scroll unless there is overflow content visible

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#2180]
The sidebar is set to `overflow: scroll` so the scrollbar gutter is visible all the time, including when there isn't overflow content. Using `overflow: auto` will only show the scrollbar & gutter when there is overflow content, otherwise it will be hidden. I believe I mentioned this a bit ago and was told it was to keep the nav from shifting when the scrollbar gutter hides/shows as overflow content is shown/disappears.

`overflow: scroll;`

<img width="1497" alt="Screen Shot 2020-10-06 at 6 07 16 PM" src="https://user-images.githubusercontent.com/35148959/95269682-9acb4600-07ff-11eb-9f51-1115ac148bd1.png">

`overflow: auto;`

<img width="1274" alt="Screen Shot 2020-10-06 at 6 15 01 PM" src="https://user-images.githubusercontent.com/35148959/95269852-e978e000-07ff-11eb-88af-e5bd4f1b3b18.png">
<img width="1278" alt="Screen Shot 2020-10-06 at 6 15 12 PM" src="https://user-images.githubusercontent.com/35148959/95269857-eaaa0d00-07ff-11eb-8ef2-56ad8c318fd9.png">

As a general principle, we use `overflow: auto` in our layouts and components anywhere we want to have scrollbars for overflow content to avoid this specific issue. It's the default behavior in our PF nav component, and it was overridden on the website. The main page section (both in Patternfly and on the website) uses `overflow: auto;`

No overflow

<img width="1349" alt="Screen Shot 2020-10-06 at 6 07 45 PM" src="https://user-images.githubusercontent.com/35148959/95269948-247b1380-0800-11eb-9a28-23fd4d745977.png">

Overflow

<img width="1280" alt="Screen Shot 2020-10-06 at 6 17 43 PM" src="https://user-images.githubusercontent.com/35148959/95270012-41afe200-0800-11eb-9196-5e360c476c94.png">

Personally I think the scrollbar gutter looks like a mistake, and would argue it being there on page load where there is no overflow content looks worse than any shifting that happens when there is overflow content and the scrollbar appears.

@mcarrano

**Comment by mcarrano** [comment]
I think you make good points @mcoker . I'd be in favor of changing this. What do you think @rachael-phillips ?

**Comment by mcoker** [comment]
It's also worth mentioning that this scrollbar doesn't show up by default on macs unless you've told the OS to always show scrollbars. But it does show up on windows machines. My computer is set to always show scrollbars so I can spot when we've accidentally set `overflow: scroll;` in the CSS like this. 

Here's what the page looks like on Windows/Edge

<img width="884" alt="Screen Shot 2020-10-14 at 12 54 47 PM" src="https://user-images.githubusercontent.com/35148959/96026994-d9bf5400-0e1c-11eb-8eb7-5c420ca00fc1.png">

**Comment by redallen** [comment]
I'm responsible for the current behavior. I implemented it this way so that the content in the side nav doesn't move:
![scrollbar-constant](https://user-images.githubusercontent.com/47335686/97487350-246bc080-1933-11eb-918f-8b6237208a1b.gif)

`overflow: auto` moves the content inside the scrollbar which feels like an odd interaction to me since the icons are right-aligned. Now that we have a long title "Writing design guidelines for PatternFly" under "UX writing" it could potentially change the text wrapping on that too:
![scrollbar-moving](https://user-images.githubusercontent.com/47335686/97487022-aefff000-1932-11eb-892a-fdb175087bc4.gif)

**Comment by mcoker** [comment]
Personally I think the shifting is fine, it's standard for that sort of thing to happen when a scrollbar appears. Here is the page's main section.

![Oct-28-2020 14-42-53](https://user-images.githubusercontent.com/35148959/97488303-11092700-192c-11eb-8a66-4885d9b3d3e0.gif)

We could also start with a section expanded, which would trigger the scrollbar to show - though I think we used to do that and changed the menus to be collapsed, so I'm assuming we want to keep that that way?

**Comment by redallen** [comment]
You've convinced me @mcoker , we can remove the `overflow-y: scroll` here: https://github.com/patternfly/patternfly-org/blob/master/packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.css#L21
