### ISSUE TITLE
Edit toolbar guidelines to address "toggle group" mentions

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2187]
Right now there is a whole section on "toggle groups" in toolbar, but this is confusing, because they are referring to something different than the toggle group component. Thinking we should re-visit the "toggle groups" naming in toolbar to something else - like filter groups or action group...
https://www.patternfly.org/v4/components/toolbar/design-guidelines#toggle-groups

@mcarrano what are your thoughts on this?

**Comment by mcarrano** [comment]
@mmenestr I admit this is confusing. But I chose this name to be in sync with the component documentation here: https://www.patternfly.org/v4/components/toolbar#examples-with-toggle-groups-and-filters  So I'd rather maintain this consistency.

@mcoker @mattnolting do you think this is something we should consider renaming down the road?

**Comment by mcoker** [comment]
@mcarrano @mmenestr Agree, this is confusing. I wonder how well this would play out if we introduce a toggle group component to a toolbar, and we need to create a BEM element for the toolbar to manage it. I'm wondering if we should rename the core toggle group to something like [button group](https://getbootstrap.com/docs/4.5/components/button-group/) or [toggle button group](https://material-ui.com/components/toggle-button/).

**Comment by mcarrano** [comment]
I would be in favor of that @mcoker . Can we do that without a breaking change? I remember some discussion with @christiemolloy when we first introduced the component. It may have been "Toggle button group" originally but we felt that was too long. I think that "Button group" would work. @christiemolloy do you remember why we settled on Toggle group?

**Comment by mcoker** [comment]
> Can we do that without a breaking change?

The toggle group component is still beta, so we can update it. I think it's a worthwhile change.

Also the toggle group component is currently just a toggle button group. Looking forward, I wonder if a "button group" could be something more generic as a way to group buttons/actions, and there is a toggle group variant. We could also move the toggle buttons in the toggle group currently to the button component as a "toggle" variant. I could see using that in components where we have button groups with variants. That may also be able to be used in place of the action list component/layout we have an issue for. WDYT?

**Comment by mattnolting** [comment]
Agree, it's confusing. I think something more explicit like `__collapsible-filters` would avoid the `__group` nomenclature altogether, bearing in mind that individual `__item` s as well as `__group` s are used/placed inside `__collapsible-filters`. It should be a discrete type of container rather than a group, with a modifier. The reason it's called `pf-m-toggle-group` is that I named it before `pf-c-toggle-group` existed and naming is hard..

**Comment by mcarrano** [comment]
I am leaning towards renaming the Toggle group component to Button group based on this feedback. @christiemolloy do you see any problem with that?

@mcoker I'd prefer to keep this as a separate component to minimize the disruption in doing this, but it's a reasonable question whether what we are calling an Action List should be coupled with this. Right now, the reason we thought of the toggle buttons as unique is that they preserve state unlike standard buttons that do not.

**Comment by mcoker** [comment]
@mcarrano sounds good to me.

**Comment by mmenestr** [comment]
@mcarrano @mcoker did any changes ever get made with this?

**Comment by mcoker** [comment]
@mcarrano it's still a beta component if we want to rename it.

**Comment by mcarrano** [comment]
I'm re-reading this and see two threads leading to different solutions. One is to rename the component called "Toggle group" to "Button group" and avoid the overlap. The other is to change the name of what we call a "toggle group" in the Toolbar component.

@mcoker do you think one is easier or makes more sense than the other?

**Comment by mcoker** [comment]
Thinking about it some more, renaming it to button group will be inconsistent with label group and chip group, since it wouldn't be a group of button components. Toggle button group seems more appropriate, and would leave room for a button group if that ever became a thing.

@mattnolting makes a good point in calling the toggle group in the toolbar "collapsible filters/content"  or "toggle content" or something.

It's probably easier to rename the toggle group in the toolbar component to something else, but that's a breaking change.

**Comment by mattnolting** [comment]
@mcoker @mcarrano Seems like a good idea to change the name of toggle group to toggle button group, as it's still beta, then possibly update the toolbar elements during a breaking change.

**Comment by mmenestr** [comment]
Ok, so in terms of this issue, it sounds like we can put this on hold until a breaking change comes along, and we rename the toolbar elements to something else.

If we do end up changing the "toggle group" component to "toggle button group" can you let me know so I can change the design guidelines accordingly? As well as its naming in the patternfly sketch kit.

**Comment by mcarrano** [comment]
@mmenestr We had more discussion about this in our PF Leads meeting today and decided that we will not make any changes to naming in the short term. While we all agree it is confusing, renaming could have other side effects. I've assigned this issue to myself and will rework the documentation to try and clarify this a bit for designers.
