### ISSUE TITLE
Add to card guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2196]
1. Add section on expandable cards - can have an expandable card header
2. Add to Image section to show another example of an image layout

![image.png](https://images.zenhubusercontent.com/5e750f70a086dc7bdce718bd/5256680e-7163-41fd-94a1-d3f25fe22b02)

**Comment by mcarrano** [comment]
@mmenestr This issue looks to have two parts. I will add discussion of expandable cards. But part 2 was to address images in cards, but I already see this in the guidelines here: https://www.patternfly.org/v4/components/card/design-guidelines#images Did someone else already make this update?

**Comment by mmenestr** [comment]
@mcarrano I can't fully remember now, I think Abi added that sections on images, but I'm wondering if this issue was to add an additional example of a way you could add images to your card (ie: maybe place them somewhere else, other than at the top of the card like that?)
