### ISSUE TITLE
Update Navigation sections and add back Utilities to site

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#2200]
Update Navigation sections and add back Utilities to site

**Get Started**
About
Design 
Develop

**Developer Resources**
Accessibility guide
CSS utility classes
Global CSS variables
Migrate
Red Hat font
Release notes
Training 
Upgrade guide

Utilities will be brought into one page per @dgutride 's recommendation. cc @mcoker and @mcarrano

**Comment by jgiardino** [comment]
Utilities are the best! I often use them along side Layouts to do minor tweaks and adjustments.

**Comment by evwilkin** [comment]
@rachael-phillips @dgutride @mcarrano @mcoker we discussed combining all the Utility pages ([see Core workspace](https://pf4.patternfly.org/utilities/accessibility)) into one page, which would be very long & a bit disorganized - what do you think of keeping them separated into tabs within a single page as seen here:
- https://patternfly-pr-3649.surge.sh/developer-resources/css-utility-classes/Accessibility

Note that css styles still need to be updated to display correctly with this approach.

**Comment by mcarrano** [comment]
My problem with this approach is that it's not very extensible. It's not great if we start adding more tabs. Do we expect the set of utility classes to grow or is this a pretty fixed set of items?

**Comment by mcoker** [comment]
Agree with @mcarrano. About the number of utilities, we just added 2 new ones in core, though that said I don't anticipate adding a lot more.

I don't feel strongly about it, but navigating utilities via tabs also feels a bit disjointed from the rest of the site. It could be from my perspective of knowing how they're built and having interacted with them previously on the website, but utilities are structured just like components and layouts. The tabs at the top of the pages on layouts and components offer different views of the current thing (core, react, demos, design). I think I would expect to see a list of utilities similar to layouts and components, and tabs for different views of a single utility - demos, design guidelines... if those were ever to apply.

**Comment by evwilkin** [comment]
Per conversation, Utilities will be added back to the site as they were previously in their own left nav section.
