### ISSUE TITLE
Patternfly component guidelines - Switch on/off

### ISSUE THREAD

**Issue by kevinhatchoua** [patternfly/patternfly-org#2201]
As  a designer, I would like more guidance and clarity about the use cases for the switch component. 
- What is the difference between a switch with a checkmark icon and one without? When should the former or latter be used?

https://www.patternfly.org/v4/components/switch

**Comment by mmenestr** [comment]
Add guidelines: Default, use the label, but if you are limited in space, use the checkmark variation

**Comment by abigaeljamie** [comment]
Alana to complete this by early December.

**Comment by abigaeljamie** [comment]
Alana to complete by 12/11
