### ISSUE TITLE
Revamp PatternFly Modal document

### ISSUE THREAD

**Issue by abigaeljamie** [patternfly/patternfly-org#2215]
Specific edits:

- First image needs to be replaced (modal needs to be rewritten to follow structure) 
- "Delete database" image needs to be replaced (modal needs to be rewritten)
- "Resource usage" image needs to be replaced (modal needs to be rewritten) 
- This line needs to be updated from "Content" section: _Clearly restate the action the user is trying to take and explicitly outline the consequences of that action._ (shouldn't be restating actions)  

Other edits: 
Read entire document and revise the content

**Comment by abigaeljamie** [comment]
Goal is to have a first draft created by mid to late November

**Comment by afialkoff** [comment]
Shared first draft with @abigaeljamie today (11/17), including new images and revamped content

**Comment by doruskova** [comment]
@afialkoff @mmenestr Just adding my doc about modals [here](https://docs.google.com/document/d/13RWveUTqmv7jsowYuSacyyBHvBNvm3PY2vLXnElBvU4/edit?usp=sharing)
because there'd be a conflict if we merged separate PRs.
