### ISSUE TITLE
Search field for icons is not rending on Google Chrome

### ISSUE THREAD

**Issue by bgliwa01** [patternfly/patternfly-org#2225]
On the icon page, the search field does not render when you are using Google Chrome.
<img width="1680" alt="Screen Shot 2020-10-26 at 2 29 11 PM" src="https://user-images.githubusercontent.com/51342070/97213148-a921d780-1797-11eb-95ee-1fda34e7ac90.png">

**Comment by evwilkin** [comment]
Closed by https://github.com/patternfly/patternfly-org/pull/2202 in yesterday's release.
