### ISSUE TITLE
docs: Some double-dashes (--) are rendered as an emdash (—)

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-org#2236]
When consulting the docs at https://www.patternfly.org/v4/guidelines/icons/, I noticed a copy/paste of the CSS variable referenced in the icon sizes was not working.

The page references --pf-global--icon--FontSize—sm, --pf-global--icon--FontSize—md, --pf-global--icon--FontSize—lg, and --pf-global--icon--FontSize—xl.

Instead of `--pf-global--icon--FontSize—lg`, it should be `--pf-global--icon--FontSize--lg`

I'm guessing this issue affects other pages too.

A workaround is to always refer to CSS variables in code blocks. If this is Markdown (which I'm guessing it is), it should probably have backticks around it, like so:

```
`--pf-global--icon--FontSize--lg`
```

**Comment by evwilkin** [comment]
Thanks for filing this @garrett, I've just put up a PR to get these (and a similar issues in the Badges design guidelines) fixed.
