### ISSUE TITLE
Add <meta name="description"> tag

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#2249]
Per spike #1626 our Lighthouse SEO report can be easily improved by added a `<meta name="description">` tag with a content attribute set to a description as explained here:

- https://web.dev/meta-description/

**Comment by evwilkin** [comment]
@abigaeljamie can you help craft a description for our site?  As mentioned in the link above, this contributes to SEO & is what displays in search engine results.

Here is an example from Carbon:

<img width="350" alt="Screen Shot 2020-11-01 at 3 01 34 PM" src="https://user-images.githubusercontent.com/8651509/97812993-30b58d80-1c53-11eb-8b5e-7b2476f8414f.png">

<img width="500" alt="Screen Shot 2020-11-01 at 3 02 23 PM" src="https://user-images.githubusercontent.com/8651509/97813008-47f47b00-1c53-11eb-958c-2a52a5ebf8c0.png">

**Comment by abigaeljamie** [comment]
Thanks for looping me in, @evwilkin ! I did some quick research on Google SEO character limits, and it usually truncates them at around 155 – 160 characters (Carbon's description has 147 characters. 

How do you feel about this? 

_PatternFly is Red Hat’s open source design system. It consists of components, documentation, and code for building enterprise applications at scale._ 

It's ultra simple and short, and it's 148 characters. I tried to get some important identifier words in there too, like "Red Hat," "open source design system" and "enterprise applications."

**Comment by evwilkin** [comment]
Thanks @abigaeljamie that sounds perfect to me.  I'll move forward with adding this - thank you for taking a look!
