### ISSUE TITLE
Problem when switching from old release to the latest release

### ISSUE THREAD

**Issue by DaoDaoNoCode** [patternfly/patternfly-org#2252]
This problem happens on [patternfly.org](https://www.patternfly.org/) on the right top corner of the page. When you choose old releases like 2020.12 or 2020.13 and try to switch back to the latest release 2020.14, you will not be able to jump back and will remain at current page. This problem doesn't happen when you choose old release 2020.11.

<img width="236" alt="Screen Shot 2020-11-03 at 2 59 08 PM" src="https://user-images.githubusercontent.com/37624318/98034528-22977680-1de5-11eb-9a8c-4939088fd9a8.png">

**Comment by redallen** [comment]
Good catch, we broke something recently. Unfortunately it's rather time-consuming to retroactively fix previous releases, but we can fix the current one.
