### ISSUE TITLE
Provide guidance on presenting disabled menu items

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2258]
Menu items in dropdown or select menus may currently be shown as disabled. However it is unclear how best to reflect the reason why an option is disabled. Some ideas include using descriptive text within the menu item or showing a tooltip or help popover. Would be good to provide designers with guidance about what options are available and when to use different approaches.

This would be added to the guidelines here: https://www.patternfly.org/v4/components/menu (will be released Nov 18th)

**Comment by andybraren** [comment]
@bmignano is currently working on [a doc](https://docs.google.com/document/d/1hlt6HLddLsmhQLMHGYpV6zzud4NBwmbnsaLk7xM2xQ4/edit#) that explores this and more.

**Comment by kaedward** [comment]
Draft doc: https://docs.google.com/document/d/1R1y-FeQVFn9XmqfBKYXkl25_b6YlCbAWlVIIbL9xgg4/edit?usp=sharing
