### ISSUE TITLE
Add Icon Font Links to Main Icon page

### ISSUE THREAD

**Issue by bdellasc** [patternfly/patternfly-org#228]
In order to access the downloads for the PatternFly and fontawesome icon fonts (for desktop use), you have to click into the cheatsheet, then on the links. Can we add those links to the top of the basic icon page as well? Two different people have asked me where to find them this week because they didn't know to click through to the cheatsheet page. Thanks!

**Comment by Essjaysee** [comment]
Also, the links to the font files are broken on this page: http://www.patternfly.org/styles/icons/cheatsheet/#_

**Comment by LHinson** [comment]
All of these issues have been addressed with the latest icon table http://www.patternfly.org/styles/icons/#
