### ISSUE TITLE
Add additional guidance to Labels doc

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2329]
Add some guidelines around using to the Label design guidelines following this doc https://docs.google.com/document/d/1K2pBe_hKevycrMQFpc8MuNnlxcPC41rmRJ74cxRnauw/edit?disco=AAAALPeUN9I&ts=5fdbe011&usp_dm=false

Maybe phrase it as suggestions:
- PatternFly recommends reserving the red, yellow and green label colors for indicating status etc....
- PatternFly recommends using outlined labels for clickable labels, and filled for un-clickable labels...

**Comment by mcarrano** [comment]
See related discussion here: https://github.com/patternfly/patternfly-design/issues/971
