### ISSUE TITLE
Docs: @propType and @hide annotations do not function

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-org#2332]
When I add `@deprecated` to a component prop, I can see it output in the example docs. However, I don't see a similar result with the `@propType` and `@hide` functionality added via https://github.com/patternfly/patternfly-org/pull/1671.

I'm expecting to see a different property type, for Chart props below, which is shown by the area chart example.

```
export interface ChartProps extends VictoryChartProps {
  /**
   * The animate prop specifies props for VictoryAnimation to use.
   * The animate prop should also be used to specify enter and exit
   * transition configurations with the `onExit` and `onEnter` namespaces respectively.
   *
   * @example {duration: 500, onExit: () => {}, onEnter: {duration: 500, before: () => ({y: 0})})}
   *
   * @propType boolean || object <------------
   */
  animate?: boolean | AnimatePropTypeInterface;
```

Is there a trick to get this working locally? I can see `@deprecated` when I rebuild the docs, but `@propType` and `@hide` do not appear to do anything.

<img width="857" alt="Screen Shot 2020-12-28 at 12 40 14 PM" src="https://user-images.githubusercontent.com/17481322/103232967-df034980-4909-11eb-894b-f1a6437cfebf.png">

**Comment by redallen** [comment]
[The file responsible for implementing these](https://github.com/patternfly/patternfly-org/blob/master/packages/theme-patternfly-org/scripts/tsDocgen.js#L5) did have `@propType` removed when upgrading the site. We can add that back and see why `@hide` isn't working like you expect.
