### ISSUE TITLE
Add guidance on draggable row usage to Data list design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2348]
This issue further elaborates on the approach for supporting drag and drop rows in a data list. Want to update design guidelines to include these use cases.

Include image and guidance on where to include the "waffle" icon which would signify the draggable affordance

Patternfly issue with mocks: https://github.com/patternfly/patternfly/issues/3765

**Comment by mmenestr** [comment]
@lclay2 add use case to issue for gina :)

**Comment by lclay2** [comment]
Hi @gdoyle1 , Kogito uses the draggable row in the DMN data types section. The use case is the user wants to add data types, but then be able to order/reorder them afterward. 
To view it in action, go to:
> https://kiegroup.github.io/kogito-online/#/
> Select "Try Sample" link in the Decision model (.DMN) card.
> Select the "Data Types" tab.
> Hover over the item and the drag grabbers appear. You can select drag up and down, as well as nest indent. Please note: The team did this before the PF pattern, so that's why it's a little different using hover versus static grab bars. cc @cardosogabriel who implemented this in case you have questions. And I contributed to the design, so can answer more detailed design background questions as needed. :)

**Comment by gdoyle1** [comment]
Added a draft of these here: https://docs.google.com/document/d/1mYyv8uva5f7TVRUao_OBcZ0TPJYsgWHllS1bWyG2N3M/edit?usp=sharing @mmenestr

**Comment by mcarrano** [comment]
Looks great @gdoyle1
