### ISSUE TITLE
Callout style for the blog

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#235]
I'd like to have a way to do callouts in the blog. The main use case is to highlight important sentences in a post, but it could also be used for "See also" types of links.  Something that has a presentation like this would be grand: http://blogs.ces.uwex.edu/wordpress/customizing-your-site/callout-box-plugin/

This would be different than blockquote, which also highlights text but remains inline with the paragraph. I'm looking for a way to repeat a sentence or two in a sidebar.

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2016. Please let me know if this is still relevant.
