### ISSUE TITLE
Add guidance on advanced search using attribute-value pairs

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2350]
Attrribute-value/advanced search is being added to  the Search Input component to support integrating a search form with a search field. This should be added to the Search Input design guidelines. (Component here: https://www.patternfly.org/v4/components/search-input#advanced)

Original design issue here: https://app.zenhub.com/workspaces/pf4-design-workspace-5b2142ff9499cb7cdaf1e632/issues/patternfly/patternfly-design/771
Core implentation here: https://github.com/patternfly/patternfly/issues/3771

Include guidance on using "=" or ":" 
Can you use either/or, or do you have to choose one or the other when you implement it

**Comment by mcarrano** [comment]
@mmenestr @afialkoff Here is a draft of the text for adding this functionality: https://docs.google.com/document/d/1FyZUKXuvlORkKxT6KtdyB559qqZFJPWUvuGZR0UgHo0/edit?usp=sharing  My proposal is to just add this to the end of the existing page here: https://www.patternfly.org/v4/components/search-input/design-guidelines

Please give this a review before I move to Markdown. Thanks.

**Comment by afialkoff** [comment]
Looks great, @mcarrano! 🙌 I left a few minor comments/suggestions in the doc.

**Comment by mcarrano** [comment]
@mmenestr Here is the updated Sketch file with new Search Input assets: https://sketch.cloud/s/5c43a9c8-2c54-4329-9f04-0d7458425de8
