### ISSUE TITLE
Update form example

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#2351]
https://www.patternfly.org/v4/components/form
The help text example is a full sentence and therefore should use punctuation.

we also want to come up with a better help text example. In this case the "full name" info should be in the label, not help text.

**Comment by abigaeljamie** [comment]
Hey, @ajacobs21e ! Thanks for filing this. It looks like updates are needed to the [Form React guidelines](https://www.patternfly.org/v4/components/form) and the [Form Design guidelines](https://www.patternfly.org/v4/components/form/design-guidelines). 

Alana and I can handle the Design guidelines, and I'm looking into who on the React side can update the React guidelines :) I'll keep you posted with updates!

**Comment by afialkoff** [comment]
I'll be updating the form design guidelines and image text by 2/1. From there, @abigaeljamie and I will hand off those materials to get updated on the React side. 👍
