### ISSUE TITLE
Create guidelines for the "Touchspin" component

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2363]
Need to create some guidelines for this component: https://www.patternfly.org/v4/components/touchspin

This should include an explanation of how the touchspin works, and use case of when to use it + examples of it in context (eg. a form)!

Will be renamed number input*

**Comment by kevinhatchoua** [comment]
[Working draft](https://docs.google.com/document/d/1V0cjU8kg3OBj00_lHAHOZ789YPHFK-FuPKc8tiL5a4Y/edit?usp=sharing)

**Comment by kevinhatchoua** [comment]
[Working draft](https://docs.google.com/document/d/1V0cjU8kg3OBj00_lHAHOZ789YPHFK-FuPKc8tiL5a4Y/edit?usp=sharing)
