### ISSUE TITLE
Create guidelines for the Slider component

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2381]
https://www.patternfly.org/v4/components/slider/

**Comment by MariSvirik** [comment]
https://docs.google.com/document/d/1dv3RUHSZT1NSAlgoTO3EuFP8qMBV3k-0MS0R0m2w7sY/edit?usp=sharing

**Comment by MariSvirik** [comment]
https://github.com/patternfly/patternfly-org/pull/2609
