### ISSUE TITLE
Add guidance on using new "inline" copy to clipboard variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2409]
We are adding a new lightweight inline variant of the Clipboard Copy component. Want to add guidance on when/why to use vs. the standard/existing variant.

cc @mmenestr

**Comment by mmenestr** [comment]
Waiting for it to be implemented... https://github.com/patternfly/patternfly/issues/3906

**Comment by lwrigh** [comment]
Here is the Google doc that features the inline copy to clipboard design documentation: https://docs.google.com/document/d/1nPTsYpqdFDvh_VyBSjziVzZku9fETHdgMpw3Zrqk1xA/edit?usp=sharing 

I will be opening a PR for it momentarily.
