### ISSUE TITLE
Code Block: design guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2410]
Need to add design guidelines for the new Code block component. Code block is a light-weight read-only component for displaying a snippet of code and associated actions. Editing is not allowed?

cc @mmenestr

**Comment by lwrigh** [comment]
Here is the Google doc that features the code block design documentation: https://docs.google.com/document/d/1Lo-ab3rdxNe4wbN1oYkJDU1cC4icVOY_DrdzeyMR_E0/edit?usp=sharing

I will be opening a PR for it momentarily.
