### ISSUE TITLE
Move Card View demo to its own page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2426]
Want to move the Card View demos for both core and React to a new page that lives in the Demos section. This will group them better with other similar demos (like primary-detail) and reserve Card demos for examples of specific card types.

@redallen let me know what's involved in moving these and if this needs to first be done in the Core and React repos, respectively. I will take care of moving the design guidelines content.

cc @mmenestr

**Comment by redallen** [comment]
@mcarrano This needs to be done in the Core/React repos and when we bump org it will be reflected. All you have to do is change `section: components` to `section: demos` in [React](https://github.com/patternfly/patternfly-react/blob/master/packages/react-core/src/demos/Card/Card.md) and [Core](https://github.com/patternfly/patternfly/blob/master/src/patternfly/demos/Card/examples/CardView.md).

**Comment by mcarrano** [comment]
Thanks @redallen . I have opened https://github.com/patternfly/patternfly/issues/3958 and https://github.com/patternfly/patternfly-react/issues/5599 to do the move then and will close this.
