### ISSUE TITLE
Expand inline edit guidelines to include editable cards

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2436]
Want to expand [these guidelines](https://www.patternfly.org/v4/components/inline-edit/design-guidelines) to include use cases that may not call for or require explicit commit (save or cancel) operations as described in this issue: https://github.com/patternfly/patternfly-design/issues/976

Consider what affordances should be provided, when to use, and how (or if) the user is able to undo actions.

cc @amysueg @lboehling feel free to add further requirements to this doc issue.

**Comment by mmenestr** [comment]
Update: the design issue has been prioritized, so I am putting this on hold for now.

**Comment by mmenestr** [comment]
Closing because this effort is no longer happening.
