### ISSUE TITLE
react-console docs is missing from https://www.patternfly.org/v4

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-org#2442]
Actually the whole 'extensions' section is missing from the website.

**Comment by KKoukiou** [comment]
@redallen where are we supposed to find the extensions documentation now then? or it's a bug?

**Comment by redallen** [comment]
You're supposed to find react extensions on https://patternfly-react.surge.sh. If you'd like to find them on patternfly.org that's outside of my jurisdiction, you'll need to wait for @mcarrano to reply to this issue.

**Comment by mcarrano** [comment]
@KKoukiou @redallen Yes, we had made a decision some time ago to not expose React extensions on the website. That said, it may be time to reconsider that. But it is important to emphasize that these are community contributions and are not supported directly by the PatternFly team. What would you think of the idea of exposing these on our [Community page](https://www.patternfly.org/v4/community) with proper disclaimers and information about how to contribute?

**Comment by KKoukiou** [comment]
@mcarrano having somewhere on the patternfly-org a link to the patternfly-react.surge.sh for me is enough. I just had no idea about this site before @redallen commented about it.

**Comment by evwilkin** [comment]
Closed in https://github.com/patternfly/patternfly-org/pull/2559
