### ISSUE TITLE
Add guidance for secondary horizontal nav

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2443]
Design issue: https://github.com/patternfly/patternfly-design/issues/958 and https://github.com/patternfly/patternfly-design/issues/876
Core issue: https://github.com/patternfly/patternfly/issues/3935

Could be used along with vertical navigation, or as secondary nav underneath masthead.

On August 4th 2021 road map...

**Comment by gdoyle1** [comment]
Wanted to get this drafted before I leave @mmenestr ! Here's the google doc: https://docs.google.com/document/d/1riXIxesxvL2sn87oejYXDtaaRjidTneKTtj6PdI2Sho/edit?usp=sharing
