### ISSUE TITLE
Add guidance in tooltips guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2450]
https://github.com/patternfly/patternfly-react/pull/5654

Want to suggest adding delays to tooltips so they don't show up immediately on hover.

Note to self: Zack "only added it into the <TableText> component. other <Tooltip>s still have the old behavior"

**Comment by mcarrano** [comment]
I think this is fine. Does it make sense to say why or under what circumstances you might want a longer or shorter delay?

**Comment by mmenestr** [comment]
**Tooltip: added entry delay**
Added a 300ms default entry delay to tooltips to prevent immediate firing when passing the mouse over a page. This value can be changed via a prop.
