### ISSUE TITLE
PatternFly logo flies down & backwards instead up & forwards

### ISSUE THREAD

**Issue by mairin** [patternfly/patternfly-org#2451]
The blue PatternFly logo on the front page of patternfly.org - it looks like it's kind of like an abstract fly with wings - flys down and backwards on the page. I know this is kind of a silly bug, I do, but it might make more sense to have the fly fly upwards and forward... the symbolism of flying backwards and downwards is probably not what you'd want.

![Screenshot from 2021-04-13 20-38-24](https://user-images.githubusercontent.com/799683/114637810-34385080-9c98-11eb-9e36-528ed054a136.png)

**Comment by evwilkin** [comment]
Closing out as homepage has been redesigned completely, to be unveiled in the coming days!
