### ISSUE TITLE
Design documentation needed for drag and drop interactions 

### ISSUE THREAD

**Issue by lwrigh** [patternfly/patternfly-org#2459]
A proposal for introducing a [drag and drop pattern ](https://docs.google.com/document/d/1LpPj68HWkyT2oq6nJDBFg_WI9pk4BWimPbw7l8yWVvQ/edit?usp=sharing)was shared at the most recent design share meeting. In a PatternFly context we discussed that going forward it would make more sense to add more design documentation guidelines around consistent drag and drop behaviors, interactions, and visual design. 

It might make sense to include this drag and drop design documentation underneath the 'Guidelines' section of PatternFly.

**Comment by mmenestr** [comment]
Guidelines draft: https://docs.google.com/document/d/1UoRGWpkycWfuSrR68dDasKC4jZFaO7OMCHuOqPvb0Js/edit#heading=h.wc4t4vt47ycu

**Comment by mcarrano** [comment]
@mmenestr I reviewed the above document, and while I think that all of the information it contains is correct, it was not what I was expecting to find here. It seems like most of the information is specific to drag and drop in the context of specific components and should probably exist in those component docs. What I was expecting here was more general guidance on things like what icons to use for drag handles, any cursor changes, or visual treatments to indicate a drop target. Also standard mouse and keyboard interactions would be helpful. To me, the only reason for having this guidance at all would be to drive consistency for any developers creating custom drag and drop interactions. Does that make sense? Maybe talking about File Upload and column reordering as examples is OK.

**Comment by mmenestr** [comment]
@mcarrano Yes that makes sense! This is the draft that Laura worked on that I haven't gotten around to reviewing but I will take a look and see what we should do from there. Might reassign to someone to cover the things you expected to see, and we can see if we can use any of what Laura wrote for the specific component guidelines!

**Comment by mmenestr** [comment]
Draft is here: https://docs.google.com/document/d/1xkxKgTo5BjgzLv4-R8sYQfVWQshNzjyixa5z3mZbuvM/edit

**Comment by mcarrano** [comment]
This looks good to me!
