### ISSUE TITLE
Add eye and eye-slash icons to PF icon set

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#2461]
Follow-up to https://github.com/patternfly/patternfly-design/issues/1036, add `eye` and `eye-slash` icons to our supported icons docs.

**Comment by bdellasc** [comment]
Should the icons be categorized as "Framework", not "Object"? Much like a dropdown arrow, ellipses, etc they're clickable and have an interaction associated with them? Sorry, I didn't catch this earlier.

**Comment by evwilkin** [comment]
@bdellasc that makes sense to me, unless @doruskova has any other thoughts I can proceed with "Framework"
