### ISSUE TITLE
Add password strength indicator in log in design guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2471]
Add to log in design guidelines to mention possibility of adding password strength indicator and the different states

patternfly-design issue: https://github.com/patternfly/patternfly-design/issues/877
core: https://github.com/patternfly/patternfly/issues/4018

**Comment by mcarrano** [comment]
Note that this was implemented as a demo here: https://www.patternfly.org/v4/demos/password-strength

**Comment by mmenestr** [comment]
@pankajshivpuje
