### ISSUE TITLE
Add usage guidance on Progress button variant

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2498]
Want to have guidance on when and how to use the Progress variant of a button: https://github.com/patternfly/patternfly/issues/3955

Some issues to address include:

* what are valid use cases for this vs a progress bar or spinner?
* What are acceptable wait intervals?
* Can the user still click the button while the spinner is active?
* What happens when the user clicks on the button? Should there be hover text to say "cancel action" or something like that?

Refers to this button: https://www.patternfly.org/v4/components/button/#progress

cc @mmenestr

**Comment by ajacobs21e** [comment]
Is the use case that the user would have clicked on a button, such as a form "submit" button, and then the button changes to the progress state until the page loads, and then the button goes away?
Or is there a use case where the button would then go back to the initial state... for example an "add object" button that would then show "creating object" and then go back to "add object" after it's created?
Or a use case where the button changes after the progress... for example "add object" -> "creating object" -> "remove object"?

**Comment by mcarrano** [comment]
This is done
