### ISSUE TITLE
Expose community assets through the PatternFly website

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2511]
Want to provide a space on the PatternFly website to expose shared assets that extend PatternFly but are maintained by the community.    

* We follow a similar model to Carbon's community asstes (https://carbondesignsystem.com/community/overview/) where we expose components that PF consumers have created specifically for RH products. 
* These components will be maintained by separate teams, like clouddot and openshift. 
* Component repos can exist in product space or within the PatternFly organization on GitHub.

This will extend the Community Projects area that currently lives on the [PatternFly Community page](https://www.patternfly.org/v4/community).

**Comment by nicolethoen** [comment]
https://docs.google.com/document/d/1P91G0aHiLkbJqDZ0EQl41kaYMizWEctsilzpCOTQbro/edit
