### ISSUE TITLE
Home page opportunity for improvement -- What, exactly, is PatternFly?

### ISSUE THREAD

**Issue by zipzit** [patternfly/patternfly-org#2535]
I came to the [PatternFly website](https://www.patternfly.org/) with no clue what I was looking at.  Here's what I first saw:

> ### Build scalable experiences in the open.
> PatternFly is an open source design system built to drive consistency and unify teams.
> 
> Hello, we're PatternFly. We think quality product experiences should be easy to build and easy to scale, so we provide the tools to make that happen.
> 

I'm like awesome.  I'm a building architect. With the words above I'm going to use PatternFly to make simply awesome buildings, right?  Can I assume you have plugins for Catia and Solidworks and Revit Computer Assisted Drafting programs?

Oh, not architecture?  Ooops.  did I get that wrong?  Oh, wait teams.  I see...

> Drive consistency, unify teams. 

This is a tool setup to help my kids soccer team excel and win the championship.  We're all in.  Oops.  Is that not it?  

I'm just reading your words.  Words matter, and in the simplest of terms, the words you guys use can use lots and lots of improvement.  

Now I'm not trying to change your design philosophy, change your governing values.  Those are super important and they inspire and bind us to do greatness.  I get it.  I'm just saying for an introduction to your product, the descriptions on your home page are simply terrible to any newcomer.  Its okay to trumpet your values and design ethos, but for the rest of us tell us what you are in simple complete words.  Its fine to add words to that in addition to the stuff you've already stated.  

My story?  I wanted to understand what PatternFly is, and how it compared to React or Gatsby software development tooling.  I came to your web page understanding not a single thing.  Next stop try some youtube intro videos. I will say, lots of crap there in the under 4 minute intros. Nothing of value.  At that point I was ready to run away.  Thought I'd give it one last go.  Then I came across this:

>     https://www.youtube.com/watch?v=f_57P7-WRp0
>     PatternFly with React: the answer to the new age Web Designing by Anisha Swain
>     Jun 14, 2020    reactify (21:59)  Anisha Swain

Wow.  React, with Bootstrap. Now you're talking, and now I'm listening.  In fact, why is there no mention of Bootstrap at all on patternfly.org? That's a horrible miss.  What are you guys thinking?  Why did I have to watch a 20 minute video to see that PatternFly includes Bootstrap?  

---Proposal-----------------------------------------------------------------------

Here is a simple proposal for a description of what I'm thinking would make more sense to a person visiting your website... 

Patternfly is a set of software development tools to aid designers and software developers create amazing webpages and software applications. At the core we start with React ( A JavaScript library and awesome component system for building digital user interfaces) and Bootstrap (a solid front end open source tool kit with Cascading Style Sheets tooling, a responsive grid system prebuilt components and powerful JavaScript plugins.) And we improve things from there... 

We've added numerous functional components beyond the standard React/Bootstrap stuff.  
We've added sketch / graphical tools to enable the entire build process (User Experience / User Interface). Here team work and collaboration is the name of the game.  
We have an integrated approach to icons, color, content and more
We get you started with responsive layouts, regardless of screen size.  Mobile first, no problem!

Components, lots and lots...

etc...

Clearly this write up is one person's opinion, no offense intended.  Isn't that part of what open source is all about?  Note, you can only be a first time visitor to https://www.patternfly.org/ once in your life.  Can we at least make that first visit informative and engaging?  Comments?

**Comment by evwilkin** [comment]
Thanks @zipzit for taking the time to write out this feedback and suggestion.  We are currently reevaluating the content on our homepage, so this is very timely.  I will note that older versions of PatternFly included Bootstrap, but we have since moved away from Bootstrap to a system built from the ground up.

We look forward to rolling out updates to our homepage, in the meantime looping @abigaeljamie and @afialkoff in on this feedback.

**Comment by evwilkin** [comment]
Closing in favor of the work being done towards https://github.com/patternfly/patternfly-org/issues/2796
