### ISSUE TITLE
Add expandable inline alert variant to alert guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2539]
**To do:** Add expandable alert to alert guidelines
See example of this here: https://www.patternfly.org/v4/components/alert/html#expandable

Arguably could just update the inline alert image to include one instance of an expandable inline alert. Then add an element number to it and describe it in one sentence.

**Background info**
See this design issue: https://github.com/patternfly/patternfly-design/issues/892
Core issues:
1. https://github.com/patternfly/patternfly/issues/4185
2. https://github.com/patternfly/patternfly/issues/4186

**Comment by wolfeallison** [comment]
Hey @mmenestr! Here is copy for the guidelines. Please let me know if you need anything else/have any comments or questions! Thanks! Expandable alert: Extends the alert and reveals additional information
