### ISSUE TITLE
Correction/comment about setup instruction on https://www.patternfly.org/get-started/setup/#_

### ISSUE THREAD

**Issue by wcohen** [patternfly/patternfly-org#258]
When attempting to setup patternfly on my Fedora 24 machine by following the instructions on https://www.patternfly.org/get-started/setup/#_  I ran into a couple issues.

1) My machine didn't have npm installed.  I initially tried "sudo yum install npm": 

$ sudo yum install npm
Yum command has been deprecated, redirecting to '/usr/bin/dnf install npm'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

Last metadata expiration check: 0:07:32 ago on Fri Aug 12 09:51:14 2016.
Error: package npm-3.5.4-5.fc24.noarch requires nodejs(engine), but none of the providers can be installed

I found that npm is in nodejs and "sudo yum install nodejs" addressed the lack of npm.

2)  "$ sudo install -g bower" looks like it should be "$ sudo npm install -g bower" in the instructions.

3) I was surprised when "bower init" seemed to ask a lot of questions.  I was assuming that it would just do some initialization in the directory without a bunch of prompting.  Some information about the questions it would ask and tips on appropriate things to put in there would be helpful.

4) It would be nice to have downloadable index.html file in addition to the screenshot of index.html to further lower the barrier to initially setting something up with patternfly.

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2016. Please let me know if this is still relevant and we will revisit.
