### ISSUE TITLE
After clicking on an AutoLinkHeader link icon, the right-side Table of Contents JumpLinks do not work

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-org#2615]
I noticed this while working on #2614. If you navigate to a specific section of a docs page using one of the permalinks created by `AutoLinkHeader`, e.g. https://www.patternfly.org/v4/components/slider#slider and then try to click one of the links in the table of contents on the right, they just scroll you to the top of the page instead of scrolling you to the matching section. These links behave normally if the URL does not have a hash.

cc @redallen

**Comment by redallen** [comment]
Yeah, I've noticed this too since we started using our own JumpLinks component. Not sure what's causing it, but it's probably in https://github.com/patternfly/patternfly-react.

**Comment by evwilkin** [comment]
@mturley @redallen I'm not seeing this behavior (video attached below), can you confirm these steps to recreate?  Thanks!

https://user-images.githubusercontent.com/8651509/128219300-9640ae43-a009-4eee-a339-bfdcbe457e8e.mov

**Comment by redallen** [comment]
@evwilkin Try clicking on an AutoLinkHeader first.
![bad-autolinks](https://user-images.githubusercontent.com/47335686/128220855-d716eeb8-2fbc-4767-8171-ea95e6e73b87.gif)

**Comment by mturley** [comment]
Huh that's odd, so it must have something to do with the click behavior on AutoLinkHeader and not the URL hash. Will update the title of the issue.
