### ISSUE TITLE
[Website] Accessibility Guide - broken link in Community page

### ISSUE THREAD

**Issue by paoloantinori** [patternfly/patternfly-org#2620]
Hi,
I need to report a broken link.

In the `Community` page, the link `Read our accessibility guide` points to https://www.patternfly.org/v4/developer-resources/accessibility-guide which does not resolve.

With the help of Google, I've managed to track an old copy of the Accessibility  Guide here: https://www.patternfly.org/2020.11/get-started/accessibility-guide  but I haven't managed to find any equivalent more recent link.

I would have open a PR myself to fix this but I'm not really sure where the link should be pointing at.

Side note:
I've been notified of the broken link by some accessibility experts who I was promoting the project to.

**Comment by evwilkin** [comment]
Thanks for reporting this @paoloantinori!  We now have an entire section of our navigation devoted to Accessibility, and we'll update the broken link to the first subcategory there ("Accessibility Fundamentals").

We're continuing to grow and improve our accessibility documentation, thanks for helping to promote this important area of focus 👍
