### ISSUE TITLE
TypeScript examples parser does not recognize `<>` type params passed into generic functions

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-org#2633]
In the TypeScript examples I'm working on, I'm passing generics into `useState` like this:

```ts
  // Index of the currently sorted column
  const [activeSortIndex, setActiveSortIndex] = React.useState<number | null>(null);
  // Sort direction of the currently sorted column
  const [activeSortDirection, setActiveSortDirection] = React.useState<'asc' | 'desc' | null>(null);
```

The docs site is rendering `ReferenceError: number is not defined` in this case. I tried to reproduce it with a more minimal example:

```ts
  function identity<T>(a: T) {
    return a;
  }

  const foo = identity<string>('foo');
```

Sure enough, this gives `ReferenceError: string is not defined`.

**Comment by mturley** [comment]
cc @redallen

**Comment by redallen** [comment]
This is a fun one... `f<ty>('foo')` is perfectly valid Javascript equivalent to `Boolean(f < ty > 'foo')`. The official `tsc` parser has special logic builtin to recognize the parentheses around `foo` as a function call rather than literal.

I'll see what I can do...
