### ISSUE TITLE
Fix axe-core issues

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-org#2663]
1. Jump links ul -> ul
2. Ensure that links with the same accessible name serve a similar purpose
  - Skip to content
  - PatternFly logo in top left
  - Open\ example\ in\ new\ window
3. Ensures landmarks are unique
  - `<nav class="ws-toc">`
  - Open example in CodeSandbox

**Comment by evwilkin** [comment]
Closing in favor of https://github.com/patternfly/patternfly-org/issues/2920
