### ISSUE TITLE
Add design usage, and api, documentation for the Select-validation component.

### ISSUE THREAD

**Issue by lclay2** [patternfly/patternfly-org#2701]
A dev team needed to know if one is required to use/show the “success” validation state (green w/check), when using the "Select#Validation component: https://www.patternfly.org/v4/components/select#validated - or is it okay to just use the error validation state? 

Response from PatternFly was that:
"there is no reason you must display the success icon. This was added to accommodate a use case where the user selects something that needs to be validated in the backend. It was a way to reflect that status back to the user that the validation had been completed. So it's designed for a pretty specific use case."

This is a request to add some basic design usage guidelines, along with API documentation, just to let folks know that you don't have to use the success presentation if you are using the component.

**Comment by mmenestr** [comment]
Draft here: https://docs.google.com/document/d/1NkZ0jSWWhaySUoeiHZJGr4OG12g53Aa0UKHfVdJ0e6g/edit

**Comment by mmenestr** [comment]
Note to self: Ready to create PR for

**Comment by lclay2** [comment]
@mcarrano , @mmenestr , the example Sketch file is on the share and is editable. I'll also share the link with you directly.
