### ISSUE TITLE
Add some guidelines about more info in a table cell

### ISSUE THREAD

**Issue by imjoyjean** [patternfly/patternfly-org#2711]
[Discussion doc on More information in a cell](https://docs.google.com/document/d/1CKrypNQLRr1nz3Mow8yckvotNlwVx_I5DOirFl4DkaQ/edit#heading=h.1vyp28uzhxwe)
Presented in PF design share, c.rh.c, OpenShift IxD, and ACM design reviews.

**Comment by imjoyjean** [comment]
Usage:

When showing multiple items in a cell, often times, space is limited depending on the number of columns shown. Try to show at least one item before hiding the rest of the items in a popover or modal. 

To truncate your list, use a grey clickable label for less visual distraction (as opposed to blue link) and indicate "_ more" to make it clear that there are more items to look at. 

- If you have less than 7 items more to show: use a popover to contain the rest of the items
- If you have more than 7 items to show: use a modal with a search bar to contain all of the items 

Example screenshots of using a clickable grey label and popover : ![image.png](https://images.zenhubusercontent.com/5e67cd4447fbdecd648558bc/230d1fde-1eac-405d-98ec-0a26473824ff)

Example screenshot of a modal: ![image.png](https://images.zenhubusercontent.com/5e67cd4447fbdecd648558bc/d6a03349-c2d0-4982-aaa7-cdcd0d6da59d)

[Marvel prototype link ](https://marvelapp.com/prototype/8b74jc1/screen/81921197)

FYI @mmenestr

**Comment by mmenestr** [comment]
Justin working on this issue in this document: https://docs.google.com/document/d/1-aAzXXgGPyWQNNZecWT5sN26yjyrRn81pdnxSCzyRF8/edit
Thinking about publishing these under the new "Patterns" section that will be introduced on the PF website.

**Comment by JustinXHale** [comment]
@imjoyjean Have you considered storing this in a drawer so that the user doesn't necessarily have to leave the table?

**Comment by JustinXHale** [comment]
@imjoyjean I think Option 2 is really good for the fact the the user still sees the table and is able to navigate to different sections. It could also have a search within the section.

**Comment by mmenestr** [comment]
Decided to add this guidance to the tables design guidelines. Can add a section in the Usage section, and H3 that is labeled "Showing more information in a table cell"

**Comment by mmenestr** [comment]
Addressed in this PR - closing
https://github.com/patternfly/patternfly-org/pull/3779
