### ISSUE TITLE
Add guidance on secondary action dropdowns

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2724]
Refer to this issue for details: https://github.com/patternfly/patternfly-design/issues/1038#issuecomment-940078919

Could add to dropdown guidelines and/or toolbar guidelines about this.

See demos of these action buttons here: https://www.patternfly.org/v4/components/dropdown#primary-toggle

https://github.com/patternfly/patternfly/issues/4434

**Comment by lclay2** [comment]
@mmenestr  
I created a first draft, please let me know what you think, thanks!
https://docs.google.com/document/d/1ueoZGUkP8brLCzBXzyDoNvnehZ5zNmcsN7FICvHAM_o/edit?usp=sharing

**Comment by lclay2** [comment]
@mmenestr , I updated the "dropdown-variants" image in Sketch.

**Comment by mmenestr** [comment]
Note to self: Ready to create a PR for (images are in Design doc assets file)
