### ISSUE TITLE
Add mention of compact label in label guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2725]
[ALREADY ASSIGNED!!] 
There is a new variation of labels called "compact labels" that was just added to PF. We want to add a section in the label guidelines to point out this variation of labels and discuss when they should be used over the default (bigger) labels. 

Examples of compact labels can be found here: https://www.patternfly.org/v4/components/label#compact

Refer to this issue for more background as to why compact labels are needed: https://github.com/patternfly/patternfly-design/issues/1048#issuecomment-940087689

**Comment by mmenestr** [comment]
@Burundi

**Comment by blfetche** [comment]
Labels document has been updated with compact labels awaiting edittable lables completion 

https://docs.google.com/document/d/1xv5szTvPDjZZwupgd8jmfJr8u73x8uJ8QeIeimiYKm4/edit#

**Comment by blfetche** [comment]
PR has been submitted and recent changes have been applied.

PR
https://github.com/patternfly/patternfly-org/pull/2882

Design Preview
https://patternfly-org-pr-2882-v4.surge.sh/v4/components/label/design-guidelines

**Comment by mmenestr** [comment]
Closed with this PR: https://github.com/patternfly/patternfly-org/pull/2882
