### ISSUE TITLE
Add to pagination guidelines: fact that you can replace total page count with "many"

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2729]
Refer to this issue for details: https://github.com/patternfly/patternfly-design/issues/1025

**Comment by doruskova** [comment]
@mmenestr Here's the update on this issue. Let me know if I can open a PR :) https://docs.google.com/document/d/1dVbi8ClcEb1kjaGfGxhixbGIvPey3zrMNpXCXHMX6Os/edit?usp=sharing
