### ISSUE TITLE
codesandbox link not working when example loads other files

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-org#2737]
example: https://www.patternfly.org/v4/demos/primary-detail
which loads DashboardWrapper.js
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/demos/examples/DashboardWrapper.js

**Comment by evwilkin** [comment]
Related issue #2705

**Comment by jschuler** [comment]
This is where the files are added that get pushed to codesandbox: https://github.com/patternfly/patternfly-org/blob/68fd0154837b578553d59d3d04f874334953a370/packages/theme-patternfly-org/helpers/codesandbox.js#L153

**Comment by nicolethoen** [comment]
FWIW - the primary culprit here is pf-react's dashboardwrapper used to build most of our full page demos. I know that Core actually reuses one of its page layout examples in its other full page demos. Is that something we could enable on the react side as well?
