### ISSUE TITLE
Extra menu on Code tab of List View page

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#274]
There is an extra HTML/CSS - AngularJS menu on the List View page code tab. One has AngularJS enabled; the other has it disabled. http://www.patternfly.org/pattern-library/content-views/list-view/#/_code

**Comment by cardosogabriel** [comment]
Thanks for the report @srambach . I fixed it 2 days ago in this PR: https://github.com/patternfly/patternfly-org/pull/271

Should go live soon.
