### ISSUE TITLE
Tooltips for colors on color palette are not dismissable

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly-org#275]
Clicking on a color block in the swatch section of the color palette page brings up a tooltip showing the variable name and the hex value. There is no way to dismiss the tooltip after it is displayed.

**Comment by dlabrecq** [comment]
Click on the color again to dismiss, but not certain this was intended @kybaker?

**Comment by LHinson** [comment]
@dabeng similar to field level help, can you make the tooltip dismissible when you click other places on the screen? See: http://www.patternfly.org/pattern-library/forms-and-controls/help-on-forms/#code
