### ISSUE TITLE
Create guidelines for text input group component

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2759]
Guidelines for this demo basically: https://www.patternfly.org/v4/components/text-input-group/react-demos
Original issue + background here: https://github.com/patternfly/patternfly-design/issues/1088

Would add design guidelines to [text input group component](https://www.patternfly.org/v4/components/text-input-group). 

The text input group component essentially does the same thing as an attribute-value filter, except that a user can type it all in/select attribute value pairs inside of a text input.

**Comment by mcarrano** [comment]
Yes. It's built on top of a text input but adds custom capabilities like allowing chips to be placed inside the field. It's one of those components that's created to work around certain technical constraints that might not mean much to designers.
