### ISSUE TITLE
Errant "</div>" at bottom of List View page

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-org#276]
At the bottom of https://www.patternfly.org/pattern-library/content-views/list-view, I noticed an errant "&lt;/div&gt;".

<img width="226" alt="screen shot 2016-08-30 at 1 03 04 pm" src="https://cloud.githubusercontent.com/assets/895728/18098934/58b891ea-6eb2-11e6-885e-bd53eb068741.PNG">

**Comment by cardosogabriel** [comment]
This was fixed here: https://github.com/patternfly/patternfly-org/pull/271
