### ISSUE TITLE
Multiple quaternary navbars display on Code tab of List View page

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-org#277]
On https://www.patternfly.org/pattern-library/content-views/list-view/#/_code, the HTML/CSS and AngularJS tabs appear twice.

![screen shot 2016-08-30 at 1 08 39 pm](https://cloud.githubusercontent.com/assets/895728/18099140/2bdee894-6eb3-11e6-8c4d-2e7d0164bc3d.PNG)

**Comment by cardosogabriel** [comment]
Also fixed here: https://github.com/patternfly/patternfly-org/pull/271
Thanks for reporting.
