### ISSUE TITLE
IA study - research follow-up

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#2789]
Card sorting study for website information architecture (IA) review wrapped up in late November.  Next steps are to reengage with the UXD research team to source recommendations for improvements to the website docs & organization based, and to create a sustainable plan for maintaining the site moving forward to avoid uncontrolled bloat.

**Comment by evwilkin** [comment]
Amber has kicked off planning for this project, to begin in early 2022.

**Comment by evwilkin** [comment]
Ivan is conducting user interviews this month with goal to wrap study & share findings in April ([timeline document here](https://docs.google.com/document/d/1d2IpoCxz74Q4FSyZGo17DwMUIBDFnSmfCkFVWIsm8BU/edit#heading=h.wdw7w4ych8tb)).

**Comment by mcarrano** [comment]
IA study is complete. Findings report here: https://docs.google.com/presentation/d/1l0RFGJr76VCgB-6P0fJLvOBy1kz-Omava9VtvxZuyAo/edit?usp=sharing Follow-up meeting scheduled for Apr 6 to discuss website roadmap and next steps.

**Comment by mcarrano** [comment]
A follow up issue has been opened here: https://github.com/patternfly/patternfly-design/issues/1141  Will close.
