### ISSUE TITLE
Review and update content on Spacers page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2859]
In working on the Typography page, I revisited the [Spacers page](https://www.patternfly.org/v4/guidelines/spacers) with @mcoker and we concluded some of the content does not make sense. Specifically, the section at the end seemed confusing and it was unclear who this information is targeted toward. We should revisit and revise as necessary.

**Comment by mmenestr** [comment]
maybe meet with stakeholders to see what should be done here + relationship with layouts too
Lucia, Michael and Michael

**Comment by mmenestr** [comment]
Not sure what this issue was referring to exactly, but @edonehoo @lboehling maybe we can revisit this as part of PF6 org updates!

**Comment by mcarrano** [comment]
I can't remember exactly what the issues were here, but it came up in a conversation with @mcoker about the content that is included here: https://www.patternfly.org/design-foundations/spacers#using-spacers-with-text It was not making sense to us and was unclear who this information was for.

**Comment by edonehoo** [comment]
this page was updated by https://github.com/patternfly/patternfly-org/issues/4130
