### ISSUE TITLE
Vertical Navigation: missing reference code

### ISSUE THREAD

**Issue by sfranzen** [patternfly/patternfly-org#286]
On the [Vertical Navigation](https://www.patternfly.org/pattern-library/navigation/vertical-navigation/#_overview) overview page, there are screenshots of three design examples (Masthead and Primary with/without icons). Only the latter two have corresponding code examples. Would it be possible to also add code for the first one?

**Comment by anx-ckreuzberger** [comment]
Also noticed this. +1

**Comment by Roupraih** [comment]
+1

**Comment by LHinson** [comment]
Yeah, we can get this posted. In the meantime, you can reference just primary here: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/vertical-navigation-primary-only.html

**Comment by dabeng** [comment]
The associated [PR](https://github.com/patternfly/patternfly-org/pull/593) has been sent.

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2018. Please let me know if this is still relevant and we will revisit.
