### ISSUE TITLE
Setting Up Patternfly should reference npm instead of bower

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-org#288]
Now that the Patternfly readme has been updated to remove all references to bower dependencies, the Setting Up Patternfly guide should also be updated to use npm instead of bower.

http://www.patternfly.org/get-started/setup/index.html
https://github.com/patternfly/patternfly/blob/master/README.md

**Comment by priley86** [comment]
+1, I noted this as well and suggested it in the initial PR. I think this would be good to suggest the use of NPM downstream instead of Bower (although it's not completely necessary).

**Comment by bleathem** [comment]
Closing as this has been resolved.
