### ISSUE TITLE
Add Quick start docs from quick starts repo to extensions docs

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#2883]
Towards epic #2903 

Add the [quick starts](https://github.com/patternfly/patternfly-quickstarts) documentation to the PatternFly site

**Comment by evwilkin** [comment]
Mockup from @mcarrano of how extensions docs could look using [expandable third level navigation](https://www.patternfly.org/v4/components/navigation/#expandable-third-level) (Catalog View shown in mockup):
![image](https://user-images.githubusercontent.com/8651509/161833427-12072f2e-9115-4375-9e0e-d339aae2c3d9.png)
