### ISSUE TITLE
Add "decision tree" to charting guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2886]
[THINKING OF ASSIGNING TO TINA - NOT UP FOR GRABS]

Would add it here: https://www.patternfly.org/v4/charts/about
Make a PatternFlied version of this kind of graphic to include in our design guidelines:

![image (93).png](https://images.zenhubusercontent.com/5e750f70a086dc7bdce718bd/540071be-ae60-4786-9e1f-6d66d8fd5998)

**Comment by tiyiprh** [comment]
Some typos on individual chart design guideline pages:

https://www.patternfly.org/v4/charts/area-chart/design-guidelines
![Area Chart Design Guidelines](https://user-images.githubusercontent.com/98424339/163018098-60106688-05f6-416e-8fdb-8dd213bd180f.png)


https://www.patternfly.org/v4/charts/bar-chart/design-guidelines
![Bar Chart Design Guidelines](https://user-images.githubusercontent.com/98424339/163018106-e16fb229-cca8-4d94-a891-d91c13d29e2a.png)
