### ISSUE TITLE
Update Icons on website

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2894]
We have recently added a new icon called "pficon-critical-risk" This has been added to core and React and requires updates to appear on the Icons page of the website (I think?). 

PR updating the icon-svgs.zip file: https://github.com/patternfly/patternfly-design/pull/1145

**Comment by mcarrano** [comment]
@evwilkin We have added a new icon per the process outlined. As a last step I'm not sure what, if anything, need's to be done to update the website. Marie's PR updates the .zip file stored in the design repo. Can you take a look when you get a chance?

**Comment by mcarrano** [comment]
@doruskova do you have time to do this? The updates would need to be in the Org repo. Otherwise I should be able to take it on.

**Comment by doruskova** [comment]
@mcarrano @evwilkin  I can update it :)

**Comment by evwilkin** [comment]
Closed in #2897
