### ISSUE TITLE
Version switcher - "latest" version link doesn't seem to work

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#2904]
If you switch to a previous release version, then switch back to the "latest" release, the link for "latest" takes you to whatever previous version you chose/are currently on instead of the latest release version.

**Comment by evwilkin** [comment]
After investigating, suspect one of two culprits:

1. The network call retrieving versions.json after switching to older version looks to return the versions.json from that release, indicating that the selected version is the `latest` version and [triggering this path](https://github.com/patternfly/patternfly-org/blob/main/packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js#L43) to switch from `v4` to the selected version number.
2. If the latest version is populated correct, [writeVersionPrefix file](https://github.com/patternfly/patternfly-org/blob/main/scripts/writeVersionPrefix.js#L15) may be replacing the `/v4`with the version number.

**Comment by evwilkin** [comment]
Related previous issue: https://github.com/patternfly/patternfly-org/pull/2257
