### ISSUE TITLE
Bug - Login documentation should specify 'Log in' is 2 words in tooltip

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#2913]
Content made a recommendation: "If you do choose to add it, I recommend changing it to "Log in" (2 words when describing the action of logging in) to keep consistency on the page"

our design guidelines should clarify that.

We had a product recommend an additional pattern to further clarify this. Is it worth adding as well @mmenestr?
![image (7)](https://user-images.githubusercontent.com/26305082/163199780-d4a7f163-2192-4b91-a246-c157ed9c5294.png)

**Comment by mmenestr** [comment]
Are you saying we should clarify when to use "log in" vs "login" in our design guidelines? 
Or what is the additional pattern you're talking about? I'm a little confused haha

**Comment by nicolethoen** [comment]
yes I think we should use "log in" instead of "login" per @wolfeallison's recommendation.

But also the pattern in the screenshot I linked doesn't just use the third party logos, but puts the tooltip text in the button. I figured to at least document the suggestion in the issue. It can be up do design if it's a worthwhile addition to the design guidelines in general.

**Comment by nicolethoen** [comment]
@mmenestr I updated the screenshot of the proposed alternate pattern.

**Comment by trahman73** [comment]
Here is an example for Ansible's use case of having multiple GitHub log in options. I'm using the PatternFly split button dropdown component in the updated mockup below.

![image](https://user-images.githubusercontent.com/13351591/163230013-9578b41c-0ed7-4d8a-8cf1-3c53f29d7714.png)

**Comment by ajacobs21e** [comment]
![image](https://user-images.githubusercontent.com/6415742/163249686-e8e5284c-c388-4fc7-90bc-6b0d0bfcc05a.png)
This is how we are showing social login icons for CIAM. One concern I have with these larger buttons with text is that it would take up 4 rows to show all of these icons, pushing the 'Register' and 'Forgot password' links further down.

One nitpick - "In" should be lowercase in all of the examples.

**Comment by ajacobs21e** [comment]
Here is another option to add to PF if there are 5+ social logins

![image](https://user-images.githubusercontent.com/6415742/163261644-ef9130b8-956c-4887-a2e2-0cf064828f4e.png)

**Comment by ajacobs21e** [comment]
It seems like there are two topics in this issue:
1) "Login" vs "Log in" usage
2) Social login button design

@nicolethoen should we split this into two issues?

**Comment by nicolethoen** [comment]
We could! I might even suggest that the issue to discuss social login button design be opened in the design repo rather than org.

**Comment by AlexSCorey** [comment]
Just a reminder that github has several different authentication options (organizations, teams, enterprise etc)  and for some of our users they might need more than 1 of those github options so I feel like [this mock up](https://github.com/patternfly/patternfly-org/issues/2913#issuecomment-1098269321) is the only option presented that helps resolve that problem

**Comment by nicolethoen** [comment]
sure @mmenestr, I'll open a follow up issue in the design repo? and close this.
