### ISSUE TITLE
Accessibility report - build & display on patternfly.org

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#2918]
We should publicly display the accessibility status of patternfly.org on the website and regularly update that information to track progress.
- Which format should the report be in to be user friendly but also comprehensive?
- Where should this live?
  - This could live on the [PatternFly's accessibility](https://www.patternfly.org/v4/accessibility/patternflys-accessibility) page and be updated with each release, with links from the release notes and being able to view previous reports using the dropdown version switcher

**Comment by mcarrano** [comment]
@evwilkin @nicolethoen do you have a sample of what this looks like now?

**Comment by nicolethoen** [comment]
https://docs.google.com/document/d/1stdDUUfJKAUGqSt2TBkfiAacQvKrgD-dToh0gMMv8nA/edit

**Comment by mcarrano** [comment]
@nicolethoen @evwilkin I agree that this makes sense to add the the [PatternFly's Accessibility page](https://www.patternfly.org/v4/accessibility/patternflys-accessibility). I can propose a design for this. We could put this information into a PatternFly table, but just a question about how this would be maintained. Would the intent be to populate from some other report? Update manually? If the later, would be want this in Markdown (although formatting of Markdown tables is pretty limited)?

**Comment by nicolethoen** [comment]
This is a report that would be rerun and updated periodically. It represents a snapshot of the state of org's accessibility on a specific date, so it could be regenerated whenever we want.

**Comment by evwilkin** [comment]
I'd say that either way we can build it using PF components rather than be limited to markdown.  It shouldn't be too much to update periodically, and ideally we can build it in a way that we can just feed in the updated data when needed.

**Comment by mcarrano** [comment]
@evwilkin @nicolethoen that all makes sense. Let me know what, if anything, you need from design in that case. Seems like you could just flow this information into a table and add to the page. If you want something more visually attractive I could queue this up for a visual designer to look at, but not sure it's worth the effort.
