### ISSUE TITLE
Add guidance on horizontal tab overflow in mobile

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2933]
Add documentation for horizontal tab overflow approach as documented in the design issue here: https://github.com/patternfly/patternfly-design/issues/1034

Core issue: https://github.com/patternfly/patternfly/issues/4800

**Comment by mmenestr** [comment]
Waiting on implementation: https://github.com/patternfly/patternfly/issues/4800

**Comment by doruskova** [comment]
Implementation https://github.com/patternfly/patternfly-react/issues/7479
