### ISSUE TITLE
Create template for demo page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2935]
When website users are viewing a demo on the website, it needs to be clear that this is a demo vs a component and what it means to be a demo. We should also link to components that are used by this demo.

**Comment by mcarrano** [comment]
@wolfeallison I've opened this new issue to track the work on a demo template that we discussed in the meeting today. I'll set up some time to talk more about what this page might look like.

**Comment by mcarrano** [comment]
See some additional design ideas here: https://docs.google.com/presentation/d/1K-VBEwKtTMVnwvRxrjvSBOx-9jsdaAubm9V2ZeOt-sI/edit#slide=id.g11cb600055a_0_0 It would be great if we can have a common set of demos between core and React that share a common description letting the user toggle between core and React versions of the demo.

Can we investigate feasibility of this?

**Comment by edonehoo** [comment]
Closing -- our demos onsite are now marked with a purple label! Let me know if you have questions or concerns.
