### ISSUE TITLE
Bug - Jumplinks have transparent background and page shows through

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#2948]
**Describe the problem**
When the jumplinks move into the dropdown above the page at a narrow width, the background color is transparent and the page content shows through them.

**Expected behavior**
In the [jumplinks demo](https://www.patternfly.org/v4/components/jump-links/react-demos/scrollspy-with-subsections/), the collapsed jumplinks are contained in a page section, which provides the background.

**Screenshots**
![image](https://user-images.githubusercontent.com/19825616/165785709-71562a1c-f6cc-4db8-b9bb-6d1d38698dcb.png)

**Any other information?**
This is possibly related to #2941 as well.

**Comment by evwilkin** [comment]
Workspace styles are being overridden - also the "Table of contents" text `.pf-c-jump-links__toggle-text` is missing.

**Comment by evwilkin** [comment]
Fixed by https://github.com/patternfly/patternfly-org/pull/3033
