### ISSUE TITLE
pfToolbar Angular directive should be included in Toolbar

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-org#297]
Although documentation and HTML/CSS code exists for the Toolbar pattern (https://www.patternfly.org/pattern-library/forms-and-controls/toolbar/#_overview), the Angular implementation is missing.  The pfToolbar directive can be found here: http://angular-patternfly.rhcloud.com/#/api/patternfly.toolbars.directive:pfToolbar.  Can we get this added to the site?  If there is an issue with implementation, can you let myself or @jeff-phillips-18 know?

**Comment by LHinson** [comment]
Closing this issue as the angular implementation is now linked in https://www.patternfly.org/pattern-library/forms-and-controls/toolbar/#code
