### ISSUE TITLE
Update images of calendar picker across design guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#2973]
Update images in [date picker](https://www.patternfly.org/v4/components/date-picker) and [calendar month](https://www.patternfly.org/v4/components/calendar-month/design-guidelines) guidelines to have the date picker use carets instead of arrows.

Refer to this issue for background: https://github.com/patternfly/patternfly/pull/4862

**Comment by doruskova** [comment]
@mmenestr Can I take this issue?

**Comment by mmenestr** [comment]
@doruskova yes! Just assigned you, ty!!
