### ISSUE TITLE
Component catalog page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#2992]
Create a new page that allows users to browse components in a card/catalog view. See designs here: https://marvelapp.com/prototype/hjbd30h/screen/86590461

**Comment by maryshak1996** [comment]
After chatting through some feedback, we are proposing the following changes (reflected in the [sketch link](https://www.sketch.com/s/7bec720b-7f77-4f22-99a1-a48735c0b147) and screenshots below)

- Provide a catalog view and list view switcher
- Remove the side panel and have card clicks direct right to the component page

**Comment by maryshak1996** [comment]
Card view
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/19824574/201135691-d3bfd176-eeb7-415d-96a9-84003c3142bd.png">

List view
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/19824574/201135750-53a6a00f-8afa-496c-9f7d-23c1812dc056.png">
