### ISSUE TITLE
Add guildelines for success/failure pie charts

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-org#3021]
As a developer, I want to see more design guidelines for charts. As an example, consider providing guidelines for a red/green pie chart representing success/failure states. Don't necessarily need more examples showing how to create a chart, but a guide as to when to use this type of chart, what colors are recommended, and when to use patterns, etc.

**Comment by dlabrecq** [comment]
About a year ago, Ethan Kim was working to solve a color contrast issue with the donut chart. Basically, products are using donut charts, and custom colors, to represent alerts; where green represents success and red for failure.

The original design issue can be found here https://github.com/patternfly/patternfly-design/issues/1136.

The solution was to make patterns available to charts. However, Ethan, Matt Carrano, and Michael Celedonia also discussed creating guidelines to describe when to use color combinations in charts Vs when to use the new patterns. While Ethan worked on guidelines, I created this issue as a placeholder.

The available chart patterns can be seen at https://www.patternfly.org/v4/charts/patterns. We're just missing some guidelines.

**Comment by mmenestr** [comment]
Document with draft: https://docs.google.com/document/d/1DgQdUJ9tLCfLCrLna6_-7wiAkHPwqF5C1RANO2XrLvQ/edit
