### ISSUE TITLE
Update docs to include component prop interface comments

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly-org#3041]
As a developer, I want to have more context regarding the component properties shown in the examples. That is, the components shown via `propComponents`.

As an example, consider the optional `ChartGroup` component. Although, we show `ChartGroup` properties [here](http://patternfly-react-main.surge.sh/charts/area-chart#chartgroup.), there is no further documentation. If the props also included a description, I believe it would help clarify how components are used.

While debugging, I confirmed that `ChartGroupProps` comments are available in the `getInterfaceMetadata` function of `theme-patternfly-org/scripts/tsDocgen.js`. Since the comments are already being read, the docs generator could include these comments with the component props output in the example -- perhaps with a flag to enable it?

**Comment by nicolethoen** [comment]
@mcarrano @mmenestr do you have any thoughts about the appearance/format of component descriptions being added above the related component prop tables?

**Comment by nicolethoen** [comment]
@jschuler @CooperRedhat @cdcabrera @wise-king-sullyman @evwilkin  this is likely something to consider during the theme reworking.

**Comment by jschuler** [comment]
Fixed in https://github.com/patternfly/patternfly-org/pull/3033
Parsing and adding interface jsdoc description as a table caption above the props table.
