### ISSUE TITLE
Add new Patterns section to the website

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3094]
Want to introduce a new primary nav section called "Patterns." This will contain design documentation to provide conventions around more complex patterns that contain multiple components. Patterns may or may not have associated demos. If a demo does exist it will live on a separate tab following the Design guidelines for that pattern.

Existing pages and demos that should move to the Patterns section include:

https://www.patternfly.org/v4/demos/card-view
https://www.patternfly.org/v4/demos/dashboard
https://www.patternfly.org/v4/demos/primary-detail
https://www.patternfly.org/v4/guidelines/bulk-selection
https://www.patternfly.org/v4/guidelines/filters

**Comment by mcarrano** [comment]
@evwilkin @nicolethoen @mmenestr I've been thinking about this more and wanted to propose a slightly different approach. What if we just update the existing "Demos" section to be "Patterns" and add the design guidelines for Filters and Bulk Selection there (move from Guidelines)?

I think that's both an easier change and also replaces "Demos" in the left nav rather than adding yet another main section. Demos would still exist for components where applicable. As a follow-up, we should move some of the existing demos, like Password generator, for example, to Components which is where users expect to find those. But I might hold on that until we release V5 to avoid too much confusion.

What do you all think?

**Comment by nicolethoen** [comment]
sounds reasonable to me. we just need to be sure we track which demos would move out of the Pattern's section - since that will take a coordinated update in core/react/org to do it correctly.

**Comment by mmenestr** [comment]
I don't have a problem with that! Though I agree some of the current demos should live under components instead because they don't quite fit the "Pattern" idea. Also, we should probably think about more officially defining what would be considered a Pattern

**Comment by mcarrano** [comment]
This is being addressed as part of #3095
