### ISSUE TITLE
Re-create tile image that is currently a screenshot

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3115]
![image.png](https://images.zenhubusercontent.com/5e750f70a086dc7bdce718bd/a642e518-d6d3-4ec2-94ba-ba3480163a86)

Re-create this image in sketch and sub it out in the tile guidelines

**Comment by doruskova** [comment]
@mmenestr Can I take this issue? :))

**Comment by mmenestr** [comment]
@doruskova Yes :D
