### ISSUE TITLE
Add information about wireframe kit to designer Get Started page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3118]
Want to add information about the Sketch wireframe library to the [Design with PatternFly page](https://www.patternfly.org/v4/get-started/design) on the website. This is is summarized in the Google doc here: https://docs.google.com/document/d/1W70DOlbpniwoYIFm2RqxBWItIBXJIP1hLVzUbL2A4Qs/edit?usp=sharing

Want to add a link to the Sketch library and documentation. Documentation location is still TBD.

**Comment by cntlsn** [comment]
As per conversation offline:
- For security reasons, the google doc linked above is only available to Red Hat associates -- Shall the content be extracted and included with the documentation already existing on the [Design with PatternFly page](https://www.patternfly.org/v4/get-started/design) page? (Note: some of the content is overlapping, so it will only be a subset of the original document that would need to be included)
- The recommended place to store the Wireframe library is the https://github.com/patternfly/patternfly-design-kit repository, shall we add a short version of the documentation to the README file of the such repo?

**Comment by mcarrano** [comment]
@cntlsn It may be that including a shortened version of this to the Readme in the design kit repo is the best solution. I don't think we want to add all of this content to the website directly. @doruskova @mmenestr what do you think.

**Comment by mmenestr** [comment]
I agree^

**Comment by cntlsn** [comment]
Here is the insight on the documentation from the research study: _Consider consolidation of lo/mid fi documentation into the high fidelity documentation in order to increase findability/reduce ‘scattering’._

So I would say whatever makes the most sense to you would do the job, as long as the Wireframe documentation is clearly and easily reachable from the PatternFly documentation. Thank you ;)

**Comment by doruskova** [comment]
@mcarrano @cntlsn Do I understand correctly that the documentation should be accessible from the design-kit README doc? Not from the PF website?

**Comment by mcarrano** [comment]
Yes. We will add a link on the designer's Get Started page once the documentation is available in the repo.

**Comment by cntlsn** [comment]
Hi @mcarrano @doruskova @mmenestr, let me summarize here a couple of conversations that happened today on different channels:
- The PatternFly Wireframe library and template `.sketch` files have been uploaded to the repo (thanks @doruskova !)
- A revised version of the PF Wireframe kit documentation will be exported (eg. as a `.pdf`) and added to the same repo folder where the `.sketch` files live
- With regard to the repo `README` file
  - we would include links to the Wireframe lib and template `.sketch` files in the introductory paragraph under the "PatternFly Design Kit" heading
  - we would add a new section to the `README` including a one-paragraph overview of the Wireframe kit, a paragraph explaining that the instructions included in the repo apply to the Wireframe kit as well, and a link to the documentation file hosted in the repo
- With regard to the `.org` static website, we would add a section to the [Get Started > Design](https://www.patternfly.org/v4/get-started/design) page featuring a high-level overview of what the Wireframe kit is and a link to this repo

Is everybody happy with the above proposal?
How can the PF Wireframe team help with this effort?

Thank you.

**Comment by doruskova** [comment]
@mcarrano @cntlsn I've created a new folder for the Wireframe kit and uploaded the library and a template file. I also updated README doc in the patternfly-design kit to let people know about the Wireframe kit and I created a guideline in markdown that comes from Alessandro's doc https://github.com/patternfly/patternfly-design-kit/blob/master/PatternFly%204%20-%20Wireframe%20library%20and%20template/Wireframe%20kit%20guideline.md

**Comment by mcarrano** [comment]
@doruskova This looks great! Thanks for turning it around so quickly. @cntlsn perhaps give it a review and let us know if everything is as you expect. We will address the additional link from the Get Started page of the website as a separate issue/update.

**Comment by mmenestr** [comment]
This looks great!!! My only comment/concern is that we now have a section called "Wireframe kit"  in the ReadMe doc but not a section for the other two kits, so it looks like the whole readme doc is referring to the wireframe kit when it's not.

Idk if we should add two mini sub section for the Symbol library "kit" and the template library "kit" ? or if that even makes sense, but let me know your thoughts!

**Comment by doruskova** [comment]
@mmenestr This guideline is related only to the Wireframe kit and this markdown doc is a nested file in the Wireframe folder. The official README doc includes general info about the Design kit and mentions shortly Wireframe library. There is also a link to a full guide. 
Here's the README doc https://github.com/patternfly/patternfly-design-kit
Here's the full Wireframe guideline https://github.com/patternfly/patternfly-design-kit/tree/master/PatternFly%204%20-%20Wireframe%20library%20and%20template

I didn't want to include all info in README doc because it shouldn't be only about wireframe kit :))

**Comment by doruskova** [comment]
Updated the README doc based on @mmenestr feedback :))

**Comment by cntlsn** [comment]
@mcarrano 
We have updated the Wireframe sketch files and documentation. Thanks to @doruskova 's effort everything is ready to be published officially on the .org website.

In https://github.com/patternfly/patternfly-org/issues/3118#issuecomment-1245789134 you mention that the work to add info and links to the Wireframe kit on the .org website can be a separate issue, but according to the title and description of this same issue it looks like the original purpose was to address the changes on the .org site, please check https://github.com/patternfly/patternfly-org/issues/3118#issue-1330348829

Whatever you decide in terms of tracking that last piece of work, we'd be happy to assist you with anything (content, etc) that could speed up the process. Thank you!
