### ISSUE TITLE
Links in jump links should update URL

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#3120]
Since the links in jump links are links that anchor you to an element on the page, should they update the URL as you click on them? I would expect them to, just like clicking on the little anchor link by a heading on the page (the links look identical). That also enables the ability to go back and forward, and when you click on a jump link, you can copy the URL in the address bar to share the URL for a particular example.

**Comment by jenny-s51** [comment]
Closing as this is now the default behavior on the PF5 site.
