### ISSUE TITLE
Do Audit of images in design guidelines that have a search input

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3163]
We have recently made sure that all search input variations use the variations shown in the PF Search Input page https://www.patternfly.org/v4/components/search-input/.

Example: Toolbar guidelines still use old input group variation of a search input which we've stopped using now.

**Comment by doruskova** [comment]
@mmenestr Can I take this issue?

**Comment by doruskova** [comment]
List of components that needs to be updated: [doc link](https://docs.google.com/document/d/1r-XYQpzVbazKCMyCRQbpyvKes4MhvyaQnPYnzxTVGhM/edit?usp=sharing)
