### ISSUE TITLE
Extract Log Viewer and update org extension docs accordingly

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#3185]
- extract the Log Viewer package from the PF React repo
- restructure Log Viewer docs with patternflly-docs
- update org accordingly to keep Log Viewer docs being displayed properly

**Comment by jessiehuff** [comment]
log viewer has been extracted here: https://github.com/patternfly/react-log-viewer
However, org still needs to be updated

**Comment by jessiehuff** [comment]
org PR: https://github.com/patternfly/patternfly-org/pull/3365
