### ISSUE TITLE
Bug - Navigation broken in Safari 16 on iOS 16 and macOS 12.6

### ISSUE THREAD

**Issue by rhwood** [patternfly/patternfly-org#3199]
**Describe the problem**
Navigation menus do not work on Safari 16 on iOS 16 and macOS 12.6. It appears that Safari is rejecting the JavaScript for navigation with 

```
SyntaxError: Invalid regular expression: invalid group specifier name
```
in an anonymous function in line 1 of the web packed Javascript (so I don't have anything more specific)

**Expected behavior**
Navigation works and there is no error

**Screenshots**
N/A

**Any other information?**
It appears that anything/everything that relies on the Javascript to function is broken including search and popup menus. https://pf4.patternfly.org is having the same issue.

**Comment by nicolethoen** [comment]
Closed by PR #3205
