### ISSUE TITLE
Add guidelines around Acronyms and referring to products in marketing materials

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3207]
Created on behalf of @arburka

**Is this a new component or an extension of an existing one?**
Extension of documentation of acronyms
https://www.patternfly.org/v4/ux-writing/terminology/#abbreviations-and-acronyms

**Describe the feature**
Add additional information related to what Josh describes in Slack
Josh
[5 hours ago](https://rhux.slack.com/archives/CQVFVCN2G/p1663858105877969?thread_ts=1663600577.207609&cid=CQVFVCN2G)
Stepping into this late, but I think it also should depend on how the company refers to itself in its own marketing materials. E.g. If you go to [Amazon's AWS website](https://aws.amazon.com/), the acronym AWS is everywhere, whereas if you go to the [Google Cloud website](https://cloud.google.com/), GCP is nowhere to be found. Looking at the Google website, it seems they primarily call their product "Google Cloud"

https://rhux.slack.com/archives/D0237NQLZ71/p1663876512688479

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**
Nope!

Any other information?
@wolfeallison @kaedward @abigaeljamie

**Comment by mmenestr** [comment]
That looks good! I would just maybe include something about referring to a company the way they refer to themselves? 
@arburka thoughts?

**Comment by arburka** [comment]
I agree with both statements @mmenestr. 

When considering whether or not to use an acronym:
1 - Never make up an abbreviation, only use if there is evidence of the company doing so.
2 - Use your best judgement and Err on the side of how the company tends to refer to itself.
3 - Make sure we are consistent in how we refer to a company across our products if possible.

**Comment by kaedward** [comment]
I tried to consolidate all the info above, wdyt?

"When referring to a product or product component, do not use abbreviations unless the company that owns the product has established that abbreviation in marketing content or other official documentation. Default to using language that the company tends to use to refer to its products, and never make up an abbreviation or acronym yourself."

@mmenestr @arburka @wolfeallison

**Comment by wolfeallison** [comment]
I like it @kaedward ! I tried to make it a bit more concise, but I think your copy works too! 

"When referring to a product, default to how the company refers to its own product. Only use an abbreviation that has already been established and never make up an abbreviation or acronym yourself to help keep consistency across all products."

**Comment by arburka** [comment]
I like it! Thank you both!

**Comment by mmenestr** [comment]
I like it too! Feel free to create a PR for this whenever you get a chance!
