### ISSUE TITLE
Remove Red Hat font page

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#3210]
re: https://github.com/patternfly/patternfly/issues/5114

A breaking change follow up from the core issue. We'll need to make updates to that page so the info is accurate.

**Comment by mcarrano** [comment]
@mcoker do we still even need this page? Do you think there is other content that needs to go here?

**Comment by mcoker** [comment]
@mcarrano we still have opt-ins for the variable font and tabular numbers, but otherwise the page is no longer relevant. FWIW, the variable font doesn't work because the font-weight mapping is off. So we could also just not advertise the variable font until that's sorted out. I believe tabular nums is being covered in a typography page?

**Comment by mcarrano** [comment]
I agree that this page is no longer needed. I changed the issue to be for removal of this page.
