### ISSUE TITLE
Create default placeholder image for components catalog view

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-org#3222]
With the addition of a component catalog view (#2992 ), we need a default image to display if a component is added to PF without an imagery for its catalog card.

**Comment by mcarrano** [comment]
@maryshak1996 I think that works. Any thoughts @mceledonia @mmenestr ? This will be used as a default placeholder in the component view when we don't have an illustration (i.e. when a new component is added).

**Comment by evwilkin** [comment]
This image is fine from my point of view, I wasn't sure if regardless of the solution we go with if there should be any sort of extra text or indicator of "image coming soon" would be needed to avoid confusion that this image isn't actually a preview of the component.  With the current blank space where the missing image would go, it's apparent that there isn't an available preview.

**Comment by mmenestr** [comment]
Weren't we going to make sure that having an image for the catalog view was going to be part of the process of adding a component to the library? I feel like we're setting ourselves up for something we wanted to avoid haha 

But if we do need a back up image, I'd almost say to leave it a grey square with the words "image coming soon" in small black text and leave it at that. To Evan's point, I think having the PF logo would potentially be confusing.

**Comment by mcarrano** [comment]
@mmenestr Agree that ideally we want to avoid this scenario. But since new components are added by dev, there's nothing to prevent this from happening, especially for components that don't start in design. That said, I don't feel strongly about a placeholder. Maybe just a grey square is fine.

**Comment by maryshak1996** [comment]
Those are really fair points (RE: not wanting to call too much attention or branding) -- a grey box is fine with me! How's something like this @mmenestr @mcarrano @evwilkin 
![Component-catalog-Default-image_2](https://user-images.githubusercontent.com/19824574/195909463-b35d287b-b73c-49b9-9ab6-afaa234de96f.png)

**Comment by mmenestr** [comment]
I personally think that’s perfect!

**Comment by mcarrano** [comment]
Thanks for working on this @maryshak1996 . I am going to close this out as I don't believe there is anything left to do.
