### ISSUE TITLE
Update icon set

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3223]
We have added a new icon for `open-drawer-right`. This needs to be added to the set that appears on the Icons page of the website. The updated .zip will is here: https://github.com/patternfly/patternfly-design/tree/master/resources/patternfly-icon-svgs

@evwilkin is there other information that is needed from Design to update this page?

**Comment by evwilkin** [comment]
Depends on https://github.com/patternfly/patternfly-design/pull/1203/files

@mcarrano we'll need the text to enter into the "Usage/tooltip" [column in the icons table](https://www.patternfly.org/v4/guidelines/icons/#font-awesome-solid-fas-vs-font-awesome-regular-far)

**Comment by mcarrano** [comment]
For text, how about "Open or close a drawer". @lboehling does that work for you?

**Comment by lboehling** [comment]
Yep that works for me @mcarrano !
