### ISSUE TITLE
Invalid SSL certificate for https://www.patternfly.org

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-org#324]
![screen shot 2016-11-15 at 1 36 24 pm](https://cloud.githubusercontent.com/assets/895728/20318508/7d46b3e4-ab38-11e6-8a46-1f9970047483.PNG)

Given the site used to run on https, this should probably be cleaned up to avoid confusion.

**Comment by rhamilto** [comment]
It looks like this was fixed, so I'm closing the issue.

**Comment by x11x** [comment]
Looks like you are having cert problems again.
I am getting invalid CN (www.github.com)

**Comment by rachael-phillips** [comment]
Thank you for filing this! We are looking into it

**Comment by rachael-phillips** [comment]
Update here: it is now fixed, so try clearing your cache and try again!
