### ISSUE TITLE
Bug - React 18 does not support ReactDOM.render

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3282]
ReactDOM.render is no longer supported in React 18. Use createRoot instead.
Causes a console warning and will prevent our apps from running in React 18, will default to behaving line React 17 (according to docs).

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

**Comment by evwilkin** [comment]
Related issue: https://github.com/patternfly/patternfly-org/pull/3203
