### ISSUE TITLE
Enhance design guidelines for our Layouts pages - Overview

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-org#3283]
We have been exploring how we can improve layout guidance for designers as part of the V5 work ([#1178](https://github.com/patternfly/patternfly-design/issues/1178)). As a result of that work, we have identified the need to enhance and improve our design guidelines for our existing layouts. 

Layout design guidelines should be created for Bullseye, Flex, Gallery, Grid, Level, Split, and Stack layouts. 

Enhanced design guidelines should include best practices and examples of our layouts in use. Would be great to show how layouts can be used at a component level (i.e. within a card body) and also how layouts can be used to organize a full page. 

I started to put together a document [here](https://docs.google.com/document/d/1s9VguARiYUotSLhikohsXlylY93J4KGSwjKfWNraiE8/edit) (definitely not yet fleshed out).

**Comment by edonehoo** [comment]
Closing because this was addressed in #3580 #3581 #3582 #3585 #3586 #3587 #3588
