### ISSUE TITLE
Patternfly site menu unusable on narrow viewport

### ISSUE THREAD

**Issue by rhwood** [patternfly/patternfly-org#329]
When the menu on https://patternfly.org is collapsed into a hamburger menu (such as on an iPhone or Firefox on a narrow window), it is unusable. Tapping or clicking on the hamburger menu does not open the menu.

**Comment by rhwood** [comment]
I also reported this as patternfly/patternfly.github.io#2 Which project is the correct site to report this against?

**Comment by LHinson** [comment]
Hey @rhwood, thanks for reporting this. We are gonna take a look at this.

**Comment by LHinson** [comment]
I think everything is back to working. Mind testing out on your end @rhwood?

**Comment by rhwood** [comment]
This appears to be working again. Thank you.

**Comment by LHinson** [comment]
Closing since it has been addressed. Thank you!
