### ISSUE TITLE
Update icons table to add new icons

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3305]
New icons were added for `data-source` and `data-sink`. The icons table on the Icons page of the website needs to be updated to add these. Assets are available in the `patternfly-design` repo per this PR: https://github.com/patternfly/patternfly-design/pull/1217

@lboehling we will need a short description of what each of these icons are for to add to the table. See https://www.patternfly.org/v4/guidelines/icons#all-icons  Can you include those here?

**Comment by lboehling** [comment]
Let's use these: 
`data-source`: "Represents a data source" 
`data-sink`: "Represents a data sink"
Data sinks and sources are common terms that can be googled if someone sees them and doesn't know what they mean.

@mcarrano
