### ISSUE TITLE
Add guidance on editing summary sentences at top of component pages

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3335]
Add guidance per Matt's email titled "updating component summaries"

"I was helping Pankaj today to update the Label Groups design docs. He wanted to add a sentence to the component summary at the top of the page and we both realized that this text no longer lives in the same .md file. I was able to figure this out and help him make the updates, but I wasn't sure you were aware of this change. Turns out updates to that text need to now be made again this JSON file: https://github.com/patternfly/patternfly-org/blob/main/packages/v4/patternfly-docs/components-data.json

Wasn't sure if that was already documented somewhere, but if not, it should probably be added to our design documentation instructions."

To clarify: In the past, in order to edit the summary sentence at the top of a component page, designers would have to open up a different file within the existing patternfly-org repo. Today, instead of doing that, you have to edit it from a different JSON file that also exists in the patternfly-org repo that everyone has forked.

**Comment by mmenestr** [comment]
Draft doc here: https://docs.google.com/document/d/1bjDRSM785cZj0V1Ro3dbZmy2R-1XaAbkvqzofAighhY/edit

**Comment by mmenestr** [comment]
Waiting on content team review -

**Comment by mcarrano** [comment]
This information is included in the instructions here: https://github.com/patternfly/patternfly-org/wiki/Adding-new-components-to-the-website  @mmenestr will also update the instructions for design guideline authors to include this.
