### ISSUE TITLE
Combine Alert and Alert Group guidelines

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3337]
Alert and alert group will be combined into one component, so we have to figure out a way to combine the design guidelines for it.

**Comment by nicolethoen** [comment]
When this is done, the link referencing the overflow message guidance on [this line](https://github.com/patternfly/patternfly-org/blob/364c2ddc8d68eb1222bc326aa246247b482b5c7e/packages/v4/patternfly-docs/content/accessibility/alert/alert.md?plain=1#L69) in the alert a11y docs will need to be updated
