### ISSUE TITLE
Implement light/dark theme switcher

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3372]
**Describe the enhancement**

For PF 5, need the ability to switch examples between light and dark theme in component preview pages (core and React).

**Are there visuals for this enhancement? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

Design issue: https://github.com/patternfly/patternfly-design/issues/1205
Design links: https://www.sketch.com/s/4abdb322-cd19-49af-8dbc-111adf6b071b

**Any other information?**

**Comment by nicolethoen** [comment]
This might need to be a dark theme switcher in the masthead rather than be implemented component by component due to technical constraints. Dark theme is all or nothing.

**Comment by nicolethoen** [comment]
starting point: https://github.com/patternfly/patternfly-org/pull/3462

**Comment by nicolethoen** [comment]
Deliverables here:
- add switcher to masthead
- Clean up custom styles and custom components to be compatible with dark theme
- itemize the work remaining (such as images needing to be updated)
  - done in tandem with designers - need to set up a meeting
