### ISSUE TITLE
Update doc-framework dependencies

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3404]
Throws warnings when people are consuming/building with documentation-framework about its dependencies not being compatible with React 18.

**Comment by wise-king-sullyman** [comment]
Additionally pf-react shows these dependency relating warnings coming from the docs framework:
![image](https://user-images.githubusercontent.com/7115053/219803423-ce450e8c-f8ec-46a0-b535-e2f2caec79e6.png)

The extension seed and log viewer (and other extensions based on the seed) show:
![image](https://user-images.githubusercontent.com/7115053/219803802-6c4350be-862b-461a-b8ab-d371a43e0399.png)

**Comment by wise-king-sullyman** [comment]
From what I can tell based on installing
- pf-react
- log viewer
- catalog view
- topology

All of the previous dependency issues have already been resolved in the latest docs framework alpha.
