### ISSUE TITLE
[Patterns] - Create guidelines around saved filtering

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3419]
This could be part of the new patterns section - or maybe just be part of the filter guidelines... TBD

**Comment by kuklas** [comment]
I will be working on updates in this document https://docs.google.com/document/d/1Vi_kM7POP74XUsUgEMG5V8XNkXwVquwAytfRnHdUgpM/edit .

**Comment by kuklas** [comment]
As this is a new section that does not exist in Patternfly, are there any expectations on what it should include? What sections?
+ Additionally, I was working on a "Save draft" / "Save-process" pattern, so I think we could make a separate issue for that. ([Here](https://docs.google.com/document/d/1tMULAK2OXE5Hz4nEjx96nyFBZjPkSPA7Ijjmtkk6qEA/edit#heading=h.i5kdd9sp2uzw))

**Comment by mmenestr** [comment]
Closing this issue because don't have anywhere to put these guidelines right now.
