### ISSUE TITLE
Update pages/404/index.js to not use CardHeaders new API

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-org#3427]
**Is this a new page or a change to an existing one?**
Change to 404 page

**Describe the enhancement**
The `Card` component's `CardHeader` API has changed.  `CardHeaderMain` is no longer exported it is rendered internally.   

This changes are in PR https://github.com/patternfly/patternfly-react/pull/8759

**Comment by nicolethoen** [comment]
closed by #3429
