### ISSUE TITLE
Navbar example at https://www.patternfly.org/pattern-library/widgets/#info-tip is wonky

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-org#343]
<img width="951" alt="screen shot 2017-01-17 at 11 38 46 am" src="https://cloud.githubusercontent.com/assets/895728/22029973/3256bc8c-dcaa-11e6-9fba-65002e047cf0.PNG">

**Comment by bleathem** [comment]
@andresgalante any thoughts on this one?
