### ISSUE TITLE
Add PatternFly for Yew as a new community project

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3430]
Add PatternFly for Yew as a new project on the [Community page](https://www.patternfly.org/v4/community) of the website.

Project name: PatternFly for Yew
Description: See below
Link: https://github.com/ctron/patternfly-yew-quickstart

**Comment by ctron** [comment]
**Description:** PatternFly for Yew provides PatternFly components for the Yew framework. Yew is a Rust based framework for creating web applications, and is also able to run in the browser using WASM. The project aims to create Yew components for all components and concepts found in PatternFly. For a quick demo and starter template, see the [PatternFly Yew Quickstart](https://github.com/ctron/patternfly-yew-quickstart).

**Comment by ctron** [comment]
> Link: https://github.com/ctron/patternfly-yew-quickstart

Maybe as link, instead use: https://github.com/ctron/patternfly-yew

As the project description links to the quick-start, and that is the link to the main project.

**Comment by ctron** [comment]
Is there anything I can do to help?

**Comment by mcarrano** [comment]
No. not really @ctron . This is a pretty simple update, but the only reason it has not gotten done yet is that the team is heads down on a PatternFly 5 major release and the website is only refreshed when there is a PatternFly release. Therefore there is no way to just dynamically update this page (@evwilkin @nicolethoen correct me if I'm wrong). Thanks for offering your help and I'll keep you posted about when we can get this online.

**Comment by ctron** [comment]
Thanks for the update and thanks for the PR. I checked the preview, this looks good to me!

**Comment by mcarrano** [comment]
Thanks for doing this @evwilkin ! But just to be clear, this update won't go live until we release PatternFly 5, correct?

**Comment by ctron** [comment]
Thanks for the clarification. Works for me. But still it could be merged so that it doesn't get overlooked in the future?

**Comment by evwilkin** [comment]
@ctron yep - thanks for the review, we can merge this now and it would shortly be live on our staging site (staging.patternfly.org) which will be promoted to the live production website upon our next release.  I'll merge now 👍

**Comment by evwilkin** [comment]
Closed by #3461
