### ISSUE TITLE
Update the docs framework to Webpack 5

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#3432]
During the Node 18 upgrade process an OpenSSL version related error was encountered. I implemented a work around in #3433, but that workaround still leaves us open to a security vulnerability that the breaking OpenSSL upgrade was meant to resolve, [as is discussed in this SO post](https://stackoverflow.com/a/73027407).

Because of this we should still upgrade to the most recently released version of Webpack to remove the previous workaround and resolve this potential security vulnerability.

**Comment by wise-king-sullyman** [comment]
CC @evwilkin, I've updated this issue with new information that you should probably be aware of.

**Comment by nicolethoen** [comment]
Closed by #3454
