### ISSUE TITLE
Design guideline enhancement for Buttons, or Modal, Drawer, Page (?)

### ISSUE THREAD

**Issue by imjoyjean** [patternfly/patternfly-org#3434]
## Requesting new features, enhancements, or design changes to PatternFly
Describe the use cases and requirements of the new feature or enhancement you are requesting.
- New guidelines for modal to include where to place buttons when there's an existing configuration that can be updated/saved or entirely deleted in one component (modal, drawer, full page form). 

Explain *why* this feature is needed and/or why these requirements cannot be met using existing components.
- There's a couple examples of this in the product (cluster template in ACM, cluster discovery in ACM) that have different interactions. 

If this is for specific applications, list them here along with any dates that you need this for.
- No hard deadlines, its a good to have. 

Link any detailed design documents, rough sketches, wireframes or workflows.
- Discussed in this[ thread ](https://patternfly.slack.com/archives/CGR204RM2/p1677703371276079)
to move forward with having the in-modal option 3 and full page option 3, but with the secondary danger button aligned right. Could also add that the wording for when this interaction happens should be maybe "Manage" instead of edit (want content team input on this!). 

Discussion image:
<img width="1500" alt="Discussion" src="https://user-images.githubusercontent.com/57908474/222549099-17f22d6b-c4d2-40dd-a10a-48aed8a3dbe7.png">

Potential final guideline after discussion:
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/57908474/222550743-dc5a6a4b-d775-4126-ac80-9e9e16b4f6aa.png">

State whether this is a new feature or an enhancement on an existing pattern by labeling it accordingly
- enhancement to the existing guidelines

If this is an enhancement to an existing feature, identify the feature that you want to modify.
- Modal https://patternfly-org-pr-3416-v4.surge.sh/v4/components/modal/design-guidelines
Still thinking if this should be updated in just buttons, or separately in drawers, modal, page instead. Please advise.

**Comment by lclay2** [comment]
@mmenestr  Hi, I'm not able to get to that thread referenced above ^^. It sounds like it'll provide more info, are you able to access it?

**Comment by mmenestr** [comment]
@lclay2 Unfortunately I think too much time has passed and it's no longer available on slack :(

**Comment by lclay2** [comment]
Blerg, okay thanks @mmenestr

**Comment by lclay2** [comment]
Hi @imjoyjean , @mmenestr  asked me to work on this. I'm not able to get to that thread referenced above ^^. It sounds like it'll provide more info, are you able to access it or provide a recap? Thank you!

**Comment by mmenestr** [comment]
Latest: Liz talked to Joy, and will start working on this now in google docs first.

**Comment by lclay2** [comment]
@mmenestr - I sent you and Joy a draft. :)

**Comment by mmenestr** [comment]
draft lik - OKed by joy and liz for PR creation https://docs.google.com/document/d/1qc7-zyWlF2JfVgwbmjs5IX5ASk8KA6UjI3tfHW6T9qc/edit#heading=h.twx8mq3hcaw0

**Comment by lclay2** [comment]
@mmenestr , it looks like this is closed/resolved now. But just in case, as best I can recall I didn't make any image changes. So it might have come from Joy originally?
