### ISSUE TITLE
Create guidelines for new User Feedback extension

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-org#3440]
Design guide lines need to be added for this extension so it can appear on the patternfly.org site. The following [document](https://docs.google.com/document/d/1YJDtqX3tkckYnSY60d4bnNoVqx2wn8BardqjX4uoyVc/edit#heading=h.q7nw7wd501rx) exits that describes how the extension works.

**Comment by andybraren** [comment]
@edonehoo's [react-user-feedback/pull/49](https://github.com/patternfly/react-user-feedback/pull/49) adds design documentation for the extension, so closing this. 👍
