### ISSUE TITLE
Update training pages to new designs

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3445]
Want to improve the look of the Training pages to be more consistent with similar catalog views in PatternFly. See designs here: https://www.sketch.com/s/661ef9d9-8307-4e50-84e5-16eea2ff18d0

Follow up to:  https://github.com/patternfly/patternfly-design/issues/1236

**Comment by edonehoo** [comment]
Closing -- we have plans to rethink and restructure our training docs post-v6. We can reference these designs, but much of the info in the mockups no longer exists or encompasses all that we need. Let me know if you have questions or concerns!
