### ISSUE TITLE
v5 - create a new migration guide

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3446]
using the existing migration guide for the v3 -> v4 migration as a template/guide, create a new migration guide for migrating between v4 -> v5. 

Largely this will be discussing how to update CSS overrides to accommodate the style collision work.

It should also include:
- how to run code mods
- (possibly) how to migrate from the deprecated legacy table to the recommended Table (formerly TableComposable)
- (possibly) how to migrate from the deprecated Select/Dropdown to the recommended Select/Dropdown
- (possibly) how to migrate from the deprecated Wizard to the recommended Wizard

**Comment by mcarrano** [comment]
We should consider where this lives in the website nav. I'm thinking that this might belong in /get-started vs /developer-resources.
