### ISSUE TITLE
v5 - create a new upgrade guide

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3447]
The upgrade guide is essentially a thorough release notes for react and html. It will require release notes to be generated by @tlabaj and @mcoker once we are feature complete.
It can be modeled after [the upgrade guide to go from v3 -> v4](https://www.patternfly.org/v4/developer-resources/upgrade-guide/).

**Comment by mcarrano** [comment]
We should consider where this lives in the website nav. I'm thinking that this might belong in /get-started vs /developer-resources.

**Comment by mcarrano** [comment]
@nicolethoen @edonehoo does this issue need to remain open? Looks like you are tracking the new upgrade guide against #3446.

**Comment by edonehoo** [comment]
@mcarrano I do have the release highlights pr tied to this issue: https://github.com/patternfly/patternfly/pull/5646
