### ISSUE TITLE
Update sideNavLayout to use DropdownNext

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-org#3450]
As part of https://github.com/patternfly/patternfly-react/issues/8072, the components used in the documentation framework's [sideNavLayout](https://github.com/patternfly/patternfly-org/blob/ee806688406004d5e6d947176c96ab159eb08f1b/packages/documentation-framework/layouts/sideNavLayout/sideNavLayout.js) will need to be updated to use DropdownNext/the new default implementation of Dropdown after react-8072 is closed out.

**Comment by thatblindgeye** [comment]
@nicolethoen this might actually be a candidate to use the Next Select instead

**Comment by nicolethoen** [comment]
Closed by https://github.com/patternfly/patternfly-org/pull/3474
