### ISSUE TITLE
Adding demos as new components for v5

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3465]
The following demos are being moved into the components section of the website for PatternFly v5. The `components-data.json` file requires updating to ensure that we have summary text and component illustrations for the new component catalog page. The affected items are:

-     Composable menu
-     Date and time picker
-     Password generator
-     Password strength

Illustration files to be added.

cc @smckinno

**Comment by smckinno** [comment]
![Password generator](https://user-images.githubusercontent.com/104632874/229551672-d6de4339-7cb4-4c4d-9445-9d553ee9237f.png)
![Password strength](https://user-images.githubusercontent.com/104632874/229551673-90ebb37e-a9d1-4549-bdbd-c55438283040.png)
![Composable menu](https://user-images.githubusercontent.com/104632874/229551674-37a27ba4-3610-4089-9e5f-bfef86c5638f.png)
![Date and time picker](https://user-images.githubusercontent.com/104632874/229551676-a124b49b-3cec-4b5b-afbf-a609012a78e2.png)

**Comment by smckinno** [comment]
https://drive.google.com/drive/folders/1inom8YtHiOE27Wx4kTCCApiR3TaAPJs7?usp=sharing 
Here is a google drive with the PNGs
