### ISSUE TITLE
Update Icon set to Include Multicluster

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3466]
Follow up on https://github.com/patternfly/patternfly-design/pull/1248  that updates the `patternfly-icons.zip` file to include a new icon. Need to update the Zip file on the server and the Icons table on https://www.patternfly.org/v4/guidelines/icons

Name: pf-icon-multicuster
Usage text: Indicates a multicluster object
Zip file: https://github.com/patternfly/patternfly-design/blob/master/resources/patternfly-icon-svgs/patternfly-icons.zip

**Comment by evwilkin** [comment]
Dependent on being added in Core repo - https://github.com/patternfly/patternfly/issues/5451
