### ISSUE TITLE
Add landing pages for major sections

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3486]
Primary sections of the website should have landing pages that provide an overview of the content when users navigate to those sections. Based on the revised IA, sections needing landing pages include: 

Design Foundations
Patterns
Extensions
Layouts
Utility classes

See https://patternfly-org-pr-3472-v4.surge.sh/v4/ for reference.

**Comment by mcarrano** [comment]
@edonehoo I created this issue and assigned it to you. Let me know if you agree that these are the sections that require landing pages. Once the content is ready we can sync with @evwilkin about where these should live in the repo and how to ensure they show at the top of the section.

cc @lboehling

**Comment by mceledonia** [comment]
@edonehoo @lboehling We're looking at making a PatternFly logo variant for PatternFly Extensions, and we think it could primarily be featured on the landing pages as well as subsequent content pages. We haven't chosen an exact variant yet but wanted to let you know so it can be considered for a feature the landing page layout. Let me know if I can help at all or if you want to discuss further ideas!
