### ISSUE TITLE
Bug - update guidelines/filters to  demos/filters

### ISSUE THREAD

**Issue by MariaAga** [patternfly/patternfly-org#3488]
**Describe the problem**
Links to guidelines/filters are broken since the page moved to demos in https://github.com/patternfly/patternfly-org/pull/3345
example: 
https://github.com/patternfly/patternfly-org/blob/7b43e14756aac308aed28e48c0c2a4812b132249/packages/v4/patternfly-docs/components-data.json#L266

**Comment by mcarrano** [comment]
Actually for v5 will be patterns/filters

**Comment by MariaAga** [comment]
Shouldnt we fix v4 docs? they will still be in use for the following months/years

**Comment by nicolethoen** [comment]
I will fix in both places :)

**Comment by nicolethoen** [comment]
I have fixed it on [PF.org](https://www.patternfly.org/v4/components/search-input) and in [the v5 branch](https://github.com/patternfly/patternfly-org/blob/v5/packages/v4/patternfly-docs/components-data.json#L266). Thanks for reporting the broken link, @MariaAga !
