### ISSUE TITLE
Core dev server style loading issue

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#3500]
Looks like the dev server is including individual component CSS into the workspace (eg, card.scss, badge.scss, etc) that is not tied to CSS changes during development, and that individual component CSS is loading after patternfly.css, which is the stylesheet that updates as we make changes during development. So changes from the individual component CSS are overriding patternfly.css due to the loading order, so changes aren't being reflected in the browser. Here's a screenshot of what I'm talking about - I changed `--pf-c-badge--Color` to `red`

<img width="1610" alt="Screenshot 2023-04-20 at 5 04 53 PM" src="https://user-images.githubusercontent.com/35148959/233497606-1661ee06-9092-4f77-bff5-59501408eb97.png">

**Comment by dgutride** [comment]
work complete on this
