### ISSUE TITLE
Add details on when to use checkbox select vs multiple select on Select design guidelines

### ISSUE THREAD

**Issue by jknilans** [patternfly/patternfly-org#3510]
**Is this a new page or a change to an existing one?**
Changing this existing page: https://www.patternfly.org/v4/components/select/design-guidelines#when-to-use-checkbox-select-versus-multiple-select

**Describe the enhancement**
It appears that this section is missing information. Currently it reads:

> **When to use checkbox select versus multiple select**
> Both the checkbox select and multiple select lists allow users to select multiple options from a list. However, there are some points to take into consideration when deciding which one to use.

And then there are screenshots of what is suggested below, however no points are listed for why one should be used instead of the other. It probably just needs a few sentences explaining the use cases for each.

**Are there visuals for this enhancement? If applicable, please include examples for each state and for varying widths**
No visuals, only new content is needed.

**Any other information?**
None. Thanks!

**Comment by kuklas** [comment]
I will be updating this document https://docs.google.com/document/d/1uLg2Yebs7ip_yGyobxsD8IYkQ2vkoiXvzeadyF8QMlQ/edit?usp=sharing
