### ISSUE TITLE
Bug - CodeSandbox for "HTML CSS variables and overrides training" page (part 1) is out-of-sync with resulting screenshot, as it doesn't include description + close button for alert message

### ISSUE THREAD

**Issue by neoncitylights** [patternfly/patternfly-org#3540]
**Describe the problem**
Hello! :) This is just a minor detail; I was going through Part 1 of the [HTML CSS variables and overrides training](https://www.patternfly.org/v4/training/html-css-variables-and-overrides-training/) guide. This links to a [CodeSandbox](https://codesandbox.io/s/html-fundamentals-start-hy2erg?file=/index.html:534-864), however initial the alert message HTML doesn't include the description and close button like the resulting screenshot. (see the screenshot attached below)

The initial alert message HTML is:
```html
<div class="pf-c-alert pf-m-success" aria-label="Success alert">
  <div class="pf-c-alert__icon">
    <i class="fas fa-fw fa-check-circle" aria-hidden="true"></i>
  </div>
  <p class="pf-c-alert__title">
    <span class="pf-screen-reader">Success alert:</span>
    Success alert title
  </p>
</div>
```

I would suggest that the mini-tutorial should include in the step about adding the description + close button, but since it's out of the scope of the specific guide (because it talks about CSS variables), I think the default HTML alert included in the CodeSandbox should be the following:

```diff
<div class="pf-c-alert pf-m-success" aria-label="Success alert">
  <div class="pf-c-alert__icon">
    <i class="fas fa-fw fa-check-circle" aria-hidden="true"></i>
  </div>
  <p class="pf-c-alert__title">
    <span class="pf-screen-reader">Success alert:</span>
    Success alert title
  </p>
+  <div class="pf-c-alert__action">
+    <button
+      class="pf-c-button pf-m-plain"
+      type="button"
+      aria-label="Close success alert: Success alert title"
+    >
+      <i class="fas fa-times" aria-hidden="true"></i>
+    </button>
+  </div>
+  <div class="pf-c-alert__description">
+    <p>Success alert description. <a href="#">This is a link.</a></p>
+  </div>
</div>
```

**Expected behavior**
By the time you complete Part 1, the success message should look like the resulting screenshot (also attached in the official PatternFly guide).

**Screenshots**

Expected screenshot:
![image](https://github.com/patternfly/patternfly-org/assets/4723983/af9bbe5c-97d4-4cbb-882a-0e16fe262128)

Actual screenshot:
![image](https://github.com/patternfly/patternfly-org/assets/4723983/9a9ad185-2836-4400-bb0b-433d8cf72846)

**Any other information?**
I would be happy to open a PR :-) However, I wasn't sure how to. I was thinking at first that there might be a way the CodeSandbox examples lives inside this repository, and the sandboxes on CodeSandbox itself syncs with the repository, but it seems like the example source code lives on CodeSandbox.

**Comment by nicolethoen** [comment]
@neoncitylights thanks so much for reporting this! I updated the starting code in the codesandbox. iF you notice anything else, let me know !
