### ISSUE TITLE
broken back-button browser navigation

### ISSUE THREAD

**Issue by lorezzed** [patternfly/patternfly-org#356]
Selecting tab headings (Overview, Design, Code) for the components cause history navigation to loop and break

Steps to reproduce:
1. Navigate to a component eg,
    http://www.patternfly.org/pattern-library/cards/aggregate-status-card/#/api
2. Click on "Design" tab which redirects to
    http://www.patternfly.org/pattern-library/cards/aggregate-status-card/#/_design
3. Select the browser back button
4. Redirects to
    http://www.patternfly.org/pattern-library/cards/aggregate-status-card/#_design
- Note `/#/_design`becomes `/#_design`
5. Get redirected back to
    http://www.patternfly.org/pattern-library/cards/aggregate-status-card/#/_design

**Comment by bleathem** [comment]
@dabeng can you take a look at this one?  It should build on your recent location manipulation bug fixes for the tab handling.

**Comment by LHinson** [comment]
Just tested this and looks like this one has been addressed so I'm closing.
