### ISSUE TITLE
Bug - Jumplinks are too narrow

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#3604]
**Describe the problem**
Jumplinks are too narrow and are causing a horizontal scrollbar

**Expected behavior**
I like letting the content stretch, but the jumplinks need a min width maybe.

**Screenshots**
<img width="590" alt="image" src="https://github.com/patternfly/patternfly-org/assets/19825616/2413ae8a-d478-4c4d-a825-1bd0103ffd98">

**Comment by andrew-ronaldson** [comment]
Closing could not replicate.
