### ISSUE TITLE
Update All Components view with new illustrations

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#3612]
Some of the illustrations for the All Components view have been reworked by Design to improve consistency. New illustrations need to be uploaded to `patternfly-org`

@smckinno can you add a link to your new files here?

**Comment by smckinno** [comment]
Here is the Google Drive: https://drive.google.com/drive/folders/1A6cqtWnJt4iWhzLlHMO9LRZN6Y-LXZNS?usp=sharing

**Comment by mcarrano** [comment]
@evwilkin please take a look at the above folder. Does capitalization in the file names matter if everything else is the same, i.e. is "About-modal.png" equivalent to "about-modal.png"?
