### ISSUE TITLE
Alert - update a11y docs for AlertActionLink children prop

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-org#3634]
To be done after https://github.com/patternfly/patternfly-react/pull/9278 is merged. With the children prop being updated to accept ReactNode as a type, we should add the children prop to the React table to mention that interactive content (such as anchors) should not be passed to the component.

**Comment by edonehoo** [comment]
Closing: It looks like this has been added https://www.patternfly.org/components/alert#alertactionlink
