### ISSUE TITLE
D3 version conflict

### ISSUE THREAD

**Issue by michpetrov** [patternfly/patternfly-org#364]
There's a node dependency for D3 v4.5.0 however PatternFly is still on 3.5.17, this breaks components such as [Heat Map](http://www.patternfly.org/pattern-library/data-visualization/heat-map/#/api). (Although heat map is kind of broken anyway due to the way it's initialized).

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2017. Please let me know if this is still relevant and we will revisit.
