### ISSUE TITLE
Update ChipGroup a11y docs for HTML

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-org#3653]
**Is this a new page or a change to an existing one?**
Existing ChipGroup a11y docs

**Describe the enhancement**
Followup to https://github.com/patternfly/patternfly/pull/5765, we should add content to the HTML table for adding an aria-label/aria-labelledby and role to `pf-v5-c-chip-group`

**Are there visuals for this enhancement? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**Any other information?**

**Comment by edonehoo** [comment]
Closing: chip is deprecated
