### ISSUE TITLE
Bug - missing Topology styles

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly-org#3665]
**Describe the problem**
A clear and concise description of the problem. Which pages are affected?

Topology is missing styles 
https://staging.patternfly.org/topology/getting-started

**Expected behavior**
A clear and concise description of the expected behavior.

**Screenshots**
If applicable, add screenshots to help explain the issue.
<img width="500" alt="Screenshot 2023-07-27 at 2 59 08 PM" src="https://github.com/patternfly/patternfly-org/assets/32821331/e97342ac-201b-4559-8061-ab0a94fb2ff3">

**Comment by nicolethoen** [comment]
fixed when we released! :)
