### ISSUE TITLE
v4-archive site search returns v5 pages

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3683]
Searching on v5 seems to work fine, but when I'm searching on v4, it gets  me back to v5 results.

**Comment by evwilkin** [comment]
We have 2 separate `appId` values from Algolia, matching the search results for the 2 different sites:
<img width="223" alt="Screenshot 2023-12-21 at 12 39 35 PM" src="https://github.com/patternfly/patternfly-org/assets/8651509/77afda44-4ab6-4ba8-8387-88ad3b5a556f">

The [current /v4 branch code in Github](https://github.com/patternfly/patternfly-org/blob/v4/packages/v4/patternfly-docs/patternfly-docs.config.js#L7-L11) shows the correct appId from Algolia for the archive site results, but the source code delivered on the V4 archive site shows that it doesn't match this - it's using the appId from Algolia that corresponds to the V5 search index:
<img width="725" alt="Screenshot 2023-12-21 at 12 38 14 PM" src="https://github.com/patternfly/patternfly-org/assets/8651509/bff83a49-e332-40c6-8c7d-196fe4a37d37">

It appears that AWS needs to be updated with code containing the correct Algolia appId in order for the archive site to reference the correct indexed archive pages.

**Comment by evwilkin** [comment]
Closed by #3876 and push to AWS v4 archive.
