### ISSUE TITLE
Update capitalization across Red Hat standards

### ISSUE THREAD

**Issue by wolfeallison** [patternfly/patternfly-org#3687]
The Capitalization across Red Hat UI's section on the Capitalization UX writing page is confusing. 
https://www.patternfly.org/ux-writing/capitalization#capitalization-across-red-hat-uis

Remove these bullets:
Write navigation items and their corresponding page titles in title case.
Write all other areas (such as menu items, button text, form field labels, and empty state headings) in sentence case.

The example image should also be updated so that the page title is in sentence case

**Comment by edonehoo** [comment]
This was addressed in this recently merged PR: https://github.com/patternfly/patternfly-org/pull/3637!
