### ISSUE TITLE
Updates to Color Palette File Downloads

### ISSUE THREAD

**Issue by bdellasc** [patternfly/patternfly-org#371]
There were a couple of errors in the downloadable palette files from the Palette page on Patternfly.org. A .zip file that contains the corrected files has been attached.

Verification Conditions:

When selecting options from the "Download Color Swatches" button:
- "For Adobe Photoshop" = PatternFly_Swatches_02-27-2017.aco
- "For Adobe Illustrator/InDesign" = "PatternFly_Swatches_02-27-2017.ase
- Last updated date should be changed to "27 Feb 2017"

[PatternFly_Swatches_02-27-2017.zip](https://github.com/patternfly/patternfly-org/files/804884/PatternFly_Swatches_02-27-2017.zip)

CC'ing: @kybaker, @andresgalante, @LHinson

**Comment by LHinson** [comment]
#376 addresses this issue so closing.
