### ISSUE TITLE
Bug - DashboardWrapper - onPageResize undefined in codesandbox

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3750]
A follow up to https://github.com/patternfly/patternfly-react/pull/9053
There are some demos - such as the bulk select table demo which still show an 'onPageResize' error when viewed in a codesandbox.

**Comment by jenny-s51** [comment]
Retested again with demos that use DashboardWrapper, and this no longer seems to be an issue, likely due to the TS conversion of the Dashboard components https://github.com/patternfly/patternfly-react/pull/9618/files getting merged
