### ISSUE TITLE
RTL handbook - add any react specific documentation, other follow ups

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#3758]
Looks like we should probably add something about

* Chart legends - https://github.com/patternfly/patternfly-react/pull/9570#issuecomment-1725916867
* `<Icon shouldMirrorRTL />` - https://github.com/patternfly/patternfly-react/blob/ff467eef5db530f0245ba29ca01db1f4a239f274/packages/react-core/src/components/Icon/Icon.tsx#L27-L30
* Anything about things that use popper?
* Link the mention of logical properties in the handbook to a docs page on what logical properties are (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values)
* Anything else?

cc @srambach @tlabaj @wise-king-sullyman @thatblindgeye @kmcfaul

**Comment by kmcfaul** [comment]
Charts info for RTL:
- `Chart`, `ChartPie`, `ChartBullet`, `ChartDonut`, `ChartDonutUtilization` all have a new `legendDirection` prop that should be set to `rtl`.
- In the case of user defined custom legends that pass custom label components, rtl support would have to be done manually as `legendDirection` does not apply.
- The `ChartAxis` representing the x-axis should additionally pass the `invertAxis` prop.
