### ISSUE TITLE
Update naming for "about" pages across website.

### ISSUE THREAD

**Issue by edonehoo** [patternfly/patternfly-org#3806]
**Is this a new page or a change to an existing one?**
Change to a few pages

**Describe the enhancement**
"About" pages across PF.org aren't accessible with VO, because they all just say "About". Updated page nav headings to be unique and more descriptive.

**Comment by andrew-ronaldson** [comment]
I discussed this with @edonehoo and although it can feel repetitive we could do _About + name_ (About extensions). Seems like a small enough fix for this VO change
