### ISSUE TITLE
Bug - Version 5.0 shouldn't be hidden from version switcher

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#3812]
We updated the website version switcher to link out to archive docs for PF4 and PF3, and use the `hidden` property in versions.json to hide each version of these previous major releases from appearing in the versions switcher (they are available on those archive sites).

Versions of the current (V5) major release do not need to be hidden and can be linked in the version switcher, currently 5.0 is hidden and can have the `hidden` property removed to reveal this in the version switcher:
- https://github.com/patternfly/patternfly-org/blob/main/packages/documentation-framework/versions.json#L27

**Comment by evwilkin** [comment]
@nicolethoen FYI to check me on this and reference for future releases

**Comment by nicolethoen** [comment]
The version switcher is broken - so the 5.0 is hidden on purpose for now. I'll take a little extra work get it all working again.
