### ISSUE TITLE
Bug - Documentation doesn't reflect pf-v5-pficon usage

### ISSUE THREAD

**Issue by mayusoma-redhat** [patternfly/patternfly-org#3823]
**Describe the problem**
The [documentation](https://www.patternfly.org/design-foundations/icons/) for v5 still uses the old `pficon-xxx` format

**Expected behavior**
The [documentation](https://www.patternfly.org/design-foundations/icons/) should reflect the correct usage for v5 as `pf-v5-pficon-xxx`

**Comment by edonehoo** [comment]
Closing: looks like this was addressed at some point ![Image](https://github.com/user-attachments/assets/91458494-dec1-4b75-ab3d-1e9215ee0203), plus the v6 site also have up-to-date info now
