### ISSUE TITLE
Make icons more discoverable

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/patternfly-org#3848]
The Algolia data shows that "icon"/"icons" make up 4.05% of all of our searches which makes it fairly clear that users are having a difficult time finding this section on their own. We should investigate how to make our icons more discoverable in our documentation.

**Comment by edonehoo** [comment]
Closing this in favor of https://github.com/patternfly/patternfly-org/issues/4398. I'll find a way to look into this as part of that research!
