### ISSUE TITLE
bootstrap-combobox old link to github repo 

### ISSUE THREAD

**Issue by mkrajnak** [patternfly/patternfly-org#386]
Hi, I've just noticed that there is an old link for bootstrap-combobox github repo  in patternfly [website](https://www.patternfly.org/pattern-library/widgets/#bootstrap-combobox).  I think it should be updated to this [one](https://github.com/patternfly/patternfly-bootstrap-combobox)

**Comment by mcarrano** [comment]
This requires an update to this file: https://github.com/patternfly/patternfly-org/blob/master/source/pattern-library/widgets/index.md and a PR against the patternfly-org repo.

**Comment by bleathem** [comment]
Thanks for reporting the issue and for the PR!
