### ISSUE TITLE
Bug - View source on GitHub links for Component Groups results in 404 - page not found

### ISSUE THREAD

**Issue by TrevorBenson** [patternfly/patternfly-org#3891]
**Describe the problem**
Each link for Component Groups source code on GitHub leads to a 404 page not found. 

Which pages are affected?
* [About component groups](https://www.patternfly.org/extensions/component-groups/about-component-groups)
* [Ansible](https://www.patternfly.org/extensions/component-groups/ansible)
* [Battery](https://www.patternfly.org/extensions/component-groups/battery)
* [Details page](https://www.patternfly.org/extensions/component-groups/details-page)
* etc.
 
It appears to be each page under the **Extensions** -> **Component Groups** navigation sidebar menu.

**Expected behavior**
Links are updated to the current location so clicking leads to the source.

**Comment by jessiehuff** [comment]
I believe that the majority of these were fixed in https://github.com/patternfly/react-component-groups/pull/89 but it looks like the about component groups page was missed so this PR should fix that: https://github.com/patternfly/react-component-groups/pull/124

**Comment by nicolethoen** [comment]
Closed by https://github.com/patternfly/react-component-groups/pull/124
