### ISSUE TITLE
Bug - Menu props tables are empty

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-org#3894]
`Menu`, `MenuList`, `MenuItem`, `MenuContent`, `MenuGroup` are not generating their props tables properly (header is present but table content is empty). This is on the org site as well as v6 staging.

`Button`, `HelperText` also missing.

**Comment by tlabaj** [comment]
We are also seeing Pops missing from `Select` prop table (e.g. `maxMenuHeight`)

**Comment by tlabaj** [comment]
this issue is probably related https://github.com/patternfly/patternfly-react/issues/10058
