### ISSUE TITLE
Document list of breaking changes for penta

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#3907]
Placeholder for working on a list of breaking changes for penta, similar to this table we created for v5 - https://www.patternfly.org/get-started/upgrade/release-notes

The majority of this will likely be the changes from the old global variable system to tokens, and there may not be a 1:1 list of "v5 global var `--pf-v5-some-var` changed to to v6 token `--pf-t-some-var`". So we should discuss whether we need to try and create a v5->v6 map of vars/tokens, or if we can just point folks to the token documentation as a reference for how to update old global vars to tokens.

**Comment by kmcfaul** [comment]
Delete old release notes page on v6 org - this references v5 still.
