### ISSUE TITLE
Medium article for Alpha release on homepage

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-org#3909]
### Goal
Create a new blog that highlights the v6 Alpha release.

Possible content
- Visual refresh with Penta
- Design tokens and their role
- Migration
- Next steps (Animations, extensions, etc.)

**Comment by edonehoo** [comment]
FYI this blog is drafted on Google docs [here](https://docs.google.com/document/d/10x0w2HKNAv6Pn_c64d8FqgrljhFxi7KFALxqlVJWR2A/edit?usp=sharing). Once alpha goes live I will need to: 
1. Update with relevant screenshots
2. Publish to Medium 
3. (Someone) Update the featured blog to point to our new post on Medium 

This blog can continue to be edited if we need to.

**Comment by andrew-ronaldson** [comment]
Closing 🎉. Article can be found [here](https://medium.com/patternfly/welcome-to-the-patternfly-6-alpha-6d6f64de5a73)
