### ISSUE TITLE
Bug - v6 docs framework - utilities need to reference pf-v6-u-[...]

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#3927]
Mostly interested in the references to `pf-v5-u-h-100` being updated on full page example pages, but I reckon all of them need to be updated since the classnames changed.

https://github.com/patternfly/patternfly-org/blob/33226a015c82b30314a5beab79278617b75bb837/packages/documentation-framework/components/example/example.js#L134

https://github.com/patternfly/patternfly-org/blob/33226a015c82b30314a5beab79278617b75bb837/packages/documentation-framework/components/example/example.js#L167

<img width="1376" alt="Screenshot 2024-03-21 at 6 59 40 PM" src="https://github.com/patternfly/patternfly-org/assets/35148959/0fa957ec-34e5-430c-a396-ad5b4fe61750">

----

FWIW I tried to make the change to submit a PR but my local dev server doesn't seem to be reloading with changes? I'm probably doing something wrong, but I tried starting the server with `yarn [start/develop/develop:v5]` and reloads don't seem to work. I'm also getting this webpack error

```
ERROR in ../../node_modules/@patternfly/design-tokens/patternfly-docs/content/tokensTable.js 47:6
Module parse failed: Unexpected token (47:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|     return (
>       <div>
|         <div
|           className="ws-css-property"

webpack 5.76.3 compiled with 1 error in 41962 ms
```

**Comment by nicolethoen** [comment]
Closed by #3931
