### ISSUE TITLE
Identify & resolve any custom styles

### ISSUE THREAD

**Issue by kmcfaul** [patternfly/patternfly-org#3945]
We should be able to remove all the CSS copied from core's pf-v6-c-content: https://github.com/patternfly/patternfly-org/blob/v6/packages/documentation-framework/templates/mdx.css#L90.

Looks like we can remove custom styles for the sidebar nav, which should resolve this issue https://github.com/patternfly/patternfly-org/issues/3953

**Comment by mcoker** [comment]
Once https://github.com/patternfly/patternfly/issues/5966 is complete, assuming those styles are pretty much a copy of the core `pf-[v]-c-content` (aka, react `<Text>` and `<TextContent>`) component, ideally, we should be able to yank out those styles and swap `.ws-[p/dl/hr/etc]` with classes from the content/text/textcontent component - eg, `.pf-v6-c-content--[p/dl/hr/etc]`.
