### ISSUE TITLE
Wizard (design tab) > "Loading Screen" image

### ISSUE THREAD

**Issue by ryanaltvater** [patternfly/patternfly-org#396]
Pink reference numbers are backwards. "Title Bar" should be 1, and "Loading Wizard State" should be 2.

http://www.patternfly.org/pattern-library/communication/wizard/#/design

**Comment by LHinson** [comment]
Hey @ryanaltvater! Fancy seeing you on here. You actually need to file this issue on the patternfly-design repo. I'm realizing that those unfamiliar with PatternFly probably don't understand the correlation between patternfly-design and our site. We should clarify that process via documentation. For now though, patternfly.org consumes the .md files in patternfly-design. 

The file you are looking for is located here: https://github.com/patternfly/patternfly-design/tree/master/pattern-library/communication/wizard/design

I'm going to close this one and move the issue over there. Feel free a to send a PR to help us quickly address the issue!

**Comment by LHinson** [comment]
Closing here as I just filed on patternfly-design as seen here: https://github.com/patternfly/patternfly-design/issues/251
