### ISSUE TITLE
Link on http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/ page goes to 404 not found page

### ISSUE THREAD

**Issue by mareknovotny** [patternfly/patternfly-org#398]
Page [http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/](http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/) contains 

> See Inline Notifications for more information.

Inline Notifications points to [http://www.patternfly.org/widgets/#progress](http://www.patternfly.org/widgets/#progress) which is not found.

**Comment by mcarrano** [comment]
I will look at this as I'm making other updates to Forms and Controls section.

**Comment by LHinson** [comment]
This particular bug has been addressed. All link in the page docs work. Closing this issue.

**Comment by mareknovotny** [comment]
awesome, thanks!
