### ISSUE TITLE
set up v5-archive.patternfly.org

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-org#3991]
Information about how to do this can be found in the [Major Release Development process doc](https://docs.google.com/document/d/1aRpzrhWZO1R30MFCnH8FtLEw43ZOn_K_XpFYWKEQGZs/edit) under the `To set up/preserve the website for the old version` heading

ultimately, the v5 branch in org should be publishing directly to the v5-archive site automatically each time code merges into that branch.

**Comment by kmcfaul** [comment]
v5-archive.patternfly.org is live
We can set up auto-pushing to the site from the v5 branch later on if needed (will be manually pushed until then).
