### ISSUE TITLE
[Documentation framework] - full page examples not working 

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#4010]
Tried pulling in the latest docs-framework package and noticed the fullpage examples are broken. Confirmed they're broken on https://staging-v6.patternfly.org/, too.

Looks to be a result of https://github.com/patternfly/patternfly-org/pull/4004, which there is a follow up for (https://github.com/patternfly/patternfly-org/issues/4005) to revert the change, so it may be a known issue? cc @nicolethoen @jenny-s51

**Comment by nicolethoen** [comment]
Closed by https://github.com/patternfly/patternfly-org/pull/4022
