### ISSUE TITLE
Update EmptyState in v6 to avoid using Header and Icon subcomponents

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-org#4018]
**Is this a new page or a change to an existing one?**

**Describe the enhancement**
Looks like before a PR for https://github.com/patternfly/patternfly-react/issues/10130 can go into React, we need to update EmptyState usage in org v6 so that we don't import EmptyStateHeader or EmptyStateIcon.

**Are there visuals for this enhancement? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**Any other information?**

**Comment by evwilkin** [comment]
Closed by #4025
