### ISSUE TITLE
Review icons.css styles for replacing custom styles with existing styling

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#4020]
Followup from #4011

Per @mcoker in [this comment](https://github.com/patternfly/patternfly-org/pull/4011#discussion_r1599051939):

This stylesheet is another good one to review as a whole and see if we can't use some existing components/layouts/styles. With the styles here, one big one that sticks out is we're not using spacer vars for spacers we support.

**Comment by nicolethoen** [comment]
Do this as a follow up to https://github.com/patternfly/patternfly-org/pull/4102

**Comment by nicolethoen** [comment]
Closed by https://github.com/patternfly/patternfly-org/pull/4146
