### ISSUE TITLE
Review community.md for removing utility classes, potentially replacing custom elements/styles

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#4021]
Followup from https://github.com/patternfly/patternfly-org/pull/4011

Per @mcoker in [this comment ](https://github.com/patternfly/patternfly-org/pull/4011#discussion_r1599054035)and [this other comment](https://github.com/patternfly/patternfly-org/pull/4011#discussion_r1599054774):

I don't know how much it matters, but it's worth noting there are a lot of utility classes used on this page where it looks like we have a stylesheet for other pages? I wonder if we should be more consistent. Also I wonder if we used `<Text>` headings, if we would need all of these margins and hwhat-not on the headings.

and

I'd expect we have `<Grid>` props that can replace the use of these `.pf-v6-l-grid/.pf-m-*` classes?

**Comment by nicolethoen** [comment]
closed by #4127
