### ISSUE TITLE
Review trainingCard.css styles for replacing custom styles with existing styling options or tokenization

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#4023]
Followup from https://github.com/patternfly/patternfly-org/pull/4011

Per @mcoker in [this comment](https://github.com/patternfly/patternfly-org/pull/4011#discussion_r1599056448):

I wonder if we could get rid of some of these styles. If not, we should probably tokenify these styles.

I think we can remove the whole design training w/ sketch page

**Comment by andrew-ronaldson** [comment]
I can help with this one. The Design section can be removed for the time being as it is referring to the Sketch training that we no longer have

**Comment by nicolethoen** [comment]
closed by #4127
