### ISSUE TITLE
Remove custom divider styles in icons.css

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#4033]
Blocked by https://github.com/patternfly/patternfly-react/issues/10390

When/if the above enhancement is complete we should see if we can use that new functionality to get rid of the custom styles we have for a divider in the icons stylesheet.

Followup from https://github.com/patternfly/patternfly-org/pull/4011#discussion_r1605141970

CC @mcoker

**Comment by nicolethoen** [comment]
Do this as a follow up to https://github.com/patternfly/patternfly-org/pull/4102

**Comment by nicolethoen** [comment]
Closed by #4146
