### ISSUE TITLE
Toolbar v6 - update spacer/spaceItems to gap props

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-org#4046]
**Is this a new page or a change to an existing one?**
Toolbar 
**Describe the enhancement**
Followup to React PR https://github.com/patternfly/patternfly-react/pull/10418
**Are there visuals for this enhancement? If applicable, please include examples for each state and for varying widths**
Include screenshots or links to Marvel or other mockups.

**Any other information?**

**Comment by evwilkin** [comment]
Closed by #4172
