### ISSUE TITLE
Some react-icons have the wrong className

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#4047]
Looking at [v6 staging on org](https://staging-v6.patternfly.org/components/label), I noticed some of the icons are off-center in the `<Label>` component, and looks to be the result of some of them having `.pf-v5-svg` (incorrect) and others having `.pf-v6-svg` (correct).

<img width="775" alt="Screenshot 2024-05-30 at 10 05 16 AM" src="https://github.com/patternfly/patternfly-org/assets/35148959/6c651b43-573c-466d-ae38-36e5bde49935">
<img width="742" alt="Screenshot 2024-05-30 at 10 05 06 AM" src="https://github.com/patternfly/patternfly-org/assets/35148959/0c3b62a7-4e2e-49e7-8c32-9e552967dd2a">

**Comment by mcoker** [comment]
cc @kmcfaul @nicolethoen

**Comment by nicolethoen** [comment]
I believe this is now resolved in a newer version of staging.
