### ISSUE TITLE
Bug - 404 page using ESIcon component

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly-org#4057]
**Describe the problem**
The 404 page code is importing and using the EmptyStateIcon component when it should be passing props to EmptyState instead.

**Expected behavior**
A clear and concise description of the expected behavior.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Any other information?**

**Comment by nicolethoen** [comment]
Closed by #4056
