### ISSUE TITLE
Review ColorFamily.css and ColorFamily.js styles for replacing custom styles with existing styling options or tokenization

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#4067]
We should evaluate these styles to determine if they're still needed and remove them if not.

Along with the styles in ColorFamily.css, the inline styles in ColorFamily.js which reference removed global styles should also be addressed under this issue.

If they are still needed we should update the currently commented out global styles with their proper token replacements.

**Comment by nicolethoen** [comment]
Per conversation with design:
- remove references to shadows
- color families should not show palette or base tokens, only semantic tokens
- see if we can have two columns under each accordion in the color families. One column for light theme semantic tokens which use these colors, one column for dark theme semantic tokens which use these colors
- pick the three-ish most common colors for each category in the color swatch section

**Comment by nicolethoen** [comment]
Closed by #4157
