### ISSUE TITLE
Review commented out global styles in icons.js

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#4074]
In the above referenced file there are several references to removed global style values which are currently commented out.

These style should be reviewed and removed if they're no longer needed, or updated to use a token if they are needed.

**Comment by nicolethoen** [comment]
Do this as a follow up to https://github.com/patternfly/patternfly-org/pull/4102

**Comment by evwilkin** [comment]
Addressed in #4146 this issue is no longer needed.
- https://github.com/patternfly/patternfly-org/commit/8dc1eaa75d6a1d1f94a5ac04944224f477f30b6e#diff-ad8e7d01989a5829dc28e2a32dbbdf7dc6ea4a8b79b541e1b2f213b80ef8bc03
