### ISSUE TITLE
Colors page: Update static content to show tokens

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-org#4077]
This [page](https://staging-v6.patternfly.org/design-foundations/colors#patternfly-palettes) does not point to the latest Design tokens and requires additional changes to explain the semantic layer vs base vs palette.

**Comment by andrew-ronaldson** [comment]
![Screenshot 2024-06-06 at 11 32 36 AM](https://github.com/patternfly/patternfly-org/assets/28658548/80679044-176a-488c-99e8-4beede9c2664)
One thing I noticed was that all the swatches seem to point to black.

**Comment by edonehoo** [comment]
This can probably also be closed by https://github.com/patternfly/patternfly-org/pull/4143, except that PR is only linking to tokens docs -- it doesn't explain token layers on its own. But that could be integrated

**Comment by nicolethoen** [comment]
@andrew-ronaldson or @lboehling do you want anything else added to the color page before GA release?

**Comment by andrew-ronaldson** [comment]
Closed by https://github.com/patternfly/patternfly-org/pull/4143
