### ISSUE TITLE
[bug]Simple Expansion - Click the ">" button can not expanse the list

### ISSUE THREAD

**Issue by zhutaoredhat** [patternfly/patternfly-org#408]
http://www.patternfly.org/pattern-library/content-views/list-view/#/code
 Click the ">" button can not expanse the list which takes me some confusing.

**Comment by LHinson** [comment]
@cliffpyles will you please review the open PRs associated with this bug? Thanks!

**Comment by dabeng** [comment]
This bug has disappeared from patternfly.org site.

![wnkuny970t](https://user-images.githubusercontent.com/5689075/40159924-0541496c-59de-11e8-8e8d-f896855a2760.gif)
