### ISSUE TITLE
Scroll position issues in v6 workspace

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#4085]
1. If you scroll down on a component example page, then navigate to another component example page via the vertical nav, the window stays scrolled instead of scrolling back to the top.
2. If you click on a jump link, the section it scrolls you to will be in the middle of the main page area. It should scroll so that the anchored section is at the top of the main page area.

cc @wise-king-sullyman

**Comment by evwilkin** [comment]
Closed by #4197
