### ISSUE TITLE
 Docs - Incorrect link for @patternfly/react-code-editor package in documentation

### ISSUE THREAD

**Issue by musama619** [patternfly/patternfly-org#4115]
There is an incorrect link in the PatternFly documentation for the `@patternfly/react-code-editor` package. The link currently directs to:

https://www.npmjs.com/package/@patternfly/react-code-editors

but it should be

https://www.npmjs.com/package/@patternfly/react-code-editor

**Steps to reproduce**

- [Go to https://www.patternfly.org/get-started/develop/](https://www.patternfly.org/get-started/develop/#install-and-configure-patternfly-react)
- In the list of react npm packages click on [@patternfly/react-code-editors](https://www.npmjs.com/package/@patternfly/react-code-editors)

**Comment by evwilkin** [comment]
Closed by #4205
