### ISSUE TITLE
Broken link on Label page

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#4124]
The "Badge" link (on the Label - Design Guidelines page under the 'Usage' section) points to a broken v4 link and should be updated:
- https://www.patternfly.org/components/label/design-guidelines/#usage

**Comment by rebeccaalpert** [comment]
This should now be fixed on v6 - going to see if it's ok to fix on the main site as well.

**Comment by evwilkin** [comment]
Closed by #4186
