### ISSUE TITLE
PF AI guidelines - UX AI Design Guidelines and Principles

### ISSUE THREAD

**Issue by kevinhatchoua** [patternfly/patternfly-org#4142]
**Needs more content** cc Abi

Need to create a new section on PF to house UXD AI ethics and guidelines.

**Comment by andrew-ronaldson** [comment]
Thanks for making the issue. I transferred to our org repo where the docs framework lives

**Comment by abigaeljamie** [comment]
Thanks, @andrew-ronaldson ! This issue bloomed from a conversation that @kevinhatchoua and I had yesterday. He and I created a document about AI ethics and guidelines, collaboratively with the rest of the AI working group. https://docs.google.com/document/d/1hwfdfQ43je4kgiLxNsIF44XvHNio5jPtkzADGh3k6Nk/edit#heading=h.jg4jg6keul4x 

The document is still WIP, and Kevin is aware that this will be a post-v6 effort. But we wanted to get this on PatternFly's radar ahead of time. Basically, similar to what IBM has done, we want to publish these AI guidelines on PatternFly, similar to how we have high-level guidelines around other key areas of design such as Accessibility, UX writing, Foundations, etc. 

I thought of @edonehoo as the Information Architecture content expert who can figure out where the content should live & how it should be structured, as well as writing/editing it. I thought of @bekah-stephens as the PatternFly designer to do the website page design that will house the content. Then it can be handed to dev for implementation — but again, we know this will be after v6 given the need for the team to focus on wrapping time-sensitive v6 work. 

Let me know what you think and if you have any questions!
