### ISSUE TITLE
Icons: A few icons are missing from the icons page

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#416]
I've gone to use a few FontAwesome icons that are used in our patterns, but noticed they were missing from our icons page:

List View Vertical Ellipsis (ellipsis-v)
Toolbar Sort (sort-alpha)

**Comment by junezhang** [comment]
@lizsurette The missing icon PR has been merged. https://github.com/patternfly/patternfly-design/pull/291
You can check the latest icons on the website: http://www.patternfly.org/styles/icons/
So I closed this issue. any problem, please reopen it.

**Comment by lizsurette** [comment]
@junezhang Awesome, thank you!
