### ISSUE TITLE
Bug - Dark/light theme toggle button contrast

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#4174]
**Describe the problem**
The dark/light theme toggle in the top toolbar is using black icon color on the blue selected toggle color. The toggle component works fine, so this is likely a leftover workspace style that is breaking it.

https://staging-v6.patternfly.org/components/toggle-group

@jknilans 

**Screenshots**
![image](https://github.com/user-attachments/assets/15b38a15-3243-4892-81df-0a591b4891b3)

**Comment by evwilkin** [comment]
Closed by  #4203
