### ISSUE TITLE
Bug - Gallery view card heights not uniform

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#4179]
The gallery view (ex: [All components](https://staging-v6.patternfly.org/components/jump-links/react-demos#demos)) card views have rows of the same height but the cards within each row should stretch vertically as needed to fill the row height so that each card within a row has a matching height.
<img width="989" alt="Screenshot 2024-08-09 at 4 12 55 PM" src="https://github.com/user-attachments/assets/7f55c2bc-485c-4daa-8327-ea99ee1be794">

**Comment by edonehoo** [comment]
Seems to be closed by https://github.com/patternfly/patternfly-org/pull/4180 -- lmk if not!
