### ISSUE TITLE
Many links on http://www.patternfly.org/pattern-library/ page goes to 404 page not found

### ISSUE THREAD

**Issue by guillaumevincent** [patternfly/patternfly-org#418]
## How to reproduce:

 * go to http://www.patternfly.org/pattern-library/
 * click on links like "Dashboard Card (Base)"

![screen shot 2017-06-08 at 08 27 26](https://user-images.githubusercontent.com/943762/26914969-500349dc-4c24-11e7-997c-4f676be8f448.png)

Date Picker, Time Picker doesn't work too

**Comment by bleathem** [comment]
@mcarrano will this be addressed with the work you are coordinating to update the pattern-library index page?

**Comment by mcarrano** [comment]
I was not planning on it as these are not in the area I am working, but can look into it.  @LHinson FYI

**Comment by lizsurette** [comment]
I noticed a separate bug for the Forms link producing a 404:
https://github.com/patternfly/patternfly-org/issues/398

Also wanted to add that Input controls too, produces a 404:
http://www.patternfly.org/pattern-library/forms-and-controls/input-controls

**Comment by mcarrano** [comment]
@bleathem @bleathem These errors result from patterns that have either been renames or removed. The problem is that this Overview page is not dynamic at all so potentially breaks whenever we update or remove content in the design repo. Would there be a way to just replace this page with something that amounts to a TOC page that could be dynamically built? IMO the current overview page with thumbnail images is not that useful and causes more trouble than it's worth.

**Comment by LHinson** [comment]
@mcarrano This pattern preview is constantly giving us problem. I think we should pull the plug on the tiles. This gives us some time to come up with the automated solution. WDYT?

**Comment by mcarrano** [comment]
Yes, I'd be in favor of that @LHinson . Only question then is what we put on that page. We still need to display something when the user clicks Overview at the top of the Patterns navigation. Thoughts?

**Comment by LHinson** [comment]
There is some overview text that can remain there in order to keep the page populated. @mcarrano will you create a story in our backlog so we don't forget to do this?

**Comment by mcarrano** [comment]
I've created https://patternfly.atlassian.net/browse/PTNFLY-2571 in the PatternFly backlog to track this work. It suggests removing the thumbnails in favor of a short text description of each category. I think that may be helpful in guiding users on finding what they are looking for without having a complete table of content on this page.

**Comment by LHinson** [comment]
That sounds great. Thanks @mcarrano. I took a quick look at the code and don't feel comfortable updating this myself so glad to see a story was added!

**Comment by dabeng** [comment]
@mcarrano @LHinson , could we just extract such short text description from overview tab of every component?

**Comment by junezhang** [comment]
@mcarrano @LHinson I made a simple design for the requirement. please help to check if it is right? 

Two things we need to update as following:
- Remove the thumbnails
- Add a short text description of each category

![firefox_screenshot_2017-10-17t03-27-01 574z](https://user-images.githubusercontent.com/701009/31645449-ab9248b8-b32e-11e7-9ae4-6c0e5392085f.png)


One question here: In patternfly.org, I haven't found any descriptions for every category, could I know who is the right person to contact for the category description? Thanks.

**Comment by LHinson** [comment]
I don't think this page is frequently visited and we are going working on idea for an updated solution. I'm not sure it's worth while to spend time on this at the moment. What do you think @mcarrano?

**Comment by junezhang** [comment]
@LHinson make sense for me. I think the overview page needs a fresh update.

**Comment by mcarrano** [comment]
I agree @LHinson . One thought that we may discuss with @bleathem is embedding the pattern status matrix (http://www.patternfly.org/patternfly-design/status/) on this page. Do you think that would have value?
