### ISSUE TITLE
Needed to hit the browser Back button twice to go back

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#422]
While jumping into specific pattern pages and back out to the overview to find and view another, I noticed that I needed to hit the browser Back button twice (it skips to a '#/api' page in the middle).

**Comment by bleathem** [comment]
@dabeng can you please take a look at resolving this issue?

**Comment by dabeng** [comment]
OK

**Comment by LHinson** [comment]
Thanks @dabeng!

**Comment by LHinson** [comment]
addressed in https://github.com/patternfly/patternfly-org/pull/425
