### ISSUE TITLE
Remove hard-coded max-width from markdown pages

### ISSUE THREAD

**Issue by evwilkin** [patternfly/patternfly-org#4224]
Our website docs have an arbitrary max-width applied to a wrapper element that content loads within [in mdx.js](https://github.com/patternfly/patternfly-org/blob/v6/packages/documentation-framework/templates/mdx.js#L94) which does not always work well for all content such as large tables and causes [hacky workarounds.](https://github.com/patternfly/design-tokens/pull/72#discussion_r1713783798)

We should look at either removing this max-width and confirm a new design direction for laying out content on the page, or at least move this rule down so that each page can more easily override the value individually where needed.

**Comment by edonehoo** [comment]
Closing: This will be addressed by upcoming refactoring.
