### ISSUE TITLE
Quick starts: Cross-referencing from the Hub and PatternFly

### ISSUE THREAD

**Issue by abigaeljamie** [patternfly/patternfly-org#4238]
**Is this a new page or a change to an existing one?**
Change to existing one: https://www.patternfly.org/extensions/quick-starts/design-guidelines 

**Describe the enhancement**
The UXD Hub now features in-depth content style guidelines for quick starts (geared towards Insights but ultimately applicable across the portfolio): https://www.uxd-hub.com/entries/resource/best-practices-for-writing-quick-starts 

This issue is to update PatternFly's design guidelines' "Content considerations" section to include some information from the Hub page while still keeping things high level and general, and to cross-link the two resources.

**Comment by edonehoo** [comment]
Closed by https://github.com/patternfly/patternfly-quickstarts/pull/327
