### ISSUE TITLE
All components page: Update component illustrations 

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-org#4249]
Follow up to https://github.com/patternfly/patternfly-design/issues/1301

Goal is to replace the visuals with something more inline with v6 visual updates. This work includes some minor design updates to the layout and page content. See [mocks](https://www.figma.com/design/qnXKjGtXlqUk4PycBot9W7/pf.org%3A-All-Components?node-id=0-1&t=9MznqXhAq5ZPru9e-1) for details

**Comment by bekah-stephens** [comment]
Here's the link to the updated illustrations - both light and dark (PNGs): https://drive.google.com/drive/folders/1oseJuG1fW2goTXTHNlRBAGMPu0713K9R
