### ISSUE TITLE
Add info to PF6 migration guide regarding potential test suite impacts

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#4277]
**Is this a new page or a change to an existing one?**
Addition to the existing migration guide

**Describe the enhancement**
We should add some documentation explaining likely test failures resulting from:

1. the addition of a wrapper div to Button
1. the change to the behavior of aria-disabled on Button when using the isDisabled prop
1. potential issues with Popper content being aria-disabled in jest in some cases

Related to issues:
https://github.com/patternfly/patternfly-react/issues/10926
https://github.com/patternfly/patternfly-react/issues/10927
https://github.com/patternfly/patternfly-react/issues/10928

**Comment by edonehoo** [comment]
Closed by https://github.com/patternfly/patternfly-org/pull/4332 🎉
