### ISSUE TITLE
Bug - Front page cards are not real links

### ISSUE THREAD

**Issue by QuLogic** [patternfly/patternfly-org#4287]
**Describe the problem**
On the front page, the "Featured blog posts" and "Stay informed" cards _look_ like links, but do not really act like them. Yes, they change the cursor to a point, and you can click on them, taking you to a new page, but that's it.

**Expected behavior**
Everything that a normal link does should apply to the cards instead of them being pseudo-links:
1. Middle clicking on a card should open a new tab with the relevant link.
2. Control-clicking on a card should also open a new tab.
3. Right-clicking a card should give the options for a link (open link, open link in new window, open link in new tab, etc.)

Additionally, clicking a blog post card should _not_ open a new tab. It's not an external topic; you should leave it to the user to decide if they want a new tab. (At least for the "Stay informed" cards, some of them have the little "external link" icon to indicate this, but the blog posts don't.)

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Any other information?**

**Comment by edonehoo** [comment]
Closing: These behaviors seem to be present with the release of the PatternFly 6 site. Let me know if you continue to have issues!
