### ISSUE TITLE
Angular examples do not work

### ISSUE THREAD

**Issue by michpetrov** [patternfly/patternfly-org#431]
Some of the Angular examples do not work, e.g.
- http://www.patternfly.org/pattern-library/communication/about-modal/#/code/angular, the modal does not launch
- http://www.patternfly.org/pattern-library/communication/notification-drawer/#/code/angular, likewise, the popup does not appear
- http://www.patternfly.org/pattern-library/communication/toast-notifications/#/code/angular, the notification is not visible

Can't tell where the problem is, there are no errors in the console.

**Comment by LHinson** [comment]
@michpetrov looks like there was a change in path (need to change "directive" to "component"). I'm working on getting this updated asap. 

Thanks for filing the issue!

**Comment by LHinson** [comment]
This is no longer an issue since we now link out to the angular showcase vs displaying angular code on page so I'm closing this issue. 

Thanks for reporting @michpetrov!
