### ISSUE TITLE
PF6 documentation: mention that breakpoint token values have changed from px to rem and suggest a solution

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/patternfly-org#4314]
**Is this a new page or a change to an existing one?**
Existing one

**Describe the enhancement**
We should advise consumers that any logic they have using the pixel values of our previous breakpoint tokens will need to be updated to account for the fact that they're now in rems.

As an example one consumer function I've seen so far stripped the `px` from the token value then parsed it as an integer, now an additional step of multiplying that int by 16 (the standard rem to pixel conversion) will need to be added.

**Comment by edonehoo** [comment]
Closed by https://github.com/patternfly/patternfly-org/pull/4332 🎉
