### ISSUE TITLE
Create a spooky custom theme for PF demo

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-org#4353]
[Figma assets](https://www.figma.com/design/wLv12GzmtBov2lgEsbgZOj/Spooky-PatternFly%3A-Design-Tokens-%26-Styles?node-id=8402-2&node-type=canvas&t=9m2ie4scEiZjeyTS-0) provided by the talented @lboehling 

[Design tokens PR](https://github.com/patternfly/design-tokens/pull/95) from the master of disaster @srambach

**Comment by lboehling** [comment]
Here are the extra halloween assets I used in those mocks! 
[spooky v6 assets.zip](https://github.com/user-attachments/files/17576713/spooky.v6.assets.zip)

for the witch hat in the menu toggle, i think we could just use the free solid `fa-hat-wizard` font awesome icon for that!

**Comment by andrew-ronaldson** [comment]
https://patternfly-org-pr-4360-site.surge.sh/tokens/halloween/tokens/halloween/
