### ISSUE TITLE
Wizard does not display on Code > Angular  tab

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly-org#454]
## Steps to reproduce
Navigate to the Code tab, then Angular tab for the [Wizard pattern](http://www.patternfly.org/pattern-library/communication/wizard/#/code/angular)

The Angular example for the wizard does not display.

## Additional notes about this issue
Build the site locally, then open the file **/_site/pattern-library/communication/wizard/index.html**

Do a find for `ng-include`, and the two results below will be found. The first one has an empty `src` value while the second one has the correct value. If you comment out the `<div>` that wraps the first include, you'll see the example display as expected.

```
<div role="tabpanel" class="tab-pane nested" id="angular">
<div ng-app="docsApp" ng-controller="DocsController" class="content">
  <div ng-include src="''"></div>
</div>


            </div>
            <div role="tabpanel" class="tab-pane nested" id="angular">
              <div ng-app="docsApp" ng-controller="DocsController" class="content">

                  <div ng-include src="'/patternfly-org/components/angular-patternfly/dist/docs/partials/api/patternfly.wizard.component.pfWizard.html'"></div>

                <!-- % include  % -->
              </div>
            </div>
```

**Comment by LHinson** [comment]
Closing this issue as it has been addressed with the newest redesign of the site, linking to the angular showcase vs displaying the code in the window. see: 
http://www.patternfly.org/pattern-library/communication/wizard/
