### ISSUE TITLE
global search on patternfly.org could be improved #595

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#460]
dabeng opened this issue on Feb 14 (moved from patternfly to patternfly-org)

-----

![screenshot from 2017-02-15 10-50-02](https://cloud.githubusercontent.com/assets/5689075/22958981/629c7544-f2f8-11e6-97b9-bb893e79b974.png)

![screenshot from 2017-02-15 10-48-57](https://cloud.githubusercontent.com/assets/5689075/22958977/5c68090e-f2f8-11e6-80ed-9b46f1a248e3.png)

Maybe the latter is more welcomed by users.

**Comment by LHinson** [comment]
@jschuler wanted to make you aware of this issue filed against our current site. I think this is something we can take into consideration as we move forward.

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2018. Please let me know if this is still relevant and we will revisit.
