### ISSUE TITLE
Notification drawer: code example doesn't contain the drawer

### ISSUE THREAD

**Issue by michpetrov** [patternfly/patternfly-org#462]
The reference markup for [horizontal navigation](http://www.patternfly.org/pattern-library/communication/notification-drawer/#/example-code-1) does not contain the code for the drawer because it's conditionally included using [a page variable](https://github.com/patternfly/patternfly/blob/1afe4f17622c1f368770718266154b2979152cbd/tests/pages/_includes/widgets/navigation/horizontal-primary-nav-bar-page.html#L1-L3). (On the other hand the vertical layout seems to work the same and the drawer is included)

As a side note: I feel like there is too much code in the example, without the drawer the example has already over 700 lines, the drawer itself has another few hundred.

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2017. Please let me know if this is still relevant and we will revisit.
