### ISSUE TITLE
Can not navigate to the right widget section

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-org#466]
Steps to reproduce the bug:
1. open http://www.patternfly.org in browser
2. click Patternfly Library in top navigation bar
3. click Widgets item in the sidebar
4. click the Badges
5. the page doesn't navigate to the right widget section. The scrollbar is still in the most top place

**Comment by LHinson** [comment]
Thanks @dabeng Can you take a look at this?

**Comment by LHinson** [comment]
Closing since this has been addressed. Thanks @dabeng
