### ISSUE TITLE
Many input boxes of widgets overlay the navigation bar of patternfly.org

### ISSUE THREAD

**Issue by dabeng** [patternfly/patternfly-org#467]
Using mouse wheel to browse the widgets page, you will find the following bugs.

![screenshot from 2017-09-14 15-29-51](https://user-images.githubusercontent.com/5689075/30417583-db11cc1a-98f5-11e7-91a1-e7d764c32215.png)
![screenshot from 2017-09-14 15-30-11](https://user-images.githubusercontent.com/5689075/30417589-e20d7e24-98f5-11e7-98ab-bf84ae555e3b.png)
![screenshot from 2017-09-14 15-30-16](https://user-images.githubusercontent.com/5689075/30417598-e9ba4bde-98f5-11e7-8358-800ba9847c98.png)
![screenshot from 2017-09-14 15-30-35](https://user-images.githubusercontent.com/5689075/30417628-131e84c2-98f6-11e7-827f-f0e0450c36d9.png)
![screenshot from 2017-09-14 15-30-47](https://user-images.githubusercontent.com/5689075/30417649-2191bc68-98f6-11e7-9897-543e9386120c.png)

**Comment by LHinson** [comment]
@dabeng can you look at this one?

**Comment by mattreid** [comment]
![screen shot 2017-09-18 at 1 44 57 pm](https://user-images.githubusercontent.com/1242413/30702567-4d8fdc94-9ebb-11e7-94b9-95d3f6aa8b09.png)
The table page size widget on the Table page also goes through the header area if you can get the page to scroll that much.

**Comment by LHinson** [comment]
https://github.com/patternfly/patternfly-org/pull/469 was merged so closing this one.
