### ISSUE TITLE
Bug: Info tip .navbar-toggle also toggles the site's navbar

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-org#474]
![screen shot 2017-10-06 at 10 24 46 am](https://user-images.githubusercontent.com/895728/31282633-24b8e1ea-aa81-11e7-91c9-8d6d62b53d71.PNG)

This is because [the site's navbar toggle no longer has a data-target attribute](https://github.com/patternfly/patternfly-org/commit/a45f9875fc878a3ae36579e6758d54731d0bff3d#diff-fe2a7a2cb093214a3aacbcc17613c498R18).

**Comment by dabeng** [comment]
Hi @rhamilto Could you give more details on repro steps ? I'm not sure which two navbars have a conflict.

**Comment by dabeng** [comment]
Hi @rhamilto . I investigate this further and find the following code snippets cause the issue:
source/assets/js/patternfly-site.js
```js
  jQuery('.navbar-toggle').on('click', function (e) { // line 97
    jQuery('.navbar-sidebar').toggleClass('open');
  });
```
The selector ".navbar-toggle" will get two toggle buttons.
<img width="749" alt="screen shot 2018-01-30 at 2 32 19 pm" src="https://user-images.githubusercontent.com/5689075/35553065-484a3072-05d1-11e8-8836-48115c366919.png">

So here's my preliminary solution and **[demo](https://rawgit.com/dabeng/patternfly-org/info-tip-dist/_site/pattern-library/widgets/#info-tip)** page:
```js
  jQuery('.navbar-fixed-top .navbar-toggle').on('click', function (e) { // line 97
    jQuery('.navbar-sidebar').toggleClass('open');
  });
```
@jeff-phillips-18 @matthewcarleton @priley86 . Do you have any thoughts about this bug-fix ?

**Comment by dabeng** [comment]
Hi @rhamilto , if add data-target prop to site's navbar toggle button, we will get the following efffect:
![datatarget](https://user-images.githubusercontent.com/5689075/35718444-8a5afbea-081f-11e8-9d87-c1e6313ba33f.gif)

By comparison, horizontal sliding is better。

**Comment by jeff-phillips-18** [comment]
The key here would be to get the InfoTIp's data-target to be used. It is different from the site's navbar so I'm not sure why its triggering both.

**Comment by cliffpyles** [comment]
@dabeng This solution looks good to me. The root of the problem seems to be multiple event listeners on the element. One of the listeners wasn't intentional.
