### ISSUE TITLE
Notification drawer examples differ

### ISSUE THREAD

**Issue by rhamilto** [patternfly/patternfly-org#487]
The [HTML/CSS](https://www.patternfly.org/pattern-library/communication/notification-drawer/#/code/html-css) examples do not utilize a hover state on individual notifications.  

<img width="323" alt="screen shot 2017-10-26 at 10 42 59 am" src="https://user-images.githubusercontent.com/895728/32059555-819f1802-ba3a-11e7-91d5-c6bb65e949a3.PNG">

The [Angular](https://www.patternfly.org/pattern-library/communication/notification-drawer/#/code/angular) example does.  

<img width="324" alt="screen shot 2017-10-26 at 10 43 12 am" src="https://user-images.githubusercontent.com/895728/32059585-908648e0-ba3a-11e7-9a14-f47f7080a8f7.PNG">

The [design documentation](https://www.patternfly.org/pattern-library/communication/notification-drawer/#/design) does not specify when to use a hover.  Which is correct?

See https://github.com/openshift/origin-web-console/pull/2383#discussion_r147146449

**Comment by serenamarie125** [comment]
@rhamilto thanks for adding this issue.  This is a problem in that our documentation and Angular implementation match, but our core implementation does not match the documentation @LHinson

**Comment by beanh66** [comment]
@LHinson When we update the core implementation and documentation, we should be sure to cover the hover state as well as the cursor change and how those relate to read and unread notifications. 

Note we are proceeding with the following behavior in the product: 
- Always (for read and unread notifications) use the blue hover state as specified in the design documentation 
- For unread notifications, use the hand cursor on hover 
- For read notifications, use the regular pointer cursor on hover
- Always show the hand cursor for links/ actions that are clickable on a read or unread notification row

**Comment by beanh66** [comment]
@mcarrano FYI

**Comment by mcarrano** [comment]
This issue is incorrectly files against patternfly.org and should be closed. A new issue has been filed against the PatternFly core implementation to update the core implementation to include the hover state over rows thus matching the Angular JS implementation.

I have also filed an issue in patternfly-design to look at use of hand vs. pointer cursors across patterns to identify a more consistent approach.
