### ISSUE TITLE
Patternfly blog page visual design issue

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#513]
moving this from the patternfly core repo seen here [#935](https://github.com/patternfly/patternfly/issues/935)

**Comment by mcarrano** [comment]
@dabeng I agree that the PatternFly blog login page is not great, but realistically this is only accessed by a few people who are authorized to create blog posts. Not sure we would prioritize this or how to update this as I know this login is served up from Wordpress.

@LHinson thoughts?

**Comment by LHinson** [comment]
This is not a priority to address given the limited audience. While not idea, it still works. I'm closing this issue as we will not address at this time or in the near future.

**Comment by dabeng** [comment]
I get it. Thank you for explanation.
