### ISSUE TITLE
Moment.js vulnerability package.json dependency

### ISSUE THREAD

**Issue by amarie401** [patternfly/patternfly-org#534]
There is a security vulnerability in moment.js. Since this is for the site then it should be okay to update the package.json to the latest version. @dabeng could you take a look at this? I don't think updating this package will have any effect on the examples on the site but would like a second opinion on this.

**Comment by dabeng** [comment]
Yes @amarie401 . I agree with you. I find that moment.js dependency has been upgraded to[ ^2.19.1](https://github.com/patternfly/patternfly/blob/master/package.json#L84). So I think it will be okay to update the package.json of patternfly.org repo to the same version.

**Comment by amarie401** [comment]
Thanks for fixing this @dabeng will close this issue now.
