### ISSUE TITLE
abstract all third-party dependencies to external link

### ISSUE THREAD

**Issue by amarie401** [patternfly/patternfly-org#538]
There has been issues where the pf-org site does not deploy/update due to the deploy size being exceeded. More recently this has been caused by a moment.js version update. See Travis: https://travis-ci.org/patternfly/patternfly-org/builds/355880364#L1900

The proposed solution is removing the thirdy-party dependencies and using a CDN instead. 

This was done recently for bootstrap slider in this PR: https://github.com/patternfly/patternfly-org/pull/531

 We're pushing unused source as well:

./bootstrap-switch/src
./bootstrap-touchspin/src
./c3/src
./d3/src
./eonasdan-bootstrap-datetimepicker/src
./google-code-prettify/src
./jquery/src
./moment/src
./patternfly-bootstrap-treeview/src
./wowjs/src

@dlabrecq @dgutride @dabeng

**Comment by dabeng** [comment]
Great idea :+1: Amiee
