### ISSUE TITLE
Remove "Name" dropdown in front of filter field on Pattern Overview page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#544]
Since the filter control on the Pattern Overview page (http://www.patternfly.org/pattern-library/) is not localized to a single attribute, the attribute dropdown is confusing and unnecessary. I should just be removed (or alternately include Name and Category and localize the filter to a single attribute at a time).

**Comment by amarie401** [comment]
@mcarrano when you say attribute dropdown are you referring to removing the caret but keeping name?

Just want to clarify.

**Comment by mcarrano** [comment]
I mean to remove the dropdown entirely.

**Comment by amarie401** [comment]
@mcarrano sounds good! thanks 👍

**Comment by amarie401** [comment]
This allows for more localization with the filter/search now by Name and Category. 

Thoughts? @mcarrano @LHinson 

<img width="1341" alt="screen shot 2018-04-05 at 8 47 18 pm" src="https://user-images.githubusercontent.com/20052391/38398607-e214d062-3912-11e8-87c1-1e96dbdfb07f.png">
<img width="1343" alt="screen shot 2018-04-05 at 8 47 44 pm" src="https://user-images.githubusercontent.com/20052391/38398610-e3570f9e-3912-11e8-9df1-c937f5f432d4.png">
<img width="1342" alt="screen shot 2018-04-05 at 8 48 00 pm" src="https://user-images.githubusercontent.com/20052391/38398611-e4ade980-3912-11e8-8a22-b31f3868d28b.png">

<img width="1342" alt="screen shot 2018-04-05 at 8 55 19 pm" src="https://user-images.githubusercontent.com/20052391/38398731-b5f1d40c-3913-11e8-8716-d212b8add725.png">

**Comment by mcarrano** [comment]
Looks good @amarie401 . I like that you are using the PF filter bar here so users can mix and match attributes if they want.  Good stuff!

**Comment by LHinson** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/eb1a2ea1-7c1f-4a92-abdb-e89cdc52edfd-15206079-98a4-479e-bb46-baa63bbd1a81-v1.png?transparent=1&palette=1&width=246)
