### ISSUE TITLE
Add dev notes for context selector

### ISSUE THREAD

**Issue by amarie401** [patternfly/patternfly-org#550]
Dev notes for the context selector should be added to specify the usage of bootstrap select, it's relation to the vertical navigation, the classes involved, and any additional notes that developers should be aware of when consuming this component.

Related to this PR: https://github.com/patternfly/patternfly-org/pull/532

See this wiki for contributing dev notes to org: [here](https://github.com/patternfly/patternfly-org/wiki/Contributing-Code-Examples#adding-developer-notes-to-code-examples)

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2018. Please let me know if this is still relevant and we will revisit.
