### ISSUE TITLE
Update Login Code Example to Account for Updated Styling

### ISSUE THREAD

**Issue by mindreeper2420** [patternfly/patternfly-org#553]
The Login code example currently on PatternFly.org will need to be updated to reflect the changes put forth by PR https://github.com/patternfly/patternfly/pull/1024. This moves the class `.login-pf` from the `<html>` element to the `<body>` element.

**Comment by amarie401** [comment]
@matthewcarleton you want me to take this to update the dev notes?

**Comment by matthewcarleton** [comment]
@amarie401 if you have the time. Just let me know if you need any help with it. Thanks!

**Comment by amarie401** [comment]
@matthewcarleton sooo I'm not sure exactly what needs to be changed since in the current dev notes we only list `login-pf-page` and not `login-pf` does this need to be added? Might be better if you or @mindreeper2420 made the update to `doc.md` table.

**Comment by matthewcarleton** [comment]
Hey @amarie401 this would be in addition to `login-pf-page`. @mindreeper2420 are you able to take care of this, I think you are more familiar with the specifics of it. Let me know if you want me to jump in though.

**Comment by amarie401** [comment]
Since I'm not familiar with the specifics of it then it might be better if you took this one @mindreeper2420 and make the necessary changes in the `doc.md` table of the login-page.

**Comment by mindreeper2420** [comment]
@amarie401 Sure, I'll take a stab at it. According to the `login.less` file, this is for the older pattern, so I'll clarify that in the `doc.md` update :)

**Comment by amarie401** [comment]
Also FYI because the pf core build is currently broken after your login changes, org cannot pick up the latest changes so it will still show`.login-pf` class on the `<html>` element.

**Comment by mindreeper2420** [comment]
PR submitted: https://github.com/patternfly/patternfly-org/pull/557. My first to patternfly-org, so please let me know if I missed something :)
