### ISSUE TITLE
Bootstrap Select dropdown not showing results

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#554]
Located here: http://www.patternfly.org/pattern-library/widgets/#bootstrap-select

It shows a blank list. Tested in Chrome, Safari and Firefox on MacOS high Sierra. 
<img width="286" alt="screen shot 2018-04-24 at 12 56 56 pm" src="https://user-images.githubusercontent.com/287880/39199061-fc873d26-47be-11e8-8554-2cb3f7ca6540.png">

**Comment by dabeng** [comment]
@matthewcarleton I think this issue is caused by the version mismatch between bootstrap-select.js(1.13.1) and bootstrap.css(1.12.2)

**Comment by dabeng** [comment]
Feel free to play around with https://codepen.io/dabeng/pen/zjBOLO and checkout different version matching. I recommend to set bootstrap-select dependency to ~1.12.2 both on patternfly repo and patternfly-org repo.

**Comment by matthewcarleton** [comment]
ok I'm going to close this so the conversation can continue in #555
