### ISSUE TITLE
Add inline-edit example to pf org

### ISSUE THREAD

**Issue by amarie401** [patternfly/patternfly-org#556]
The inline edit example should be added to pf-org.

Recently merged in PF core: https://github.com/patternfly/patternfly/pull/979

**Comment by amarie401** [comment]
Issue in core needs to be filed to add `forms.less` to `patternfly-additions.less` for pf-org consumption for this example otherwise it cannot consume the styles:

<img width="1143" alt="screen shot 2018-04-24 at 5 30 35 pm" src="https://user-images.githubusercontent.com/20052391/39216041-26c554dc-47e8-11e8-9f91-6b62fe916f0e.png">

**Comment by dabeng** [comment]
Hi @amarie401 Thanks a lot for contributing code to add inline edit example on patternfly.org site 👍

I find that forms.less has been imported by patternfly-adjusted.less - https://github.com/patternfly/patternfly-org/blob/master/source/_less/patternfly-adjusted.less#L19

**Comment by amarie401** [comment]
I wasn't using the latest you are right, thanks for your help @dabeng I will add you as a reviewer once the PR is up :)
