### ISSUE TITLE
Error 404 on download page

### ISSUE THREAD

**Issue by ia3andy** [patternfly/patternfly-org#560]
From the http://www.patternfly.org/ if I click on `Download`, I end up on http://www.patternfly.org/download/ with a `404` message:

![image](https://user-images.githubusercontent.com/2223984/39356208-b3fb7dd0-4a0f-11e8-9773-daaf6c882876.png)

**Comment by amarie401** [comment]
Hi @ia3andy there was a decision to remove the download page a few weeks ago. Please see this  PR for more information. There is now a Repositories page.

PR: https://github.com/patternfly/patternfly-org/pull/541

**Comment by amarie401** [comment]
@ia3andy where do you see a link to the download page? I am curious since the link to access that page has been removed.

**Comment by ia3andy** [comment]
There on the left side "Code Download":
![image](https://user-images.githubusercontent.com/2223984/39364907-e242d98e-4a2f-11e8-96a2-3a150b9e82a8.png)

**Comment by amarie401** [comment]
I see! Thanks @ia3andy 👍

**Comment by ia3andy** [comment]
@amarie401 👍 Always happy to help ;)

**Comment by amarie401** [comment]
fix has been merged #561
