### ISSUE TITLE
blog post about accessibility leads to 404

### ISSUE THREAD

**Issue by abonas** [patternfly/patternfly-org#563]
https://blog.patternfly.org/patternfly/accessibility-is-usability/ leads to 404
(not sure if this should be fixed in this repo or not)

**Comment by amarie401** [comment]
I believe this issue is fixed now @mindreeper2420 I know you did something in relation to the blog if I'm not mistaken?

**Comment by LHinson** [comment]
Yeah, this is resolved so I'm going to close. Thank you both!
