### ISSUE TITLE
It would be friendlier to have unique titles for pages

### ISSUE THREAD

**Issue by mattreid** [patternfly/patternfly-org#569]
The current PF site uses the same name for any page. After having browsed several pages and wanting to go back to a specific one, I right clicked on the back button to see all the pages I went to, and there's nothing to help me know which is the right one without just blindly going backwards a bunch.

It'd be nice if the pages were named uniquely so I could know which page I was going to when doing something like this.

![screen shot 2018-05-22 at 1 25 10 pm](https://user-images.githubusercontent.com/1242413/40380093-077b72e8-5dc6-11e8-8a10-71652199fa09.png)

**Comment by amarie401** [comment]
I can look more into this @mcarrano

**Comment by amarie401** [comment]
It seems that the pages that actually do show a unique title in the back button/history all have front matter with a title. I tried adding front matter with a title to the `code.md` files for each pattern but that doesn't appear to work. @dabeng do you have any idea how to do this?

**Comment by dabeng** [comment]
Hi @amarie401 @mcarrano  I created a [demo page](https://rawgit.com/dabeng/patternfly-org/page-title/_site/pattern-library/) to add unique title for some sub pages of patternfly library section. If you are content with this Demo, I'll continue forward with PR.

![ezh8snipvb](https://user-images.githubusercontent.com/5689075/40601320-48171576-6287-11e8-839b-c4227b418889.gif)

Additional info, I just add unique title for pages under categories "Application Framework" and "Cards"

**Comment by amarie401** [comment]
@dabeng Your demo looks great to me, if you could add the unique titles to the other categories as well then please continue forward with a PR for this. Thanks! 👍

**Comment by amarie401** [comment]
This issue has been fixed and the PR has been merged. I will go ahead and close this.
