### ISSUE TITLE
Can't copy pficon-enhancement icon from Icons page

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-org#575]
The copy to clipboard feature doesn't work on the pficon-enhancement Icon on the Icons page. All others seem to be working fine.

**Comment by michpetrov** [comment]
There's a class missing in the [source file](https://github.com/patternfly/patternfly-design/blob/master/styles/icons/icons.md) at patternfly-design. It's a trivial fix but perhaps it would be better to separate the data from the table to avoid this kind of issue.

**Comment by mcarrano** [comment]
I have opened a new issue in patternfly-design here to address this: https://github.com/patternfly/patternfly-design/issues/674 and will close this one out.

@michpetrov Welcome any ideas about a better way to structure this. Agree that the markdown is currently messy and leaves us open to these types of errors.
