### ISSUE TITLE
Information Architecture: Taxonomy/Competitive Review

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#578]
In this issue, design will research and become familiar with the industry standards for design system IAs as well as the current PatternFly IA proposal. The result of this issue is to:

- Determine current gaps or questions with the IA proposal and identify potential solutions or additional issue to identify solutions
- Review current studies around and results around the preferences for a flat IA 

Resources 
[need IA proposal @mcarrano} 
[need IA category definitions @mcarrano] 
[research from sara]

**Comment by dmiller9911** [comment]
Wanted to add my opinion on this.  As a developer, I am not a fan of the nested views. I usually have to expand two or three before I find what I am looking for. Most systems for React have a single section for components so it is easy to `ctrl + f` to find the components. Some good examples where I can quickly find the docs I need:

https://material-ui.com/getting-started/installation/
https://mineral-ui.com/getting-started
https://react.lightningdesignsystem.com/components/accordions
https://atlassian.design/guidelines/product/overview
http://blueprintjs.com/docs/v2/#core

All of these have components all together.

**Comment by rachael-phillips** [comment]
Completed Exercise

**Comment by rachael-phillips** [comment]
Completed Exercise
