### ISSUE TITLE
Update date-time-picker name in code.md

### ISSUE THREAD

**Issue by amarie401** [patternfly/patternfly-org#579]
A recent [merge](https://github.com/patternfly/patternfly-design/pull/676) in the design repo and file name [change]( https://github.com/patternfly/patternfly-design/pull/676/files#diff-98cd7b8ca62f8ed8654710bcebe71b15R6) has caused the travis build to fail due to not being able to find the file in that path. This will just require updating the path name.

Error:

```
Liquid Exception: Could not locate the included file 'code/forms-and-controls/date-and-time/code.md' 
in any of ["/home/travis/build/patternfly/patternfly-org/_build/_includes"]. Ensure it exists in 
one of those directories and, if it is a symlink, does not point outside
 your site source. in /_layouts/page-pattern.html
```

**Comment by mcarrano** [comment]
@amarie401 Sorry about this. We had changed the name of this pattern in the design library from "Datepicker" to "Date and Time" and I did not realize that there was a build dependency.

**Comment by amarie401** [comment]
No worries @mcarrano! I'll submit a PR to fix this issue soon!
