### ISSUE TITLE
PatternFly -> Cards -> Aggregate Status Card -> Code -> Angular-PatternFly : missing images

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-org#58]
![image](https://cloud.githubusercontent.com/assets/12733153/15401455/a7afaac2-1dbd-11e6-83ad-489ae5a16a9a.png)

**Comment by dlabrecq** [comment]
The angular-patternfly examples are looking for img/kubernotes.svg and img/OpenShift-logo.svg, which are not in patternfly-org -- not even the correct directory structure.

**Comment by dlabrecq** [comment]
Fixed.
