### ISSUE TITLE
Define PatternFly 4 - Value Prop, Tone, & Voice

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#585]
Write 1-2 sentences that summates PatternFly 4's value prop. What will make users engaged with PatternFly 4?

Value prop leads the tone and voice for the homepage. Homepage will be a good place to start for establishing out voice.

**Comment by stacymcauliffe** [comment]
Starting putting together notes around Value Prop content: 
https://docs.google.com/document/d/1aI5r4Qlu0ASXbva0TthHqE3JRHGpS-xyyKg-HheWSt8/edit?usp=sharing

**Comment by rachael-phillips** [comment]
We resolved this issue.
