### ISSUE TITLE
Angular-PatternFly Plunker examples aren't styled correctly

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-org#59]
I believe the PF javascript is referenced correctly in the generated Plunker, however none of the PF styles/css seems to be included:

![image](https://cloud.githubusercontent.com/assets/12733153/15401817/398c6a4c-1dbf-11e6-968c-906d048a853b.png)

Note: this issues exists in the angular-patternfly ng-doc generation.  Research might have to be done to figure out how the ngdocs bower lib generates the Plunker exercises, and to have the process include the appropriate css.

**Comment by dlabrecq** [comment]
I'm not sure I completely understand the issue, but it's the same for angular-patternfly.rhcloud.com. This page is a direct include from angular-patternfly.

**Comment by dtaylor113** [comment]
Ok, updated an a-pf issue:

https://github.com/patternfly/angular-patternfly/issues/65

- Dave
