### ISSUE TITLE
PF.org footer Twitter, Facebook, and google+ links; should they open in new tabs/windows?

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-org#60]
Just annoying, I clicked on Twitter, which went to PF twitter page, however it replaced PF.org, so when I closed the twitter window, I had to re-launch PF.org.

**Comment by dtaylor113** [comment]
On the Community page, these same links do open Twitter, FB, and G+ in new tabs/windows.

**Comment by dlabrecq** [comment]
Added target="_blank" to open in new tab/window.
