### ISSUE TITLE
What is the purpose of Icon "Cheatsheet"?

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-org#62]
There are little differences between the main Icon page and the linked icon "Cheatsheet".  Just wondering if we should combine the two pages into one.

The list of PF icons are the same in the main Icon page and the 'cheatsheet', however the cheatsheet does have additional functionality:

"To use on the desktop, install PatternFlyIcons-webfont.ttf or FontAwesome.otf, set it as the font in your application, and copy and paste the icons directly from this page into your designs."

- the .ttf and .otf files are links which downloads the files when clicked
- If you hover over a PF icon you get a "Copy to clipboard" which works, I guess, not sure where I'm supposed to 'paste' the content.  Pasted into text editor and IDE, but displayed a binary object?

"
![image](https://cloud.githubusercontent.com/assets/12733153/15402528/ab96fe74-1dc2-11e6-8d57-a1d8f2f06d48.png)

Seems like we could add the same functionality to the main Icon page and remove the 'cheatsheet'

**Comment by Rohoover** [comment]
I like this idea, but for search purposes, if someone were to type "cheatsheet", the PF icon list would need to show up. Cheatsheet isn't something coined by PF.

**Comment by dlabrecq** [comment]
@LHinson We plan to keep the cheat sheet, right?

**Comment by LHinson** [comment]
@Rohoover @dlabrecq @dtaylor113 check out the future plans for the icons page here - https://patternfly.atlassian.net/browse/PTNFLY-1034

**Comment by Rohoover** [comment]
Looks great. Love the columns that outline usage.
