### ISSUE TITLE
Widgets nav in alphabetical order, but widgets themselves are not

### ISSUE THREAD

**Issue by cshinn** [patternfly/patternfly-org#63]
This makes it sort of hard to find things because it is unclear where you are on the page

**Comment by dlabrecq** [comment]
Yes. I believe this is in the backlog and depends on Joe's research. Thanks for the feedback.

**Comment by LHinson** [comment]
Whoops, sorry didn't meant to close. This is important :) Yes, we are waiting on feedback from Joe. I'll check in with him to see if we can at least make this update.

**Comment by dlabrecq** [comment]
Reordered the widgets in alphabetical order. Will adjust widgets page, after receiving Joe's feedback, if necessary.
