### ISSUE TITLE
No nav link that takes users to top of widgets page

### ISSUE THREAD

**Issue by cshinn** [patternfly/patternfly-org#64]
As far as I can tell, there is no nav link that takes users to https://v2-patternfly.rhcloud.com/pattern-library/widgets/ 

Clicking on the "widgets" menu item should probably link there in addition to expanding the accordion (because there is a "widgets" page unlike the other primary nav categories)

**Comment by dlabrecq** [comment]
You're right in that there is no direct link to widgets. In fact, we don't have direct links to any of the menu items. For example, if you want to navigate to trend card, users must first click on cards to expand the sub-menu. Not sure we want to change the navigation behavior for widgets only? However, I'll defer to @LHinson.

**Comment by cshinn** [comment]
the current format would make sense to me if it weren't for the widgets summary paragraph and title at the top of the page. the only way to get up there right now is to go to a specific widget and scroll to the top of the page

**Comment by dlabrecq** [comment]
Right. We're planning to make some changes here. For example, we will remove the sections labeled; CSS, JavaScript, etc. and create an overview at the top. So, above the accordion menu item, there will also be an overview menu item. Waiting for Joe's research, but believe we will start making changes soon.

**Comment by dlabrecq** [comment]
Added an overview link at the top of the widgets menu. Will adjust widgets page, after receiving Joe's feedback, if necessary.
