### ISSUE TITLE
Content - Contribute

### ISSUE THREAD

**Issue by stacymcauliffe** [patternfly/patternfly-org#640]
Create content for the contribute experience

- [x] Contribute for devs
- [x] Contribute for designers
- [ ] Determine where this lives in the repo (contribute.md)

**Comment by gdoyle1** [comment]
-- Notes from meeting -- 

MVP launch solution for designers:
1. Colleen's documentation on contribution - surface these guidelines to contributors
- Workflow and timeline (slide 99)
- Types
- Examples
--> AI: Take a pass at putting this info together and put it in a google doc and get Stacy, Rachael and Matt C's approval --> final deliverable will be an .md file
--> Tweak Liz's designs

Set of issues to address in the future:
1. patternfly-design - contribution instruction variation 1
--> contributing.md file based on pf3
2. patternfly-react - contribution instruction variation 2
3. patternfly-core - contribution instruction variation 3

**Comment by gdoyle1** [comment]
Here's what I started! @rachael-phillips @stacymcauliffe https://docs.google.com/document/d/14YcBbXwBXNNy1fJxedcyw9cnZk8lCOA5QGzBFtewUOo/edit?usp=sharing

**Comment by gdoyle1** [comment]
https://docs.google.com/document/d/14YcBbXwBXNNy1fJxedcyw9cnZk8lCOA5QGzBFtewUOo/edit?usp=sharing @stacymcauliffe @rachael-phillips I finished the content for both designers and developers here. Thoughts?

**Comment by mcarrano** [comment]
@gdoyle1 @stacymcauliffe @rachael-phillips @LHinson I just did a review of the draft content and suggested a bunch of changes around the design contribution process. See my comments and suggestions in the Google doc here: https://docs.google.com/document/d/14YcBbXwBXNNy1fJxedcyw9cnZk8lCOA5QGzBFtewUOo/edit?usp=sharing

Do these proposed changes make sense? If not, we can meet and review.
