### ISSUE TITLE
Broken link for bootstrap-datetimepicker documentation

### ISSUE THREAD

**Issue by michaelkro** [patternfly/patternfly-org#646]
The link to the `bootstrap-datepicker` doc found [in the description on this page](https://www.patternfly.org/pattern-library/forms-and-controls/date-and-time/) points to

```
http//eonasdan.github.io/bootstrap-datetimepicker/
```

which does not work.  Needs to be updated to

```
https://eonasdan.github.io/bootstrap-datetimepicker/
```

**Comment by rachael-phillips** [comment]
I'm closing this issue as it hasn't been visited since 2018. Please let me know if this is still a concern and we will revisit.
