### ISSUE TITLE
Bottom of PF Home/Splash page, 'Featured Content' carousel, clickable?

### ISSUE THREAD

**Issue by dtaylor113** [patternfly/patternfly-org#65]
Just seems to show images with no text and clicking on images doesn't do anything.

**Comment by dlabrecq** [comment]
There is a story in the backlog to change the controls. Until then, you have to give it a few seconds before it begins scrolling -- controls will also appear toward the bottom.

**Comment by dtaylor113** [comment]
I assume at a later time, a user be able to click on images to get more information on the feature?

**Comment by dlabrecq** [comment]
It's not click-able on the existing web site. However, I'll make sure to speak about it with @LHinson.

**Comment by LHinson** [comment]
@dtaylor113 there is an update to this. It includes a "learn more" link that takes the user to the relevant page.

**Comment by dlabrecq** [comment]
Done. There is now a "more information" link, in addition to navigation controls -- see #86.
