### ISSUE TITLE
Migration Guide

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#658]
Content and dev should work together to create a readable, usable migration guide. The Migration guide should help users migrate to PF4 in a couple different ways:

1. Reading the holistic migration guide in order to understand migration to PF4.
2. Migration at the component level.

**Comment by stacymcauliffe** [comment]
Notes from conversation with Dana: 
There are considerations for migration from a dev perspective, but it's vital to start a migration conversation off with design considerations:

-How is existing layout going to be impacted by this change?
-Nav structure and options are likely going to be impacted- what do designers need to know?
-From a visual perspective, what do we need to consider? Does placement need to change? How is spacing impacted?
-Other points of possible conflict from an interaction design perspective...

This document should walk designers through the pertinent issues they may face, show them how to create a solid plan of action, and then help them communicate with dev about how to execute on that plan.

**Comment by stacymcauliffe** [comment]
Submitted PR #996 for this issue

**Comment by rachael-phillips** [comment]
This work has been completed
