### ISSUE TITLE
Verify placement: Red Hat logo, legal text, social media buttons

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#66]
I'm not aware of the correct design but it seems odd that the red hat logo, legal text and social media icons are all inline within the what's new row. Can/should they be moved to white row below?

![screen shot 2016-05-19 at 1 21 47 pm](https://cloud.githubusercontent.com/assets/18266453/15402994/d5b8bb50-1dc4-11e6-8576-6eb601361b65.png)

I noticed in mobile it's overlapping content.

![screen shot 2016-05-19 at 1 23 55 pm](https://cloud.githubusercontent.com/assets/18266453/15403045/ffa6d032-1dc4-11e6-833e-bc31ad091b7e.png)

**Comment by sjcox-rh** [comment]
Roxanne you are correct.  That content should be on it's own white section at the bottom of the page.  Same as other sub pages within site.  

See attachment for correct implementation (+ Red Hat logo, not sure why it's missing on that page.  I'll open another issue for that):

<img width="1176" alt="screen shot 2016-05-19 at 10 58 07 am" src="https://cloud.githubusercontent.com/assets/16257540/15404078/bd731b80-1db0-11e6-9495-6b789406ac93.png">

**Comment by dlabrecq** [comment]
This may be the result of making the footer float. That is, when the page does not have much content, the footer should always float to the bottom of the page.

I see the overlap on a non-mobile browser, too. We may need help from @cardosogabriel on this?

In the mean time, please look at another page to see if the footer is dispayed properly? For example:

https://v2-patternfly.rhcloud.com/pattern-library/cards/aggregate-status-card/#/api

**Comment by cardosogabriel** [comment]
Well observed @Rohoover . @dlabrecq , I'm taking a look at the issue.

**Comment by cardosogabriel** [comment]
Fix submited at https://github.com/patternfly/patternfly-org/pull/72

**Comment by dlabrecq** [comment]
Fixed.
