### ISSUE TITLE
Getting Started Pages 

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#667]
A first draft of our Getting Started pages for designers, React dev, and Core dev.

**Comment by stacymcauliffe** [comment]
Made updates to HTML procedure - content is ready for review: https://docs.google.com/document/d/1eUO6AywaB6QhN2RuXkEA1mtzuHriL15c9pjH4ahm0uA/edit?usp=sharing

React is still a WIP

**Comment by gdoyle1** [comment]
InVision link with designs: https://redhat.invisionapp.com/share/RNPUZIBCU2Q
