### ISSUE TITLE
Footer for site

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#669]
Gina created footer for site.

**Comment by gdoyle1** [comment]
<img width="851" alt="screen shot 2019-01-10 at 10 17 37 am" src="https://user-images.githubusercontent.com/30870144/50977777-fa78ae00-14c0-11e9-964f-555ef521e1d0.png">
This is what I came up with for the footer. I was thinking we could have a third column of links but wasn't sure what to put there that wouldn't change if the toggle were to switch from HTML to React. Let me know what you think! @rachael-phillips

**Comment by gdoyle1** [comment]
I agree layouts and styles may be up in the air across React/Core - I was thinking the links would navigate users to the main page of layouts/styles, without going to a specific layout or style. And you're right about the order - I'll change that to match the same as it is on the left nav.

**Comment by rachael-phillips** [comment]
That sounds like a good plan. On Styles, fyi there looks like there's a redundancy with the React storybook (something new that has come up), so we'll probably need to solve for in the site design as to not have two Styles categories that mean two different things: http://patternfly-react.surge.sh/patternfly-4/components/backgroundimage/ . We could rename Styles for design to something else.
