### ISSUE TITLE
Search experience and Mapping tags for Search

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#670]
Requirements for this issue:
- Define the search functionality with dev
- Define search by tagging - complete exercise to map specific search terms as keywords. For example. header vs. masthead. The user could search for either.
- Find a technical solution for search. Ex. Algolia plug in
- Design a search results page

**Comment by gdoyle1** [comment]
@rachael-phillips is this the same as #668 ?

**Comment by rachael-phillips** [comment]
This is looking great!

**Comment by gdoyle1** [comment]
Still fleshing out how search will look but here's what I'm thinking https://redhat.invisionapp.com/share/W3Q3PI2RNFV

**Comment by gdoyle1** [comment]
Updates to search interaction wireframes:https://redhat.invisionapp.com/share/W3Q3PI2RNFV#/342294335_Search_Interaction

Icon mapping (still fleshing out the components): https://docs.google.com/spreadsheets/d/10aL0kQzicpS6bM6sIyE1nznfkI393qdMj3luIErYtA0/edit?usp=sharing

**Comment by gdoyle1** [comment]
@jschuler @rachael-phillips Here are the wireframes and documentation for search. Let me know if you need anything else here! https://redhat.invisionapp.com/share/W3Q3PI2RNFV

**Comment by rachael-phillips** [comment]
Closed issue because this work has been complete.
