### ISSUE TITLE
Styles Pages

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#677]
We'll need pages for colors, typography, content, etc.

**Comment by gdoyle1** [comment]
Here's my first pass on the colors page: https://redhat.invisionapp.com/share/9GQCHXH46QV. Still working on this!

**Comment by gdoyle1** [comment]
@jschuler @rachael-phillips @stacymcauliffe Here are the wireframes for typography. Please give some feedback there if anyone thinks there's missing aspects! https://redhat.invisionapp.com/share/Z7QELXXAXUR (commented on wrong issue at first - sorry)

**Comment by gdoyle1** [comment]
@jschuler @rachael-phillips Here's the icons page! In my opinion, I think we only need the icon listing page for MVP (with all interactions documented on the screens). Here's the listing of all icons being used in the designs as of right now in "Icon listing" https://docs.google.com/spreadsheets/d/10aL0kQzicpS6bM6sIyE1nznfkI393qdMj3luIErYtA0/edit?usp=sharing.

**Comment by gdoyle1** [comment]
https://redhat.invisionapp.com/share/FCPVCIVHUJ8 @jschuler @rachael-phillips Here are the icons pages designs! The spec is in there too.

**Comment by gdoyle1** [comment]
@jschuler @rachael-phillips Here is the Spacers page design! Spec is in the InVision project as well. https://redhat.invisionapp.com/share/JBQL3AE8G4S

**Comment by gdoyle1** [comment]
All styles pages will be found in this InVision project from now on: https://redhat.invisionapp.com/share/3WQLMKRU6M2

**Comment by gdoyle1** [comment]
@jschuler Updated the typography and spacers pages with the variable names here https://redhat.invisionapp.com/share/3WQLMKRU6M2.

**Comment by rachael-phillips** [comment]
All styles pages are completed (Colors will be wrapped up in colors issue)
