### ISSUE TITLE
[Picture]The picture shows list view page with a little problem

### ISSUE THREAD

**Issue by zhutaoredhat** [patternfly/patternfly-org#69]
![list-view-example](https://cloud.githubusercontent.com/assets/13375283/15415582/0866bf00-1e76-11e6-9fa7-cb8fc51d1568.png)

In the first line, the "Active" and "...(more)" buttons with a little problem.  They are malposition.

**Comment by dlabrecq** [comment]
This is actually an image pulled from the existing site. We'll need someone to clean this image up.

**Comment by dlabrecq** [comment]
@LHinson Can we get a new image?

**Comment by LHinson** [comment]
here you go @dlabrecq 
![list-view-example](https://cloud.githubusercontent.com/assets/7924406/15729882/03cbd1aa-2836-11e6-93b4-e9ba935d4b88.png)

**Comment by dlabrecq** [comment]
Done.
