### ISSUE TITLE
Spacers Content and Page for Website - Styles page

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#699]
The spacers page will live under the styles section of the website.

**Comment by stacymcauliffe** [comment]
Draft content here: https://docs.google.com/document/d/1YtDVhQePLWYxrvj_ZS2jd3wNyxJXHUZ-SBGu38yu2Ag/edit?usp=sharing

reviewed and approved by Gina - after convo with dana and kyle, need to add info re: variables
