### ISSUE TITLE
Footer text overlaps carousel

### ISSUE THREAD

**Issue by Essjaysee** [patternfly/patternfly-org#71]
![screen shot 2016-05-20 at 9 26 30 am](https://cloud.githubusercontent.com/assets/3267889/15429084/04caaa04-1e6d-11e6-8021-0ff722a107e5.png)

**Comment by dlabrecq** [comment]
This is the same issue as #66. @cardosogabriel please take a look?

**Comment by cardosogabriel** [comment]
Fix submitted at https://github.com/patternfly/patternfly-org/pull/72

**Comment by dlabrecq** [comment]
Fixed.
