### ISSUE TITLE
Design Guidelines - Date and Time

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#712]
Define design guidelines for displaying date and time and usage for date and time pickers.

**Comment by mcarrano** [comment]
@stacymcauliffe I created this issue to track the work on date and time formats. Please attach any links here.

**Comment by stacymcauliffe** [comment]
Draft guidelines are here: https://docs.google.com/document/d/1RA3C5Caza3boGz-uJ8b0-R7HOhNdS83SfRpcKH_5vxk/edit?usp=sharing
