### ISSUE TITLE
Masthead - Design Guideline Doc

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#714]
Add a design guidelines page for Masthead. This should provide guidance on what goes inside the masthead and use of utility bar items. See https://www.patternfly.org/pattern-library/application-framework/masthead/ for PF3 documentation.

**Comment by mcarrano** [comment]
An initial draft can be found here: https://docs.google.com/document/d/1fuII5EhFAQMtYpSBOLPgWPLuQ0cQUgHVUbmSjrtMUJE/edit?usp=sharing

**Comment by mmenestr** [comment]
Maybe add this to the page documentation in the future...

**Comment by mcarrano** [comment]
@mmenestr since I am working on design documentation for the Page component, I decided to take this on since it is implemented as part of the page. There may be some changes coming but at least this will get us a baseline.

**Comment by mmenestr** [comment]
Sounds great, thank you @mcarrano !
