### ISSUE TITLE
Empty States - Design Guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#716]
Add guidelines for using the empty state pattern. When to use? How to use? Variants?

**Comment by katierik** [comment]
Sharing this doc/design I've been putting together for the Cloud Services platform. 
I've designed out examples of different types of empty state for different use cases. This may be helpful in writing the design guidelines/I will need to update if guidelines differ.

https://docs.google.com/presentation/d/1ZSyFaxtCjJ5yf-v6hYKH2IroSENftwpN1D38zyAVfWA/edit?usp=sharing

**Comment by stacymcauliffe** [comment]
yaaassssss thanks so much @katierik, this is great!

**Comment by mcarrano** [comment]
@stacymcauliffe I reviewed your first draft here: https://docs.google.com/document/d/1webFuxv2nD8sPTCJ8l3Xt7MTDCHqTufXu3kzHexNCdw/edit?usp=sharing I think this looks great and I wouldn't change anything. My only comment is whether we should add a variant about success messages. I'm thinking about the issue coming from the Integrately team here: https://github.com/patternfly/patternfly-next/issues/1423  I've also used this sort of pattern in my wizard designs. You can see examples here: https://redhat.invisionapp.com/share/W3QA5O64XNQ

Because of the number of different use cases this pattern can be used for, I wonder if we can find a better general term than "empty state." It's more like a generic message template that can be used for a variety of use cases, presenting empty states being one. Thoughts?

**Comment by stacymcauliffe** [comment]
Thanks @mcarrano - I can definitely add a success state. I think it's ok to continue referring to this pattern as an empty state. It's certainly what I expect when I hear the term. I think we could start with it listed at an empty state and see if we get feedback from folks that it feels confusing. Let me know what you think.

**Comment by mcarrano** [comment]
Sounds good @stacymcauliffe I don't have a better idea.
