### ISSUE TITLE
Data Loading - Design Guidelines

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#717]
Add guidelines for representing loading states in various views. Consider use of spinners, skeleton loading.

**Comment by katierik** [comment]
Wanted to share the research done for the Cloud Services platform: https://docs.google.com/presentation/d/1kfKbl5HtumYiNm-ubJxxP93EqJjfThijEd6n1QIhD60/edit?usp=sharing

Essentially:
Use a spinner when there is an unknown quantity or shape of data coming.
Use a spinner when it is likely it will fail or show an empty state.
Use skeleton loading for data that we know the shape/quantity of.
Skeleton loading should be progressive - load static text first!

**Comment by RonnyPfannschmidt** [comment]
another important detail to consider - skeleton loading should ensure equivalent sizes to actual data  display -else the ux size change in loading situations and their followup creates unnecessary  disruption due to size and scroll changes

**Comment by mcarrano** [comment]
@gdoyle1 I was thinking a bit about your question regarding spinner usage and what to document.
I think there are three things to consider...

1. indicating loading at the page level.
2. Loading at the card (or container) level (e.g. cards within dashboards)
3. Loading at the element level:
-Data loading in tables and lists.
- Loading for discrete elements like fields, dropdown menus, etc.

It would be good to create some examples of these use cases that designers can leverage.
I know, for example, that there are cases where it could take time for a list of values in a type-ahead select to load

**Comment by gdoyle1** [comment]
I've updated data loading guidelines here: https://docs.google.com/document/d/16Lx4N7aTqtvv5aS7h8mF8hnMuL6SmmfAA5qNn9L1gug/edit?usp=sharing @mcarrano That incorporates the examples you gave above!
