### ISSUE TITLE
Charting - Design Guidelines Part 1

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#720]
Add design guidelines for usage of various charts and graphs to represent data.

**Comment by gdoyle1** [comment]
This issue will cover the different types of charts and usage guidelines for them. A separate issue will cover chart coloring.

**Comment by gdoyle1** [comment]
Here's the doc I've been working on https://docs.google.com/document/d/1-R9JGlkTeU8-xa0lkfox4kn5HxFN6vJjQ1i9NN1-z6M/edit?usp=sharing
