### ISSUE TITLE
Colors Styles Page

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#722]

**Comment by gdoyle1** [comment]
Had to update the typography and spacers pages with variable names. Moving onto this now and should have a design ready by Monday!

**Comment by gdoyle1** [comment]
@rachael-phillips @jschuler  Here are wireframes for the colors page on a light background. https://redhat.invisionapp.com/share/3WQLMKRU6M2#/350346135_Colors_Light_Background I need to create the spec and the dark background page still! @stacymcauliffe I wrote a bunch of content that I'll set up a time with you to review!

**Comment by gdoyle1** [comment]
I added wireframes for the light and dark background tabs for colors page. There is a mobile mockup of how the pages should scale https://redhat.invisionapp.com/share/3WQLMKRU6M2. Going to close this now as I pass it off to Liz!
