### ISSUE TITLE
Select all across pages pattern for tables and lists

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#727]
There is a need for a pattern for selecting items across **pages in a list**. [Aka, when there are 2+ pages of data, it is unclear if select all applies to just the visible page, or the entire list. Gmail has a pretty good pattern for this]

This is an enhancement to the "select all" checkbox that is already available in the data table & toolbar. 

WIP Design: https://sketch.cloud/s/JaL1e 

EDIT: This exists as a pattern in PF3 - https://www.patternfly.org/pattern-library/forms-and-controls/bulk-selector/#design

**Comment by mcarrano** [comment]
Thanks for taking this on @katierik . In looking at your WIP design, this is something that will most likely be an enhancement to the Data Table component and will require code at that level to make it work. Once you have a final design proposal, what I recommend is that we open an issue in the patternfly-next repo to get this into the roadmap. @rachael-phillips FYI.

**Comment by rachael-phillips** [comment]
That sounds like a good plan to me :)

**Comment by katierik** [comment]
Awesome - I've updated the pattern to match the same as in PF3 

Cloud doc: https://sketch.cloud/s/JaL1e
Design file: https://drive.google.com/file/d/1Bx5gjpMj4DghnavcwF0j5svcaLFOKVM8/view?usp=sharing

**Comment by rachael-phillips** [comment]
I've opened an issue for this on next.
