### ISSUE TITLE
HTML/CSS: Implementing the Component page

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#739]
Adam will implement the visual designs for the live site when Liz completes the high fidelity mockups.

**Comment by rachael-phillips** [comment]
Adam and Joachim will meet to go over site structure.

**Comment by mindreeper2420** [comment]
@rachael-phillips I believe that this is complete - can you verify?

**Comment by rachael-phillips** [comment]
Yes, we can close this issue.
