### ISSUE TITLE
Link to accessibility guide wrong

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#745]
https://www.patternfly.org/get-started/frequently-asked-questions/#accessibility
<accessibility guide> link still goes to pf-next.com and not https://pf4.patternfly.org/accessibility-guide

**Comment by ajacobs21e** [comment]
Also the link at the bottom of 
https://www.patternfly.org/v4/design-guidelines/content/voice-and-tone

goes to 
https://www.patternfly.org/v4/get-started/accessibility

and not
https://pf4.patternfly.org/accessibility-guide

**Comment by rachael-phillips** [comment]
I'm closing this issue as this should be resolved now.
