### ISSUE TITLE
Styling for Search

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#755]
Visual design will advise on styling for search based on the newly implemented search feature on the website workspace: https://v2.patternfly.org/

And based on the Algolia documentation that powers the search: https://community.algolia.com/docsearch/styling.html

**Comment by gdoyle1** [comment]
Initial InVision wireframes for search experience: https://redhat.invisionapp.com/share/W3Q3PI2RNFV

**Comment by rachael-phillips** [comment]
We would have to move in the font work first to the website. This will need a design review. Wait to do a review of the Red Hat font then start adding Red Hat font on Search.

**Comment by rachael-phillips** [comment]
For refining our search experience I think the interaction that Medium uses will work beautifully: https://medium.com/

And here is reference to how it could look like in our site:

I can send over the svg.
<img width="1047" alt="Screen Shot 2019-04-05 at 11 30 19 PM" src="https://user-images.githubusercontent.com/40275806/55664403-fed01100-57fa-11e9-96b4-53e5ab3ae748.png">

**1** - The static state of the search before the user interacts
**2** - Once the user has clicked on the search icon the icon moves left and help text appears as seen on medium.com

**Comment by rachael-phillips** [comment]
We want to modify the look of the Algolia tag on search. How can we make the purple icon fit in more with the styling of the website?

**Comment by mindreeper2420** [comment]
@rachael-phillips From what I have seen, we cannot alter the Algolia logo. That is provided in the code as an image, directly from their codebase.

**Comment by rachael-phillips** [comment]
I'm closing this issue because we have completed this work
