### ISSUE TITLE
Descriptions for Component Pages 

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#757]
We have 10-15 descriptions written. How are these being pulled in currently and how can we format this to be maintainable in the future?

**Comment by mcarrano** [comment]
Need to complete this work. Drafts of remaining descriptions can be found here: https://docs.google.com/document/d/1P_Nxc1iAM__IcdS2-2Upumby3si2Y2QZSOzyEV3AUzg/edit?usp=sharing

**Comment by rachael-phillips** [comment]
Content has to be moved into Mardown by @mcarrano. @jschuler will assist @mcarrano in learning how to add descriptions.

**Comment by rachael-phillips** [comment]
https://github.com/patternfly/patternfly-org/pull/786

**Comment by rachael-phillips** [comment]
This work has been completed.
