### ISSUE TITLE
Remove button alignment from Buttons and Links guideline

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#765]
Per this issue: https://github.com/patternfly/patternfly-next/issues/1599, we want to remove references to button placement from [Buttons and Links guidelines](https://v2.patternfly.org/design-guidelines/usage-and-behavior/buttons-and-links) for now until we are able to make updates to our modal components.

**Comment by stacymcauliffe** [comment]
Completed and merged
