### ISSUE TITLE
Extensions Package - Determine where it will live on the site

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#779]
Determine where extensions package will live on the site, and implement the solution.

**Comment by rachael-phillips** [comment]
@jschuler We don't want to surface extensions package examples on the site. What would be a creative way for users to access them? Should we create another category for extensions packages below demos?

**Comment by jschuler** [comment]
With extensions package, do you specifically mean react-inline-edit-extension and react-virtualized-extension? I think we could add an Extensions category in the nav and list those under that

**Comment by rachael-phillips** [comment]
Yes, that's exactly what I think we should do.

**Comment by jschuler** [comment]
@rachael-phillips is this covered with the Experimental section? Or should this target a different set of components?

**Comment by rachael-phillips** [comment]
It's a totally different section. It should be a category at the very bottom of the left nav under Documentation. These are things that outside contributors offer that PatternFly won't support.

**Comment by rachael-phillips** [comment]
Due to a lack of users we will not move forward with offering an extensions package on the site.

**Comment by rachael-phillips** [comment]
I'm closing this issue because it is outdated
