### ISSUE TITLE
Creating banner for PatternFly 3 Site

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#781]
Let's use Liz's banner design to create one for PatternFly 4. 

Open question:
- Should it be in the styles for PatternFly 3 or 4?

**Comment by rachael-phillips** [comment]
Here is an image of the designs:

<img width="1680" alt="Screen Shot 2019-04-05 at 10 39 40 PM" src="https://user-images.githubusercontent.com/40275806/55664461-0217cc80-57fc-11e9-8f6b-a0a09e43bb26.png">


I added the Sketch file to https://drive.google.com/drive/u/1/folders/1MaI3Sewes8h4fxD2h4P6R6cZuRQIBYBf

**Comment by rachael-phillips** [comment]
@stacymcauliffe will you check the copy of this banner to help me make sure it makes sense for introducing the PF4 site on patternfly,org? I want it to look as similar as possible to the banner that we will have on the PF4 homepage.

**Comment by stacymcauliffe** [comment]
@rachael-phillips - 

"PatternFly 4 is live! Visit the website for new design, code samples, and documentation." Link text: "Go to PatternFly 4"

**Comment by rachael-phillips** [comment]
Awesome, thanks!

**Comment by jschuler** [comment]
Done!
