### ISSUE TITLE
Add mailing list and forum to footer

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#783]
Add mailing list flow and forum to footer.

To-dos:
- Rachael to determine mailing list flow
- Joachim / Adam to add Forum and mailing list to footer

**Comment by mindreeper2420** [comment]
@rachael-phillips where in the footer will these links go? Currently, the QUICK LINKS column has 5 items in it, vs 3 items in the CONTRIBUTE column. Do you want a third column with PatternFly specific links? i.e Font Awesome, where they use a PROJECT column and put a link to the license, GitHub link, and old version. They have a separate column of COMPANY for their Blog and such.

**Comment by rachael-phillips** [comment]
What if we add a third column called "Stay in Touch" on the right next to Quick Links and Forum? Then we add Forum link and mailing list link under Stay in Touch. Does that make sense?

**Comment by mindreeper2420** [comment]
@rachael-phillips I think that'd be a good way to go - I'll put it together and add a screenshot here.

**Comment by mindreeper2420** [comment]
@rachael-phillips here are screenshots of the implementation:

**Desktop:**
<img width="1920" alt="Screen Shot 2019-04-04 at 11 49 27 AM" src="https://user-images.githubusercontent.com/4032718/55569574-ced81f00-56cf-11e9-9703-efe619859e41.png">

**Tablet:**
<img width="621" alt="Screen Shot 2019-04-04 at 11 49 38 AM" src="https://user-images.githubusercontent.com/4032718/55569585-d4356980-56cf-11e9-98fe-27123266b411.png">

**Mobile:**
<img width="410" alt="Screen Shot 2019-04-04 at 11 52 38 AM" src="https://user-images.githubusercontent.com/4032718/55569777-29717b00-56d0-11e9-9cc9-beddaf189296.png">

**Comment by mindreeper2420** [comment]
Fixed with referenced PR. Can be updated as needed.
