### ISSUE TITLE
Improve readability of Design Guideline pages

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#784]
Want to improve the presentation of design guidelines pages to be more readable. Specific issues to address include:

* Left justify images
* Add a max/fixed with to pages so they don't stretch to fill the window. This will make text more readable on wide screens.

**Comment by ajacobs21e** [comment]
This may be related - if this should be a separate issue let me know and I'll create it.

When looking at a design guideline page, like 
https://v2.patternfly.org/design-guidelines/usage-and-behavior/forms
and then opening an example, like
https://v2.patternfly.org/static/eb38f9ceb56f32dba10837aa67f9c2aa/2d45d/all-required.png
the image doesn't have a white background and therefore renders poorly if you're using the Mac dark theme (which many designers are using).
<img width="360" alt="Screen Shot 2019-04-03 at 2 11 52 PM" src="https://user-images.githubusercontent.com/6415742/55502387-72ff8e80-561a-11e9-906e-741178f83432.png">

I haven't checked any other examples yet.

**Comment by gdoyle1** [comment]
@ajacobs21e @mcarrano I think it's a problem with exporting the artboards as pngs from Sketch - we need to make sure we check that box to export them with a background and then confirm it is white. Might be good to send out a reminder/update the design docs assets process with that ^

**Comment by ajacobs21e** [comment]
Yep that would fix it @gdoyle1 ! I can volunteer to QA the site and make a list of which pngs need to be re-exported. Would that be helpful?

**Comment by gdoyle1** [comment]
@ajacobs21e Yeah that'd be great, thanks!

**Comment by ajacobs21e** [comment]
Issue to do the QA (assigned to me): https://github.com/patternfly/patternfly-org/issues/791

Issue to update the process doc: https://github.com/patternfly/patternfly-org/issues/792

**Comment by mcarrano** [comment]
Thanks @ajacobs21e ! That's a great catch. @rachael-phillips @stacymcauliffe FYI

**Comment by stacymcauliffe** [comment]
Man, I am going to have to update all of mine. Thanks for catching that, @ajacobs21e

**Comment by rachael-phillips** [comment]
Closing this issue as this has been completed
