### ISSUE TITLE
What is the criteria to flip patternfly.org to the new site?

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#787]
TBD for Sprint 8-9

Notes: 
- Warning for switching for new site

**Comment by jschuler** [comment]
I had done work for adding PF3 content under the v3 sub folder here:
https://github.com/patternfly/patternfly-org/pull/1082
When we're ready we can update this PR (it is outdated now and needs a rebase).

**Comment by rachael-phillips** [comment]
We have a clear path forward
