### ISSUE TITLE
QA all example images in Design Guidelines of v2 site

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#791]
I will QA all of the example images to make sure they have been exported with a white background so that they can be viewed on Mac dark theme. 

Audit spreadsheet:
https://docs.google.com/spreadsheets/d/1XiirMJ3osSDpge3TaGVBEvI4CLh4A_mo_DeVoL0qQ80/edit#gid=0

I'll update this story when I'm done.

**Comment by ajacobs21e** [comment]
Audit is complete @gdoyle1 @stacymcauliffe  @LHinson @rachael-phillips

**Comment by LHinson** [comment]
Thanks @ajacobs21e I'll mark this as done then.
