### ISSUE TITLE
Update the design docs assets process doc

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#792]
Images from Sketch need to be exported with a white background in order to render properly when using the Mac dark theme. Please update the process doc to add this step.

**Comment by rachael-phillips** [comment]
@gdoyle1 @stacymcauliffe is this something you are aware of and/or want to take on?

**Comment by gdoyle1** [comment]
@rachael-phillips Yeah I spoke with Allie about this yesterday - I believe there's a process that @mcarrano documented that we should update so the images from sketch are exported with a white background. I was going to take on an issue to update all the images that do not currently have white backgrounds (Allie is creating a list for me) and reupload them.

**Comment by rachael-phillips** [comment]
Awesome, thanks so much! That's great to hear :)

**Comment by rachael-phillips** [comment]
@gdoyle1 do you know what our status is on this particular issue?

**Comment by rachael-phillips** [comment]
Closing this as this issue was completed
