### ISSUE TITLE
Updating Footer links

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#793]
Remove Facebook icon, I don't think we have a Facebook page. 

Twitter Link: https://mobile.twitter.com/patternfly_des
Mailing List link: https://www.redhat.com/mailman/listinfo/patternfly

**Comment by rachael-phillips** [comment]
Hey @mindreeper2420 did you see the links I included above to add to the footer?

**Comment by mindreeper2420** [comment]
@rachael-phillips I've updated the Mailing List URL and removed the Facebook icon, but we don't want to use the mobile twitter link - I've kept it as the standard Twitter link, which will automatically redirect to mobile (or the app, if installed) for the user upon clicking.
