### ISSUE TITLE
How to Style Anchor Links on each page

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#794]
Rachael will work with Adam on how to style the Anchor links on each component page.

**Comment by rachael-phillips** [comment]
Currently there is a bug on anchor links: 

<img width="423" alt="Screen Shot 2019-04-25 at 3 06 41 PM" src="https://user-images.githubusercontent.com/40275806/56761619-c96c7280-676b-11e9-9d60-260e80098843.png">

**Comment by rachael-phillips** [comment]
We will need to make sure the color is consistent across the flow. Preference for black rather than blue links. Thanks for taking this @dgutride

**Comment by dgutride** [comment]
@rachael-phillips  - I can fix the bug with the duplicate anchor, if you want color fixed, we should chat with @christiemolloy

**Comment by rachael-phillips** [comment]
@christiemolloy will remove the blue color for black
