### ISSUE TITLE
Bug: line appearing on HTML examples components page

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#801]
There is a line appearing on the HTML example components page that does not appear in Liz's wires. Here is an example of the line we should remove: <img width="564" alt="Screen Shot 2019-04-05 at 10 23 21 PM" src="https://user-images.githubusercontent.com/40275806/55663812-75681100-57f1-11e9-8bb6-eee2d6154697.png">

**Comment by mindreeper2420** [comment]
Related to PR https://github.com/patternfly/patternfly-org/pull/764
