### ISSUE TITLE
Implement Styles Pages

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#802]
There are 4 styles pages that we will need to create for launch

- Spacers
- Typography
- Colors
- Iconography

There pages have all been added to the Drive: https://drive.google.com/drive/u/1/folders/1MaI3Sewes8h4fxD2h4P6R6cZuRQIBYBf

**Comment by mindreeper2420** [comment]
Once the four referenced PRs are merged, this story will be complete.

**Comment by mindreeper2420** [comment]
All PRs merged - marking as complete.
