### ISSUE TITLE
Implement Getting Started Pages

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#803]
We will need to slightly refine the Getting Started pages per Liz's wires which can be found here: https://drive.google.com/drive/u/1/folders/1MaI3Sewes8h4fxD2h4P6R6cZuRQIBYBf

**Comment by mindreeper2420** [comment]
Once the referenced PR is merged, this story should be complete.

**Comment by mindreeper2420** [comment]
Completed and verified in Master.
