### ISSUE TITLE
Changing all left-hand side documentation to sentence case

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#807]
In this issue we need to go through our left-hand side and component documentation pages of the website and change every title to sentence case. Here are two examples. 

"About Modal" should be "About modal"
"AboutModalBox" should be "About modal box"
"ApplicationLauncher Props" should be "Application launcher props"

 cc @stacymcauliffe

**Comment by dgutride** [comment]
All side navigation has been fixed for component documentation - closing.
