### ISSUE TITLE
PF4 "Get Started" / "Why" button styles (padding, borders) change when navigating away from home page and back

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-org#811]
When I first open the website, the buttons in the main splash area look like this:

![Screenshot 2019-04-10 16 57 45](https://user-images.githubusercontent.com/811963/55913127-dc9b1200-5bb1-11e9-8cfd-754bf776c53e.png)

When I click the Get Started button and then click my browser's Back button, they look like this:

![Screenshot 2019-04-10 16 59 18](https://user-images.githubusercontent.com/811963/55913179-ff2d2b00-5bb1-11e9-9d95-02fddd131118.png)

Recording:

![Ox7hzdEgFR](https://user-images.githubusercontent.com/811963/55913222-1f5cea00-5bb2-11e9-9e54-474c14a44945.gif)

**Comment by rachael-phillips** [comment]
This issue should be resolved now, I'm closing this issue
