### ISSUE TITLE
PF blog site which is referenced by the PF beta site brings you back to regular PF site

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-org#82]
Starting on beta.patternfly.org - if i navigate to PF Blogs, it brings me to blog.patternfly.org which has navigation pointing back to the regular PF site.

Will this be updated once the new site goes live?

**Comment by dlabrecq** [comment]
blog.patternfly.org will continue to be it's own site. Thanks!

**Comment by serenamarie125** [comment]
@dlabrecq but with the nav items in  blog.patternfly.org be updated to reflect the new site?

**Comment by dlabrecq** [comment]
Ah, yes. We have a story to update that once the old site is turned off.

**Comment by LHinson** [comment]
https://patternfly.atlassian.net/browse/PTNFLY-1415

**Comment by dlabrecq** [comment]
Navigation has been changed -- site is live.
