### ISSUE TITLE
Website styling bleeds into examples

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly-org#828]
For example, the hamburger icon is missing for these page demos
https://www.patternfly.org/v4/documentation/react/demos/pagelayout/examples/page-layout-default-nav

**Comment by kybaker** [comment]
@jschuler The navigation is also not matching core because of this issue.

**Comment by mturley** [comment]
This might be another good use case for https://github.com/Wildhoney/ReactShadow -- we could render all our examples in Shadow DOM nodes with only the patternfly styles applied to them, and then we're free to use whatever CSS we like in the website without risk of affecting the examples. https://medium.com/rate-engineering/winning-the-war-of-css-conflicts-through-the-shadow-dom-de6c797b5cba

**Comment by jschuler** [comment]
Fixed and in production
https://www.patternfly.org/v4/documentation/react/demos/pagelayout/pagelayoutdefaultnav/
