### ISSUE TITLE
What's New on the home page is out of date 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly-org#83]
What's New on the home page is out of date.

**Comment by dlabrecq** [comment]
Updated all the posts for this year and up to November 5, 2015. There are older posts, but not certain we need all that or if it's even relevant for the new site? It's time consuming to add each post to it's own file, fix the broken links, etc.

By default, we're only showing the last 3 posts on the home page. If you click on the view more link, it was only showing the last 10; although, I changed that to 50.
