### ISSUE TITLE
Style copy to clipboard notification

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#857]
This needs to be styled to match the color scheme of the rest of the site: 

<img width="284" alt="Screen Shot 2019-04-26 at 1 13 46 PM" src="https://user-images.githubusercontent.com/40275806/56824664-224c1180-6825-11e9-8186-7641e173ca0a.png">

**Comment by christiemolloy** [comment]
@rachael-phillips could you provide some more info here :)

**Comment by rachael-phillips** [comment]
Yes, I can. Can we add copy to clipboard styling that is more in line with the website work? For example, Roboto text with a light grey background? I can mock something up really quick if needed. What would be best for you?

**Comment by christiemolloy** [comment]
@rachael-phillips it would be great if you could mock something up

**Comment by rachael-phillips** [comment]
Christie and I discussed and are all set to move forward
