### ISSUE TITLE
Home page missing image

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#862]
Using: Firefox on a Mac

Image of laptop not loading correctly

![Xnip2019-04-26_14-08-26](https://user-images.githubusercontent.com/23172038/56827491-ff256000-682c-11e9-9089-b8d49157c2df.jpg)

**Comment by mindreeper2420** [comment]
This appears to be a Firefox bug - renders correctly in Chrome and Safari.

**Comment by Rohoover** [comment]
Same for me.

**Comment by rachael-phillips** [comment]
I'm closing this issue because it is resolved.
