### ISSUE TITLE
Table format in Alerts and Notifications design page

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#863]
This table becomes difficult to read due to lack of space between cells and vertical centering
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/alerts-and-notifications#alerts-and-notifications

![image](https://user-images.githubusercontent.com/19825616/56827522-16644d80-682d-11e9-9f0d-20fcc4791ff4.png)

**Comment by christiemolloy** [comment]
This issue is related to markdown styling for tables @rachael-phillips should we add a tag for all of these?

**Comment by rachael-phillips** [comment]
Yes, we should
