### ISSUE TITLE
Check Styling Tabs in the Nav

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#865]
Should this space exist between tabs? Looks weird IMO

<img width="530" alt="Screen Shot 2019-04-26 at 2 09 47 PM" src="https://user-images.githubusercontent.com/20118816/56827489-fdf43300-682c-11e9-8d9f-e4d1fd17d655.png">

**Comment by katierik** [comment]
Firefox on Mac - seeing a different tab issue! Theres a black gap 
![Xnip2019-04-26_14-16-02](https://user-images.githubusercontent.com/23172038/56827844-e8333d80-682d-11e9-8282-94f9a0513593.jpg)

**Comment by mturley** [comment]
I'm seeing @katierik's issue with the gap under the tab, on Firefox but not in Chrome.

**Comment by rachael-phillips** [comment]
Yes, @christiemolloy I think we should fix it.

**Comment by rachael-phillips** [comment]
@christiemolloy how quick of a fix is this compared to the other things we are trying to get done in the next couple of days?

**Comment by christiemolloy** [comment]
@rachael-phillips looks like this issue is actually a bug that is happening in Patternfly, just captured in Patternfly - https://github.com/patternfly/patternfly-next/issues/1794

**Comment by rachael-phillips** [comment]
Closing because this has been resolved
