### ISSUE TITLE
Updates to Footer

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#866]
<img width="227" alt="Screen Shot 2019-04-26 at 1 11 10 PM" src="https://user-images.githubusercontent.com/35148959/56827630-fe88cb80-6824-11e9-89c9-3d1f8c7aa353.png">

**Comment by katierik** [comment]
![Apr-26-2019 14-13-23](https://user-images.githubusercontent.com/23172038/56827678-81ae1f80-682d-11e9-96d7-fbc82272df2b.gif)

**Comment by Rohoover** [comment]
This seems especially problematic when in smaller views.

<img width="769" alt="Screen Shot 2019-04-26 at 2 15 57 PM" src="https://user-images.githubusercontent.com/18266453/56827845-e9646a80-682d-11e9-9897-c2e6a02d9521.png">

**Comment by rachael-phillips** [comment]
Also from Liz:

The hover effect on items in the footer look off
Update type styles of the footer to reflect the new Design System Collaborative styles
%footer-headline
Font family	Red Hat Text
Font weight	Medium
Font size	14px (0.875rem)
Line height	21px (1.5)
Case	Uppercase
Web weight	700
%footer-text
Font family	Red Hat Text
Font weight	Regular
Web weight	400

The gray PatternFly section on the right in the footer should be 4 columns wide

**Comment by rachael-phillips** [comment]
Sentence case does not match in footer: 
"Privacy Statement" vs. "Terms of use," etc.

Screen Shot 2019-04-26 at 2 49 27 PM

Seen on Desktop.

**Comment by mindreeper2420** [comment]
@rachael-phillips Do you have a link to the Design System Collaborative styles that are referenced above?

**Comment by rachael-phillips** [comment]
No, I do not. That's something that Liz Hoover or Kyle will have to provide for us. I can post about that in the chat.

**Comment by lizhoover** [comment]
https://www.dropbox.com/s/ojcz0tr9zef8oau/RHDDS-Master-File-WIP-03-14.sketch?dl=0

https://docs.google.com/spreadsheets/d/1C0JFvlo9wKOeF1iACvLvLarTrJCfjdrffx5vI8N-gQE/edit?pli=1#gid=0

**Comment by rachael-phillips** [comment]
Closing this as this work has been completed
