### ISSUE TITLE
Colors page incorrect margins on mobile viewport size

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-org#868]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/30935938/56827680-82df4c80-682d-11e9-9630-488aea1c497a.png">

Desktop with window resized, FF
Overlapping text with color swatch

Re: #722

**Comment by rachael-phillips** [comment]
Hi Michael, thanks for filing this! Great find! I'm going to close this one because we have a repeat open
