### ISSUE TITLE
Fix buttons on home page on mobile

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#869]
On mobile these buttons shouldn't stretch to full width. They arent on desktop. 

<img width="462" alt="Screen Shot 2019-04-26 at 2 13 22 PM" src="https://user-images.githubusercontent.com/20118816/56827663-7a871180-682d-11e9-8c26-8c7a2da2c1d6.png">

**Comment by rachael-phillips** [comment]
@christiemolloy how would you expect this to behave?

**Comment by rachael-phillips** [comment]
I'm closing because this has been resolved
