### ISSUE TITLE
Alignment of the HTML/React switcher is incorrect on Firefox

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-org#870]
On Firefox only, there is an alignment problem with the switcher at the top of the Documentation nav. See screen shot:

![Screen Shot 2019-04-26 at 2 11 16 PM](https://user-images.githubusercontent.com/6619860/56827702-9094d200-682d-11e9-9451-c684035e41fd.png)

**Comment by mindreeper2420** [comment]
Note: the class `.pf-site-switcher-group` should have the `align-items` attribute changed to `flex-start` instead of `end`.

```
.pf-site-switcher-group {
  align-items: flex-start;
}
```

**Comment by mturley** [comment]
I can confirm that I'm seeing this in Firefox but not in Chrome, on my mac.
