### ISSUE TITLE
Broken links on Home Page

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#871]
![Xnip2019-04-26_14-14-25](https://user-images.githubusercontent.com/23172038/56827741-a904ec80-682d-11e9-8875-41d14e681e84.jpg)

All the links are leading to 404

**Comment by mindreeper2420** [comment]
related to https://github.com/patternfly/patternfly-org/issues/873 - dynamic linking broken

**Comment by rachael-phillips** [comment]
This is resolved now
