### ISSUE TITLE
Empty state for icons?

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#872]
When there are no search results for icons, should we have an empty state component for better user experience?

<img width="722" alt="Screen Shot 2019-04-26 at 2 15 17 PM" src="https://user-images.githubusercontent.com/20118816/56827782-bf12ad00-682d-11e9-803d-144556859a4b.png">

**Comment by rachael-phillips** [comment]
Thanks for filing this! Great find!
