### ISSUE TITLE
Footer links are broken

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-org#873]
Footer Quicklinks in PF4 website lead to 404s (except for PatternFly 3). Viewing on desktop.

Quicklinks:
<img width="176" alt="Screen Shot 2019-04-26 at 2 15 54 PM" src="https://user-images.githubusercontent.com/7014965/56827821-d94c8b00-682d-11e9-8b78-7d13da28dd24.png">

**Comment by mindreeper2420** [comment]
related to https://github.com/patternfly/patternfly-org/issues/871 - dynamic linking broken

**Comment by rachael-phillips** [comment]
Closing as this is captured
