### ISSUE TITLE
Documentation tables are too wide and no horizontal scroll to allow viewing them

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#874]
Documentation tables are too wide to view at certain viewports and there's no horizontal scroll to even get to them.

Example, but on a lot or all HTML pages
https://www.patternfly.org/v4/documentation/core/components/alert#alert

![image](https://user-images.githubusercontent.com/19825616/56827711-95598600-682d-11e9-83cf-3396366b3e1a.png)

**Comment by rachael-phillips** [comment]
@srambach are you still seeing this issue now?

**Comment by rachael-phillips** [comment]
@srambach are you still seeing this issue now?

**Comment by srambach** [comment]
This is looking a lot better. There are just a few minor things I see now:

Right before a breakpoint: 
![image](https://user-images.githubusercontent.com/19825616/73373910-5908f980-4287-11ea-939c-2cc5b730200e.png)

At the narrowest Chrome window:
![image](https://user-images.githubusercontent.com/19825616/73373929-61f9cb00-4287-11ea-85ea-907c0a2773ae.png)

The list has a max-width but the search box doesn't:
![image](https://user-images.githubusercontent.com/19825616/73373973-70e07d80-4287-11ea-80e9-a895fdef94f5.png)

Similar list in the React pages can get cramped before hitting the breakpoint:
![image](https://user-images.githubusercontent.com/19825616/73374009-7f2e9980-4287-11ea-8a66-9b3b5a261999.png)

**Comment by redallen** [comment]
Our tables need some responsive CSS added at ~732px.

**Comment by mcoker** [comment]
Seeing this, too. In case it helps to troubleshoot, here's an example https://www.patternfly.org/v4/components/data-list/html/.

The examples stop shrinking around 715px, but if you remove the "usage" table under the [compact data list example](https://www.patternfly.org/v4/components/data-list/html/#compact), the page shrinks some more and stops around 615px.
