### ISSUE TITLE
Right edge of nav should align with the left edge of first link in header?

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#875]
Should the nav end where "get started" begins?

<img width="493" alt="Screen Shot 2019-04-26 at 1 15 17 PM" src="https://user-images.githubusercontent.com/35148959/56827816-75be5f80-6825-11e9-8542-917b73f73beb.png">

**Comment by rachael-phillips** [comment]
Ouch, yes! Great catch.

**Comment by rachael-phillips** [comment]
Closing this as this work has been completed
