### ISSUE TITLE
React code styling is different then HTML.

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-org#877]
The code styling for react when you expand it is a black background, while the HTML code is a white background.

**Comment by mindreeper2420** [comment]
**React**
<img width="617" alt="Screen Shot 2019-04-26 at 2 24 14 PM" src="https://user-images.githubusercontent.com/4032718/56828283-09e0f480-682f-11e9-8dba-cf5cbc80e95a.png">

**HTML**
<img width="564" alt="Screen Shot 2019-04-26 at 2 24 21 PM" src="https://user-images.githubusercontent.com/4032718/56828296-106f6c00-682f-11e9-82ea-09b5fab4f5af.png">
