### ISSUE TITLE
Alerts and Notifications Page

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#878]
In Usage and Behavior > Alerts and Notifications:

These links seem odd here:

<img width="686" alt="Screen Shot 2019-04-26 at 2 17 44 PM" src="https://user-images.githubusercontent.com/20118816/56827920-20d31700-682e-11e9-8a05-059fb0d2f7bf.png">

**Comment by rachael-phillips** [comment]
I'm closing this issue as it has been resolved.
