### ISSUE TITLE
Layout previews are missing styling that demonstrates the concept

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#879]
https://www.patternfly.org/v4/documentation/core/layouts/flex

![image](https://user-images.githubusercontent.com/19825616/56827889-08fb9300-682e-11e9-81c9-aaeb43aa97c9.png)

Should look like:
![image](https://user-images.githubusercontent.com/19825616/56827911-1b75cc80-682e-11e9-9170-1a17fa66149b.png)

**Comment by srambach** [comment]
Gallery also doesn't show the dotted outlines.

No borders on website:
![image](https://user-images.githubusercontent.com/19825616/56827996-5415a600-682e-11e9-9ecc-502bb013b3b0.png)

Preview in workspace:
![image](https://user-images.githubusercontent.com/19825616/56828015-61cb2b80-682e-11e9-986f-7c0dfa06681f.png)

**Comment by srambach** [comment]
Looks like all the previews of the layouts don't pick up the special workspace styling.

**Comment by tlabaj** [comment]
The same issue exists in React previews.

**Comment by rachael-phillips** [comment]
Thanks for finding this!

**Comment by rachael-phillips** [comment]
Test to make sure these examples are fixed upon this issue being completed: https://www.patternfly.org/v4/documentation/core/components/dropdown

**Comment by redallen** [comment]
Dana will figure out the issue for this in Core, I'll fix it for React upstream in patternfly-react this afternoon. If I have a little extra time I can fix the chart styles upstream too and we can look into including those.
