### ISSUE TITLE
Open in new window for React does not work

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-org#880]
The open in new window for React documentation does not work we receive a 404 error.

**Comment by dlabaj** [comment]
<img width="275" alt="Screen Shot 2019-04-26 at 2 27 19 PM" src="https://user-images.githubusercontent.com/6126356/56828542-8542a600-682f-11e9-8067-e9860f8cb0f6.png">

**Comment by rachael-phillips** [comment]
Thanks for filing this! Great find!
