### ISSUE TITLE
Documentation Responsive Mobile State Overflow

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#881]
When in the smallest screen width, content is running off the screen and not visible.

This is Safari + Firefox on Mac

<img width="512" alt="Screen Shot 2019-04-26 at 2 18 48 PM" src="https://user-images.githubusercontent.com/18266453/56828019-65f74900-682e-11e9-929c-438e642eb762.png">

**Comment by mturley** [comment]
I'm noticing this specifically in the CSS variables sections, much of the other site content does appear to be responsive.

**Comment by mindreeper2420** [comment]
Dynamically generated content for the win :-)

**Comment by christiemolloy** [comment]
We're going to add functionality to our PF Tables to fix this:
https://github.com/patternfly/patternfly-next/issues/1791

**Comment by rachael-phillips** [comment]
I'm closing this as this problem has been resolved.
