### ISSUE TITLE
React Toolbar demo page - need more vertical space

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-org#882]
On page: https://www.patternfly.org/v4/documentation/react/demos/toolbardemo/
The content area is short, so when you hit the filter menu, it goes under the footer. Just need more space under the demo. 

![image](https://user-images.githubusercontent.com/2206023/56827992-524be280-682e-11e9-8c97-ace50982b692.png)

**Comment by rachael-phillips** [comment]
The toolbar drop down is too long and we have overflow.

**Comment by jeperry** [comment]
removing one of the items in the dropdown would be a fine fix.

**Comment by rachael-phillips** [comment]
@jeperry I'm closing this because this should be resolved now
