### ISSUE TITLE
Images look low quality 

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#883]
Usage and Behavior > Buttons and links:

Button Image looks really low quality:

<img width="662" alt="Screen Shot 2019-04-26 at 2 20 16 PM" src="https://user-images.githubusercontent.com/20118816/56828036-74ddfb80-682e-11e9-8b50-4e986fa76d5f.png">

**Comment by ajacobs21e** [comment]
https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology#truncation 
These images are extremely hard to read

**Comment by ajacobs21e** [comment]
^ actually those images look fine when opening full size in a new window. I think the previews on the page should be bigger though.

I think it was done to make the images all the same size but most of those weirdly have a large area of white space to the right of the actual image.

**Comment by mmenestr** [comment]
This was fixed with my button design guideline update some months ago, so i'm closing!
