### ISSUE TITLE
Toggle Dark Theme does not work for React

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-org#884]
Toggle dark theme does not work for React documentation.

**Comment by dlabaj** [comment]
<img width="317" alt="Screen Shot 2019-04-26 at 2 21 53 PM" src="https://user-images.githubusercontent.com/6126356/56828257-fd5c9c00-682e-11e9-83b1-bc7b107fc1d0.png">

**Comment by rachael-phillips** [comment]
Thanks for filing this! Great find! I'm going to close this issue because we're going to remove this icon.
