### ISSUE TITLE
Content - Getting started 

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#885]
The definitions are a little unclear. I think it would be good to include some "layout" examples, especially since the word isn't fully descriptive.
![Xnip2019-04-26_14-18-57](https://user-images.githubusercontent.com/23172038/56828091-8c1ce900-682e-11e9-8db0-f877965c418c.jpg)

**Comment by rachael-phillips** [comment]
These are good points! @stacymcauliffe making you aware

**Comment by redallen** [comment]
@katierik How about "Layouts are containers that allow you position components on pages."?

**Comment by katierik** [comment]
@redallen A lot more clear IMO!
