### ISSUE TITLE
Design Guidelines - Mobile State Overflow

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#887]
Mac -- Safari/Firefox/Chrome

Smallest width the content is overflowing.

<img width="366" alt="Screen Shot 2019-04-26 at 2 21 45 PM" src="https://user-images.githubusercontent.com/18266453/56828218-dc944680-682e-11e9-90c0-2e30720b270a.png">

**Comment by rachael-phillips** [comment]
Thanks for filing this! This is definitely a good one to know about

**Comment by rachael-phillips** [comment]
This should be resolved now
