### ISSUE TITLE
Content - Getting started for devs

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#890]
Admitting this is nit-picky 😄 
The "Download a package manager" and the titles of the package managers have the same heading weight so its a little confusing if like... is there content missing under "Download a package manager"?

![Xnip2019-04-26_14-23-07](https://user-images.githubusercontent.com/23172038/56828221-e0c06400-682e-11e9-9c8a-89f0a38bd246.jpg)

Edit: Should package manager be sentence case? (@stacymcauliffe ?)

**Comment by katierik** [comment]
Also on this page, looks like some internal notes got left behind
![Xnip2019-04-26_14-27-47](https://user-images.githubusercontent.com/23172038/56828572-925f9500-682f-11e9-8487-d6bd34dc53b9.jpg)

**Comment by katierik** [comment]
Should this be a comma?
![Xnip2019-04-26_14-27-47](https://user-images.githubusercontent.com/23172038/56828648-c20e9d00-682f-11e9-9dc0-f0c0b0d93d16.jpg)

**Comment by katierik** [comment]
This seems awkward to me, maybe "The package also includes" instead?
![Xnip2019-04-26_14-31-08](https://user-images.githubusercontent.com/23172038/56828768-0306b180-6830-11e9-8c30-16b6a8e7fdae.jpg)

**Comment by rachael-phillips** [comment]
Great points! @stacymcauliffe making you aware

**Comment by rachael-phillips** [comment]
This has been resolved
