### ISSUE TITLE
Getting started for developers hard to read

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-org#891]
The getting started for developers page I find very hard to read and follow, and keep my place on as I look at a part, look away to perform, and look back to the page.  The combination of fonts and spacing with so much font switching makes the page difficult to parse, especially in this section:
![image](https://user-images.githubusercontent.com/3739227/56828300-12d1c600-682f-11e9-9805-06f07e6a3b01.png)

**Comment by jeperry** [comment]
+1 a few specific examples to note:
doubling up on headers
![image](https://user-images.githubusercontent.com/2206023/56828911-5da00d80-6830-11e9-90ae-4ca6a6ae21bf.png)

mixed sizes (list is smaller text
![image](https://user-images.githubusercontent.com/2206023/56828944-73adce00-6830-11e9-876f-bbcc84a084c7.png)

In general, using bold inline at the beginning of sentences is adding to the difficult legibility.

**Comment by jeperry** [comment]
At the very bottom of the page this CTA link should not have a period. 
![image](https://user-images.githubusercontent.com/2206023/56829123-e6b74480-6830-11e9-890a-dd7eb5ecba59.png)

**Comment by rachael-phillips** [comment]
Thanks for filing this! @gdoyle1 @stacymcauliffe I'm wondering if we could incorporate more of Gina's design work on this moving forward to improve readability?

**Comment by evwilkin** [comment]
Resolved by combination of https://github.com/patternfly/patternfly-org/pull/985/files#diff-d8b6f76ff2336ecdfef673bfee635415, https://github.com/patternfly/patternfly-org/pull/1012/files#diff-d8b6f76ff2336ecdfef673bfee635415, https://github.com/patternfly/patternfly-org/pull/1411/files, https://github.com/patternfly/patternfly-org/pull/987/files and https://github.com/patternfly/patternfly-org/pull/843/files
