### ISSUE TITLE
Code snippet styling

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#893]
Admittedly a preference, but I'd like to see more of a difference for code snippets in the HTML documentation. I like how it has a background in the workspace.

![image](https://user-images.githubusercontent.com/19825616/56828269-03eb1380-682f-11e9-8232-b0921addf538.png)

old way, easier to pick out the code snippets:
![image](https://user-images.githubusercontent.com/19825616/56828307-15ccb680-682f-11e9-9a3e-84fa0fab338e.png)

**Comment by rachael-phillips** [comment]
Thanks for filing this! Good to know!

**Comment by evwilkin** [comment]
Related issue https://github.com/patternfly/patternfly-org/issues/2128

**Comment by redallen** [comment]
Styling has been added to all code blocks. Closing in favor of #2128.
