### ISSUE TITLE
Button padding 

### ISSUE THREAD

**Issue by lizhoover** [patternfly/patternfly-org#895]
Button style should match new style guide. Padding 16, 32, 16, 32  https://www.patternfly.org/v4/
![Screen Shot 2019-04-26 at 2 20 44 PM](https://user-images.githubusercontent.com/48283814/56828397-34cb4880-682f-11e9-8d7c-794cad740623.png)

**Comment by rachael-phillips** [comment]
I'm closing this issue as it is outdated
