### ISSUE TITLE
Icons Page: Icon Copy buttons are not intuitive

### ISSUE THREAD

**Issue by tlabaj** [patternfly/patternfly-org#896]
When you click on an Icon the popover has 3 buttons at the bottom.  The "Copy HTML" and "Copy React" are not intuitive.  It is not clear what will be copied to the clipboard.

**Comment by rachael-phillips** [comment]
Good to know! Thanks Titani! There will be a new icons enhancement shortly, and we should include this.

**Comment by rachael-phillips** [comment]
@tlabaj I'm closing this because we've made improvements to make these buttons more intuitive
