### ISSUE TITLE
Looking for Patternfly 3 banner - close button

### ISSUE THREAD

**Issue by lizyochemwood** [patternfly/patternfly-org#897]
Should there be a close icon on the right of the looking for patterfly 3 band at the top of the homepage?

<img width="1328" alt="Screen Shot 2019-04-26 at 2 21 32 PM" src="https://user-images.githubusercontent.com/50029146/56828382-2ed56780-682f-11e9-9937-b52ee08b54d9.png">

Desktop, chrome

**Comment by rachael-phillips** [comment]
@lizyochemwood Great find! Unfortunately, we ran into some technical trouble with the close button of all things, so we decided to remove it for the time being. Do you feel this greatly impacts the user experience?
