### ISSUE TITLE
Core: Page demos don't have hamburger like preview thumbnail

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-org#898]
https://www.patternfly.org/v4/documentation/core/demos/page

Thumbnails show a hamburger but demos in new tab do not.

**Comment by rachael-phillips** [comment]
Thanks for filing this and great catch. This is a known bug. @jschuler can this be fixed by launch?

**Comment by rachael-phillips** [comment]
This bug has been resolved. I'm closing this issue
