### ISSUE TITLE
Link to WCAG AA-compliance tool

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#899]
Bottom of https://www.patternfly.org/v4/design-guidelines/styles/colors

The link to WCAG AA-compliance tool goes to
https://www.boia.org/free-wcag-accessibiliy-scan?hsa_acc=1828379424&hsa_net=adwords&hsa_cam=328753088&hsa_ad={creative}&hsa_kw=wcag%20aa%20compliance&hsa_grp=1262239697427090&hsa_mt=p&hsa_ver=3&hsa_src=o&hsa_tgt=kwd-78890206622858:loc-190&msclkid=c25d4c88cab01c3858be1048787cf985&utm_source=bing&utm_medium=cpc&utm_campaign=*WCAG%20-%20JF-B%20-%20CHANGED%20TO%20CPA%20(Jan.%2017)&utm_term=wcag%20aa%20compliance&utm_content=Compliance
{whoa right}

Should it instead be https://www.boia.org/free-wcag-accessibiliy-scan ?

The text says "Check color contrast between background color and text color using a WCAG AA-compliance tool."
I would expect this to go to something like https://contrastchecker.com/ which lets you directly test the contrast between two colors rather than a tool to scan the whole site.

**Comment by mindreeper2420** [comment]
ooof - good catch @ajacobs21e. That would be a copy/paste error when grabbing the link.
