### ISSUE TITLE
Focus ring is cut off on code buttons

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#900]
Focus ring is cut off for the buttons on the code previews in HTML

https://www.patternfly.org/v4/documentation/core/demos/alert

![image](https://user-images.githubusercontent.com/19825616/56828482-693f0480-682f-11e9-8f3c-1b28c4c4e118.png)

**Comment by rachael-phillips** [comment]
cc @christiemolloy @mindreeper2420 we may want to remove this functionality for now seeing that it is only on Core and is problematic for styling and alignment

**Comment by srambach** [comment]
I'm not sure what functionality you mean, but if you mean the code preview and toher buttons, please don't. The focus ring overlap is a nit but they are essential.

**Comment by rachael-phillips** [comment]
I see what you are saying now Sarah! Ignore my comment above

**Comment by rachael-phillips** [comment]
@srambach I don't see this issue in Chrome anymore. Are you seeing it in any of your browsers?

**Comment by rachael-phillips** [comment]
I'm closing this because it has been resolved
