### ISSUE TITLE
Responsive behavior needs to match Core vs. React

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#901]
One example is toolbar. HTML:

<img width="388" alt="Screen Shot 2019-04-26 at 2 26 42 PM" src="https://user-images.githubusercontent.com/40275806/56828510-752ac680-682f-11e9-8346-b234253be26c.png">

React
<img width="485" alt="Screen Shot 2019-04-26 at 2 27 23 PM" src="https://user-images.githubusercontent.com/40275806/56828521-78be4d80-682f-11e9-890d-277ea7fd4db1.png">

**Comment by christiemolloy** [comment]
In this case, the toolbar in React is actually an outdated Demo, we dont have a toolbar in React as of now, but that would fix this.

Will look for other examples

**Comment by rachael-phillips** [comment]
Closing because these examples are outdated
