### ISSUE TITLE
Search box text "Search" difficult to see

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#904]
Maybe it's my old eyes but specifically in Safari the search field text is difficult to see. It's lighter in Safari (mac)
Safari on left, Chrome on right.
<img width="555" alt="Screen Shot 2019-04-26 at 2 25 18 PM" src="https://user-images.githubusercontent.com/18266453/56828586-9be8fd00-682f-11e9-8817-2a905a50dac1.png">

**Comment by rachael-phillips** [comment]
Agreed. We should build in more contrast.

**Comment by mindreeper2420** [comment]
related to https://github.com/patternfly/patternfly-org/issues/755
