### ISSUE TITLE
Progress bar guidelines - image missing

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-org#905]
In the progress bar usage and behavior page (https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/progress-bar) there is a missing image under the when to use header.

![image](https://user-images.githubusercontent.com/3739227/56828578-97244900-682f-11e9-8cbd-bdf44e1d6e31.png)

**Comment by rachael-phillips** [comment]
Thanks for filing this! Great find!

**Comment by rachael-phillips** [comment]
Closing this as this work has been completed
