### ISSUE TITLE
No Fav Icon old or new :(

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#908]
Safari/Chrome/Firefox - Mac
Need a cool PF fav icon.

<img width="59" alt="Screen Shot 2019-04-26 at 2 29 40 PM" src="https://user-images.githubusercontent.com/18266453/56828710-e8ccd380-682f-11e9-957f-b8242fe2c96c.png">
<img width="180" alt="Screen Shot 2019-04-26 at 2 30 05 PM" src="https://user-images.githubusercontent.com/18266453/56828711-e8ccd380-682f-11e9-9344-4ec2ddd1cb05.png">

**Comment by jschuler** [comment]
This works now, thanks @Rohoover
