### ISSUE TITLE
404 Error from Demos links on About page

### ISSUE THREAD

**Issue by vconzola** [patternfly/patternfly-org#909]
When you click either of the links in the Demos section of the About page you get a 404 error.
![Screen Shot 2019-04-26 at 2 29 51 PM](https://user-images.githubusercontent.com/22823035/56828722-ed918780-682f-11e9-8c2c-f3f0a552c48e.png)

![Screen Shot 2019-04-26 at 2 30 53 PM](https://user-images.githubusercontent.com/22823035/56828737-f6825900-682f-11e9-8cd7-b6d3e696d3fe.png)

**Comment by rachael-phillips** [comment]
I'm closing this issue because this should be resolved
