### ISSUE TITLE
Image placement on Design Guidelines > Content > Writing

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-org#912]
The image of the spreadsheet is small and hard to read. 

The centered placement makes it difficult to figure out what this image is related to. As a lazy human I saw a picture and immediately looked at that first but it doesn't have a caption or isn't clearly associated with content to help me understand what it's for.

**Comment by mcarrano** [comment]
@ajacobs21e Can you take another look at this? Since this was opened we've updated the page formatting so images are now left aligned. Unless you still think there is a problem here, I am going to close.

**Comment by ajacobs21e** [comment]
It's much better. I still think the spreadsheet is a little small and there's no longer the option to click on the image to open it in a new tab and see it full size. Do you think that would help?

**Comment by mcarrano** [comment]
@abigaeljamie @rachael-phillips I'm curious what you guys think about this in the context of what we are trying to communicate in this page. What this is saying is that all on-screen content should be managed in a separate document as this makes it easier to review and edit. I know that I've done this in prior jobs where isolating strings for translation was necessary. Not sure is this is typically being done on RH projects or if this is even germane to what we are trying to communicate on this page. Let me know what you think.

The page in question is here: https://www.patternfly.org/v4/design-guidelines/content/writing

**Comment by abigaeljamie** [comment]
Hi, @mcarrano ! For the UX writing requests I've worked on for RH products, we've never used a separate sheet like that. I usually take a look at the design plans in Marvel and assist with copy, or we collaborate on the content in a Google Doc. 

I think it's OK to remove the sheet image section. It looks like this document is covering where writing fits into the design process, then writing tips/guidance and things to consider. The sheet chunk of this is getting a little too in-depth, in my opinion. I think we could cut from where it starts ("During this stage, it's also useful to pull...") and ends (last bullet list item below the sheet). This way, we still keep the meaning of the doc and the meaning of that section (focus on content at the beginning design stages), but we don't get so into detail with a sheet—especially considering we don't seem to adopt that practice ourselves! :D 

But that's just my two cents. @rachael-phillips , do you have any thoughts on this too?

**Comment by mcarrano** [comment]
I have sent an pull-request to remove this content as suggested by @abigaeljamie above. https://github.com/patternfly/patternfly-org/pull/1750

@abigaeljamie @rachael-phillips can you please review and make sure you are in sync with this? Thanks.

**Comment by rachael-phillips** [comment]
@mcarrano looks good to me! I left my review 👍
