### ISSUE TITLE
Bad text spacing for typescript example configuration link

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-org#913]
There should be more spacing around the Typescript link at https://www.patternfly.org/v4/get-started/developers

<img width="710" alt="Screen Shot 2019-04-26 at 2 31 15 PM" src="https://user-images.githubusercontent.com/7014965/56828792-0e59dd00-6830-11e9-8417-c4400f666aba.png">

**Comment by rachael-phillips** [comment]
Hi @rebeccaalpert this should be resolved now. I'm going to close this issue
