### ISSUE TITLE
Navigation system page - numbered list has no new line break

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-org#914]
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/navigation-system on a desktop

On Navigation system usage and behavior page the numbered list has no new line breaks, it is all listed as one long stream of content.

![image](https://user-images.githubusercontent.com/3739227/56828855-3b0df480-6830-11e9-8496-7bae8f45c92c.png)

**Comment by stacymcauliffe** [comment]
Fixed

![image](https://user-images.githubusercontent.com/35926653/57016356-b0d6df00-6be7-11e9-8884-14edd4fa9018.png)
