### ISSUE TITLE
Get started link in the footer not found 

### ISSUE THREAD

**Issue by lwrigh** [patternfly/patternfly-org#915]
**The description of the bug:**

When you click on the 'Get started' link in the footer it throws a 404. 

**What device you are viewing it on (Desktop, mobile, tablet, etc.):**
Desktop

**Screenshot:**
<img width="1440" alt="Screen Shot 2019-04-26 at 2 30 14 PM" src="https://user-images.githubusercontent.com/20227374/56828805-187bdb80-6830-11e9-8863-7f45571721b3.png">

**Link to the specific page where you are viewing the bug:**
https://www.patternfly.org/v4/

**Comment by rachael-phillips** [comment]
Thank you for filing this one! Closing this issue as this is a known issue.
