### ISSUE TITLE
React documentation examples - adding space between multiple objects

### ISSUE THREAD

**Issue by mceledonia** [patternfly/patternfly-org#916]
Sometimes objects in react documentation stick together which isn't representative of how they would actually look or be used:

https://www.patternfly.org/v4/documentation/react/components/alert/

Alerts
<img width="880" alt="image" src="https://user-images.githubusercontent.com/30935938/56828812-1ca7f900-6830-11e9-9e50-0e4143b2c847.png">

Badges
<img width="280" alt="image" src="https://user-images.githubusercontent.com/30935938/56828830-26c9f780-6830-11e9-923c-7d14f5466d82.png">

Desktop

**Comment by jschuler** [comment]
Hi @mceledonia , we were not applying workspace styling before, but now we are. So at least the alerts have spacing between them now. The workspace styling is inherited upstream from the patternfly-react repo. For the badges there are no specific workspace styles to add a space between them. And unlike traditional HTML, when react renders sibling spans it does not add an implicit space between them. So if we want the space between the items we can either add a react workspace style or add spaces to the rendered HTML. I've created an issue for this upstream
https://github.com/patternfly/patternfly-react/issues/2520
