### ISSUE TITLE
Global navigation

### ISSUE THREAD

**Issue by lizhoover** [patternfly/patternfly-org#917]
Spacing is incorrect for global navigation (I believe this spacing is set to 32px)
![Screen Shot 2019-04-26 at 2 31 19 PM](https://user-images.githubusercontent.com/48283814/56828886-4c570100-6830-11e9-998f-e506ee5ef289.png)

Laptop
https://www.patternfly.org/v4/get-started/about

**Comment by rachael-phillips** [comment]
Hi @lizhoover I'm going to close this issue because it has been resolved
