### ISSUE TITLE
Remove ","

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#918]
Design Guidelines > Usage and Behavior > Modal (bottom of page)

<img width="604" alt="Screen Shot 2019-04-26 at 2 31 20 PM" src="https://user-images.githubusercontent.com/20118816/56828877-495c1080-6830-11e9-97ca-bf4668b06a30.png">

**Comment by LHinson** [comment]
redundant issue with #950. closing this one but FYI PR #972 addresses this one too
