### ISSUE TITLE
Icons used in documentation

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#919]
Some non-PF icons were being used in the documentation. Nit-picky but I think PF icons here would be great. Eat our own dog food approach.

<img width="773" alt="Screen Shot 2019-04-26 at 2 33 07 PM" src="https://user-images.githubusercontent.com/18266453/56828915-60026780-6830-11e9-85a6-df4f8829a34b.png">

**Comment by rachael-phillips** [comment]
Great point! Let's see if we can get our authors to add PF icons instead. cc @mcarrano
