### ISSUE TITLE
Help icon in top and left align examples are inconsistent with the rest of the form page

### ISSUE THREAD

**Issue by nlcwong** [patternfly/patternfly-org#920]
The screenshots depicting examples of [top and left alignments of form labels](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms#labeling) have help icons that are inconsistent with the rest of the screenshot examples in the rest of the [form  guideline](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms) page.

Screenshots:
<img width="713" alt="Screen Shot 2019-04-26 at 2 36 30 PM" src="https://user-images.githubusercontent.com/31672086/56829065-c1c2d180-6830-11e9-9198-d629e5455128.png">

<img width="715" alt="Screen Shot 2019-04-26 at 2 36 10 PM" src="https://user-images.githubusercontent.com/31672086/56829072-c5eeef00-6830-11e9-8e3b-040bc298cb31.png">

**Comment by rachael-phillips** [comment]
@mcarrano @stacymcauliffe making you aware of this discrepancy in the design guidelines.

**Comment by mcarrano** [comment]
Yeah, we do have an open issue to update the Form guidelines here. This should be addressed as part of that work. https://github.com/patternfly/patternfly-org/issues/1137

**Comment by rachael-phillips** [comment]
I'm going to close this issue because we have #1137 open which will fix this.
