### ISSUE TITLE
Search/branding spacing at breakpoints

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#921]
<img width="966" alt="Screen Shot 2019-04-26 at 3 34 07 PM" src="https://user-images.githubusercontent.com/287880/56828943-d4d99f80-6838-11e9-8254-7728ceefe2ae.png">
The spacers around the search, branding look a bit off at this break point (medium?).
reduce the left/right spacing and increase the top spacers.

**Comment by rachael-phillips** [comment]
Closing because this issue should be resolved now
