### ISSUE TITLE
Get started link for components in the footer not found

### ISSUE THREAD

**Issue by lwrigh** [patternfly/patternfly-org#922]
**The description of the bug**
When you click on the 'Components' link in the quicklinks column in the footer it throws a 404.

**What device you are viewing it on (Desktop, mobile, tablet, etc.)**
Desktop

**Screenshot**
<img width="1440" alt="Screen Shot 2019-04-26 at 2 35 10 PM" src="https://user-images.githubusercontent.com/20227374/56829026-a5269980-6830-11e9-95cd-322a3b7058e8.png">

**Link to the specific page where you are viewing the bug**
https://www.patternfly.org/v4/documentation/react/components/

**Comment by rachael-phillips** [comment]
Thank you for filing this one! Closing this issue as this is a known issue.
