### ISSUE TITLE
Content - Getting started for designers

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#925]
![Xnip2019-04-26_14-37-29](https://user-images.githubusercontent.com/23172038/56829128-e9b23500-6830-11e9-9480-ee3f924d9c30.jpg)

These two links don't seem right (even with the v4 relative-stuff).

**Comment by rachael-phillips** [comment]
Hi @katierik , can you tell me more about what doesn't feel right about them?

**Comment by katierik** [comment]
Looks like they're pointing at a place that makes sense now!
![Xnip2019-05-02_15-12-01](https://user-images.githubusercontent.com/23172038/57100327-a8b49780-6cec-11e9-8f13-78135f36535f.jpg)
