### ISSUE TITLE
Opening a React component example in fullscreen opens all the examples in one page

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly-org#926]
When you click this icon on a React example: ![Screenshot 2019-04-26 14 36 36](https://user-images.githubusercontent.com/811963/56829043-b374b580-6830-11e9-866a-dbb3ad2dcfab.png)

I would expect to see only that specific example open in a new window (which is how the HTML examples behave) but instead it's opening a page containing all of the examples for that component on top of each other.

For example: https://www.patternfly.org/v4/documentation/react/components/table/fullscreen

This makes it difficult to find the particular example you clicked on, especially for components with many large examples like Table.

**Comment by rachael-phillips** [comment]
Ouch. Great find! Thanks for pointing that out!

**Comment by rachael-phillips** [comment]
We have currently taken this icon out, to avoid this issue. In upcoming sprints we should resolve for viewing examples full screen.

**Comment by rachael-phillips** [comment]
We created a workaround so that this won't be an issue anymore
