### ISSUE TITLE
About Modal text needs a space in two instances

### ISSUE THREAD

**Issue by rblackbu** [patternfly/patternfly-org#927]
Description:
About Modal text needs a space in two instances between "t" and "M"

Device: 
Desktop, Chrome version 73.0.3683.103

Screenshot: 
![spacing](https://user-images.githubusercontent.com/25234746/56829132-ecad2580-6830-11e9-8d68-9f37e919d23f.png)

Link to page:
https://www.patternfly.org/v4/documentation/react/components/aboutmodalodal

**Comment by rachael-phillips** [comment]
Thanks for filing this! Great find! This is a known issue that we are hoping to fix asap.
