### ISSUE TITLE
Examples for alerts show different on React vs HTML version

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#928]
We added breaks between them to avoid that odd overlapping issue. 
<img width="922" alt="Screen Shot 2019-04-26 at 3 37 16 PM" src="https://user-images.githubusercontent.com/287880/56829167-66e1a800-6839-11e9-83d8-ea51e6d90f6f.png">
<img width="921" alt="Screen Shot 2019-04-26 at 3 37 51 PM" src="https://user-images.githubusercontent.com/287880/56829169-66e1a800-6839-11e9-8603-2714caef7e03.png">

**Comment by rachael-phillips** [comment]
@jschuler will this be fixed when we pull in the new React build?

**Comment by rachael-phillips** [comment]
I think this issue has been resolved.
