### ISSUE TITLE
Modal guidelines - icons broken

### ISSUE THREAD

**Issue by catrobson** [patternfly/patternfly-org#929]
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal viewing on desktop.

All icons for "Icons use in modal dialogs" are broken:
![image](https://user-images.githubusercontent.com/3739227/56829189-136b5c00-6831-11e9-8437-c13ab10105db.png)

**Comment by rachael-phillips** [comment]
Thanks for filing this! Great find!

**Comment by christiemolloy** [comment]
We should pull in the font awesome icon rather than using img
