### ISSUE TITLE
Remove gray background behind About Patternfly section

### ISSUE THREAD

**Issue by lizyochemwood** [patternfly/patternfly-org#931]
Remove gray background behind the About PatternFly section on the homepage

<img width="1264" alt="Screen Shot 2019-04-26 at 2 38 12 PM" src="https://user-images.githubusercontent.com/50029146/56829186-11a19880-6831-11e9-9610-75a19f573a83.png">

Viewing in Chrome on desktop

**Comment by rachael-phillips** [comment]
Thanks for filing this! Great find!
