### ISSUE TITLE
Search does not navigate to link location on page.

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-org#932]
When searching for content using global search, you will only navigate to the location on the page for what you are searching for if you already on the page where the content is.  If you are not on the page you will just be taken to the page and not navigated to the content you are searching for.

For Example:

I did a search for **FormSelectOptions Props**

<img width="1260" alt="Screen Shot 2019-04-26 at 2 36 33 PM" src="https://user-images.githubusercontent.com/6126356/56829204-1d8d5a80-6831-11e9-9518-2770506ead5b.png">

I'm only navigated to this section if I am on the page, otherwise I will be taken to the top of the page.

<img width="1677" alt="Screen Shot 2019-04-26 at 2 36 54 PM" src="https://user-images.githubusercontent.com/6126356/56829206-1e25f100-6831-11e9-8320-51c2442b2392.png">

**Comment by jschuler** [comment]
@dlabaj is this still not working for you? I just tried and it was working for me

**Comment by rachael-phillips** [comment]
I'm closing this issue as it has been resolved.
