### ISSUE TITLE
Styles link in footer not found

### ISSUE THREAD

**Issue by lwrigh** [patternfly/patternfly-org#934]
**The description of the bug**
When you click on the 'Styles' link in the footer it throws a 404. 

**What device you are viewing it on (Desktop, mobile, tablet, etc.)**
Desktop

**Screenshot**
<img width="1440" alt="Screen Shot 2019-04-26 at 2 39 30 PM" src="https://user-images.githubusercontent.com/20227374/56829212-241bd200-6831-11e9-97bd-03e67708b939.png">

**Link to the specific page where you are viewing the bug**
https://www.patternfly.org/v4/design-guidelines/styles/

**Comment by rachael-phillips** [comment]
Thank you for filing this one! Closing this issue as this is a known issue.
