### ISSUE TITLE
Tab Navigation on Mobile

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#936]
Logo/Search spacing and the tabs are not fitted for the smallest state.
Chrome/Mac
<img width="420" alt="Screen Shot 2019-04-26 at 2 39 06 PM" src="https://user-images.githubusercontent.com/18266453/56829237-3433b180-6831-11e9-8b79-77e4fb3a4953.png">

**Comment by rachael-phillips** [comment]
Thanks for filing this! Yes, this needs to be fixed.

**Comment by rachael-phillips** [comment]
This issue has been resolved
