### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by lizhoover** [patternfly/patternfly-org#937]
Responsive issues 
Laptop
https://www.patternfly.org/v4/documentation/react/components/button/
![Screen Shot 2019-04-26 at 2 40 21 PM](https://user-images.githubusercontent.com/48283814/56829317-66ddaa00-6831-11e9-9719-a00f0280815b.png)

**Comment by christiemolloy** [comment]
Update the table to use the modifier `pf-m-grid-xl`
