### ISSUE TITLE
Popover on icons page can extend beyond viewport (right side)

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-org#938]
https://www.patternfly.org/v4/design-guidelines/styles/icons

The direction should be reversed instead of going beyond the view port. 
![image](https://user-images.githubusercontent.com/2206023/56829264-4877ae80-6831-11e9-9c16-a5728f6d8c06.png)

Works ok on the rightmost tile, but here it obscures the tile, so that is a bug too:
![image](https://user-images.githubusercontent.com/2206023/56829306-5fb69c00-6831-11e9-9204-3c91c1f19be3.png)

**Comment by jeperry** [comment]
These popovers are not friendly on mobile either. I'm less concerned about that use case but worth noting.

**Comment by rachael-phillips** [comment]
Hi Jeremy! Great news - we are going to be building a better icons design next week that won't include the popovers. I'm going to close this in hopes that the new design gets in for launch.
