### ISSUE TITLE
Layouts link in footer not found

### ISSUE THREAD

**Issue by lwrigh** [patternfly/patternfly-org#939]
**The description of the bug**
When you click on the 'Layouts' link in the footer it throws a 404. 

**What device you are viewing it on (Desktop, mobile, tablet, etc.)**
Desktop

**Screenshot**
<img width="1440" alt="Screen Shot 2019-04-26 at 2 42 02 PM" src="https://user-images.githubusercontent.com/20227374/56829343-7b21a700-6831-11e9-9cb8-854899fc65ad.png">

**Link to the specific page where you are viewing the bug**
https://www.patternfly.org/v4/documentation/react/layouts/

**Comment by rachael-phillips** [comment]
Thank you for filing this one! Closing this issue as this is a known issue.
