### ISSUE TITLE
Full page overlay doesn't fit the about modal

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-org#940]
Firefox on Mac

The overlay is bigger than the content, and it looks slightly off.
![Apr-26-2019 14-42-20](https://user-images.githubusercontent.com/23172038/56829418-a906eb80-6831-11e9-990b-e5b3ea037298.gif)

**Comment by rachael-phillips** [comment]
Thanks for filing this! We already have an issue open for this one, so I'm going to close it.
