### ISSUE TITLE
Link Icon is confusing and could benefit from a popup

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-org#941]
Wasn't sure what the expected behavior of this link button in the image below was:

<img width="404" alt="Screen Shot 2019-04-26 at 2 42 48 PM" src="https://user-images.githubusercontent.com/6126356/56829530-fd11d000-6831-11e9-9418-148fab80702b.png">

It could benefit from a tool tip describing what it is and how to use it.

**Comment by rachael-phillips** [comment]
Thanks for filing this! I totally agree. I'm going to close this because we already have an open issue for this
