### ISSUE TITLE
Search experience/mental model

### ISSUE THREAD

**Issue by schizari** [patternfly/patternfly-org#943]
No sure if this is a bug or a usability issue - but I automatically press 'Enter' as soon I finish typing in a search bar and I would only look at the pop up window if I am looking for suggestions (Google is to blame for this habit). 

However, pressing Enter after a search on PF will take you to the first option in the list which is not the behavior I expect to happen (again because of Google). I wonder if other users have same expectations/ perception? 

<img width="650" alt="Screen Shot 2019-04-26 at 11 43 37 AM" src="https://user-images.githubusercontent.com/33766334/56829437-8c11ee80-6818-11e9-9108-832cea6f2b3d.png">

**Comment by rachael-phillips** [comment]
Let's see if we can remove this behavior cc @jschuler what do you think? Is this possible?

**Comment by jschuler** [comment]
I guess this is like a filter dropdown, so as you type relevant results are displayed. By default the first entry is highlighted, but it is possible to use the arrow keys to select a different entry to navigate to when the Enter key is pressed.
This behavior is different from a search field where you only see results once you hit the Enter key (usually in a full page view).
We could possibly modify this to disable the automatic selection of the first item and prevent the Enter/Return key from doing anything.
But we should evaluate if this effort is needed first before jumping in I think.

**Comment by redallen** [comment]
Pressing enter in the search box no longer does anything.
