### ISSUE TITLE
responsive issue with graphic

### ISSUE THREAD

**Issue by lizhoover** [patternfly/patternfly-org#945]
a responsive issue with graphic - can the content stack so the image can be large enough to read?
Laptop
https://www.patternfly.org/v4/design-guidelines/styles/typography
![Screen Shot 2019-04-26 at 2 46 39 PM](https://user-images.githubusercontent.com/48283814/56829581-2599ca00-6832-11e9-9e9c-4b97c6547f33.png)

**Comment by evwilkin** [comment]
Resolved in https://github.com/patternfly/patternfly-org/pull/1616
