### ISSUE TITLE
Footer styling

### ISSUE THREAD

**Issue by lizyochemwood** [patternfly/patternfly-org#946]
1. The hover effect on items in the footer look off
2. Update type styles of the footer to reflect the new Design System Collaborative styles
%footer-headline
Font family		Red Hat Text
Font weight		Medium
Font size			14px (0.875rem)
Line height		21px (1.5)
Case			Uppercase
Web weight		700

%footer-text
Font family		Red Hat Text
Font weight		Regular
Web weight		400

3. The gray PatternFly section on the right in the footer should be 4 columns wide

<img width="1181" alt="Screen Shot 2019-04-26 at 2 40 06 PM" src="https://user-images.githubusercontent.com/50029146/56829618-419d6b80-6832-11e9-80ef-b56bfc53809e.png">

Desktop, Chrome

**Comment by rachael-phillips** [comment]
Hi @lizyochemwood we have an issue open for this, so if you don't mind I'm going to copy your text over there.
