### ISSUE TITLE
Refine Search algorithm 

### ISSUE THREAD

**Issue by Rohoover** [patternfly/patternfly-org#947]
If I search for "close icon", I would anticipate seeing a result that would lead me to the icon library. Can we look into this as general feedback?

<img width="556" alt="Screen Shot 2019-04-26 at 2 46 06 PM" src="https://user-images.githubusercontent.com/18266453/56829603-321e2280-6832-11e9-985b-8bb473d5024d.png">

**Comment by Rohoover** [comment]
This probably needs to be done for at least our most common icons.

**Comment by rachael-phillips** [comment]
Thanks for filing this! Great find!

**Comment by evwilkin** [comment]
This looks to be resolved now - icons are the first result for this search
![Screen Shot 2020-07-25 at 6 16 32 PM](https://user-images.githubusercontent.com/8651509/88467247-1412f800-cea3-11ea-9c3e-ff450430b49b.png)
