### ISSUE TITLE
STAY IN TOUCH links in the footer should open a new tab

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-org#949]
Currently the _Forum_ and _Mailing list_ links under STAY IN TOUCH in the footer replace the contents of the current browser tab.  Links which are navigating to a site other than PatternFly should be brought up in a new browser.

**Comment by rachael-phillips** [comment]
Thanks for filing this! Great find!

**Comment by mindreeper2420** [comment]
Tested on Chrome and Firefox on macOS and the links in the footer open in a new tab. My guess is that there was a build running the completed after the bug bash took place.

**Comment by serenamarie125** [comment]
thanks @mindreeper2420 just retested as well, and it is opening in a new tab.
