### ISSUE TITLE
Formatting fixes on about modal usage page

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-org#951]
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/about-modal

List text is smaller that regular body, and sub-bullets on item 6 are not indented. 
![image](https://user-images.githubusercontent.com/2206023/56829680-6a256580-6832-11e9-9ff7-e385dbad238d.png)

Under usage, subheading "How to access..." is not on line by itself.
![image](https://user-images.githubusercontent.com/2206023/56829704-7a3d4500-6832-11e9-8ab8-8f7957e1a1fb.png)

**Comment by stacymcauliffe** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/35926653/57016341-9d2b7880-6be7-11e9-8fa0-10cbb28f1f5d.png)
