### ISSUE TITLE
Inconsistent case in footer

### ISSUE THREAD

**Issue by rebeccaalpert** [patternfly/patternfly-org#952]
"Privacy Statement" vs. "Terms of use," etc.

<img width="980" alt="Screen Shot 2019-04-26 at 2 49 27 PM" src="https://user-images.githubusercontent.com/7014965/56829780-a8228980-6832-11e9-9b3c-3e93efec2951.png">

Seen on Desktop.

**Comment by rachael-phillips** [comment]
Great point! I added this to: https://github.com/patternfly/patternfly-org/issues/866
