### ISSUE TITLE
Tracking feedback on PF4 website Doc

### ISSUE THREAD

**Issue by lizhoover** [patternfly/patternfly-org#953]
The thinks on this list still need to be fixed
Laptop
https://docs.google.com/document/d/16qv5lUuEDqT2_GKveF8xnqISnc4ywmGm_aJhYb2P7uM/edit#heading=h.kpbl57m5dozk

**Comment by evwilkin** [comment]
Closing as issues are outdated and work has begun on new website redesign (https://app.zenhub.com/workspaces/pf-infrastructure-5dd71dfec0ccd30001367fdf/issues/patternfly/patternfly-org/1793)
