### ISSUE TITLE
Spacing issue on style guide page

### ISSUE THREAD

**Issue by lizyochemwood** [patternfly/patternfly-org#955]
The copy is running into the column of copy next to it on this page: https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology

<img width="1022" alt="Screen Shot 2019-04-26 at 2 50 43 PM" src="https://user-images.githubusercontent.com/50029146/56829879-e1f39000-6832-11e9-80ae-ed5f7602b93e.png">

Chrome/Desktop

**Comment by rachael-phillips** [comment]
Great find! Thanks for filing this!
