### ISSUE TITLE
Javascript seed project is missing from getting started

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-org#956]
For the PatternFly seed project we have two branches for react developers.  The main branch is typescript, developers wishing to use typescript should fork or clone from that branch.  For Javascript developers they should fork or clone from the following branch:

https://github.com/patternfly/patternfly-react-seed/tree/javascript

The starting with the react seed section here https://www.patternfly.org/v4/get-started/developers#installing-and-configuring should be updated with this information

<img width="1181" alt="Screen Shot 2019-04-26 at 2 52 11 PM" src="https://user-images.githubusercontent.com/6126356/56829912-fafc4100-6832-11e9-93b6-d2eff843c9be.png">

**Comment by stacymcauliffe** [comment]
PR merged, closing
