### ISSUE TITLE
"CSS variable" on typography page isn't a CSS variable

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly-org#957]
The "Global CSS Variable" value on https://www.patternfly.org/v4/design-guidelines/styles/typography#usage-guidelines is `.pf-c-title`. That's a class, not a variable.  I think those are meant to be these

```
  --pf-global--FontSize--4xl
  --pf-global--FontSize--3xl
  --pf-global--FontSize--2xl
  --pf-global--FontSize--xl
  --pf-global--FontSize--lg
  --pf-global--FontSize--md
  --pf-global--FontSize--sm
  --pf-global--FontSize--xs
```

**Comment by rachael-phillips** [comment]
@stacymcauliffe do you know how we go about updating these?

**Comment by christiemolloy** [comment]
@rachael-phillips I did this page, and in the design there was a placeholder variable, we need someone on the js side to update `typography.js` so that those variables are rendered from global vars/type page

**Comment by rachael-phillips** [comment]
@christiemolloy did we completely wrap this up or is there more to do here?

**Comment by christiemolloy** [comment]
@rachael-phillips yes my fault, it was wrapped up here: #1072
