### ISSUE TITLE
Buttons and links example in design guidance: image of button uses old blue color

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-org#958]
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/buttons-and-links

Blue has changed since the image here was made.

**Comment by rachael-phillips** [comment]
Great find. Thanks for filing it!

**Comment by jeperry** [comment]
I realize there are a LOT of images and many predate some design changes like the blue color we use for links and buttons. Fixing these would be a big maintenance issue and would hate to see this prioritized over other more important fixes. It may not be that important to update these all unless more significant changes happen.

**Comment by rachael-phillips** [comment]
I see. Yes, I agree, and I think it's good to keep this in mind because maintenance is, of course, always a challenge. I would like to see all of these updated eventually!

**Comment by stacymcauliffe** [comment]
PR merged
