### ISSUE TITLE
Could we add the icon to the icon info tip?

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-org#962]
I'd consider this an enhancement.  Since the info tip covers the actual icons, could we add the icon in the info tip, in case the user identifies with the icon visual rather than the icon name?

<img width="670" alt="Screen Shot 2019-04-26 at 2 56 26 PM" src="https://user-images.githubusercontent.com/12504403/56830147-91c8fd80-6833-11e9-91a7-106e46a643de.png">

**Comment by rachael-phillips** [comment]
Hi @serenamarie125 thanks for filing! Great news! We are going to be adding a more sophisticated icon design next week which would eliminate this problem. I'll leave this issue open until we make the changes.

**Comment by rachael-phillips** [comment]
This has been resolved
