### ISSUE TITLE
Blue text impersonates a link

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#963]
I feel a little silly saying so, but after years of conditioning, the blue text makes me feel that this should be a link. 

![image](https://user-images.githubusercontent.com/19825616/56830138-8c6bb300-6833-11e9-87ba-8b995dbdc963.png)

**Comment by rachael-phillips** [comment]
That's not silly at all. I can definitely see that, and I think this is something we should take into consideration for future design work.

**Comment by rachael-phillips** [comment]
Hi @srambach do you think this has been resolved with the new styling?

**Comment by srambach** [comment]
I'm not sure what the new styling is - looks the same to me except possibly less bold?
![image](https://user-images.githubusercontent.com/19825616/68601428-4b0ac000-0472-11ea-852e-5fe30adfd125.png)

**Comment by evwilkin** [comment]
This is removed with the new website redesign going live later this week:

![Screen Shot 2020-09-14 at 5 18 24 PM](https://user-images.githubusercontent.com/8651509/93139244-5f30d680-f6ae-11ea-80ee-bd963d82d561.png)
