### ISSUE TITLE
Documentation section's framework toggle button is confusing

### ISSUE THREAD

**Issue by nlcwong** [patternfly/patternfly-org#965]
Scenario:
On the [Forms design guideline page](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms) there is a view forms demo link that redirects the user to the [Core Forms page](https://www.patternfly.org/v4/documentation/core/demos/basicforms). If the user wanted to see the equivalent React demo version, if they try and click on the "React | HTML" toggle button to see the React version of a forms demo, they are navigated to the [About modal](https://www.patternfly.org/v4/documentation/react/components/aboutmodal) react demo I was expecting to see the [react demo of forms](ttps://www.patternfly.org/v4/documentation/react/components/form/)

The demo link isn't all that confusing in that I now see that there is only a core version of the forms demo (might want to explicitly call that out in the guidelines page you are going to core version), but what is confusing is that when I clicked on the react toggle, I was expecting to land on a page that is about forms (the components version if no demo was available).

I think the real issue is that the toggle button makes me think that it will toggle between core vs. react versions of the same component/demo/layout we are on.  Maybe its a visualization or layout issue of where the toggle button is, but never really thought of the toggle button as a top level navigational link that won't persist selections made below it.

**Comment by rachael-phillips** [comment]
Thanks so much for filing this! Great news - we are going to work on this toggle experience so that if you are viewing forms on HTML/CSS and you toggle to React you would land on forms.
