### ISSUE TITLE
Design guidelines for Forms - request for more info and minor edits

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly-org#966]
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms

We should be consistent in presenting top alignment for labels as the first (default) guidance.
- CURRENT: Field labels can be aligned to the left or top of the field depending on the layout of your page and the amount of space you have to work with.
- CHANGE TO: Field labels can be aligned to the top or left of the field depending on the layout of your page and the amount of space you have to work with.

Subheadings in "Provide the right data input" are appearing inline instead of on their own line

Do and Don't - Don'ts are not lined up with Do. 
![image](https://user-images.githubusercontent.com/2206023/56830316-0734ce00-6834-11e9-8f09-e282e42f0b2a.png)

Can the design guidance include a suggestion on size and especially width of controls?

**Comment by rachael-phillips** [comment]
@christiemolloy is this something that will be fixed in your efforts working with Stacy?

**Comment by stacymcauliffe** [comment]
Submitted PR #996 for this issue

**Comment by stacymcauliffe** [comment]
PR merged
