### ISSUE TITLE
No hover on expandable categories in left nav

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly-org#967]
It feels like there should be a hover on the categories in the left navigation.

![image](https://user-images.githubusercontent.com/19825616/56830436-4ebb5a00-6834-11e9-908e-b0bce2f578af.png)

**Comment by rachael-phillips** [comment]
Hi Sara, thanks for filing this! I'm seeing hover states. What browser are you viewing this on?

**Comment by srambach** [comment]
Ah, I see that it is there in design guidelines, but not in documentation, using both Chrome and FF.

**Comment by rachael-phillips** [comment]
Oh I see it now! Weird! Thanks!

**Comment by rachael-phillips** [comment]
Closing this as this has been completed
