### ISSUE TITLE
documentation table content cut off (html)

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-org#969]
This is most visible in the about modal documentation.
<img width="415" alt="Screen Shot 2019-04-26 at 4 43 23 PM" src="https://user-images.githubusercontent.com/287880/56832457-744f6000-6842-11e9-8e78-834038fddcf3.png">

**Comment by rachael-phillips** [comment]
Thanks for filing this! What browser are you on? I'm not seeing this issue quite yet

**Comment by matthewcarleton** [comment]
I saw this in Chrome. The main issue is the table is not responsive so if you resize it just crops the content.

**Comment by rachael-phillips** [comment]
Thanks!
