### ISSUE TITLE
Charts design guidelines and Colors for charts pages & links

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-org#971]
The chart components links on the chart guidelines are broken. The colors for charts links are broken too. (what did i do???)

GIFs on the colors for charts page are massive

**Comment by rachael-phillips** [comment]
@gdoyle1 do I need to assign this to a dev to look at or is this an update you are making already?

**Comment by gdoyle1** [comment]
@rachael-phillips I'm going to make this today! Might need a dev's help if I can't figure out the link issue. But going to take it on now

**Comment by rachael-phillips** [comment]
Ok great! Let me know if you need any dev help

**Comment by gdoyle1** [comment]
@mindreeper2420 this bug is also for this issue: 
<img width="291" alt="Screen Shot 2019-05-01 at 8 52 58 AM" src="https://user-images.githubusercontent.com/30870144/57017766-8e948f80-6bee-11e9-9493-f89526203701.png">

**Comment by rachael-phillips** [comment]
Closing this as it has been completed
