### ISSUE TITLE
Pagination search results should include Design Guidelines

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly-org#978]
Although pagination doesn't include it's own section in Design Guidelines, I would think when searching for Pagination it should match to the Toolbar documentation.

**Comment by rachael-phillips** [comment]
Hi @serenamarie125 I've taken a look at this issue, and I don't think there is any way for us to accomplish this because the search feature limits the amount of customizations we can do. @jschuler what are your thoughts?

**Comment by evwilkin** [comment]
Closing as it looks like this is resolved now - Pagination does have a page in Design Guidelines which the search results point to: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/pagination#main-content
