### ISSUE TITLE
Colors in Colors Page Breaking

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly-org#983]
At a certain viewport this is happening:

<img width="408" alt="Screen Shot 2019-04-29 at 9 12 36 AM" src="https://user-images.githubusercontent.com/20118816/56898418-fd42e300-6a5e-11e9-8b3f-cb87609f15b9.png">

**Comment by mindreeper2420** [comment]
@christiemolloy I believe the color blocks just need to be updated to dynamically resize on the smaller viewports - right now, they are a fixed size.

**Comment by mindreeper2420** [comment]
Closing with merge of PR.
