### ISSUE TITLE
Icon page descriptions

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-org#993]
Import all icon descriptions to the icons page. If we cannot import the icon descriptions be the release date we should remove this section.

**Comment by dgutride** [comment]
Where are the icon descriptions in the repo @rachael-phillips ?

**Comment by rachael-phillips** [comment]
The icon descriptions we are going to use are the contextual usage categories listed here: https://www.patternfly.org/styles/icons/

**Comment by dgutride** [comment]
Descriptions were removed temporarily

**Comment by evwilkin** [comment]
Closed by https://github.com/patternfly/patternfly-org/pull/1840
